### ISSUE TITLE
混淆规则

### ISSUE THREAD

**Issue by Reginer** [alibaba/fastjson#1011]
fastjson的混淆规则是什么 ？

**Comment by googleweb** [comment]
https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by Reginer** [comment]
@googleweb 
你好，不是的，是防止混淆的规则，AS配置在proguard-rules.pro文件下。
比如网上流传的规则是这个：
-dontwarn com.alibaba.fastjson.**
-keep class com.alibaba.fastjson.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
但是并不好用。
