### ISSUE TITLE
fastjson反序列化对象中，对于Collection属性如果只有get方法（没有set方法），会对Collection进行的元素进行重复add，造成数据不一致

### ISSUE THREAD

**Issue by Viyond** [alibaba/fastjson#1013]
如题，如果参与序列化的对象中的属性（如Map、Collection等类型）只定义了对应的get方法，而没有定义set方法，则fastjson则会对对应的属性进行重复的putAll或者addAll操作，造成属性实际值发生变化。
说明：
fastjson版本：从1.2.7 到 1.2.24均测试过，均存在此类问题。

测试case代码如下：
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONWriter;
import com.alibaba.fastjson.parser.Feature;
import com.alibaba.fastjson.serializer.SerializerFeature;

import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import java.nio.charset.CodingErrorAction;

public class DefaultJsonSerializer {

    private static final Charset CHARSET = Charset.forName("UTF-8");

    public static <T> void serialize(T obj, OutputStream out) {
        JSONWriter writer = null;
        try {
            writer = new JSONWriter(new OutputStreamWriter(out, CHARSET.newEncoder().onMalformedInput(CodingErrorAction.IGNORE)));
            writer.config(SerializerFeature.QuoteFieldNames, true);
            writer.config(SerializerFeature.SkipTransientField, true);
            writer.config(SerializerFeature.SortField, true);
            writer.config(SerializerFeature.WriteEnumUsingToString, false);
            writer.config(SerializerFeature.WriteClassName, true);
            writer.config(SerializerFeature.DisableCircularReferenceDetect, true);
            writer.writeObject(obj);
            writer.flush();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (Exception e) {
                }
            }
        }
    }

    public static <T> T deserialize(byte[] in) {
        return (T) JSON.parse(in, 0, in.length, CHARSET.newDecoder(), Feature.AllowArbitraryCommas,
                Feature.IgnoreNotMatch, Feature.SortFeidFastMatch, Feature.DisableCircularReferenceDetect,
                Feature.AutoCloseSource);
    }

}

//**********************   测试代码    *********************

public class TestDomain {

    private List<Integer> list;

    public TestDomain(){
        list = new ArrayList<Integer>();
        list.add(1);
    }

    public List<Integer> getList(){
        return list;
    }

}

public class TestDomainTest {

    public static void main(String[] args) {
                 ByteArrayOutputStream bos = new ByteArrayOutputStream();
                 try{
                         TestDomain testDomain = new TestDomain();
                         System.out.println("before:" + testDomain.getList());

            DefaultJsonSerializer.serialize(testDomain, bos);
            Object object = DefaultJsonSerializer.deserialize(bos.toByteArray());
            TestDomain desRes = (TestDomain)object;

            System.out.println("after:" + desRes.getList());
        }finally {
            try{
                bos.close();
            }catch (IOException ex){
                ex.printStackTrace();
            }
        }
    }
}

//***********************     输出结果如下      *******************************
before:[1]
after:[1, 1]

//**********************   原因初步定位   ************************
debug了一下fastjson的代码，发现问题出在类FieldDeserializer的setValue方法上，如下截图

![image](https://cloud.githubusercontent.com/assets/4710189/22687129/c6770fc6-ed61-11e6-91b4-477f712e275f.png)

针对反射方式获取到value后进行重复add，不大清楚以上逻辑的处理原因。
还请麻烦 @wenshao 帮忙看看，非常感谢。

**Comment by wenshao** [comment]
很多ValueObject的Collection类型属性只有getter没有setter，针对这种情况，fastjson做了特别处理。这不符合你的需求么？既然输入中有数据，为啥不add进去呢？

**Comment by landawn** [comment]
反序列化一个JSON字符串： {"@type":"net.java8.lambda.TestDomainTest$TestDomain","list":[1]}
最终得到TestDomain的List里面有两个“1”。
这不应该看作是一个正确的结果。

**Comment by Viyond** [comment]
getter返回的值在对象实例化时候就已经决定了，部分场景并不需要setter，不可否认部分场景下就是有这种需求，可是这种对象在经过反序列化之后之后，内部属性的值已经变了（和实际不一致）。我的理解对象序列化之前和反序列化之后，前后对象属性值必须是对称的，否则这种序列化机制就不符合预期的结果。

**Comment by wuwen5** [comment]
在这个用例中，的确应该以原始json串数据为准。

 * 没有setter时, "{"list":[1]}" --> ```TestDomain``` list 应该是 1个元素, 覆盖构造函数初始化的值.
 * 没有setter时,  "{"list":[]}" -->  ```TestDomain``` list 应该是 0个元素, 覆盖构造函数初始化的值.
 * 没有setter时,  "{"list":null}" -->  ```TestDomain``` list 应该是 1个元素,不覆盖，保留构造函数中加载的.
 * 有setter时,  "{"list":null}" -->  ```TestDomain``` list 应该是 null, (覆盖).

个人观点，如有不对请指正.
#1027 中提交了testcase 和 修复建议。 请review.
@wenshao

**Comment by landawn** [comment]
对不起，前面我没有看仔细看构造函数的代码：

`public TestDomain(){
    list = new ArrayList<Integer>();
    list.add(1);
}
`
这样的构造函数不符合一个用于序列号的常用结构体的规范。虽然反序列号后的结果不符合预期，但fastjson本身并没有错，所以我不认为这是一个bug，同时也认为没有必要为一些不规范/怪异的需求去更改框架，应尽量让框架接单一些。
