### ISSUE TITLE
fastjson支持 Javabean的复用么

### ISSUE THREAD

**Issue by wangsai-silence** [alibaba/fastjson#1014]
在一些特殊场景，会有大量频繁的json解析，目前的api上看，只能是每次new一个新的对象出来。这样会导致频繁的内存抖动，请问是否有针对性的解决方案。

**Comment by wenshao** [comment]
支持的，我写了demo给你，你看是否满足你的需求
https://github.com/alibaba/fastjson/wiki/ReuseObject_cn

**Comment by wangsai-silence** [comment]
谢谢，正是我要找的东西，辛苦了
