### ISSUE TITLE
解析com.fasterxml.jackson.databind.node.ObjectNode不是需要返回的结果

### ISSUE THREAD

**Issue by 282919088** [alibaba/fastjson#1041]
在框架中对返回的结果使用了fastjson处理,但是因为要集成activiti工作流引擎,activiti中使用的是jackson的json处理.导致返回的结果集出错.
![111](https://cloud.githubusercontent.com/assets/4486214/23347927/bea7ae66-fce0-11e6-850d-0a2a09e53206.jpg)

![222](https://cloud.githubusercontent.com/assets/4486214/23347920/b7c111c8-fce0-11e6-8717-82b7ae177d8a.jpg)

目前只能继承 FastJsonHttpMessageConverter 然后在对返回的结果进行判断处理
![3333](https://cloud.githubusercontent.com/assets/4486214/23348047/c7cd60d4-fce1-11e6-8222-cc132a6d5ddd.jpg)

**Comment by haimanchen** [comment]
我也遇到了这个问题 不知道现在有没有好的办法呢？
