### ISSUE TITLE
能提供一个IgnoreType 的Feature吗？

### ISSUE THREAD

**Issue by rmfish** [alibaba/fastjson#1047]
由于历史原因，json数据中保存了@type类型，但是对应的class包名重构修改了，这时parse时会抛错。
eg:
{"@type":"a.Value";"value":1}
但是Value包名重构成b.Value
这时执行 JSONObject.parseObject(bytes, a.C.class)会抛
com.alibaba.fastjson.JSONException: type not match

**case:**
> 
package b;
public class Value {
    private Integer value;
    public Integer getValue() {
        return value;
    }
    public void setValue(Integer value) {
        this.value = value;
    }
}

>
String s = "{\"@type\":\"a.Value\",\"value\":1}";
b.Value v  = JSONObject.parseObject(s, b.Value.class);

**expect:**
>
b.Value v  = JSONObject.parseObject(s, b.Value.class,Feature.IGNORE_TYPE);

**Comment by wenshao** [comment]
已接受Pull Reuqest，但会重命名为IgoreAutoType
