### ISSUE TITLE
fastjson 搭配springmvc 使用时, 如果请求不声明 accept 的请求头, 那么会抛出异常

### ISSUE THREAD

**Issue by uaufdh** [alibaba/fastjson#1084]
fastjson 搭配springmvc 使用时, 如果请求不声明 accept 的请求头, 那么会抛出异常
异常为: 'Content-Type' cannot contain wildcard type '*'
建议:
修改 构造方法为 super(MediaType.ALL) 
举例: (这里参考了 jackson, 因为 jackson 亲测没有此问题 ) super( new MediaType[]{MediaType.APPLICATION_JSON, new MediaType("application", "*+json")});

**Comment by wenshao** [comment]
@VictorZeng 你帮忙看一下？

**Comment by VictorZeng** [comment]
@uaufdh MediaType.ALL是支持所有请求类型，修改为MediaType.APPLICATION_JSON, new MediaType("application", "+json") 难得仅支持JSON相关类型吗

**Comment by uaufdh** [comment]
@VictorZeng 你好, 之前我这里已经是在 org.springframework.http.converter.StringHttpMessageConverter 中配置了 `supportedMediaTypes` 为 `application/json`, 但是只要请求头不带 accept, 那么 fastjson 就会抛出异常, 而 jackson 不会, 请您再看看, 谢谢

**Comment by VictorZeng** [comment]
@uaufdh Content-Type设置了吗

**Comment by uaufdh** [comment]
@VictorZeng 你好, 我刚刚又测试了一遍,代码没有改,  请求没有 accept 字段, 没有再发生之前的异常.

**Comment by uaufdh** [comment]
@VictorZeng 
你好, 这个问题还是存在的. 我刚刚找到了问题发生的情况, 使用 @ResponseBody 注解, 还是会有异常.
spring 版本是 4.3.6.RELEASE, fastjson 是 1.2.29
并且我在 `org.springframework.http.converter.StringHttpMessageConverter` 中加了
`<property name="supportedMediaTypes">
                    <list>
                        <value>application/json</value>
                        <value>text/html</value>
                        <value>text/plain</value>
                    </list>
                </property>`
使用的注解是 `@Controller ` 和` @RestController`, 返回值是 JsonObject 类型都有这种情况
只要请求头没有 accept 字段, 那么就直接会抛出异常
 ` 'Content-Type' cannot contain wildcard type '*' 对应的我找到 源码 at org.springframework.http.HttpHeaders.setContentType(HttpHeaders.java:733)`
 里面有两行
`Assert.isTrue(!mediaType.isWildcardType(), "\'Content-Type\' cannot contain wildcard type \'*\'");
        Assert.isTrue(!mediaType.isWildcardSubtype(), "\'Content-Type\' cannot contain wildcard subtype \'*\'");`
并且只要加上 accept 请求头, 比如 accept: application/json, 那么问题就没有了.
某些特殊情况下确实没提供 accept 请求头, 那么也不应该出现异常. 
请您再看看

**Comment by uaufdh** [comment]
@VictorZeng 
已经解决了这么多天的困扰. 应该把 `supportedMediaTypes` 属性 加在 `FastJsonHttpMessageConverter4` 里面, 放在 `StringHttpMessageConverter` 没作用
