### ISSUE TITLE
可否开放抽象类的工厂方法构造

### ISSUE THREAD

**Issue by OhmygodWorks** [alibaba/fastjson#1085]
在1.1.56.android版本里确认到，在生成JavaBeanInfo的时候检测标记有@JSONCreator工厂方法的条件是该类必须是非抽象的类。
我可以理解对构造函数必须限制是非抽象的实体类，但是就个人经验来说，工厂方法应该没有必要限制必须是实体类。
如果是出于考量特别作的限制，还请科普一下限制的原因。
如果没有必需的原因，还请开放限制，让（.android版本的）抽象类也可以通过标注了@JSONCreator的工厂方法来实例化，这样就方便和Google的Auto Value库一起用了。

谢谢

**Comment by wenshao** [comment]
已经支持，将会在1.2.30 & 1.1.57.android版本中支持，谢谢你的反馈

**Comment by wenshao** [comment]
已经支持，将会在1.2.30 & 1.1.57.android版本中支持，谢谢你的反馈

**Comment by OhmygodWorks** [comment]
谢谢你的对应。
