### ISSUE TITLE
fastjson1.2.29 json解析报错

### ISSUE THREAD

**Issue by JPMonty** [alibaba/fastjson#1093]
代码：JSON.parse(bytes, new Feature[0])    
项目之前用的版本1.1.40完美运行

升级 1.2.29后报错：
com.alibaba.fastjson.JSONException: autoType is not support.

**Comment by xusheng1987** [comment]
https://github.com/alibaba/fastjson/wiki/enable_autotype

**Comment by JPMonty** [comment]
谢谢！
