### ISSUE TITLE
1.2.29 Spring 4.3.6 FastJsonConfig 配置问题

### ISSUE THREAD

**Issue by wudihaike** [alibaba/fastjson#1099]
```
<property name="fastJsonConfig">
                    <bean class="com.alibaba.fastjson.support.config.FastJsonConfig">
                        <property name="features">
                            <list>
                                <value>AllowArbitraryCommas</value>
                                <value>AllowUnQuotedFieldNames</value>
                                <!--禁用循环引用检测-->
                                <value>DisableCircularReferenceDetect</value>
                                <!--初始化为空的字符串字段-->
                                <value>InitStringFieldAsEmpty</value>
                            </list>
                        </property>
                        <property name="dateFormat" value="yyyy-MM-dd HH:mm:ss"></property>
                    </bean>
</property>
```
InitStringFieldAsEmpty 这个参数为何没用,为null 依然过滤掉了....

**Comment by wenshao** [comment]
@VictorZeng 帮看一下？

**Comment by VictorZeng** [comment]
@wudihaike 我感觉你需要的应该是 SerializerFeature.WriteNullStringAsEmpty

**Comment by wudihaike** [comment]
@VictorZeng 我是用在Spring4.*配置用的,是FastJsonHttpMessageConverter4 旧版的是 `<bean id="fastJsonHttpMessageConverter"class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">
                <property name="supportedMediaTypes">
                    <list>
                        <value>application/json;charset=UTF-8</value>
                    </list>
                </property>
                <property name="features">
                    <array value-type="com.alibaba.fastjson.serializer.SerializerFeature">
                        
                        <value>DisableCircularReferenceDetect</value>
                        
                        <value>WriteMapNullValue</value>
                        
                        <value>WriteNullNumberAsZero</value>
                        
                        <value>WriteNullStringAsEmpty</value>
                        
                        <value>WriteNullListAsEmpty</value>
                        
                        <value>WriteNullBooleanAsFalse</value>
                    </array>
                </property>
            </bean>`
问题是我看源码这个已经被Deprecated了. 还有什么其它方法配置吗?

**Comment by VictorZeng** [comment]
@wudihaike see https://github.com/alibaba/fastjson/wiki/FastJsonHttpMessageConverter_CN

**Comment by wudihaike** [comment]
@VictorZeng 谢谢解答,亲测成功,功能变得更加灵活了.
