### ISSUE TITLE
FastJson不能正确处理引号

### ISSUE THREAD

**Issue by qiuxiafei** [alibaba/fastjson#1109]
重现代码：
```java
import com.alibaba.fastjson.JSON;
import org.apache.commons.lang3.tuple.Pair;

/**
 * Created by xiafei.qiuxf on 2017/3/28.
 */
public class FastJsonBug {
    public static void main(String[] args) {
        Pair<String, String> data = Pair.of("key", "\"the\"content");
        System.out.println(JSON.toJSONString(data));
    }
}
```

输出：
```
{"key":""the"content"}
```

影响版本：1.2.24, 1.2.25

使用的commons-lang3版本为：3.4

**Comment by wenshao** [comment]
我测试的结果和你的不一样，如下：
```
{"fst":"key","snd":"\"the\"content"}
```

**Comment by ayanamist** [comment]
我能确认也有这个问题，fastjson 1.2.24版本
问题发生在`com.alibaba.fastjson.serializer.SerializeWriter#writeFieldValueStringWithDoubleQuote`这个方法里

```java
value.getChars(0, valueLen, buf, valueStart);
```

这里直接用`getChars`的结果填充了`buf`，导致引号没有转义就进到了最终的结果中。

**Comment by wenshao** [comment]
问题重现，正常情况不会这样，我要仔细看一下具体是怎么回事

**Comment by ayanamist** [comment]
因为只有实现`java.util.Map.Entry`接口时，FastJSON才会在`com.alibaba.fastjson.serializer.MiscCodec`里用到`com.alibaba.fastjson.serializer.SerializeWriter#writeFieldValueStringWithDoubleQuote`这个方法，然后就会有问题

不依赖commons-lang3的case

```groovy
import com.alibaba.fastjson.JSON;

Map.Entry<String, String> data = new AbstractMap.SimpleImmutableEntry("key", "\"the\"content");
System.out.println(JSON.toJSONString(data));
```

**Comment by wenshao** [comment]
谢谢提醒，问题重现并解决，等周末发布新版本1.2.31吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.31
新版本发布已解决问题，请升级
