### ISSUE TITLE
fastjson性能问题

### ISSUE THREAD

**Issue by hpt321** [alibaba/fastjson#111]
最近在使用fastjson（版本：fastjson-1.1.27.jar）时，发现一个问题，当被序列化或反序化的文本内容比较大时（比如300KB），如果JVM当前要执行YGC，这时可能会在到达safepoint时，整个JVM将会暂停等待fastjson中的counted-loop循环执行完后再执行YGC。 
　　如果是我的推断有误，请给予纠正。 
    谢谢

**Comment by wenshao** [comment]
没有信息无法进一步诊断，先关闭了
