### ISSUE TITLE
 json字符串转换对象时，如果键值中间有空格会转换失败

### ISSUE THREAD

**Issue by alphta** [alibaba/fastjson#1111]
1.2.30版本 json字符串转换对象时，如果键值中间有空格会转换失败

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by alphta** [comment]
不算BUG，原因我也没找到。
我再次封装了parseObject，增加了参数Feature.InitStringFieldAsEmpty，然后将json字符串转换引用的jar包里的对象就会失败；1. 删除参数Feature.InitStringFieldAsEmpty会转换成功；2. 将对象提出来转换会成功；
谢谢！

**Comment by ChetWang** [comment]
我们也碰到了，我觉得是一个bug。我是在老项目升级fastjson时碰到的，在fastjson 1.2.29及以前，是没问题的；1.2.30后，InitStringFieldAsEmpty会把其他正常有值字段也变成空字段。

**Comment by nickwongwong** [comment]
> 能提供重现问题的testcase么？
@wenshao 

复现了BUG,InitStringFieldAsEmpty引发的问题
升级之后版本：1.2.58 1.2.59
很老之前的版本是正常的

```java
//类定义
public static class OfferInfoExtend {
        private String company;
        
        public String getCompany() {
            return company;
        }

        public void setCompany(String company) {
            this.company = company;
        }
    }`
```
```java
       //company字段无法解析，去掉InitStringFieldAsEmpty就正常了
        String offers = "[{\"comment\":\"\",\"company\":\"阿里巴巴\"}]";
        List<OfferInfoExtend> offerExtends = JSONArray.parseObject(offers,
            new TypeReference<List<OfferInfoExtend>>() {}, InitStringFieldAsEmpty);
        for (OfferInfoExtend offerExtend : offerExtends) {
            System.out.println(offerExtend.getCompany());
        }
```
![image](https://user-images.githubusercontent.com/16626084/62923464-56e9d600-bde0-11e9-9dfb-0d490318e225.png)
