### ISSUE TITLE
解析属性第一位是数字时异常 NumberFormatException

### ISSUE THREAD

**Issue by xiushao1024** [alibaba/fastjson#1112]
##当属性的第一位是数字时（如：345_xiu），JsonPath尝试将属性转换为Integer类型，出现java.lang.NumberFormatException。

我的解决方案是在传入表达式时添加"\\"进行转义，伪代码：
String path = "$.xiu.\\345_xiu";
JsonPath.eval(jsonOgject , path);

希望有更好的解决方法。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.31
新版本发布已解决问题，请升级

**Comment by xiushao1024** [comment]
你好，最近使用JsonPath解析的时候遇到另一个问题。当json 的属性名为数字并且数值过大时（超过integer.max_value），直接使用JsonPath表达式解析报错。

java.lang.NumberFormatException: For input string: "1234567899999"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:495)
	at java.lang.Integer.parseInt(Integer.java:527)


public static void main(String[] args) {
		//正常解析
		String json1 = "{\"articles\":{\"2147483647\":{\"XXX\":\"xiu\"}}}";
		String path1 = "$.articles.2147483647.XXX";
		Object read = JSONPath.read(json1, path1);
		
                //报错
		String json2 = "{\"articles\":{\"2147483648\":{\"XXX\":\"xiu\"}}}";
		String path2 = "$.articles.2147483648.XXX";
		Object read2 = JSONPath.read(json2, path2);
	}
