### ISSUE TITLE
如何将Long,Double，Integer,Date的默认值设置为""

### ISSUE THREAD

**Issue by hwck** [alibaba/fastjson#1119]
有没有类似的接口实现之后，可以设置默认值。
暂时 使用SerializerFeature.WriteMapNullValue 之后replace 将所有的null 替换为“”

**Comment by xusheng1987** [comment]
这不是个正确的问题

**Comment by wenshao** [comment]
WriteNullStringAsEmpty
WriteNullNumberAsZero
这两个能符合你需求么？如果还是不行，用ValueFilter吧

**Comment by hwck** [comment]
@wenshao 这两个都用了，需求是将所有的基本类型都改为String类型，如果为null 就转换为“”显示，用WriteNullNumberAsZero,如果为null=0 不是“”,所以就在想有什么方法将所有的类型转为“”。用valueFilter是可以达到效果，谢谢！
