### ISSUE TITLE
1.2.31版JSONField的問題

### ISSUE THREAD

**Issue by unoya** [alibaba/fastjson#1134]
我的class裡使用如下:
	@JSONField(ordinal = 1, name="Dimension")
	private int dimension;
	@JSONField(ordinal = 2, name="PassCode")
	private String passCode;
	@JSONField(ordinal = 3, name="BlockPos")
	private BlockPos blockpos;
但輸出純文字資料後的內容卻沒有照著排列, 而且blockpos字母也沒有依照大小寫去更動.
如下:
[[{"PassCode":"010","blockPos":{"x":526,"y":65,"z":554},"Dimension":0}]]

**Comment by wenshao** [comment]
问题没重现 https://github.com/alibaba/fastjson/commit/9d29a791ece012f70bc394762a82fb52e5b495c9

**Comment by unoya** [comment]
我在開發Minecraft的mod, 使用到Forge的API.
看了你的測試檔,我大約猜到也許是BlockPos這個class的問題了, 看來我得自己重寫這個類別的功能了.
謝謝幫助測試.
