### ISSUE TITLE
请教1.2.6版本下 Date转换报错问题

### ISSUE THREAD

**Issue by SevenFxm** [alibaba/fastjson#1139]
上游系统返回日期带9999-09-09就会报错
java.lang.NumberFormatException: For input string: "9999-09-09"
通过
JSON.parseArray(jsonObect.get("dataList").toString(), Model.class);
这种方式转换并且尝试过在字段上方加上
@ JSONField(format = "yyyy-MM-dd")
任然未解决，请问有什么比较好的解决方法嘛？

**Comment by wenshao** [comment]
这个日期格式对么？

**Comment by SevenFxm** [comment]
上游系统的数据库好像是SQLServer 他们那边业务支持需要这么大的日期

**Comment by SevenFxm** [comment]
嗯嗯，理解咯非常感谢，另外我将9999转换下replace("\"9999-09-09\"", "\"9999-09-09  00:00:00\""),貌似就支持了,是不是我超额的日期都要按这种格式转换下呃

**Comment by SevenFxm** [comment]
应该是超过3000年都要这么操作嘛？
