### ISSUE TITLE
当类中属性未提供getter方法，序列化为“{}”

### ISSUE THREAD

**Issue by butioy** [alibaba/fastjson#1145]
今天没事写着玩，出现一个问题，网上也没找到什么好的方案。
写了一个普通的类，里面的3个属性没有提供getter方法，序列化时是一个空json。

![entity](https://cloud.githubusercontent.com/assets/3390055/25012429/0db248d2-20a3-11e7-8400-bb2a04354cbe.JPG)

![serializer](https://cloud.githubusercontent.com/assets/3390055/25012714/f627ecc0-20a3-11e7-9a72-f58646dbdfdb.JPG)

这个是FastJson的问题，还是我这边使用的方式不对？如果是我使用方式不对，还请告诉我正确的使用方法， 还有就是我不想在实体类中加上getter方法！！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/FieldBased_cn
这个是不是你需要的？
