### ISSUE TITLE
如果一个字段有数据为数组，没数据为空字符串，我该如何解析

### ISSUE THREAD

**Issue by yizems** [alibaba/fastjson#1150]
能不能类型错误的时候 ，给予null值，或者空数组，不要直接崩溃

**Comment by xiaochengxuyuan** [comment]
@yizeliang  这不是你直接 try-catch 一下想怎么来就怎么来了。。。

**Comment by wenshao** [comment]
这是个问题，将会解决，不过你最好提供样本，这样好能确保解决你的问题。

**Comment by yizeliang** [comment]
@wenshao 我fork了Android分支上的项目,直接在抛出异常的地方 return 就能拿到空的List,我这里是针对List,对数组没有测试 , 我前段时间有试过master分支上的代码去解析,发现会产生一个 只有一个元素的List,第一个元素为null,,这个就很尴尬了,,,,下面是数据样本:
正常数据json:
{
    "list": [
        "aaa",
        "bbb"
    ]
}
不正常json:
{
    "list": ""
}

解析类:
public class Demo{
public List<String> list;
getter...
setter...
}
恩,大概就这个样子,总体来说还是 后台数据不够规范引起的,也是出于无奈,接口没有办法去修改,所以,,,这是一个悲伤的故事....

**Comment by wenshao** [comment]
我会尽快发布一个新版本，也许就是这几天

**Comment by wenshao** [comment]
标准版本和android版本都已经修复，我会尽快发布一个新的android版本。

**Comment by yizeliang** [comment]
@wenshao 3Q,修复bug 速度真快 =.=
