### ISSUE TITLE
bean有重载的set方法时，解析不稳定，有时候不能重载正确的set方法

### ISSUE THREAD

**Issue by viphyy** [alibaba/fastjson#1154]
比如
class Goods{

- [ ] //...

setPrice(String price)
setPrice(Integer price)
//...
}
传json {"price":"23"}

有时候不能正确匹配setPrice(String price) ,大多时候可以正常解析

**Comment by wenshao** [comment]
这个问题修复过，你用的是什么版本？升级到1.2.31试试看

**Comment by viphyy** [comment]
赞赞赞
