### ISSUE TITLE
Spring 4.3.7 @ResponseBody 返回Json格式String 带\

### ISSUE THREAD

**Issue by wudihaike** [alibaba/fastjson#1163]
1.说明
接口是调用第三方的,返回的就是json,所以直接用String输出到前端了,原先用的是**Jackson**,是没问题.
2.后台JAVA
```
@PostMapping("HPImageArchive")
@ResponseBody
public String HPImageArchive(@RequestParam String date)
```
3.返回
```{"data":"{\"images\":[{\"startdate\":\"20170423\",\"fullstartdate\":\"201704231600\",\"enddate\":\"20170424\",\"url\":\"/az/hprichbg/rb/AlbertaTeepee_ZH-CN11572775476_1920x1080.jpg\",\"urlbase\":\"/az/hprichbg/rb/AlbertaTeepee_ZH-CN11572775476\",\"copyright\":\"一个圆锥形帐篷，加拿大艾伯塔省南部 (© ImagineGolf/Getty Images)\",\"copyrightlink\":\"http://www.bing.com/search?q=%E5%B8%90%E7%AF%B7&form=hpcapt&mkt=zh-cn\",\"quiz\":\"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20170423_AlbertaTeepee%22&FORM=HPQUIZ\",\"wp\":true,\"hsh\":\"b38751dbd64b23ac0f3aecbc06ce6974\",\"drk\":1,\"top\":1,\"bot\":1,\"hs\":[]}],\"tooltips\":{\"loading\":\"正在加载...\",\"previous\":\"上一个图像\",\"next\":\"下一个图像\",\"walle\":\"此图片不能下载用作壁纸。\",\"walls\":\"下载今日美图。仅限用作桌面壁纸。\"}}\r\n","message":"","ok":true,"stateCode":"100"}```

**Comment by wenshao** [comment]
data的数据类型是String，序列化的结果当然是带\。看看这个是不是你要：https://github.com/alibaba/fastjson/wiki/JSONField_jsonDirect_cn
