### ISSUE TITLE
无法将开头为“__”转成JsonString

### ISSUE THREAD

**Issue by shuiyueIII** [alibaba/fastjson#1165]
变量
Number __v;
转成jsontring变为了
"__v":{}
转换出错！

**Comment by wenshao** [comment]
Number不应该转换为{}的，怎样的场景？

**Comment by shuiyueIII** [comment]
不是number的问题，是变量名的问题，变量名以两个“_”开头是有问题的，用toJsonString()转就会转错

**Comment by wenshao** [comment]
如果https://github.com/alibaba/fastjson/commit/14add663b0f7928c15b29603e95ee51d71bbe79f 这个testcase，问题没有重现

**Comment by shuiyueIII** [comment]
public static void main(String[] args){
        Model model = new Model();
        model.set__v(3);
        String json = JSON.toJSONString(model);
        assertEquals("{\"__v\":3}", json);
    }
    public static class Model {
        public Number __v;
        public Number get__v() {
            return __v;
        }
        public void set__v(Number __v) {
            this.__v = __v;
        }
    }
直接赋值没有问题，自动生成的getter和setter后，转换成的json就生成{"__v":3,"_v":3}了
