### ISSUE TITLE
JSON.toJavaObject can't be compatible 

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/fastjson#1178]
```
public class TestModel implements Serializable {
    public String info;
}
```

```
String json = "{\n" +
            " \"info\": {\n" +
            "        \"test\": \"\", \n" +
            "    }\n" +
            "}";

JSONObject jsonObject = JSON.parseObject(json);
TestModel loginResponse = JSON.toJavaObject(jsonObject, TestModel.class);

```

If I use the version <= 1.1.46.android,there is no problem.But if I use the version > 1.1.46.android, it will throw a JSONException(can not get javaBeanDeseriallizer)

I must write the modle like this when the version > 1.1.46.android
```
public class TestModel implements Serializable {
    public JSONObject info;
}

```

Is there any solution？

**Comment by wenshao** [comment]
问题修复并已发布 https://github.com/alibaba/fastjson/releases/tag/1.1.57.android
