### ISSUE TITLE
fastjson能否设置不序列化lazy的数据？

### ISSUE THREAD

**Issue by RozwelGustab** [alibaba/fastjson#1190]
springboot1.4.2 
fastjson1.2.31
```
 @OneToMany(mappedBy = "department",fetch = FetchType.LAZY)
 private List<Employee> employees;
```
在entity中已经设置为fetch为lazy了
但是在序列化的时候 还是会去将这个lazy的数据加载出来
有没有类似于jackson中FORCE LAZY LOADING这样的设置？

**Comment by wenshao** [comment]
按理来说不应该的，在com.alibaba.fastjson.util.TypeUtils#isProxy这个方法中如果识别到是hibernate的代理，就会unwrap处理，从而避免lazy loading，你能帮忙调试一下是怎么情况么？

**Comment by RozwelGustab** [comment]
@wenshao  刚刚大概调试了一下
hibernate的版本是5.2.4.Final
TypeUtil中的断点一直没有进去（除了刚开始Config里进了一下）
具体是这样的情况
Department这个实体中有FetchType.LAZY的List Employee
当spring.jpa.open-in-view保持默认的true时
在FiledInfo.class中
```
public Object get(Object javaObject) throws IllegalAccessException, InvocationTargetException {
        if(this.method != null) {
            Object value = this.method.invoke(javaObject, new Object[0]);
            return value;
        } else {
            return this.field.get(javaObject);
        }
    }
```
invoke 了getEmployees方法 从而加载了lazy的employees

接下来我将spring.jpa.open-in-view设置为false
同样运行到上面的get(Object javaObject)时 没有加载lazy的数据
此时return的value是一个PersistentBag
最终在ListSerializer 的write方法中触发了LazyInitializationException。
```
 if(object == null) {
            out.writeNull(SerializerFeature.WriteNullListAsEmpty);
        } else {
            List list = (List)object;
            if(list.size() == 0) {
                out.append("[]");
            } else {········
```
在调用list.size()的时候抛出了LazyInitializationException。

**Comment by wenshao** [comment]
已经支持，预计下个周末（5月21日）发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。

**Comment by izern** [comment]
还是不行啊，我在isProxy 打断点，根本没有运行到这。hibernate version4.3.6
并且在类中的懒加载的属性，显示的是XX = persistenBag
![image](https://user-images.githubusercontent.com/17672970/29658895-2376071c-88ef-11e7-9877-663ae567e899.png)

**Comment by neil4dong** [comment]
@izern  你需要去看一下hibernate 的LazyInitializationException相关的内容。 这个错误不是由于Fastjson导致的。 而是fastjson在序列化的时候调用了属性的getXXX方法。  你调用的地方或者配置不对。 你直接调用getXXX也是会抛出这个异常的。

**Comment by izern** [comment]
@neil4dong 这个异常我是知道的。 但是fastjosn在1.2.33 设置了不序列化lazy的属性，理论上不应该调用这个get方法，不序列化属性。 但是结果还是序列化了

**Comment by MroZ11** [comment]
如果我需要序列化懒加载对象 应该怎么做？
