### ISSUE TITLE
fastjson 怎么这么不稳定啊？表示很伤心

### ISSUE THREAD

**Issue by jarvan4dev** [alibaba/fastjson#1196]
1.2.29版本 @JSONField(serialzeFeatures = SerializerFeature.WriteEnumUsingToString) 无效，已经复写了toString方法，然后切换到1.2.32版本又好了，表示很伤心啊，温少 @wenshao 这样怎么用到生产中啊？！求稳定，一直很看好fastjson的

**Comment by xusheng1987** [comment]
SerializerFeature无效的地方还有不少呢，得慢慢修复

**Comment by wenshao** [comment]
之前没做JSONField上的支持，升级到新版本就好了，这个不完全算是稳定性问题，应算是是功能不完整

**Comment by jarvan4dev** [comment]
@wenshao JSONType我也试过了，也不行啊

**Comment by wenshao** [comment]
JSONType已经支持了，等下个版本发布吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
