### ISSUE TITLE
android版本的TypeReference类并没有带参构造方法 

### ISSUE THREAD

**Issue by Zengyonghao** [alibaba/fastjson#1197]
无法传入type 所以当使用泛型反序列化的时候会照成解析出来的对象是jsonobject类型

**Comment by Zengyonghao** [comment]
无法传入type 所以当使用泛型反序列化的时候会解析出来的泛型为jsonObject

**Comment by wenshao** [comment]
已经支持，请用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.58.android
