### ISSUE TITLE
$ref反序列化出现异常

### ISSUE THREAD

**Issue by gjbxx110** [alibaba/fastjson#1198]
`
{
  "types": [
    {
      "type": "com.taobao.mtop.common.Result",
      "$ref": "com.taobao.mtop.common.Result"
    }
  ]
}
`
这段在反序列化的时候，报错。
`
Object obj=JSON.parse(str, Feature.DisableCircularReferenceDetect);
`
需求是：忽略所有$ref字段

**Comment by wenshao** [comment]
什么版本？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
