### ISSUE TITLE
Android版本JSONField注解不支持alternate属性

### ISSUE THREAD

**Issue by msdx** [alibaba/fastjson#1199]
问题同https://github.com/alibaba/fastjson/issues/878
但Android版本（1.1.52.android）不支持。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/commit/1fc94116b909a1bc75c09527955ef0fa2356f50a 已经支持，将会在合适的时间发布新版本。

**Comment by wenshao** [comment]
已经支持，请用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.58.android
