### ISSUE TITLE
list中有重复对象时，生成的json后有{"$ref":"$[14]"}等异常字符串

### ISSUE THREAD

**Issue by creky** [alibaba/fastjson#120]
list中有重复对象时，使用JSONArray.toJSONString(items)生成的json后有{"$ref":"$[14]"}等异常字符串。如下：
{正常json字符串},{"$ref":"$[10]"},{"$ref":"$[11]"
},{"$ref":"$[12]"},{"$ref":"$[13]"},{"$ref":"$[14]"},{"$ref":"$[15]"},{"$ref":"$
[16]"},{"$ref":"$[17]"},{"$ref":"$[18]"},{"$ref":"$[19]"},{"$ref":"$[20]"},{"$re
f":"$[21]"},{"$ref":"$[22]"},{"$ref":"$[23]"},{"$ref":"$[24]"},{"$ref":"$[25]"},
{"$ref":"$[26]"},{"$ref":"$[27]"}]

**Comment by greenlaw110** [comment]
我们在实际工作中也遇到这种情况。后来的解决方案是在前端做一个resolver来解析引用，这个库发布到了npm上面：https://www.npmjs.com/package/fastjson_ref_resolver。如果有需要的同行，可以参考一下

**Comment by wikimore** [comment]
今天遇到这个问题了，说实话，这虽然是个功能，但是默认应该是关闭的吧。默认打开有点不顾使用者了。

**Comment by bcqtt** [comment]
我也遇到了，详细解决看这里
http://blog.csdn.net/bcqtt/article/details/75048833

**Comment by tianxianglan** [comment]
这应该是在业务层面避免这种情况吧，不过看看各位大佬的解决办法还是很受益的
