### ISSUE TITLE
toJavaObject 增加泛型支持

### ISSUE THREAD

**Issue by anjia0532** [alibaba/fastjson#1205]
参考 #969 

需求，将一个json字符串中的某个key转换成JavaBean。

```java
jsonobj.getJSONObject("key").toJavaObject(new TypeReference<List<vo>>(){}.getType());
```
报错，`The method getObject(String, Class<T>) in the type JSONObject is not applicable for the arguments (String, Type)`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。

**Comment by anjia0532** [comment]
好的，温少
