### ISSUE TITLE
enum实现JSONAware的时候，没有调到JSONAware里面去

### ISSUE THREAD

**Issue by nuclearg** [alibaba/fastjson#1222]
定义一个enum，并且实现JSONAware接口。

期望能够使用JSONAware的toJSONString输出，但实际走的是enum的name()。

版本号1.2.27和1.2.32都试过了

在我的工程里可以稳定重现，但目前还未能构造一个精简的case，所有把这段代码摘出来的测试都可以走到JSONAware里面去。

类结构大致如下：

![image](https://cloud.githubusercontent.com/assets/1854156/26364096/b162cc2c-4015-11e7-8c66-7303b28b78c4.png)

在调用 type的get方法时的堆栈如下：

![image](https://cloud.githubusercontent.com/assets/1854156/26364214/212cc45e-4016-11e7-86fd-051ec17ff4a4.png)

希望这个堆栈信息能够有所帮助

**Comment by kimmking** [comment]
原来是你，明天我看看。

**Comment by kimmking** [comment]
恩济，加我微信，名字就叫kimmking

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
