### ISSUE TITLE
1.1.57.android  DefaultFieldDeserializer 没有处理 parser.context 为 null 的情况，导致解析出错

### ISSUE THREAD

**Issue by yrom** [alibaba/fastjson#1231]
粗略看了下[DefaultJSONParser.java](https://github.com/alibaba/fastjson/blob/android/src/main/java/com/alibaba/fastjson/parser/DefaultJSONParser.java)代码，这个 [context](https://github.com/alibaba/fastjson/blob/android/src/main/java/com/alibaba/fastjson/parser/DefaultJSONParser.java#L1320) 在 `lexer.disableCircularReferenceDetect` 为 true 的时候不会被赋值。即指定了 `Feature.DisableCircularReferenceDetect` 之后。

而 master 分支上的 [DefaultFieldDeserializer.java](https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/parser/deserializer/DefaultFieldDeserializer.java#L51) 代码其实处理了。

**Comment by wenshao** [comment]
已经支持，请用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.58.android
