### ISSUE TITLE
自定义注解与自定义Serializer的疑问

### ISSUE THREAD

**Issue by hillfly** [alibaba/fastjson#1234]
目前我有这样的需求：
实体类中有key字段，转json时我需要把key转换为对应的value，但是由于转换映射表有多个，所以我想用自定义注解在key字段上进行标注，类似这样 '@TransferVal("tableName")' ，然后在自定义Serializer中进行转换。
现在我在ObjectSerializer中并没有找到有获取字段Field或者获取自定义注解的地方，请问有办法吗？

在jackson中可以在Serializer中实现ContextualSerializer，在beanProperty中可以获取自定义注解信息。

谢谢！

**Comment by wenshao** [comment]
参考这个 https://github.com/alibaba/fastjson/wiki/ContextValueFilter
