### ISSUE TITLE
android1.1.5.7版本 seeAlso在解析子类的时候，只能通过内定关键字@type去解析

### ISSUE THREAD

**Issue by sandywen123** [alibaba/fastjson#1236]
android1.1.5.7版本 客户端在通过seeAlso在反序列化json数据的时候，只能通过识别内定关键字@type去解析，是否能提供自定义关键字，比如我想通过关键字“floortype”去实现，因为服务端不一定用的fastjson，所以我想能不能提供自定义SeeAlso反序列化化关键字的功能。
SerializeConfig.getGlobalInstance().setTypeKey();这个只能定义序列化的关键字，不能定义反序列化解析的关键字

**Comment by wenshao** [comment]
已经支持，请用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.58.android
