### ISSUE TITLE
springMVC中使用带下划线开头的变量 下划线丢失

### ISSUE THREAD

**Issue by pphh77** [alibaba/fastjson#1254]
springMVC4.3.8  fastjson版本1.2.32
<bean id="fastJsonHttpMessageConverter4"
				class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4">
有一个实体中变量为_parentId 返回后前面的_就没有了,换成springMVC默认的转换器jackson2.8.2就没有问题

**Comment by kimmking** [comment]
确实存在，testcase如下：
https://github.com/kimmking/fastjson/commit/42d10a67415dc8b9113cddd57e417cd033fda0ec

**Comment by wenshao** [comment]
故意这样设计的，请使用@JSONField
```java
    public static class B {
        @JSONField(name = "_parentId")
        private String _parentId;

        public String get_parentId() {
            return _parentId;
        }

        public void set_parentId(String _parentId) {
            this._parentId = _parentId;
        }
    }
```

**Comment by pphh77** [comment]
@wenshao ，那这样就太麻烦了 我不可能去把项目里面所有的字段看看有没有_开头的然后都找出来加上@jsonfield，如果换成别的json库还得每个去掉。
