### ISSUE TITLE
class泄漏问题

### ISSUE THREAD

**Issue by wizardleeen** [alibaba/fastjson#1258]
在jetty容器中用fastjson序列化HttpServletRequest对象或导致class泄漏，严重时会导致meta区溢出，导致无限FGC。详见: [分析文档](http://13009206.blog.51cto.com/12999206/1934624)

**Comment by kimmking** [comment]
jetty class泄露的坑很多，源代码里我记得一大堆处理具体class泄露的trick代码，我感觉可能需要把fastjson也mock进去。

**Comment by kimmking** [comment]
还有不应该直接序列化HttpServletRequest类，建议封装POJO来序列化。

**Comment by kimmking** [comment]
从你描述的情况来看，bug应该提交到jetty。

另外不知道你用的jetty版本是多少，最新版本是否也有此问题。

**Comment by wizardleeen** [comment]
jetty版本：8.1.16.v20140903。  jetty也有bug，他的设计意图应该是：WebAppClassLoader先自己load，load不到再让parent load，实际情况是自己loadClass失败就报异常了。 最新版本的jetty已经修复了。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.34 问题已经修复，请使用新版本。
