### ISSUE TITLE
NameFilter和ValueFilter的效果不正确啊

### ISSUE THREAD

**Issue by FrankKS** [alibaba/fastjson#1274]
<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.9</version>
		</dependency>

----------------------------
public class JSONTest2 {
static class User{
		private int id;
		
		private String name;// 姓名
		
		private int age; // 年龄
		
		// 配置序列化的名称
		 
		private String sex;

		public User(){}
		public User(int id, String name, int age, String sex) {
			super();
			this.id = id;
			this.name = name;
			this.age = age;
			this.sex = sex;
		}

		/**
		 * @return the id
		 */
		public int getId() {
			return id;
		}

		/**
		 * @param id the id to set
		 */
		public void setId(int id) {
			this.id = id;
		}

		/**
		 * @return the name
		 */
		public String getName() {
			return name;
		}

		/**
		 * @param name the name to set
		 */
		public void setName(String name) {
			this.name = name;
		}

		/**
		 * @return the age
		 */
		public int getAge() {
			return age;
		}

		/**
		 * @param age the age to set
		 */
		public void setAge(int age) {
			this.age = age;
		}

		/**
		 * @return the sex
		 */
		public String getSex() {
			return sex;
		}

		/**
		 * @param sex the sex to set
		 */
		public void setSex(String sex) {
			this.sex = sex;
		}
		
		
		
	}
	public static void main(String[] args) {
User user = new User();
		user.setAge(20);
		user.setId(10);
		user.setName("sadd");
		user.setSex("F");

NameFilter filter = new NameFilter() {
			@Override
			public String process(Object object, String name, Object value) {
				if (name.equals("name")) {
					return "nt";
				}
				return name;
			}
		};

		/*ValueFilter filter = new ValueFilter() {
			@Override
			public Object process(Object object, String name, Object value) {
				if (name.equals("name")) {
					return "张三";
				}
				return value;
			}
		};*/

String jsonString = JSON.toJSONString(user, filter);
		System.out.println(jsonString);  //{"age":20,"id":10,"name":"sadd","sex":"F"}这是最终的结果，难道是我用的方式不对？
}

**Comment by kimmking** [comment]
https://github.com/kimmking/fastjson/blob/2bc7b0bf8c9e80d85641351c6aba1015a3687c60/src/test/java/com/alibaba/json/bvt/issue_1200/Issue1274.java

see here

**Comment by FrankKS** [comment]
NameFilter和ValueFilter两个filter，关键需要@JSONType()注解到需要用到的对象上面:如:

**Comment by kimmking** [comment]
不需要手误而已
