### ISSUE TITLE
使用TypeReference导致我的应用内存泄露

### ISSUE THREAD

**Issue by FJCDrome** [alibaba/fastjson#1281]
写了段测试代码，放在Activity的onCreate执行，代码如下：
while (true) {
            String responseStr2 = "json数据";
            Result<Map<String, Object>> responseObject = JSON.parseObject(responseStr2, new       TypeReference<Result<Map<String, Object>>>() {});
        }
在运行过程中可以看到内存一直在稳定增长，请问为什么没有释放掉？
如果循环里面没有使用TypeReference，内存稳定在一定区域。
我使用的是    compile 'com.alibaba:fastjson:1.1.58.android'
如果使用方式有问题，请帮我指出，谢谢！

**Comment by jonenet** [comment]
Result<Map<String, Object>> responseObject  你的这个引用每次指向的都是一个新对象，堆内存坑定爆炸

**Comment by FJCDrome** [comment]
@jonenet 一次循环结束之后，这个对象不就没人引用他了吗，GC应该是可以回收掉的啊？实际回收不了。我不用TypeReference的时候，循环里面responseObject每次也是一个新的对象，但是这时候GC是可以回收的。

**Comment by FJCDrome** [comment]
![df1f3c05-ca42-419c-85a1-02eba2e20b74](https://user-images.githubusercontent.com/22695744/27465460-3a65010e-5806-11e7-90d2-ed46f0277a52.png)

**Comment by FJCDrome** [comment]
循环一段时间IdentityHashMap里面会越堆越多

**Comment by wuwen5** [comment]
我本地测试是正常的哦
jdk1.8.0_66.jdk
![image](https://user-images.githubusercontent.com/5037807/27465506-79e73bee-5806-11e7-9225-744149c32fe3.png)
![image](https://user-images.githubusercontent.com/5037807/27465531-b5a748f4-5806-11e7-8fd2-d5d80bbb0619.png)

```java
while (true) {
            String responseStr2 = "{value:{'key':'value'}}";
            Result<Map<String, Object>> responseObject = JSON.parseObject(responseStr2, new TypeReference<Result<Map<String, Object>>>() {});
        }
```
```java
public static class Result<T> {
        public T value;
    }
```

**Comment by FJCDrome** [comment]
@wuwen5 测试用的是com.alibaba:fastjson:1.1.58.android 这个版本吗？

**Comment by FJCDrome** [comment]
![test](https://user-images.githubusercontent.com/22695744/27465891-0bae013c-5809-11e7-8da4-d9edaca20e0d.png)

**Comment by FJCDrome** [comment]
按照我的测试
TypeReference<Result<Map<String, Object>>> typeface = new TypeReference<Result<Map<String, Object>>>() {};
        while (true) {
            String responseStr2 = "{value:{'key':'value'}}";
            Result<Map<String, Object>> responseObject = JSON.parseObject(responseStr2, typeface);
        }
这样内存是稳定的，如果每次都在循环里面new一个TypeReference
protected TypeReference(){
        Type superClass = getClass().getGenericSuperclass();

        type = ((ParameterizedType) superClass).getActualTypeArguments()[0];
    }
这里获取的type每次都是一个新的实例，我看到说type会是IdentityHashMap的key对吧，这就可以解释了。但是为什么你在循环里面每次也是new一个对象，测试会没问题，使我们用的fastjson版本不同吗
@wuwen5

**Comment by FJCDrome** [comment]
针对我的情况，自己根据泛型缓存一份TypeReference
    private static Map<Class,TypeReference> resultMap;
    public static  <K> TypeReference<Result<K>>  getResultTypeReference(final K k){
        if(resultMap == null){
            resultMap = new HashMap<>();
        }
        TypeReference<Result<K>> typeReference = resultMap.get(k.getClass());
        if(typeReference == null){
            typeReference = new TypeReference<Result<K>>(){};
            resultMap.put(k.getClass(),typeReference);
        }
        return typeReference;
    }
能解决我现在遇到的问题，先不管了..如果有什么新的进展，please @我一下

**Comment by wuwen5** [comment]
@FJCDrome 我是在java jdk环境测试的， 奇怪 好像安卓的环境下确实有问题，我先装个安卓环境再试试.

另外你可以使用多参数的写法测试下，带参数的写法内部会自己缓存.

```
public static <T> Response<T> parseToMap(String json, Class<T> type) {
     return JSON.parseObject(json, 
                            new TypeReference<Response<T>>(type) {});
}
```

**Comment by FJCDrome** [comment]
@wuwen5 多参数的方式试了一下，直接拷例子的代码，没有内存泄露的问题。

**Comment by FJCDrome** [comment]
public static <K, V> Map<K, V> parseToMap(String json, K keyType, V valueType) {
        return JSON.parseObject(json, new TypeReference<Map<K, V>>(keyType.getClass(), valueType.getClass()) {});
    }

String json = "{1:{name:\"ddd\"},2:{name:\"zzz\"}}";
        while (true){
            Map<Integer, Result> map = parseToMap(json, 1, new Result());
        }
不过我这样测试，内存还是会不停的增长。按照我的理解，这里.class和getClass效果应该是一样的啊
