### ISSUE TITLE
scala JSON.toJSONString error

### ISSUE THREAD

**Issue by shijinkui** [alibaba/fastjson#1282]
code below:

```
object JsonUtil {
  def main(args: Array[String]): Unit = {
    val obj = Test(111, "Ssldjflds")
    import com.alibaba.fastjson.JSON
    val jsonString = JSON.toJSONString(obj)
    println(jsonString)
  }

}

case class Test(i: Int, j: String)
```

error:

```
error: ambiguous reference to overloaded definition,
[ERROR] both method toJSONString in object JSON of type (x$1: Any, x$2: com.alibaba.fastjson.serializer.SerializerFeature*)String
[ERROR] and  method toJSONString in object JSON of type (x$1: Any)String
[ERROR] match argument types (com.huawei.dfs.util.Test)
[ERROR]     val jsonString = JSON.toJSONString(obj)
```

**Comment by kimmking** [comment]
暂不支持scala的class/object/caseclass, 你可以使用
https://github.com/json4s/json4s

**Comment by shijinkui** [comment]
> 暂不支持scala的class/object/caseclass, 你可以使用

Thanks. scala是有不少可选的json库.

**Comment by DecKen** [comment]
@shijinkui 改下代码还是可以使用
object JsonUtil {
  def main(args: Array[String]): Unit = {
    val obj = Test(111, "Ssldjflds")
    import com.alibaba.fastjson.JSON
    val jsonString = JSON.toJSONString(obj, SerializerFeature.EMPTY: _*)   // 使用这个方法绕过toJSONString(Object object, SerializerFeature... features), 原来代码实际调用的是toJSONString(object, emptyFilters), 这样用SerializerFeature.EMPTY: _*代替, : _*就是scala将emptyFilters转成可变长参数
    println(jsonString)
  }
}

import scala.beans.BeanProperty
case class Test(@BeanProperty i: Int, @BeanProperty j: String)   //加上BeanProperty的目的是让这个类有getter和setter方法

**Comment by iluvsnail** [comment]
我是用java代码折中了下

**Comment by chengxii** [comment]
使用这个代替了一下
JSON.toJSONString(msg, new SerializeFilter[0])
![image](https://user-images.githubusercontent.com/24629765/40896939-943f2386-67ea-11e8-8dbd-43c2ee9b8270.png)

**Comment by schahaha** [comment]
> @shijinkui 改下代码还是可以使用
> object JsonUtil {
> def main(args: Array[String]): Unit = {
> val obj = Test(111, "Ssldjflds")
> import com.alibaba.fastjson.JSON
> val jsonString = JSON.toJSONString(obj, SerializerFeature.EMPTY: _*) // 使用这个方法绕过toJSONString(Object object, SerializerFeature... features), 原来代码实际调用的是toJSONString(object, emptyFilters), 这样用SerializerFeature.EMPTY: _*代替, : _*就是scala将emptyFilters转成可变长参数
> println(jsonString)
> }
> }
> 
> import scala.beans.BeanProperty
> case class Test(@BeanProperty i: Int, @BeanProperty j: String) //加上BeanProperty的目的是让这个类有getter和setter方法

加上SerializerFeature.EMPTY这个确实就生效了，谢谢。

**Comment by KevinYangCode** [comment]
对象里面存在List<User> 字段，转化不出来
