### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to com.alibaba.fastjson.JSONObject

### ISSUE THREAD

**Issue by z7658329** [alibaba/fastjson#1296]
code:
JSON.parseObject("1");

then throw Exception:
![image](https://user-images.githubusercontent.com/5474723/27627047-f66853a0-5c1c-11e7-925d-70d68d56c6c6.png)

原因：fastJson解析的时候 判断入参是原始类型，就直接返回原始类型数据，这样在JSON类 parseObject处理直接报错
![image](https://user-images.githubusercontent.com/5474723/27627186-6eabda12-5c1d-11e7-8232-de757e8b4e82.png)

能不能统一封装一下所有的Exception，对外抛出JSONException

**Comment by z7658329** [comment]
其实挺建议fastJson针对一个parseXXX的方法 对外只抛出一个解析异常的这样更友好

**Comment by z7658329** [comment]
@wenshao  所以，你们的观点是？

**Comment by wenshao** [comment]
我认同

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.34 问题已经修复，请使用新版本。
