### ISSUE TITLE
writeNonStringValueAsString 属性的作用范围

### ISSUE THREAD

**Issue by feixueck** [alibaba/fastjson#1297]
该属性可以将非string类型的转换成string输出 ,但是我想得到一个 value完全是字符串的json返回,
发现date类型的 属性 输出仍然是 数字,没有用双引号包裹. 其他的是正常的.
麻烦问下 date类型的 要怎么设置 或者 能不能设置成 也返回一个字符串类型的时间戳? 
比如 :如下用法 
`String text = JSON.toJSONString(vo, SerializerFeature.WriteNonStringValueAsString);`
得到了:
`{"gmtCreated":1498704358837,"id":"111"}`
想要的是
`{"gmtCreated":"1498704358837","id":"111"}`

**Comment by wenshao** [comment]
使用1.2.33版本试试看？

**Comment by feixueck** [comment]
上面的问题就是针对1.2.33版本的 .
不过改自己改造了下,在配置fastJsonConfig的时候,属性serializeConfig里面put了一个自定义的DateSerilializer,专门转换date类型的 .
多谢回复 .
