### ISSUE TITLE
can not cast to Date, value : 2017-06-29T08:06:30.000+05:30

### ISSUE THREAD

**Issue by slbfs** [alibaba/fastjson#1298]
使用北京时区 +08:00 转换没有问题，切换时区后，转换出现异常；
com.alibaba.fastjson.JSONException: can not cast to Date, value : 2017-06-29T08:06:30.000+05:30
	at com.alibaba.fastjson.util.TypeUtils.castToDate(TypeUtils.java:327)
	at com.alibaba.fastjson.JSONObject.getDate(JSONObject.java:286)

**Comment by kimmking** [comment]
能否提交一个测试代码

**Comment by wenshao** [comment]
问题已经修复，请使用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.35
