### ISSUE TITLE
java.lang.ClassCastException: org.json.JSONArray cannot be cast to com.alibaba.fastjson

### ISSUE THREAD

**Issue by huminted** [alibaba/fastjson#1303]

**Comment by kimmking** [comment]
can you submit some codes for reproducing
 this error,thx

**Comment by huminted** [comment]
JSONArray array=new JSONArray(jsonArray);
            for (int i = 0; i <array.size() ; i++) {
                JSONObject object=jsonArray.getJSONObject(i);
                cartlist.add(new CartList(object.getString("name"),
                                          object.getString("imgurl"),
                                          (object.getString("prices"))));
                total=total+ Double.valueOf(object.getString("prices"));
            }
            System.out.println("total"+total);
            tvtotla.setText(String.valueOf(total));


            adapter =new CartAdapter(cartlist);
                recyclerView.setAdapter(adapter);



        } catch (JSONException e) {
            e.printStackTrace();
        }

**Comment by kimmking** [comment]
jsonArray is

**Comment by huminted** [comment]
[{"author":{"__type":"Pointer","className":"_User","objectId":"a876c49c18"},"createdAt":"2017-07-02 20:06:13","imgurl":"https:\/\/ss0.bdstatic.com\/70cFuHSh_Q1YnxGkpoWK1HF6hhy\/it\/u=11075891,34401011&fm=117&gp=0.jpg","name":"衣架","objectId":"029d5493cd","prices":"1","updatedAt":"2017-07-02 20:06:13"}]

**Comment by kimmking** [comment]
jsonArray是字符串的话，jsonArray.getJSONObject(i)是不是写错了？

**Comment by kimmking** [comment]
怀疑你有地方写错了，如下代码运行时没有问题的，请参考：
```
public class Issue1303 extends TestCase {
    public void test_for_issue() {
        String jsonString = "[{\"author\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"a876c49c18\"},\"createdAt\":\"2017-07-02 20:06:13\",\"imgurl\":\"https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=11075891,34401011&fm=117&gp=0.jpg\",\"name\":\"衣架\",\"objectId\":\"029d5493cd\",\"prices\":\"1\",\"updatedAt\":\"2017-07-02 20:06:13\"}]";
        JSONArray jsonArray = JSON.parseArray(jsonString);
        //jsonArray = new JSONArray(jsonArray);//这一句打开也一样是正确的
        double total = 0;
        for (int i = 0; i <jsonArray.size() ; i++) {
            JSONObject object=jsonArray.getJSONObject(i);
            assertEquals("衣架",object.getString("name"));
            total=total+ Double.valueOf(object.getString("prices"));
        }
        assertEquals(1.0d,total);
    }
}
```
