### ISSUE TITLE
对象转Json报错空指针错误版本1.2.31不报错,1.2.32开始报错

### ISSUE THREAD

**Issue by topud** [alibaba/fastjson#1305]
从fastjson 1.2.32版本开始,xml转对象后(转换成功),再转Json (JSON.toJSONString)报错:
fieldinfo空指针错误

XML:
<config>
 
	<category>
 
		<category value="treeTable" label="树结构表（一体）">
			<template>treetable/controller.xml</template>
			<template>treetable/service.xml</template>
			<template>treetable/dao.xml</template>
			<template>treetable/entity.xml</template>
			<template>treetable/mapper.xml</template>
			<template>treetable/viewForm.xml</template>
			<template>treetable/viewList.xml</template>
		</category>
 

	</category>
 
	<javaType>
		<dict value="String" label="String"/>
		<dict value="Long" label="Long"/>
		<dict value="Integer" label="Integer"/>
		<dict value="Double" label="Double"/>
		<dict value="java.util.Date" label="Date"/>
		<dict value="com.treps.modules.sys.entity.SysUser" label="User"/>
		<dict value="com.treps.modules.sys.entity.Org" label="Org"/>
		<dict value="com.treps.modules.sys.entity.Area" label="Area"/>
		<dict value="This" label="ThisObj" description="生成当前对象"/>
		<dict value="Custom" label="Custom" description="自定义对象，生成后手动设置"/>
	</javaType>
 
	<queryType>
		<dict value="=" label="="/>
		<dict value="!=" label="!="/>
		<dict value="&gt;" label="&gt;"/>
		<dict value="&gt;=" label="&gt;="/>
		<dict value="&lt;" label="&lt;"/>
		<dict value="&lt;=" label="&lt;="/>
		<dict value="between" label="Between"/>
		<dict value="like" label="Like"/>
		<dict value="left_like" label="Left Like"/>
		<dict value="right_like" label="Right Like"/>
	</queryType>
 
	<showType>
		<dict value="label" label="标签"/>
		<dict value="input" label="单行文本"/>
		<dict value="textarea" label="多行文本"/>
		<dict value="select" label="下拉选项"/>
		<dict value="radiobox" label="单选按钮"/>
		<dict value="checkbox" label="复选框"/>
		<dict value="dateselect" label="日期选择"/>
		<dict value="userselect" label="人员选择"/>
		<dict value="orgselect" label="部门选择"/>
		<dict value="areaselect" label="区域选择"/>
		<dict value="treeselect" label="树选择控件"/>
		<dict value="fileselect" label="文件上传选择"/>
	</showType>
</config>

class1: GenConfig
/////////////////////////////////////
import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import com.treps.modules.sys.entity.Dict;

 
@XmlRootElement(name="config")
public class GenConfig implements Serializable {
	
	private static final long serialVersionUID = 1L;
	private List<GenCategory> categoryList;	// 代码模板分类
	private List<Dict> javaTypeList;		// Java类型
	private List<Dict> queryTypeList;		// 查询类型
	private List<Dict> showTypeList;		// 显示类型

	public GenConfig() {
		super();
	}

	@XmlElementWrapper(name = "category")
	@XmlElement(name = "category")
	public List<GenCategory> getCategoryList() {
		return categoryList;
	}

	public void setCategoryList(List<GenCategory> categoryList) {
		this.categoryList = categoryList;
	}

	@XmlElementWrapper(name = "javaType")
	@XmlElement(name = "dict")
	public List<Dict> getJavaTypeList() {
		return javaTypeList;
	}

	public void setJavaTypeList(List<Dict> javaTypeList) {
		this.javaTypeList = javaTypeList;
	}

	@XmlElementWrapper(name = "queryType")
	@XmlElement(name = "dict")
	public List<Dict> getQueryTypeList() {
		return queryTypeList;
	}

	public void setQueryTypeList(List<Dict> queryTypeList) {
		this.queryTypeList = queryTypeList;
	}

	@XmlElementWrapper(name = "showType")
	@XmlElement(name = "dict")
	public List<Dict> getShowTypeList() {
		return showTypeList;
	}

	public void setShowTypeList(List<Dict> showTypeList) {
		this.showTypeList = showTypeList;
	}
	
}
 
/////////////////////////////////////

**Comment by kimmking** [comment]
能否做个testcase，谢谢。

**Comment by wenshao** [comment]
问题已经修复，请使用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.35
