### ISSUE TITLE
反序列化时，字符串能不能自动去除两端空白呢（Trim)

### ISSUE THREAD

**Issue by bingoohuang** [alibaba/fastjson#1310]

**Comment by kimmking** [comment]
建议在业务里处理，这样做改变了语义。

**Comment by bingoohuang** [comment]
可以加一个类似序列化时的ValueFilter么，可以自己添加额外的处理。或者自己定制化一个StringDeserializer，来做自动trim啊，我一会试试看。

**Comment by bingoohuang** [comment]
ParserConfig.getGlobalInstance().putDeserializer(DateTime.class, new JodaDateTimeDeserializer()); 
ParserConfig.getGlobalInstance().putDeserializer(String.class, new TrimStringDeserializer());
DateTime反序列化器，能正确使用，我重置String的反序列化器时，对于JAVABEAN中的String属性，则没有效果啊。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
已经支持，请使用新版本 
```java
public class Model {
     JSONField(format="trim")
     public String name;
}
```
