### ISSUE TITLE
fastjson的文档写的跟屎一样。 

### ISSUE THREAD

**Issue by lilijreey** [alibaba/fastjson#1314]
能把文档写好点不

**Comment by xuefenghai** [comment]
语气很不对，捡现成的，这么没品

**Comment by kimmking** [comment]
大家一起来写吧
我带头

**Comment by wenshao** [comment]
文档确实没写好，wiki文档权限是开放的，觉得有不好的地方，能参与进来一起改进么？

**Comment by lilijreey** [comment]
语气是有点不好，但是作者既然做开源项目就应该把文档放在很重要的位置。 我个人的遭遇是有一些case半天不知道怎样用fastjson实现。文档也没有交代。 要么看源码要么上网搜。 真心累人。
