### ISSUE TITLE
fastjson <1.2.34> java.lang.NullPointerException: null 	at com.alibaba.fastjson.util.FieldInfo.getFieldType(FieldInfo.java:302)

### ISSUE THREAD

**Issue by ohalo** [alibaba/fastjson#1316]
if (fieldType instanceof ParameterizedType) {
            ParameterizedType parameterizedFieldType = (ParameterizedType) fieldType;

            Type[] arguments = parameterizedFieldType.getActualTypeArguments();
            TypeVariable<?>[] typeVariables = null;
            ParameterizedType paramType = null;
            if (type instanceof ParameterizedType) {
                paramType = (ParameterizedType) type;
                typeVariables = clazz.getTypeParameters();
            } else if(clazz.getGenericSuperclass() instanceof ParameterizedType) {
                paramType = (ParameterizedType) clazz.getGenericSuperclass();
                typeVariables = clazz.getSuperclass().getTypeParameters();
            }

            boolean changed = getArgument(arguments, typeVariables, paramType.getActualTypeArguments());
            if (changed) {
                fieldType = new ParameterizedTypeImpl(arguments, parameterizedFieldType.getOwnerType(),
                                                      parameterizedFieldType.getRawType());
                return fieldType;
            }
        }

ParameterizedType paramType  is null  

下面的if判断条件都不满足，抛出异常了

**Comment by kimmking** [comment]
最新代码，已经改了

**Comment by kimmking** [comment]
@wenshao 跟#1306重复了
最近一次发布版本应该已经好了

**Comment by wenshao** [comment]
问题已经修复，请使用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.35
