### ISSUE TITLE
Fastjson for JAX-RS Provider 支持数据输出xss漏洞安全转义

### ISSUE THREAD

**Issue by tbjinyuan** [alibaba/fastjson#1321]
具体xss漏洞的data response输出
{
  "name": "<script>alert(1);</script>",
  "age": 18
}

安全转义后
{
  "name": "&lt;script&gt;alert(1);&lt;/script&gt;",
  "age": 18
}

建议方式
fastJsonConfig 可以提供一个方法由使用方set方法是否需要安全转义Feature，类似
fastJsonConfig.setSerializerFeatures(SerializerFeature.DisableCircularReferenceDetect);

**Comment by tbjinyuan** [comment]
安全转义后
{
  "name": "&lt;script&gt;alert(1);&lt;/script&gt;",
  "age": 18
}

**Comment by kimmking** [comment]
我总觉得这种validate操作应该是业务的一部分。
入库的时候应该就处理转义。

**Comment by wenshao** [comment]
SerializerFeature.BrowserSecure

**Comment by vipcxj** [comment]
话说这安全转义的例子是不是有问题，完全没看出转义前和转义后有什么区别~

**Comment by tbjinyuan** [comment]
@vipcxj 那是github显示问题

**Comment by wenshao** [comment]
问题已经修复，请使用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.35
