### ISSUE TITLE
不知道fastjson能不能在反序列化出现异常时定位到某一个类属性

### ISSUE THREAD

**Issue by Lostars** [alibaba/fastjson#1330]
比如一个属性是数字，json传入的是一个字母或者其他的东西，这时抛出的都是运行时异常，堆栈信息也无法精确定位到某一个属性，都是数字格式化异常或者其他什么的转换异常。

用了hibernate的验证这样可以统一的处理参数的问题，让报错更加的友好

**Comment by wenshao** [comment]
感谢反馈，问题已经修复，请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.37
