### ISSUE TITLE
fastjson don't work with jersey jsonp 

### ISSUE THREAD

**Issue by tbjinyuan** [alibaba/fastjson#1341]
1,代码demo:

@GET
@Path("{id}")
@Produces({"application/javascript","application/json"})
@JSONP(queryParam="callback")
public Book getBookById(@PathParam("id") Long id){
    return idBookMaps.get(id);
}

2,使用到jersey拦截器,fastjson扩展器

JsonWithPaddingInterceptor 默认框架注册，代码如下图：
@Override
    public void aroundWriteTo(final WriterInterceptorContext context) throws IOException, WebApplicationException {
        final boolean isJavascript = isJavascript(context.getMediaType());
        final JSONP jsonp = getJsonpAnnotation(context);

        final boolean wrapIntoCallback = isJavascript && jsonp != null;

        if (wrapIntoCallback) {
            context.setMediaType(MediaType.APPLICATION_JSON_TYPE);

            context.getOutputStream().write(getCallbackName(jsonp).getBytes(MessageUtils.getCharset(context.getMediaType())));
            context.getOutputStream().write('(');
        }

        context.proceed();

        if (wrapIntoCallback) {
            context.getOutputStream().write(')');
        }
    }

FastJsonProvider，显示注册  register(FastJsonFeature.class)，其中FastJsonFeature代码如下：
public class FastJsonFeature implements Feature {

    private final static String JSON_FEATURE = FastJsonFeature.class.getSimpleName();

    @Override
    public boolean configure(final FeatureContext context) {
        final Configuration config = context.getConfiguration();
        final String jsonFeature = CommonProperties.getValue(config.getProperties(), config.getRuntimeType(), InternalProperties.JSON_FEATURE, JSON_FEATURE,
            String.class);
        // Other JSON providers registered.
        if (!JSON_FEATURE.equalsIgnoreCase(jsonFeature)) {
            return false;
        }
        // Disable other JSON providers.
        context.property(PropertiesHelper.getPropertyNameForRuntime(InternalProperties.JSON_FEATURE, config.getRuntimeType()), JSON_FEATURE);
        // Register FastJson.
        if (!config.isRegistered(FastJsonProvider.class)) {
            //DisableCircularReferenceDetect
            FastJsonProvider fastJsonProvider = new FastJsonProvider();
            FastJsonConfig fastJsonConfig=new FastJsonConfig();
            //fastJsonConfig.setSerializerFeatures(SerializerFeature.DisableCircularReferenceDetect,SerializerFeature.BrowserSecure);

            fastJsonConfig.setSerializerFeatures(SerializerFeature.DisableCircularReferenceDetect);

            fastJsonProvider.setFastJsonConfig(fastJsonConfig);
            context.register(fastJsonProvider, MessageBodyReader.class, MessageBodyWriter.class);
        }
        return true;
    }

}

3,使用到jersey拦截器,fastjson扩展器

3.1 经过fastjson序列化后response返回时callback后面尾部数据被截断了，导致前端无法解析报错，如下：

curl -HAccept:application/javascript http://localhost:7001/api/books/2

callback({"bookId":2,"bookName":"Python源码剖析","isbn":"911122","publishTime":1500952351284,"publisher":"电子工业�%

3.2 注释掉//register(FastJsonFeature.class),启用框架自带jackson序列化后输出的正常的数据，能正常解析，如下：

curl -HAccept:application/javascript http://localhost:7001/api/books/2

callback({"bookId":2,"bookName":"Python源码剖析","publisher":"电子工业出版社","isbn":"911122","publishTime":1500953117679,"hello":null})%

4，环境版本，jersey 2.23.2;fastjson 1.2.35_preview_04

**Comment by wenshao** [comment]
@VictorZeng @neil4dong 帮忙看一下

**Comment by kimmking** [comment]
FastJsonProvider的兼容性确实有点问题，
我打了一个简单的例子，
 register(FastJsonProvider.class); 不好使
 register(JacksonJsonProvider.class); 好使

明天我再仔细看看

**Comment by VictorZeng** [comment]
我这里测试没发现该问题 jersey 2.23.2 fastjson 1.2.35

**Comment by kimmking** [comment]
奇数位乱码，感觉像是utf8的问题，楼主换英文试试截断不

**Comment by tbjinyuan** [comment]
@kimmking 一样的截断 
register(FastJsonFeature.class);
请求：
curl -HAccept:application/javascript http://localhost:7001/api/books/2

输出:
callback({"data":{"bookId":2,"bookName":"Python","isbn":"911122","publishTime":1501037292943,"publisher":"taibei"},"success":true,"timestamp":"2017-07-26 1%

另外我测试代码本身就是utf-8编码，样本数据
   bookStore.add(new Book(2L,"Python","taibei","911122",new Date()));

通用代码换成jackson,
 register(JacksonObjectMapperProvider.class);
 register(JacksonFeature.class);

输出效果：
callback({
  "timestamp" : "2017-07-25 22:58:02",
  "success" : true,
  "data" : {
    "bookId" : 2,
    "bookName" : "Python源码剖析",
    "publisher" : "电子工业出版社",
    "isbn" : "911122",
    "publishTime" : 1500994681985
  }
})

**Comment by tbjinyuan** [comment]
JacksonObjectMapperProviderdaima 代码如下，主要是去掉官方默认null值的输出
/*
 * @author zhengke(晋元)
 * @date 2017/7/25 下午10:21
 */
@Provider
public class JacksonObjectMapperProvider implements ContextResolver<ObjectMapper> {

    final ObjectMapper defaultObjectMapper;

    public JacksonObjectMapperProvider() {
        defaultObjectMapper = createDefaultMapper();
    }

    @Override
    public ObjectMapper getContext(final Class<?> type) {
        return defaultObjectMapper;
    }

    private static ObjectMapper createDefaultMapper() {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        return mapper;
    }

}

**Comment by VictorZeng** [comment]
@tbjinyuan 能否提交一下测试用例 我这里没法复现你的问题 testcase see #1342

**Comment by tbjinyuan** [comment]
/**
 * 书籍资源API接口管理类
 * @author zhengke(晋元)
 * @date 2017/5/8 下午7:43
 */
@Path("books")
@Api(value = "书籍web 资源服务", produces = "application/json")
public class BookResource extends BaseResource{

    private static final List<Book> bookStore = new ArrayList<>();
    private static  Map<Long,Book> idBookMaps = new HashMap<>();
    private static  Map<String,Book> nameBookMaps = new HashMap<>();

    static {
        bookStore.add(new Book(1L,"<script>Python基础教程;</script>","电子工业出版社","911122",new Date()));
        bookStore.add(new Book(2L,"Python","taibei","911122",new Date()));
        bookStore.add(new Book(3L,"Python学习手册","电子工业出版社","911122",new Date()));
        bookStore.add(new Book(4L,"可爱的Python","电子工业出版社","911122",new Date()));
        idBookMaps = CollectionConvertUtil.list2Map(bookStore,Book.class,"bookId");
        nameBookMaps = CollectionConvertUtil.list2Map(bookStore,Book.class,"bookName");
    }


    @POST
    @Path("{id}")
    @ApiOperation(value = "新增书籍",
        notes = "传入书籍id来修改书籍",
        response = Book.class)
    @ApiResponses(value = { @ApiResponse(code = 400, message = "id不合法"),
        @ApiResponse(code = 404, message = "未找到服务") })
    public Book createBook(@ApiParam("书籍id")@PathParam("id") Long id,@ApiParam("updateBook") Book newBook){
        newBook.setBookId(6L);
        return newBook;
    }

    @GET
    @Path("search")
    @ApiOperation(value = "根据条件查询书籍",response = Book.class,responseContainer = "List")
    public List<Book> searchBooks(@ApiParam("条件") @QueryParam("q") String q){
        return bookStore.stream()
            .filter(book -> book.getBookName().indexOf(q) > -1)
            .collect(Collectors.toList());
    }


    @PUT
    @Path("{id}")
    @ApiOperation(value = "根据ID修改书籍", response = Book.class)
    public Book updateBook(@ApiParam("书籍id")@PathParam("id") Long id, @ApiParam("updateBook") Book updateBook){
            return updateBook;
    }

    @DELETE
    @Path("{id}")
    @ApiOperation(value = "根据ID删除书籍")
    public boolean delBookById(@ApiParam("书籍id") @PathParam("id") Long id){
        idBookMaps.remove(id);
        return true;
    }


    @GET
    @ApiOperation(value = "分页查询",response = Book.class ,responseContainer = "List")
    public List<Book> getByPaging(@ApiParam("当前的页码") @QueryParam("start") int start,
                                  @ApiParam("每页的数量") @QueryParam("size") int size){
        return bookStore.subList(start,size);
    }

    @GET
    @Path("{id}")
    @ApiOperation(value = "获取图书信息",response = Book.class)
    @Produces({"application/javascript","application/json"})
    @JSONP(queryParam="callback")
    public Book getBookById(@PathParam("id")  @ApiParam("书籍id") Long id){
        return idBookMaps.get(id);
    }

    @GET
    @Path("list")
    @ApiOperation(value = "获取所有图书信息",response = Book.class)
    @JSONP(queryParam="callback")
    //@Produces({"application/json", "application/javascript"})
    @Produces({"application/javascript","application/json" })

    public List<Book> getBooks(){
        List books = new ArrayList();
        idBookMaps.values().stream().forEach(book -> books.add(book));
        return books;
    }

    @GET
    @Path("name")
    @ApiOperation(value = "获取图书信息",response = Book.class)
    @Produces({"application/javascript","application/json"})
    @JSONP(queryParam="callback")
    public String  getBookName(){
        return "jinyuan";
    }

}

**Comment by tbjinyuan** [comment]
关注jsonp请求   @GET
    @Path("{id}")
    @ApiOperation(value = "获取图书信息",response = Book.class)
    @Produces({"application/javascript","application/json"})
    @JSONP(queryParam="callback")
    public Book getBookById(@PathParam("id")  @ApiParam("书籍id") Long id){
        return idBookMaps.get(id);
    }，json请求是没问题的

**Comment by VictorZeng** [comment]
@tbjinyuan 抱歉，复现不出来你个问题，我的测试用例和你提供的基本一样，请见#1342
或者去掉swagger再试试

**Comment by neil4dong** [comment]
我这边也没法复现这个问题。   - -

**Comment by neil4dong** [comment]
@VictorZeng [https://github.com/alibaba/fastjson/pull/1342](url) 你添加的这个case可能不太准确。 我调试的时候发现有多个MessageBodyWriter ，然后获取到的是GensonJsonConverter实现，没有调用FastJsonProvider。 

但是我调试的时候手动改为FastJsonProvider也没能重现这个问题。

**Comment by VictorZeng** [comment]
@neil4dong 抱歉，测试用例是在本地工程写的，没发现这个问题，瞄了一眼Jersey源码，Genson有`AutoDiscoverable`的实现，所以自动加载了

**Comment by kimmking** [comment]
我这里可以稳定复现了，原因在于FastJsonProvider里直接把json的length作为Content Length输出了，实际上前后加了一个callbackName()，报文实际长度变了，client读取数据按Content Length就被截断了一部分。而且callbackName越长，截断的越多。

跟踪了一下jersey+jackson代码，发现jersey会自动添加Content Length，无需在jacksonProvider中处理，也就是说FastJsonProvider中的这个添加Content Length的操作完全是多余了。

**Comment by kimmking** [comment]
@wenshao @VictorZeng @neil4dong @tbjinyuan

**Comment by kimmking** [comment]
https://github.com/kimmking/fastjsontest

复现的代码。

**Comment by neil4dong** [comment]
真是厉害了。 看样子有必要加一些报文长度的单元测试

**Comment by tbjinyuan** [comment]
@wenshao @kimmking @VictorZeng @neil4dong @zhuzhaoyuan 感谢各位，kimmking  很👍，前端时间一直扎根在业务一个大项目中，没及时看到消息，今晚下载新版本，本地测试了，ok
