### ISSUE TITLE
PropertyNamingStrategy可以通过XML配置实现吗

### ISSUE THREAD

**Issue by muziling** [alibaba/fastjson#1343]
在XML里的 FastJsonHttpMessageConverter 位置，能直接配置PropertyNamingStrategy的属性吗，
比如配置为 SnakeCase。 如果可以的话，要怎么配置

**Comment by muziling** [comment]
自己写了一个类，配置到xml里面就可以了，看来代码只要对propertyNamingStrategy加一个set方法就可以了。

`
import com.alibaba.fastjson.PropertyNamingStrategy;
import com.alibaba.fastjson.serializer.SerializeConfig;

public class FastJsonSerializeConfig extends SerializeConfig {
    public FastJsonSerializeConfig() {

    }
    public void setPropertyNamingStrategy(PropertyNamingStrategy propertyNamingStrategy) {
        this.propertyNamingStrategy = propertyNamingStrategy;
    }
}
`

**Comment by kimmking** [comment]
你发现了一个问题，这个属性在SerializeConfig里是个public的field，而不是property

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
问题已经修复，请使用新版本
