### ISSUE TITLE
json 解析值问题

### ISSUE THREAD

**Issue by lveliu** [alibaba/fastjson#1358]
测试代码：
OrgCode bean:
public class OrgCode {
    private String orgcode;
    
    public String getOrgcode() {
        return orgcode;
    }

    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    @Override
    public String toString() {
        return "OrgCode {" +
                "orgcode='" + orgcode + '\'' +
                '}';
    }
}
运行示例：
public static void main(String[] args) {
     String json = "{\"orgcode\":\"11111\",\"orgCode\":\"222222\"}";
     OrgCode jsonBean= JSON.parseObject(json, OrgCode.class);
     System.out.println(jsonBean);
}
测试输出结果：
OrgCode {orgcode='222222'}

在对应bean里面创建一个orgCode 属性，结果正常，输出结果为：
OrgCode {orgcode='11111',orgCode='222222'}

对于我只需要小写的orgcode，在烦序列化时该如何配置。

测试发现：
该orgcode 被赋予了两次值，第一次是1111，第二次是222222，怎么能在反序列化时把属性真实对应起来，不要忽略大小写。

**Comment by ScienJus** [comment]
@lveliu 使用的版本是？在旧版本是有这个问题，但是新版本应该已经修复了。

**Comment by lveliu** [comment]
thinks 1.2.28 是这样  1.2.30 已经解决

**Comment by lveliu** [comment]
@wenshao  可以关闭此问题！ 1.2.30 已经解决该问题。
