### ISSUE TITLE
FastJsonProvider+httpclient出现异常"Content-Length header already present"

### ISSUE THREAD

**Issue by jqncc** [alibaba/fastjson#1361]
在resteasy client中使用fastjson的 provider替换默认的jackson,提交json数据是出现异常"Content-Length header already present",
resteasy client使用的是httpclient提交数据,这个异常是httpclient检查到http header里已经存在Content-Length所以抛出的,
在FastJsonProvider里writeTo方法发现有这样一句:httpHeaders.add("Content-Length", String.valueOf(len));

**Comment by kimmking** [comment]
使用目前主干代码版本即可。

**Comment by wenshao** [comment]
问题已经解决，预计在周末发布新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
问题已经修复，请使用新版本
