### ISSUE TITLE
反序列化时对map对象的处理的问题

### ISSUE THREAD

**Issue by ivansong92** [alibaba/fastjson#1363]
版本1.2.35，根据网友的http://blog.csdn.net/kkgbn/article/details/76349803 这个博客，问题仍旧在，问题出在DefaultJSONParser.handleResovleTask这个方法里，对于$ref这种，跟踪代码的时候都是扔ResovleTask交给DefaultJSONParser.handleResovleTask处理，问题原因就是对于$ref 指向前面map中的value时没有处理好，结果反序列化为null

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
问题已经修复，请使用新版本
