### ISSUE TITLE
如果对象属性为引用类型，toJSONString方法会出现反斜杠。

### ISSUE THREAD

**Issue by jwongo** [alibaba/fastjson#1369]
class Foo {
       int a;
       String b;
       Bar bars;
}

class Bar {
      int c;
}

Foo foo = new Foo();
...
JSON.toJSONString(foo);
其中a, b正常，c会带有反斜杠，包括key和value，求解。
DisableCheckSpecialChar不起作用，而且看源码已废弃。

**Comment by kimmking** [comment]
`
public class Issue1369 extends TestCase {
    public void test_for_issue() throws Exception {
        Foo foo = new Foo();
        foo.a = 1;
        foo.b = "b";
        foo.bars = new Bar();
        foo.bars.c = 3;
        String json = JSON.toJSONString(foo);
        System.out.println(json);
    }

    public static class Foo {
        public int a;
        public String b;
        public Bar bars;
    }
    public static class Bar {
        public int c;
    }
}
`
输出
`
{"a":1,"b":"b","bars":{"c":3}}
`
未发现此问题

**Comment by jwongo** [comment]
补充一点 
Bar是通过泛型接口拿到的数据
e.g.
<T> T getBar(String params); 
Bar bar = getBar(params);
