### ISSUE TITLE
kotlin该如何正确使用fastjson？

### ISSUE THREAD

**Issue by limuyang2** [alibaba/fastjson#1374]
kotlin中的data class，fastjson无法解析

**Comment by wenshao** [comment]
正在支持，android版本和标准都将会支持

**Comment by kimmking** [comment]
Ref: #1374

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.1.61.android
已经支持，请使用新版本

**Comment by limuyang2** [comment]
谢谢，一小时前看到您发布了61新版。幸苦了

发自我的 iPhone

在 2017年8月9日，00:54，高铁 <notifications@github.com<mailto:notifications@github.com>> 写道：


https://github.com/alibaba/fastjson/releases/tag/1.1.61.android
已经支持，请使用新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.1.62.android
1.1.62.android版本完善了kotlin支持，支持nullale dataclass
