### ISSUE TITLE
LinkedList序列化的性能bug

### ISSUE THREAD

**Issue by crazysheep2008** [alibaba/fastjson#1375]
测试代码如下：
import com.alibaba.fastjson.JSON;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

/***
 * @auth yfeng
 * @create 2017-08-06 9:53
 */
public class FastJSONTest {
    public static void main(String[] args) {
        List<Integer> arraylist = new ArrayList<>();
        List<Integer> linkedlist = new LinkedList<>();

        fillData(arraylist);
        fillData(linkedlist);

        toJSONTest(arraylist);
        toJSONTest(linkedlist);
    }

    private static void fillData(List<Integer> list) {
        for (int i = 0; i < 50000; i++) {
            list.add(i + 1);
        }
    }

    private static void toJSONTest(List<Integer> list) {
        long start = System.currentTimeMillis();
        String data = JSON.toJSONString(list, false);
        long end = System.currentTimeMillis();
        System.out.println(String.format("spend time %s ms", end - start));
    }
}
我的本机笔记本输出：
spend time 143 ms
spend time 5293 ms

性能bug的代码原因在JSONSerializer这个类中，对于prettyFormat = true的情况使用java 5增强for循环，即遍历器进行元素遍历序列化。但是对于prettyFormat = false的逻辑分支则统一使用了Object item = list.get(i);下标值的方式遍历，恰好对于LinkedList的链表结构非常吃力。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
问题已经修复，请使用新版本

**Comment by yangyangyaha** [comment]
这个真的解决了吗
![fastjsonbug](https://user-images.githubusercontent.com/4545922/48403952-17fff480-e76a-11e8-90b5-81d5cb0b07a2.png)
我看到ListSerializer中还是一样的问题呢
