### ISSUE TITLE
Java pojo long 通过 JSON.toJSONString(pojo) 精度丢失

### ISSUE THREAD

**Issue by whatisgolang** [alibaba/fastjson#1378]
public class A{
private long seqId;
//getter and setter
}

A a = new A();
a.setSedId(1287456613511241739l);

JSON.toJSONString(a);

seqid  值变成：1287456613511241700

**Comment by neil4dong** [comment]
看起来像是你写错了

**Comment by whatisgolang** [comment]
@neil4dong   my fault
