### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 160

### ISSUE THREAD

**Issue by Shadowsay** [alibaba/fastjson#1386]
java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:868)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:602)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1411)

spring mvc+ fastjson时出现问题。

fastjson版本号  1.2.35

提供测试数据
```# 今夏爱用护肤品安利 #  品牌：Tom Ford/汤姆福特        

      单品：四色眼影盘 色号：01#GOLDEN MINK              质地：粉状                            产地：美国                            参考价：588元 /10G       <img src="http://image.uhomed.com/ab5036a0011f567e78c205ef41dea34c.png" width="259" height="306">  TomFord四色眼影是我最喜欢的眼影系列之一。他家眼影粉质出众配色出彩上眼特别好看，又持久，不知道要画什么眼影的时候总是会拿来用。01Golden Mink是我入手的第一盘TomFord的眼影，当初也是做了很多功课。这盘有两格亮片色和两格丝光色。它的配色相对清淡日常又百搭，至今这盘的使用率也是最高的。  手臂试色图，如下：  <img src="http://image.uhomed.com/4c8ef07a71f36f138c81c2844f78282d.png" width="546" height="302">  #今夏爱用护肤品安利#                            ```

**Comment by Shadowsay** [comment]
@wenshao

**Comment by Shadowsay** [comment]
#今夏爱用护肤品安利#  品牌：Tom Ford/汤姆福特              单品：四色眼影盘 色号：01#GOLDEN MINK              质地：粉状                            产地：美国                            参考价：588元 /10G       <img src="http://image.uhomed.com/ab5036a0011f567e78c205ef41dea34c.png" width="259" height="306">  TomFord四色眼影是我最喜欢的眼影系列之一。他家眼影粉质出众配色出彩上眼特别好看，又持久，不知道要画什么眼影的时候总是会拿来用。01Golden Mink是我入手的第一盘TomFord的眼影，当初也是做了很多功课。这盘有两格亮片色和两格丝光色。它的配色相对清淡日常又百搭，至今这盘的使用率也是最高的。  手臂试色图，如下：  《img src="http://image.uhomed.com/4c8ef07a71f36f138c81c2844f78282d.png" width="546" height="302">  #今夏爱用护肤品安利#

**Comment by Shadowsay** [comment]
经测试，内容中出现\n 就会报错

**Comment by Shadowsay** [comment]
目测和这个问题是一样的 #125

**Comment by Shadowsay** [comment]
经测试，那个空格配着 换行\ n 就会出现此问题

**Comment by 1021683053** [comment]
@Shadowsay 你个大傻吊！
