### ISSUE TITLE
fastjson  处理 boolean  返回空值

### ISSUE THREAD

**Issue by samuelway** [alibaba/fastjson#1408]
fastjson  处理 boolean  返回空值

**Comment by wenshao** [comment]
遇到什么问题了？

**Comment by samuelway** [comment]
使用jsonobject parseArray转换树形结构list 时 第一层的boolean类型（属性是 checked=true 这种类型）  有值  第二层  boolean 没了

**Comment by samuelway** [comment]
也就是  boolean 属性丢失了

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by samuelway** [comment]
具体事例已经上传了您看下[JsonParseDemo.zip](https://github.com/alibaba/fastjson/files/1237634/JsonParseDemo.zip)

**Comment by samuelway** [comment]
@wenshao  有解决方法么？

**Comment by GodzillaHua** [comment]
@samuelway SysResources你這個少了checked属性和get set方法呀

**Comment by samuelway** [comment]
转换的是sysResourcesVo
