### ISSUE TITLE
HashMap中相同value转json的时候,后面的value会出错

### ISSUE THREAD

**Issue by MrWangyaya** [alibaba/fastjson#1410]
`public class FastJsonTest {

    public static void main(String[] args) {

        User user = new User();
        user.setId(1);
        user.setName("cx");
        List<User> list = new ArrayList<User>();
        list.add(user);

        HashMap <String,List<User>> map = new HashMap<String, List<User>>();
        map.put("南京",list);
        map.put("上海",list);

        HashMap<String,User> map2 = new HashMap<String, User>();
        map2.put("深圳",user);
        map2.put("北京",user);

        String mapJson = JSON.toJSONString(map);
        String mapJson2 = JSON.toJSONString(map2);

        System.out.println("map1:"+mapJson);
        System.out.println("map2:"+mapJson2);

    }

    static class User implements Serializable{
        private int  id;
        private String name;

        public User() {
        }

        public int getId() { return id; }
        public void setId(int id) { this.id = id; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        @Override
        public String toString() {
            return id + "-" + name;
        }
    }
}`

打印出来:`map1{"上海":[{"id":1,"name":"cx"}],"南京":[{"$ref":"$.上海[0]"}]}
map2{"深圳":{"id":1,"name":"cx"},"北京":{"$ref":"$.深圳"}}`

**Comment by oawang** [comment]
JSON.DEFAULT_PARSER_FEATURE |= Feature.DisableCircularReferenceDetect.getMask();
