### ISSUE TITLE
可否全局定义反序列化自动识多种日期格式，如：yyyy-MM-dd HH:mm

### ISSUE THREAD

**Issue by oawang** [alibaba/fastjson#1411]
现有，反序列化能够自动识别如下日期格式：

ISO-8601日期格式
yyyy-MM-dd
yyyy-MM-dd HH:mm:ss
yyyy-MM-dd HH:mm:ss.SSS

可否自定义多种日期格式

**Comment by wenshao** [comment]
感谢反馈，问题已经修复，请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.1.37
