### ISSUE TITLE
FastJson 1.2.37 "unclosed.str" issue with valid input

### ISSUE THREAD

**Issue by greenlaw110** [alibaba/fastjson#1422]
Note the issue only captured on [v1.2.37](https://github.com/alibaba/fastjson/releases/tag/1.2.37).

Given two strings below:

```java
String strOk = "{\"v\": 111}";
String strBad = "{\"v\":111}";
```

Note the only difference is there is a whitespace behind `:` in `strOk`.

parsing `strOk` is fine:

```
Foo ok = JSON.parseObject(strOk, Foo.class);
```

This will cause the `unclosed.str` issue:

```
Foo bad = JSON.parseObject(strBad, Foo.class);
```

Screenshot:
![image](https://user-images.githubusercontent.com/216930/29490423-74f36cb6-857e-11e7-8fa5-d603b557eb64.png)

The full code to reproduce the issue:

https://gist.github.com/greenlaw110/3d0fc68a569565bdf1c9056ef25ab1fb

**Comment by wenshao** [comment]
bug fixed, please try the last version. https://github.com/alibaba/fastjson/releases/tag/1.2.38
