### ISSUE TITLE
FastJson 1.2.37 parsing overlow long value issue

### ISSUE THREAD

**Issue by greenlaw110** [alibaba/fastjson#1423]
Give class:

```java
    public static class LongVal {
        private long v;
        public void setV(long v) {
            this.v = v;
        }

        @Override
        public String toString() {
            return String.valueOf(v);
        }
    }
```

Give the following code to call fastjson:

```java
        BigInteger n = new BigInteger(String.valueOf(Long.MAX_VALUE)).add(new BigInteger("1"));
        Map<String, BigInteger> map = new HashMap<>();
        map.put("v", n);
        String strBad = JSON.toJSONString(map);
        System.out.println(JSON.parseObject(strBad, LongVal.class));
```

Expected behavior: raise `NumberFormatException`

found it print out `-9223372036854775808`

Screenshot:
![image](https://user-images.githubusercontent.com/216930/29490663-4e5b35cc-8586-11e7-9979-2f74b27987f9.png)

The full source code the reproduce this issue:
https://gist.github.com/greenlaw110/e906970a13921fc30adada704468c63f

**Comment by wenshao** [comment]
thank you, bug has been fixed and added several tests.

**Comment by wenshao** [comment]
bug fixed, please try the last version. https://github.com/alibaba/fastjson/releases/tag/1.2.38
