### ISSUE TITLE
处理getBoolean(String key)返回为空

### ISSUE THREAD

**Issue by ARabbitCoder** [alibaba/fastjson#1426]
没有这个键值时报异常   
 public Boolean getBoolean(String key) {
        Object value = get(key);
        if (value == null) {
            return null;
        }
        return castToBoolean(value);
    }
debug的时候发现return null后，还会走return castToBoolean(value)导致异常。

**Comment by vipcxj** [comment]
这是你看错了吧，或者源码在debug时行数对应错误，或者源码和实际jar包不匹配~ 已经return了怎么可能继续走下去~

**Comment by wenshao** [comment]
应该是getBooleanValue报错吧，如果是getBooleanValue报错，升级到最新的1.2.36就好了

**Comment by ARabbitCoder** [comment]
是版本的问题
