### ISSUE TITLE
Json parse时支持string内的特殊字符

### ISSUE THREAD

**Issue by jeck218** [alibaba/fastjson#1428]
用户传入的string有json不支持的特定字符，希望能在用户没有转义的情况下能支持自动转义掉

char  any-Unicode-character-
    except-"-or-\-or-
    control-character
\"
\\
\/
\b
\f
\n
\r
\t
\u

**Comment by neil4dong** [comment]
如果是一个json字符串内有非法字符，那这就不是一个正确的json字符串。

**Comment by jeck218** [comment]
我测试发现已经支持了
\r\n这些都可以
