### ISSUE TITLE
在gradle构建的kotlin项目中报错：default constructor not found. class model.bean.Profile

### ISSUE THREAD

**Issue by NameSpace5** [alibaba/fastjson#1431]
idea中完全的kotlin项目中没问题，在gradle构建的kotlin项目中报错，请问是不支持吗？我用Gson转完全没问题的。

代码这样：Profile就不贴了
val profile = Profile::class
val array = ArrayList<Profile>()
val jsonObject = JSON.toJSONString(JSON.parseObject(result)["profile"])
array.add(JSON.parseObject(jsonObject,profile.javaObjectType))

**Comment by kimmking** [comment]
新版应该不存在这个问题：

https://github.com/alibaba/fastjson/wiki/Use-Fastjson-in-Kotlin

**Comment by NameSpace5** [comment]
我测试的是新版本的1.2.37

**Comment by wenshao** [comment]
会尽快发布一个版本解决此问题

**Comment by wenshao** [comment]
问题已经修，使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.38
