### ISSUE TITLE
父类型引用指向的子类型对象序列化时候子类型对象属性丢失

### ISSUE THREAD

**Issue by xiangyubo** [alibaba/fastjson#1434]
我遇到的问题是，我有一个对象Base，有个子对象A继承Base.
Base aa = new A()。
String text = JSON.toJSONString(aa);
这个时候text里面只有Base的属性，没有A里的属性。我不知道是不是我用的不太对，在网上查也没太多信息。

**Comment by vipcxj** [comment]
A没写getter方法吧~

**Comment by xiangyubo** [comment]
我去，兄台正解啊！加了马上就好了。
