### ISSUE TITLE
页面发出ajax的post请求，参数是一个string，接受端为enum字段，enum上加deserializer没用

### ISSUE THREAD

**Issue by liujiong1982** [alibaba/fastjson#1444]
页面发出ajax的post请求，参数是一个string，接受端为enum字段，enum上加@JSONType(deserializer= EnvEnumDeserializer.class)
希望EnvEnumDeserializer能够反序列化传来的string，变为enum

**Comment by wenshao** [comment]
问题已经修，请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.38
