### ISSUE TITLE
jsonpath路径中含有纯数字节点的时候,不支持

### ISSUE THREAD

**Issue by merciqiao** [alibaba/fastjson#1445]
JSONPath.read(json,"data.data.map.21160001");
JSONPath.read(json,"data.data.map.B21160002");
当jsonpath中,节点开头为数字时,你们会判断成array类型,而我的map节点是map类型的,于是就抛出异常了,麻烦修正这个问题

**Comment by merciqiao** [comment]
JSONPath.read(json,"data.data.map.21160001");//抛出异常
JSONPath.read(json,"data.data.map.B21160002");//正常获取到值
我急用这个功能,麻烦快快修正,不然我给修正了

**Comment by kimmking** [comment]
我印象中改过了？

**Comment by wenshao** [comment]
什么版本，在最新版本https://github.com/alibaba/fastjson/releases/tag/1.2.37 中没问题

**Comment by merciqiao** [comment]
我之前用的1.2.22,1.2.37没问题,谢谢了

**Comment by Nisus-Liu** [comment]
`1.2.70` 版本貌似还是这个问题??
