### ISSUE TITLE
如何关闭FastJsonProvider向JAXRS的自动注册?

### ISSUE THREAD

**Issue by firingsloth** [alibaba/fastjson#1448]
如题，这会影响现有使用了jackson的JAXRS工程 @alibaba-oss

**Comment by kimmking** [comment]
@VictorZeng zeng

**Comment by VictorZeng** [comment]
@firingsloth In Jersey `FastJsonAutoDiscoverable.autoDiscover = false; `

**Comment by firingsloth** [comment]
@VictorZeng 非常感谢您的回复，但是我是用的是RestEasy，是否有类似的解决方案？或者有什么建议？

**Comment by VictorZeng** [comment]
@firingsloth RestEasy不会自动注册啊

**Comment by VictorZeng** [comment]
@firingsloth 可能RestEasy自动scan了provider吧，这样试试呢
```xml
     <context-param>
         <param-name>resteasy.scan.providers</param-name>
         <param-value>false</param-value>
     </context-param>
 
     <context-param>
         <param-name>resteasy.providers</param-name>
         <!-- 
         <param-value>com.alibaba.fastjson.support.jaxrs.FastJsonProvider</param-value>
         -->
         <param-value>com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider</param-value>
     </context-param>
```

**Comment by firingsloth** [comment]
@VictorZeng 抱歉回复的有些晚，问题已经解决了
起因是我在pom中引入了
<dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-servlet-initializer</artifactId>
        </dependency>
意味着开启自动扫描，所以FastJsonProvider必然会被扫描到（这个没有找到解决办法去避免，你上面发的配置方式在自动扫描模式下不生效）

但是如果引入
<dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
        </dependency>
RestEasy可以保证优先使用这个Provider去处理，我缺少了这个Maven配置所以一直在使用FastJsonProvier；
RestEasy官方文档给的类似问题的解决方案也不太理想
![image](https://user-images.githubusercontent.com/27909764/30020236-c4359cfe-9195-11e7-80de-1811af820074.png)
