### ISSUE TITLE
JSON.parseObject(json, String.class) 报错

### ISSUE THREAD

**Issue by i-show** [alibaba/fastjson#1457]
```
String value = "https://github.com/alibaba/fastjson";
String json = JSON.toJSONString(value);
Log.i(TAG, "onCreate: json = " + json);
String result = JSON.parseObject(json, String.class);
```
这个样子肯定会报错，我看在 

> https://github.com/alibaba/fastjson/issues/1059  中说 “xxx” 不是一个json， 但是我在toJSON的时候也是转换成一个简单的 “xxx”

感觉逻辑上达不到闭环

版本： 1.1.62.android

**Comment by kimmking** [comment]
单独一个string，不需要tojson，parse

**Comment by i-show** [comment]
@kimmking  但是有时候封装工具类的时候 谁知道别人会不会传入String.class , 我这里只是一个简单的场景说明一下当前的问题

**Comment by wenshao** [comment]
我在最新版本上测试是好的

**Comment by i-show** [comment]
Sorry ，我在Demo中搞错了 @wenshao

**Comment by CuiXiaoDao** [comment]
好像1.59版本确实出现了这个问题。
```java
    @Test
    public void test2() {
        System.out.println(JSON.parseObject("testString", String.class));
    }
```

堆栈信息
![image](https://user-images.githubusercontent.com/13762352/62537135-530b0080-b882-11e9-8bea-fc15744d1296.png)
