### ISSUE TITLE
A Misnomer

### ISSUE THREAD

**Issue by Richard-Cao** [alibaba/fastjson#1460]
![image](https://user-images.githubusercontent.com/5953992/30199333-de2a78ac-94a4-11e7-8495-9b9ec4c90b81.png)

This [statement](https://github.com/alibaba/fastjson/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/849c99ec46628f56ff9ad8490d81bd8c32ee1663) is not appropriate.

**Comment by HackenHYJ** [comment]
As a technician, we should always be modest !
So I agree with you !

**Comment by jiangyuanyuan** [comment]
As a technician, we should always be modest !
So I agree with you !

**Comment by daquexian** [comment]
It is annoying. And I think many programmers(e.g myself) will have a bad impression on both fastjson and alibaba because of this.

**Comment by kimmking** [comment]
Removed it, thanks for suggestion.

**Comment by kimmking** [comment]
And we will check all documents and rearrange them for developers.

**Comment by Richard-Cao** [comment]
@kimmking 👍

**Comment by wenshao** [comment]
谢谢反馈
