### ISSUE TITLE
@JSONField(name = "MD5")，失败，用的最新版

### ISSUE THREAD

**Issue by dawangzai** [alibaba/fastjson#1478]
@JSONField(name = "MD5")
private String md5;
转化之后是 “mD5”。用的是最新版 “1.1.63.android”

**Comment by wenshao** [comment]
getter烦那个发是怎样的？

**Comment by dawangzai** [comment]
@wenshao 
以前是这么写的
   public String getMD5() {
        return md5;
    }

    public void setMD5(String md5) {
        this.md5 = md5;
    }

刚才改成下面这样的 getter 和 setter，试了一下就成功了转化成了 “MD5”
    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }
