### ISSUE TITLE
Kotlin中异常com.alibaba.fastjson.JSONException: create instance error

### ISSUE THREAD

**Issue by ZYRzyr** [alibaba/fastjson#1483]
数据类:
`data class Person(var name: String, var age: Int, var desc: String)`

JSON:
json = `{"age":99,"name":"robohorse"}`

测试：
```
@Test
fun testFastJson() {
    val person = JSON.parseObject(json, Person::class.java)
    Assert.assertEquals(99, person.age)
}

@Test
fun gson() {
    val person = Gson().fromJson(json, Person::class.java)
    Assert.assertEquals(99, person.age)
}
```
运行，用例`testFastJson`报异常：com.alibaba.fastjson.JSONException: create instance error
如果`Person`是Java写的，就没错
```

环境：
Android Studio Canary 3.0 Beta6

kotlin_version = '1.1.4-3'
"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
"org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

com.alibaba:fastjson:1.2.38 or com.alibaba:fastjson:1.1.63.android
```

**Comment by wenshao** [comment]
这个问题是因为desc缺失导致的

**Comment by ZYRzyr** [comment]
谢谢提醒
但我的意思是，如果实体类是`Java`写的，就算没有`desc`，也会默认`desc`是`null`且不会报错，那么`Kotlin`写的数据类也应该是这样，但事实是会报异常。
如果这不是BUG，我将关闭此`issuse`

**Comment by iykzhang** [comment]
data class Person(var name: String?, var age: Int?, var desc: String?)

加上问号就可以了
