### ISSUE TITLE
JSON字符串中含有Java的关键字，如何处理？

### ISSUE THREAD

**Issue by hzwplus** [alibaba/fastjson#1484]
场景：
后台返回的JSON中有个字段名为"new"，这是java的关键字，在bean里面没办法直接使用。

解决方案：
Fastjson提供了注解，可以处理这种情况。

bean：
`
@SerializedName("new")
@JSONField(name="new")
private boolean newMember;

public boolean isNewMember() {
    return newMember;
}

public void setNewMember(boolean newMember) {
    this.newMember = newMember;
}
`

**Comment by kimmking** [comment]
那么，问题是？
