### ISSUE TITLE
SupportNonPublicField不支持parse基类的private成员

### ISSUE THREAD

**Issue by dwing4g** [alibaba/fastjson#1494]
加SupportNonPublicField特性parse到类中普通的private成员没有问题,
但这个类如果有基类, 那么基类的private成员应该也能支持parse吧?
目前的1.2.38版貌似不支持.

**Comment by neil4dong** [comment]
这个属于java语言的特性哈。  父类的private 的属性， 在子类是不可见的

**Comment by dwing4g** [comment]
parser赋值private成员就已经破坏语言特性了吧, 肯定用反射机制去赋值的,
既然用了反射, 基类也应该可以反射赋值的.

**Comment by vipcxj** [comment]
我觉得基类private字段不一定要支持，protect肯定要支持的，package看情况

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.39
问题已经修复，请用新版本

**Comment by vipcxj** [comment]
如果不加判断直接支持父类的private字段，很容易引发新问题吧，毕竟父类的private字段对子类是完全不可见的，比如子类同样可以声明同名的父类的private字段
