### ISSUE TITLE
dependence error

### ISSUE THREAD

**Issue by caorong** [alibaba/fastjson#1497]
org.springframework.core.ResolvableType used in FastJsonHttpMessageConverter not contains in Spring MVC 3.2.x 

It is spring4 feature

**Comment by wenshao** [comment]
@VictorZeng

**Comment by VictorZeng** [comment]
@caorong see #1501

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.39
bug fixed in new version. please use 1.2.39
