### ISSUE TITLE
两边枚举类不相同，反序列化时报错的问题

### ISSUE THREAD

**Issue by huzhongchun0918** [alibaba/fastjson#1498]
序列化方定义的枚举类型为：
```java
public enum BuFlag
{
  IS_NEED_CHECK_IDENTITY(1L, "a"),  HAS_CHECK_IDENTITY(2L, "b"),
  QUALITY_GRADUATE(3L, "c");
  
  private long bit;
  private String desc;
  
  private BuFlag(long bit, String desc)
  {
    this.bit = bit;
    this.desc = desc;
  }
  
  public long getBit()
  {
    return this.bit;
  }
}
```
反序列化定义的枚举类型为：
```java
public enum BuFlag
{
  IS_NEED_CHECK_IDENTITY(1L, "a"),  HAS_CHECK_IDENTITY(2L, "b");
  
  private long bit;
  private String desc;
  
  private BuFlag(long bit, String desc)
  {
    this.bit = bit;
    this.desc = desc;
  }
  
  public long getBit()
  {
    return this.bit;
  }
}
```
反序列方定义的类没有定义QUALITY_GRADUATE(3L, "c")。
使用场景为序列方返回Set<BuFlag> set，set里面的元素为IS_NEED_CHECK_IDENTITY，QUALITY_GRADUATE。在反序列方解析时报
Caused by: java.lang.IllegalArgumentException: No enum constant test.BuFlag.QUALITY_GRADUATE
        at java.lang.Enum.valueOf(Enum.java:236)
        at com.alibaba.fastjson.parser.deserializer.EnumDeserializer.deserialze(EnumDeserializer.java:61)

fastjson版本为1.2.5，试了最新版也是一样报错，请问这个有办法解决吗？可以让反序列化方在反序列时，如果没有定义QUALITY_GRADUATE，就丢弃QUALITY_GRADUATE这个值吗？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.39
新版本我测试是好的，请验证，如果还有问题，再提issue
