### ISSUE TITLE
增加一些工具类或者函数，输出格式化的字符串

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/fastjson#150]
便于调试。尽管很多编辑器都可以格式化JSON字符串，但是复制出去再格式化总是不太方便。是否可以考虑增加格式化的函数？

**Comment by roaporl** [comment]
PrettyFormat使用的 \t 缩进，可不可以指定空格数目

**Comment by looly** [comment]
@wenshao 同问，可否自定义格式化输出缩进空格数？
