### ISSUE TITLE
lazy加载异常的BUG

### ISSUE THREAD

**Issue by RozwelGustab** [alibaba/fastjson#1519]
@wenshao 
之前提过一个 [issue](https://github.com/alibaba/fastjson/issues/1190)是关于序列化lazy数据的，因为后来那个项目废弃了，就一直没有验证，今天重新用到了这个功能，发现还是不行。
经过检查发现FieldSerializer.getPropertyValueDirect方法似乎有些问题：
`if (persistenceOneToMany && TypeUtils.isHibernateInitialized(fieldValue)) {
            return null;
        }`
TypeUtils.isHibernateInitialized返回的是这个value是否已被初始化，如果未被初始化，进行json转换会出lazy异常，这里应该少了个！号。
还有一点，这里只判断了oneToMany的情况，manyToOne情况下还是会抛异常。

**Comment by wenshao** [comment]
已经修改了，能帮忙验证一下么？

**Comment by RozwelGustab** [comment]
感谢 已经没有问题了。
