### ISSUE TITLE
fastjson日期格式化24小时

### ISSUE THREAD

**Issue by maliqiang** [alibaba/fastjson#1523]
我添加了@JSONField(
        format = "yyyy-MM-dd HH:mm:ss"
    )，然后也在输出的时候使用了JSON.toJSONString(jsonObj, new SerializerFeature[]{SerializerFeature.WriteNullStringAsEmpty, SerializerFeature.WriteDateUseDateFormat})，怎么输出的时间是2017-10-12 00:00:00，我要的是2017-10-12 23:59:59啊

**Comment by kimmking** [comment]
你原本的时间就是2017-10-12 00:00:00
