### ISSUE TITLE
@JSONField not working on kotlin

### ISSUE THREAD

**Issue by livelazily** [alibaba/fastjson#1526]
Sample code is:
```kotlin
import com.alibaba.fastjson.JSON
import com.alibaba.fastjson.annotation.JSONField

fun main(args: Array<String>) {
    val dt = DataClass("ccc", "ddd")
    val json = JSON.toJSONString(dt)
    println(json)
}

data class DataClass(
    @JSONField(name = "Id")
    val Aa: String,

    @JSONField(name = "Name")
    val Bb: String
)
```
It's output:
```json
{"aa":"ccc","bb":"ddd"}
```
This is not correct, it's output should be `{"Id":"ccc","Name":"ddd"}`

If I change the field name `Aa` to `aa`, it is working normal

Environment:
fastjson version: 1.2.39
kotlin version: 1.1.51
java version: 1.8.0_144

**Comment by sd4324530** [comment]
see #1476

**Comment by wenshao** [comment]
@livelazily #1476 是否符合你描述？问题是否已解决？

**Comment by livelazily** [comment]
加了
```
compile "org.jetbrains.kotlin:kotlin-reflect"
```
依旧是不行,

已经改用 `@field:JSONField` 的方法暂时使用着

**Comment by kimmking** [comment]
data class DataClass(
    @field:JSONField(name = "Id")
    val Aa: String,

    @field:JSONField(name = "Name")
    val Bb: String
)

**Comment by livelazily** [comment]
@kimmking 这样写是 ok 的, 但就像 #1476 说的, wiki 上貌似是2种写法都可以

现在就不清楚这个现象是 bug 还是 feature 了

**Comment by limuyang2** [comment]
@livelazily 我添加了这个后，@JSONField可以工作了，`compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"`

**Comment by livelazily** [comment]
@limuyang2 我建立了个测试仓库
https://github.com/livelazily/fastjson-kotlin

加了 `compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"` 之后依旧是不行

**Comment by wenshao** [comment]
谢谢反馈，问题重现并解决，我将会尽快发布新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.40
问题已经修复，请用新版本
