### ISSUE TITLE
PropertyFilter javadoc错误

### ISSUE THREAD

**Issue by imJude-z** [alibaba/fastjson#1527]
[Wiki页](https://github.com/alibaba/fastjson/wiki/SerializeFilter) 上提供了ProperyFilter的使用方法，但是没有完整的输入输出的例子。

而ProperyFilter.apply()方法上对于返回值的javadoc为"return true if the property will be filtered out, false otherwise"，与实际情况相反，相关的单元测试也可以说明。
如：[com/alibaba/json/bvt/serializer/filters/PropertyFilterTest.java](https://github.com/alibaba/fastjson/blob/d84c669c0c6920f86d68d39c654bf1cc835da7d1/src/test/java/com/alibaba/json/bvt/serializer/filters/PropertyFilterTest.java)

**Comment by wenshao** [comment]
你来提交一下patch帮忙修正，可以么？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.40
问题已经修复，请用新版本
