### ISSUE TITLE
fastjson-android  parse crash

### ISSUE THREAD

**Issue by wanggang0813** [alibaba/fastjson#1529]
问题版本 ： >= 1.1.60
复现Case： 
    public static class Person {
        public int Id;
        public String name;
        public double height;
    } 
   jsonStr ："[{\"isId\":false,\"Id\":138042533,\"name\":\"example\",\"height\":172}]"

   List<Person> list = JSON.parseArray(jsonStr, Person.class);
结果：
   com.alibaba.fastjson.JSONException: cast error, field : Id, value false

**Comment by wanggang0813** [comment]
1.1.59及早期版本没有该问题，试了将isId 换成 isname 不会有问题，将isId换成 isheight 会有问题; 推测基本数据类型解析有问题，期待尊敬的开发同学早日修复该问题。 谢谢！

**Comment by wanggang0813** [comment]
When to publish android-1.1.65?

**Comment by wenshao** [comment]
问题已经修复，将会在下周末发布新版本

**Comment by wanggang0813** [comment]
@wenshao  作者您好，您有没有收到国内厂商比方说华为适配Android O 的fastjson解析失败的相关反馈？

**Comment by wenshao** [comment]
@wanggang0813 没有哦，手机淘宝和支付宝钱包都用fastjson，如果有相关的问题，我应该收到相关信息的。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.1.65.android
已经支持，请使用新版本
