### ISSUE TITLE
关于使用FastJsonpResponseBodyAdvice,无论callback传与不传,返回格式都是application/javascript

### ISSUE THREAD

**Issue by rplees** [alibaba/fastjson#1533]
FastJsonHttpMessageConverter.writeInternal判断obj为MappingFastJsonValue时,没有对obj.jsonpFunction非空判断,又不想使用ResponseJSONP注解, 好像ResponseJSONP是方法上生效

**Comment by Luckywb** [comment]
可以先自已重写了下方法`protected void writeInternal(Object object, HttpOutputMessage outputMessage) throws IOException`，加上function判断

**Comment by Luckywb** [comment]
不知道是不是出于安全性考虑，老版本的jsonp实现类都标记为`Deprecated`，新的实现方式看源码好像都要加ResponseJSONP注解，有点小难用

**Comment by wenshao** [comment]
@VictorZeng

**Comment by VictorZeng** [comment]
@rplees  你的诉求是即可以使用FastJsonpResponseBodyAdvice来使用jsonp接口，然后又能在正常json接口返回MediaType.APPLICATION_JSON 对吧

**Comment by neil4dong** [comment]
#1538 做了新的修改， ResponseJSONP可以注解在类上面。  
MappingFastJsonValue改回了原来对jsonpFunction的非空判断。

**Comment by rplees** [comment]
@Luckywb 嗯,我也是自己这样解决的.

**Comment by rplees** [comment]
@VictorZeng 不好意思,现在才看到信息, 我的意思是 xxx.json Response Content Type的是MediaType.APPLICATION_JSON,xxx.json?callback=foo Response Content Type 是application/javascript, 我的做法跟 @Luckywb 是一样的
