### ISSUE TITLE
kOTLIN

### ISSUE THREAD

**Issue by 291700351** [alibaba/fastjson#1547]
kotlin在Android7.0模拟器上会出现default constructor not found

**Comment by wenshao** [comment]
fastjson什么版本？

**Comment by 291700351** [comment]
fastjson: com.alibaba:fastjson:1.1.64.android
AndroidStudio2.3 and AndroidStudio3.0

Bean:
`class Head {
    var msg: String = "" //mock
    var code: String = "" //0000
    override fun toString(): String = "Head(msg='$msg', code='$code')"
}`

`val head = JSON.parseObject<Head>(headStr, Head::class.java)`

Exception Message:
` com.alibaba.fastjson.JSONException: default constructor not found. class com.yaomi.yzd.entity.Head`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.1.65.android
已经支持，请使用新版本
