### ISSUE TITLE
SpringMVC集成fastjson设置日期格式对LocalDateTime不起作用

### ISSUE THREAD

**Issue by yizmao** [alibaba/fastjson#1551]
https://github.com/alibaba/fastjson/wiki/%E5%9C%A8-Spring-%E4%B8%AD%E9%9B%86%E6%88%90-Fastjson

FastJsonConfig config = new FastJsonConfig();
config.setDateFormat(yy-MM-dd HH:mm:ss)

结果为："2017-10-27T13:00:22.915"

**Comment by VictorZeng** [comment]
@yizmao 你确定将FastJsonConfig注入到FastJsonHttpMessageConverter？

**Comment by yizmao** [comment]
@Configuration
public class HttpMessageConverterConfig {

    @Bean
    public WebMvcConfigurer configureMessageConverters(){

        return new WebMvcConfigurer() {
            @Override
            public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {

                FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();

                FastJsonConfig config = new FastJsonConfig();
                /*设置序列化日期格式为timestamp格式*/
                //config.setDateFormat(JSON.DEFFAULT_LOCAL_DATE_TIME_FORMAT);
                converters.add(converter);

            }
        };
    }
}
@VictorZeng

**Comment by VictorZeng** [comment]
@yizmao 朋友，你得`converter.setFastJsonConfig(config);`

**Comment by yizmao** [comment]
@VictorZeng  谢谢老哥，是我脑子抽了没看到
