### ISSUE TITLE
java8 环境的有些测试用例编译通不过

### ISSUE THREAD

**Issue by lovepoem** [alibaba/fastjson#1561]
![image](https://user-images.githubusercontent.com/827112/32336822-50e74e0e-c02b-11e7-8d20-c661f39678f2.png)
java8 环境的有些参数为null的测试用例通不过，在本地跑测试，需要jdk什么版本？

我本地的环境：
Apache Maven 3.2.3 
Java version: 1.8.0_11, vendor: Oracle Corporation

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/32336822-50e74e0e-c02b-11e7-8d20-c661f39678f2.png)
再一个java8 环境的很多测试用例编译通不过

**Comment by neil4dong** [comment]
编译目标版本是1.5

**Comment by wenshao** [comment]
再更新一下代码，之前提交过有问题的代码

**Comment by lovepoem** [comment]
更新代码后已经解决，棒棒哒
