### ISSUE TITLE
请问，fastjson支持kotlin的数据类吗？

### ISSUE THREAD

**Issue by jeff-sun** [alibaba/fastjson#1562]
请问，fastjson支持kotlin的数据类吗？

**Comment by wenshao** [comment]
支持的，最近几个版本都在完善的kotlin的支持。这个周末会再发一个版本增强对kotlin的支持。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.40
新版本发布，进一步增强了对kotlin的支持
