### ISSUE TITLE
当JavaBean的字段数量超过256个时，PropertyNamingStrategy.SnakeCase设置无效。

### ISSUE THREAD

**Issue by frankhuasf** [alibaba/fastjson#1565]
[LargeBean.java.txt](https://github.com/alibaba/fastjson/files/1443862/LargeBean.java.txt)
当JavaBean的字段数量超过256个时，PropertyNamingStrategy.SnakeCase设置无效。
请问下JavaBean的字段数量是否有限制？
fastjson:1.2.40
环境:spring mvc，idea
示例如下：
    @Test
    public void testToSnakeCaseJson() throws Exception {
        LargeBean expectedBean = new LargeBean();
        expectedBean.setId("S35669");
        expectedBean.setNetValueDate(20171105);
        String expectedStr = "{\"id\":\"S35669\",\"net_value_date\":20171105}";
        SerializeConfig serializeConfig = new SerializeConfig();
        serializeConfig.propertyNamingStrategy = PropertyNamingStrategy.SnakeCase;
        String actualStr = JSON.toJSONString(expectedBean, serializeConfig);
        JSONObject actualBean = JSON.parseObject(actualStr);
        Assert.assertEquals(expectedStr, actualStr);
        Assert.assertEquals(expectedBean.getId(), actualBean.getString("id"));
        Assert.assertEquals(expectedBean.getNetValueDate(), actualBean.getInteger("net_value_date"));
    }

**Comment by neil4dong** [comment]
#1568 fixed

**Comment by wenshao** [comment]
新版本已经支持，请使用新版本
