### ISSUE TITLE
新版本JSON.toJSONString(testingOrder, SerializerFeature.WriteNullBooleanAsFalse),随便加一个类似的feauture,就会把模型类的null值给打印出来

### ISSUE THREAD

**Issue by lvdong** [alibaba/fastjson#1570]
新版本JSON.toJSONString(testingOrder, SerializerFeature.WriteNullBooleanAsFalse),随便加一个类似的feauture,就会把模型类的null值给打印出来
 System.out.println(com.alibaba.fastjson.JSON.toJSONString(testingOrder));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(testingOrder,
                SerializerFeature.WriteNullBooleanAsFalse));
下面是对比。
{"delFlag":"0","new":true}

{"age":null,"approvePoints":null,"bloodFigures":null"}

求指教

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.41
新版本已经支持，请使用新版本
