### ISSUE TITLE
GenericFastJsonRedisSerializer与FastJsonRedisSerializer 热部署问题

### ISSUE THREAD

**Issue by fengyuchenglun** [alibaba/fastjson#1577]
GenericFastJsonRedisSerializer与FastJsonRedisSerializer在spring boot热部署(devtool)重启后 redis FastJsonRedisSerializer反序列失败。出现
分别出现
java.lang.ClassCastException: com.forever.springboot.auth.entity.UserEntity cannot be cast to com.forever.springboot.auth.entity.UserEntity

com.alibaba.fastjson.JSONObject cannot be cast to com.forever.springboot.auth.entity.UserEntity。
默认Serializer没有问题。

**Comment by lihengming** [comment]
@fengyuchenglun  看下这个：http://blog.csdn.net/xichenguan/article/details/73741835

**Comment by fengyuchenglun** [comment]
谢谢  已经找到原因  jackjson也有同样的问题
