### ISSUE TITLE
PropertyFilter 和 SerializerFeature.BeanToArray 联合使用有错

### ISSUE THREAD

**Issue by patrickzhe** [alibaba/fastjson#1580]
需要jsonToString 一个 java bean, 使用了PropertyFilter 和 SerializerFeature.BeanToArray ,想要筛选几个需要的属性，然后去掉key,array输出, code 类似：
 SimplePropertyPreFilter classAFilter = new SimplePropertyPreFilter(ClassA.class, "code");
  SerializeFilter[] filters =new SerializeFilter[]{classAFilter};
JSON.toJSONString(classA, filters, SerializerFeature.BeanToArray );
但是结果，显示只有SerializerFeature.BeanToArray 起了作用，filter 没有
如果去掉feature, 则可以使filter 起作用
问，如何同时起作用？

**Comment by patrickzhe** [comment]
补充，使用的版本 1.2.36

**Comment by wenshao** [comment]
问题重现，目前是不支持的，这个会修复，我要想一下怎么实现

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.45
问题已修复，请用新版本

**Comment by patrickzhe** [comment]
太好了，会测试下
