### ISSUE TITLE
Web应用tomcat部署成功，weblogic 12c部署失败

### ISSUE THREAD

**Issue by xingguang2013** [alibaba/fastjson#1589]
web应用使用了fastjson，打成war包部署在tomcat上是可以的，但部署在weblogic 12c上出现下面的错误信息：

`####<Nov 17, 2017 10:50:11 AM CST> <Info> <com.sun.jersey.api.core.PackagesResourceConfig>  <AdminServer> <Scanning for root resource and provider classes in the packages:
  com.alibaba.fastjson.support.jaxrs> 
####<Nov 17, 2017 10:50:11 AM CST> <Info> <com.sun.jersey.api.core.ScanningResourceConfig>  <AdminServer> <No root resource classes found.> 
####<Nov 17, 2017 10:50:11 AM CST> <Info> <com.sun.jersey.api.core.ScanningResourceConfig>  <AdminServer> <Provider classes found:
  class com.alibaba.fastjson.support.jaxrs.FastJsonProvider> 
####<Nov 17, 2017 10:50:13 AM CST> <Info> <com.sun.jersey.server.impl.application.WebApplicationImpl>  <AdminServer> <Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM'> 
####<Nov 17, 2017 10:50:18 AM CST> <Error> <com.sun.jersey.server.impl.application.RootResourceUriRules>  <AdminServer> <The ResourceConfig instance does not contain any root resource classes.> 
####<Nov 17, 2017 10:50:18 AM CST> <Error> <HTTP>  <AdminServer> <Servlet: "Jersey" failed to preload on startup in Web application: "xx.war".
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)`

去掉fastjson包的依赖，weblogic就可以成功部署，请问是否是fastjson哪里还需要专门针对weblogic的配置？

**Comment by duqicauc** [comment]
是不是包冲突？

**Comment by wenshao** [comment]
升级到最新版本1.2.40试试看？

**Comment by xingguang2013** [comment]
@wenshao 目前就是用的最新版本1.2.40

**Comment by xingguang2013** [comment]
@duqicauc  之前怀疑过，weblogic.xml加上<prefer-web-inf-classes>true</prefer-web-inf-classes>也是这个问题，只有把fastjson包去掉就好了

**Comment by xingguang2013** [comment]
从异常信息可以看出是weblogic 扫描到了 com.alibaba.fastjson.support.jaxrs包以及com.alibaba.fastjson.support.jaxrs.FastJsonProvider，导致出现的问题

**Comment by VictorZeng** [comment]
@xingguang2013 在启动之前 jersey  FastJsonAutoDiscoverable.autoDiscover = false; 试试

**Comment by xingguang2013** [comment]
@VictorZeng  您好，我的web应用是没有用到jersey的。按照您说的，我在`web.xml`的listener中配置了`FastJsonAutoDiscoverable.autoDiscover = false; `，但还是不可以。不行的话，先按照上面的方式，打出的war包删除fastjson.jar中的com.alibaba.fastjson.support.jaxrs包。谢谢您

**Comment by VictorZeng** [comment]
@xingguang2013 不好意思 weblogic不太熟 不知道有没有什么配置能更改 不自动scan Provider

**Comment by kimmking** [comment]
jersey.config.disableAutoDiscovery

https://stackoverflow.com/questions/24308639/weblogic-disable-jersey-scanning

**Comment by xingguang2013** [comment]
@VictorZeng   谢谢您提供的思路

**Comment by xingguang2013** [comment]
@kimmking 我还在查找配置jersey.config.disableAutoDiscovery的官方说明以及方式，感谢您提供的建议

**Comment by kimmking** [comment]
核心问题是，weblogic 12内置了对jersey的支持。

**Comment by kimmking** [comment]
@wenshao 
解决这个问题的根本办法就是把对不同其他类库支持的package，拆成独立的包：fastjson-xxx

**Comment by VictorZeng** [comment]
@kimmking 我所说的模块化就是这个意思

**Comment by kimmking** [comment]
@VictorZeng 是的，可以先处理core api之外的部分。

**Comment by xingguang2013** [comment]
感谢各位，已在weblogic官网[https://docs.oracle.com/middleware/12213/wls/RESTF/intro-restful-service.htm](url)找到相关配置信息
> The JAX-RS provides support for creating web services according to REST architectural style. JAX-RS uses annotations to simplify the development of RESTful web services. By simply adding annotations to your web service, you can define the resources and the actions that can be performed on those resources. JAX-RS is part of the Java EE 7 full profile, and is integrated with Contexts and Dependency Injection (CDI) for the Java EE Platform (CDI), Enterprise JavaBeans (EJB) technology, and Java Servlet technology.

正如同@kimmking 所讲的。[https://jersey.github.io/documentation/latest/deployment.html#deployment.autodiscoverable](url)，不过尝试了各种配置方式，都无法有效的让weblogic获取到jersey.config.disableAutoDiscovery为false的设置。目前还是用删除fastjson的com.alibaba.fastjson.support.jaxrs包方式解决的。

**Comment by kimmking** [comment]
@xingguang2013   fastjson一直没分包，给你带来不便，深感歉意。

**Comment by xingguang2013** [comment]
没关系，已经改用 [`jackson`](https://github.com/FasterXML/jackson-core.git) 了，谢谢

**Comment by houyuxue369** [comment]
您好，我现在也遇到了这个问题，删除了jaxrs包就可以了，可以这么做不，会不会带来一些其他的问题呢？

**Comment by VictorZeng** [comment]
fastjson2现已发布，可以尝试使用一下~
https://github.com/alibaba/fastjson2

**Comment by houyuxue369** [comment]
您好，我现在用的版本是1.2.80 我一旦切到 fastjson2后，有一些方法用不了了，代码里用的地方也比较多，要是重新改的话，来不及了。有没有其他的办法呢

**Comment by delayk** [comment]
> 您好，我现在用的版本是1.2.80 我一旦切到 fastjson2后，有一些方法用不了了，代码里用的地方也比较多，要是重新改的话，来不及了。有没有其他的办法呢

自己编译吧，太坑了
