### ISSUE TITLE
大数字通过fastjson序列化的时候报错，比如：4294967284超过了int的最大值，序列化成int的时候保存。java.lang.NumberFormatException: 4294967284

### ISSUE THREAD

**Issue by doinfi** [alibaba/fastjson#1591]
大数字通过fastjson序列化的时候报错，比如：4294967284超过了int的最大值，序列化成int的时候保存。java.lang.NumberFormatException: 4294967284
能不能优化，当数字超过Integer.MAX_VALUE;的时候返回0，或者最大值，fastjson应该添加这样的配置，免得数据错误，整个解析中断。

**Comment by kimmking** [comment]
相当于是fastjson修改了一个数据，存在一个问题：
用户再反序列化的时候，跟原来的json对不上了。

**Comment by doinfi** [comment]
明白了，谢谢
