### ISSUE TITLE
parser/deserializer/ThrowableDeserializer.java 里 deserialze() 可疑的空指针解引用 

### ISSUE THREAD

**Issue by viennadd** [alibaba/fastjson#1613]
Hi,

我们的代码检查器 Pinpoint 报告了一处可疑的空指针解引用，
https://github.com/alibaba/fastjson/blob/fcd2ae7723ddc84191cc9b90b453d58b30c02e2c/src/main/java/com/alibaba/fastjson/parser/deserializer/ThrowableDeserializer.java#L131-L150

149 行的 `exBeanDeser` 变量是否有可能跳过全部初始化赋值（139 返回 false 的话） 导致维持 null 值，然后触发空指针解用？

这处是真的有潜在问题?，还是 139 行的检查是非必要？

祝好，
Sourcebrella Inc.

**Comment by richardxx** [comment]
阿里大神们麻烦抽空看看，多谢！

**Comment by wenshao** [comment]
谢谢反馈，问题已经修复，将会在下一版本中带上

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.42
新版已发布，请使用新版本。
