### ISSUE TITLE
util/FieldInfo.java 里 getInheritGenericType() 可疑的空指针解引用

### ISSUE THREAD

**Issue by viennadd** [alibaba/fastjson#1614]
Hi,

我们的代码检查器 Pinpoint 报告了一处可疑的空指针解引用，
https://github.com/alibaba/fastjson/blob/fcd2ae7723ddc84191cc9b90b453d58b30c02e2c/src/main/java/com/alibaba/fastjson/util/FieldInfo.java#L349-L378

349 行是否可能返回 false，导致 377 行使用 `class_gd` 时触发空指针解引用？

祝好，
Sourcebrella Inc.

**Comment by wenshao** [comment]
问题确实存在，已经修复，将会在下一个版本中带上，谢谢反馈！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.42
新版已发布，请使用新版本。
