### ISSUE TITLE
无法支持同一类中多个Date系列化成不同格式

### ISSUE THREAD

**Issue by mfkvfn** [alibaba/fastjson#162]
比如
piblic class User{
    private Date birthday;
    private Date lastLoginTime;
}
上面一个想系列化为yyyy-MM-dd，下面一个想系列化为yyyy-MM-dd HH:mm。

目前并不能很方便地进行处理。 建议增加一些Annotation，可以直接加在field上。比如
@DateFormatter //默认为yyyy-MM-dd
@DateFormatter("yyyy年MM月dd日")
@DateTimeFormatter //默认为yyyy-MM-dd HH:mm
@DateTimeFormatter("yyyy年MM月dd日HH时mm分")

**Comment by caijiangyang** [comment]
发现我这边现在@JSONField(format = "yyyy-MM-dd HH:mm")不起作用
