### ISSUE TITLE
定制序列化时，需要同时修改key和Value怎么处理

### ISSUE THREAD

**Issue by sandyfog** [alibaba/fastjson#163]
序列化时需要同时修改Key和Value
参考文档：https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96
文档给出如下接口：
 // 修改Key，如果需要修改Key,process返回值则可
  public interface NameFilter extends SerializeFilter {
      String process(Object object, String propertyName, Object propertyValue);
  }

  // 修改Value
  public interface ValueFilter extends SerializeFilter {
      Object process(Object object, String propertyName, Object propertyValue);
  }
但是两个接口的方法名字和参数完全一样，只有返回值不一样，通过实现两个接口达不到要求。

**Comment by wenshao** [comment]
没有进一步信息，先关闭了
