### ISSUE TITLE
fastjson1.1.46.sec01和1.2.41版本在key为integer等数字类型时不兼容

### ISSUE THREAD

**Issue by panmissl** [alibaba/fastjson#1633]
1.1.46.sec01，key为数字类型时会作toString处理。所以 parse出来的对象要用字符串类型为key才能获取。但在1.2.41版本，key还是会保持数字类型，所以parse出来的对象要用Integer类型才能取得。
下面是DefaultJSONParser.java的源码贴图：
![1](https://user-images.githubusercontent.com/12045446/33643489-05afbac2-da05-11e7-9af3-444fc55d850e.png)
![2](https://user-images.githubusercontent.com/12045446/33643490-05dfa48a-da05-11e7-85f5-3906e7972eef.png)

下面是测试用例：

`public class FastjsonTest {

    public static void main(String[] args) {
        String text = "{123:\"abc\"}";
        JSONObject obj = JSON.parseObject(text);
        int intKey = 123;
        String strKey = "123";

        String intValue = (String) obj.get(intKey);
        String strValue = (String) obj.get(strKey);

        System.out.println("intKey: " + intKey + ", intValue: " + intValue);
        System.out.println("strKey: " + strKey + ", strValue: " + strValue);
    }

}`

**Comment by kimmking** [comment]
有点奇怪，按理key必须是string

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.42
新版已发布，请使用新版本。
