### ISSUE TITLE
Android Studio version detector is misunderstanding the next version

### ISSUE THREAD

**Issue by manoelarandaneto** [alibaba/fastjson#1634]
Android Studio version detector is misunderstanding the next version because you are using same artifactId for Java and Android library and just puting different version to both of them, it's better if you split up in 2 artifactId and we don't need to check last version on Jcenter

> A newer version of com.alibaba:fastjson than 1.1.67.android is available: 1.2.40 less... (Ctrl+F1) 
> This detector looks for usages of libraries where the version you are using is not the current stable release. Using older versions is fine, and there are cases where you deliberately want to stick with an older version. However, you may simply not be aware that a more recent version is available, and that is what this lint check helps find.

**Comment by wenshao** [comment]
I see what you mean, but it's not good to change, a lot of users are already using it.
