### ISSUE TITLE
（fastjson-1.2.24）反序列化偶尔获取不到对象

### ISSUE THREAD

**Issue by lucky-clover** [alibaba/fastjson#1643]
ChmInfo chmInfo = JSON.parseObject(data,chmInfo .class);
ChmRequest chmRequest = JSON.parseObject(JSON.toJSONString(chmInfo.getData()), ChmRequest .class);
chmInfo.getData()序列化前是POJO。

其中data的值为：
{
    "_id": {
        "$oid": "5a2f36bef7e3a221c248d2c2"
    },
    "createOperId": "lucky",
    "createTime": 1513043646199,
    "data": {
        "chmVO": {
            "address": "中国",
            "name": "clover"
        },
        "traceId": "4638EEC869714B27BBE558E52E3066CB"
    },
    "operType": "query",
    "procInstId": "1234556",
    "systemId": "mgmt"
}

现在的问题是chmRequest 得到的值偶尔会获取不到chmInfo.getData()序列化前的对象，parseObject之后chmRequest.getChmVO==null.
有意思的时候本地测试正常，服务器重启之后也会正常。
本地JDK1.7，服务器JDK版本1.8

fastjson版本：fastjson-1.2.24

**Comment by hfq-zhangwenhui** [comment]
对于嵌套的支持有一些问题

**Comment by dk-star** [comment]
嵌套支持有问题

**Comment by lucky-clover** [comment]
暮然回首看到了这个：
https://github.com/alibaba/fastjson/issues/569

**Comment by lucky-clover** [comment]
这个问题和问题https://github.com/alibaba/fastjson/issues/569 并不一样。
反序列化的时候使用new TypeReference<?>() {}即可。
导致这一问题的主要原因是，同一块代码处理了不同的业务逻辑，所以没有使用new TypeReference<?>() {}。图省事，连续两次反序列化导致bug出现。
