### ISSUE TITLE
反序列化不支持java.sql.Time类型

### ISSUE THREAD

**Issue by xyz327** [alibaba/fastjson#1644]
对象内有`java.sql.Time`类型字段时 反序列化会报错,
跟踪代码发现是`com/alibaba/fastjson/util/TypeUtils.java`类中没有对`java.sql.Time`的反序列进行支持.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.43
问题已修复，请使用新版本
