### ISSUE TITLE
list序列化问题

### ISSUE THREAD

**Issue by objectboy2016** [alibaba/fastjson#1650]
# 版本:1.2.42
# 方法: JSON.toJSONString(obj);
# fastjson序列化结果:

{"msg":"成功","routings":[{"adultPrice":4220,"adultTax":512,"adultTaxType":0,"applyType":0,"childPrice":3170,"childTax":392,"childTaxType":0,"currency":"RMB","data":"e042dcaa-aa26-4b64-88e9-36228d335394","fromSegments":[{"aircraftCode":"388","arrAirport":"SYD","arrTime":"2017-12-21T09: 45: 00.000+11: 00","cabin":"L","cabinClass":1,"carrier":"QF","codeShare":false,"depAirport":"HKG","depTime":"2017-12-20T21: 15: 00.000+08: 00","flightNumber":"118","stopCities":""}],"nationalityType":0,"priceType":0,"retSegments":[],"rule":{"baggage":"-","endorse":"-","endorsement":1,"hasBaggage":1,"hasEndorse":1,"hasNoShow":1,"hasRefund":1,"noShowLimitTime":1,"other":"退改签需要提前三个工作日联系客服","partEndorse":1,"partEndorsePrice":1,"partRefund":1,"partRefundPrice":1,"penalty":2,"refund":"-","specialNoShow":0},"ticketInvoiceType":0,"ticketTimeLimit":120},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"},{"$ref":"$.routings[0]"}],"status":200}

# gson序列化结果:

{"msg":"成功","routings":[{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]},{"applyType":0,"ticketTimeLimit":120,"adultTax":512,"data":"027e1965-d469-4686-823d-6943c912b13b","childTax":392,"adultPrice":4220,"priceType":0,"ticketInvoiceType":0,"rule":{"specialNoShow":0,"partEndorse":1,"other":"退改签需要提前三个工作日联系客服","endorsement":1,"baggage":"-","penalty":2,"partRefundPrice":1,"hasRefund":1,"partEndorsePrice":1,"hasBaggage":1,"endorse":"-","hasNoShow":1,"hasEndorse":1,"noShowLimitTime":1,"partRefund":1,"refund":"-"},"childTaxType":0,"fromSegments":[{"cabinClass":1,"carrier":"QF","stopCities":"","depTime":"2017-12-20T21: 15: 00.000+08: 00","codeShare":false,"aircraftCode":"388","cabin":"L","arrAirport":"SYD","depAirport":"HKG","arrTime":"2017-12-21T09: 45: 00.000+11: 00","flightNumber":"118"}],"nationalityType":0,"currency":"RMB","adultTaxType":0,"childPrice":3170,"retSegments":[]}],"status":200}

**Comment by ok406lhq** [comment]
？

**Comment by objectboy2016** [comment]
请问这是什么问题

**Comment by wenshao** [comment]
有循环引用了，加上SerializerFeature.DisableCircularReferenceDetect)可以解决问题的。比如：
```java
JSON.toJSONObject(obj, SerializerFeature.DisableCircularReferenceDetect);
```
