### ISSUE TITLE
建议ASMDeserializerFactory中一段代码 ASMDeserializerFactory.class.getPackage().getName();修改为ASMDeserializerFactory.class.getName(),因为在一些情况下会出现null

### ISSUE THREAD

**Issue by HunterPan** [alibaba/fastjson#1652]
例如：使用Mockito mock数据单元测试时，如果我们使用mockClassLoader类加载器时，mockClassLoader不会definePackages，导致getPackAge为null

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.43
问题已修复，请使用新版本
