### ISSUE TITLE
String解析为JSONObject，特别是含嵌套结构时，字段名如何大小写不敏感？

### ISSUE THREAD

**Issue by DuLerWeil** [alibaba/fastjson#1653]
我知道这很操蛋，但某运营商研究院的规范就是这么脑残，非得支持不敏感。

仅一层json结构时好处理，如下代码，利用commons-collections中的CaseInsensitiveMap可实现。
```
final TypeReference<CaseInsensitiveMap<String, Object>> typeReference = new TypeReference<CaseInsensitiveMap<String, Object>>(){};
CaseInsensitiveMap<String, Object> test = JSON.parseObject("", typeReference);
```

但涉及多层json结构时，嵌套对象又都解析为JSONObject里默认的HashMap或LinkedHashMap，它们是大小写敏感的。

想问fastjson有没相关api，可以自定义JSONObject中Map的类型为CaseInsensitiveMap？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/CustomMapDeserializer

**Comment by DuLerWeil** [comment]
这。。。动作神速

**Comment by DuLerWeil** [comment]
@wenshao wiki版本貌似应该改成1.2.44开始支持

**Comment by DuLerWeil** [comment]
试了下，有点点别扭。期望有下面这样的写法。
`
    @Test
    public void test() {
        ParserConfig config = new ParserConfig();
        MapDeserializer deserializer = new MapDeserializer() {
            public Map<Object, Object> createMap(Type type) {
                return new CaseInsensitiveMap<Object, Object>();
            }
        };

        config.putDeserializer(Map.class, deserializer);

        JSONObject jsonObject = JSON.parseObject("{\"vAl1\":{\"vAl2\":{}}}", config, Feature.CustomMapDeserializer);
        
        JSONObject val1 = jsonObject.getJSONObject("val1");
        assertEquals(1, val1.size());
        
        JSONObject val2 = val1.getJSONObject("val2");
        assertEquals(0, val2.size());

        JSONArray jsonArray = JSON.parseArray("[{\"vAl1\":{\"vAl2\":{}}}]", config, Feature.CustomMapDeserializer);
        assertEquals(1, jsonArray.size());
        
        jsonObject = jsonArray.getJSONObject(0);
        
        val1 = jsonObject.getJSONObject("val1");
        assertEquals(1, val1.size());
        
        val2 = val1.getJSONObject("val2");
        assertEquals(0, val2.size());
    }
`
