### ISSUE TITLE
期望JSONField的日期格式配置能作用到Date的集合对象中

### ISSUE THREAD

**Issue by home4j** [alibaba/fastjson#1660]
![image](https://user-images.githubusercontent.com/1128385/34145935-1784af4a-e4d3-11e7-969f-ca114f327fc1.png)

如图

**Comment by kimmking** [comment]
这种情况，更建议你使用全局性配置。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.44
问题解决，请使用新版本
