### ISSUE TITLE
在kotlin  使用TypeReference的fastjsonframework不能解析项目实体类

### ISSUE THREAD

**Issue by yangchaojiang** [alibaba/fastjson#1673]
java:

public class Test {

    public static void  main() {
        String jsonString = "[{\"ptId\":1,\"ptName\":\"KeMotion\"},{\"ptId\":2,\"ptName\":\"KePlast\"},{\"ptId\":3,\"ptName\":\"KeTop\"}]";
        TypeReference type=new TypeReference<List<TestBean>>(){};
        List<TestBean> list= JSONObject.parseObject(jsonString, type.getType());
        for (TestBean testBean : list) {
            System.out.println(testBean.ptName);
        }
    }
    public static class  TestBean{
       public String  ptId;
        public  String ptName;
    }
}
 运行没有问题

kotlin：1.2.0 版本
object Test {

    fun main() {
        val jsonString = "[{\"ptId\":1,\"ptName\":\"KeMotion\"},{\"ptId\":2,\"ptName\":\"KePlast\"},{\"ptId\":3,\"ptName\":\"KeTop\"}]"
        val type = object : TypeReference<List<TestBean>>() {

        }
        val list = JSONObject.parseObject<List<TestBean>>(jsonString, type.type)
        for (testBean in list) {
            println(testBean.ptName)
        }
    }

    class TestBean {
        var ptId: String? = null
        var ptName: String? = null
    }
}
kotlin 解析：错误日志:
fastjson:
Caused by: java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.keba.utils.Test$TestBean

**Comment by wenshao** [comment]
fastjson什么版本？

**Comment by yangchaojiang** [comment]
1.1.56.android 版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.1.67.android
用1.1.67.android试试问题是否还存在

**Comment by yangchaojiang** [comment]
好的，谢谢

**Comment by yangchaojiang** [comment]
没有问题了。谢谢了。
