### ISSUE TITLE
请问Andriod代码混淆时,内部类报错 default constructor not found，怎么破

### ISSUE THREAD

**Issue by xing-kenny** [alibaba/fastjson#168]
混淆声明如下：

```
-keep public class * implements java.io.Serializable {  
    public *;  
}  
```

JAVA代码有如下两种写法
写法1,有两个java类文件

文件1：

```
public class LoginStartBeanData implements Serializable {
```

文件2：

```
public class LoginStartBean implements Serializable {

    private static final long serialVersionUID = -436820542377254363L;
private int code = 0;
private String errormsg = "";
private LoginStartBeanData data;
```

写法2,一个java文件

public class LoginStartBean implements Serializable {

private static final long serialVersionUID = -436820542377254363L;
public int code = 0;
public String errormsg = "";
public Data data;

public class Data implements Serializable {
目前写法1成功，写法2失败，
报错

FATAL EXCEPTION: main
 com.alibaba.fastjson.JSONException: default constructor not found. class
 com.test.LoginStartBean$Data
at com.alibaba.fastjson.util.DeserializeBeanInfo.computeSetters(Unknown Source)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(Unknown Source)
at  com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(Unknown Source)

请问怎样让写法2也能混淆成功？

**Comment by halfhq** [comment]
加入static无效，请参考：https://github.com/alibaba/fastjson/issues/1173

**Comment by halfhq** [comment]
1.使用static类
2.创建一个interface IFastJson，将此类的全部implements IFastJson
3.在proguard.txt中配置

-keep class * implements com.xxxx.IFastJson { 
    public <init>(***);
}
