### ISSUE TITLE
1.2.44版本 序列化List可能有bug

### ISSUE THREAD

**Issue by ZZMarquis** [alibaba/fastjson#1693]
public static class Employee {
    private Integer id;
    private String name;
    
    public Integer getId() {
      return id;
    }
    
    public void setId(Integer id) {
      this.id = id;
    }
    
    public String getName() {
      return name;
    }
    
    public void setName(String name) {
      this.name = name;
    }
  }
  
  public static class Department {
    private String name;
    
    private List<Employee> employees;

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public List<Employee> getEmployees() {
      return employees;
    }

    public void setEmployees(List<Employee> employees) {
      this.employees = employees;
    }
  }
  
  public static void main(String[] args) {
    Employee e1 = new Employee();
    e1.setId(1);
    e1.setName("Jack");
    Employee e2 = new Employee();
    e2.setId(2);
    e2.setName("Mike");
    
    List<Employee> employees = new ArrayList<>();
    employees.add(e1);
    employees.add(e2);
    
    Department d1 = new Department();
    d1.setName("OPS");
    d1.setEmployees(employees);
    Department d2 = new Department();
    d2.setName("RD");
    d2.setEmployees(employees);
    
    List<Department> departments = new ArrayList<>();
    departments.add(d1);
    departments.add(d2);
    
    System.out.println(JSON.toJSONString(departments));
  }

输出结果是：
[{"employees":[{"id":1,"name":"Jack"},{"id":2,"name":"Mike"}],"name":"OPS"},{"employees":[{"$ref":"$[0].employees[0]"},{"$ref":"$[0].employees[1]"}],"name":"RD"}]

**Comment by Veiintc** [comment]
JSON.toJSONString(departments, SerializerFeature.DisableCircularReferenceDetect)

**Comment by ZZMarquis** [comment]
@Veiintc 多谢指点
