### ISSUE TITLE
FastJson升级到1.2.44报错

### ISSUE THREAD

**Issue by ghostjuneyao** [alibaba/fastjson#1699]
原使用FastJson 1.2.7版本，使用上没有问题，但升级到1.2.44版本报错。
com.alibaba.fastjson.JSONException: syntax error, expect ,, actual string
        at com.alibaba.fastjson.parser.DefaultJSONParser.accept(DefaultJSONParser.java:1451)
        at com.alibaba.fastjson.serializer.MiscCodec.deserialze(MiscCodec.java:224)
        at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_17_RatingDetailATO.deserialze(Unknown Source)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:378)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1349)
        at com.alibaba.fastjson.parser.deserializer.JavaObjectDeserializer.deserialze(JavaObjectDeserializer.java:45)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:654)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:365)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:269)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:488)

   升级到1.2.7.sec01，并通过脚本方式开启autoType白名单运行正常。

**Comment by ghostjuneyao** [comment]
问题已经通过单侧工具重现：
{"@type":"com.taobao.huijin.hjbase.ratingdetail.dto.RatingDetailReadMTO","amount":285.600000,"billId":3945,"bizId":"6000007==201712==USER_ID==2049884395&&CONTRACT_NO==\"no1513922344271\"","bizTime":"2017-12-31 00:00:00","bizType":"6000007","currency":"CNY","dealTime":"2017-12-23 14:11:03","detailType":"CYCLE_CHARGING","extendInfo":{"@type":"java.util.LinkedHashMap","BUY_AMOUNT":"3","P_BIZ_ID":"USER_ID==2049884395&&CONTRACT_NO==\"no1513922344271\"","SETTLE_SIDE":"654321","SETTLE_CYCLE_TYPE":"3","AUCTION_PRICE":"119","CALCULATE_RANGE":"STORE","TOTAL_NUM":"1","BILL_CYCLE":"201712","IS_PRE_CHARGING":"false","BRANCH_SHOP":"branchShop1","CONTRACT_TYPE":"HEMA_CHARGING_PROD","stepRateType":"3","SOURCE_TYPE":"PURCHASE_ADJUST","SETTLE_SIDE_NICK":"测试结算主体","express_value":"USER_ID==2049884395&&CONTRACT_NO==\"no1513922344271\"","BIZ_TIME":"2017-12-22 13:59:05","TRADE_ID":"1513922344273","QUANTITY":"3.000000","MES_RECEIVE_TIME":"2017-12-22 13:59:05","UN_TAX_UNIT_PRICE":"100.000000","AUCTION_ID":"123","AUCTION_NAME":"测试商品","rate_value":"{\"extendInfo\":{},\"intervalValues\":[{\"max\":600.000000,\"min\":0.000000,\"rate\":0.600000},{\"max\":1000.000000,\"min\":600.000000,\"rate\":0.300000},{\"max\":999999999999.000000,\"min\":1000.000000,\"rate\":0.100000}]}","CAT_ID":"16","UNIT":"kilometer","TERM_NAME":"盒马.合同返利.促销推广费","USER_ID":"2049884395","UNIT_PRICE":"119.000000","tbRuleCode":"HM_SETTLE_CHARGING","AMOUNT":"357.000000","CAT_NAME":"水果","EXTERNAL_NO":"HM==1513922344273","CHANNEL":"online","is_default_rate":"false","CURRENCY":"CNY","rate_rule_id":"300000531","OTHER_USER_NICK":"甲方","RATE_TYPE":"14","ITEM_NAME":"盒马.促销推广费","rate_rule_inst_id":"1009129180821","TAX_RATE":"0.190000","ITEM_CODE":"BILL_HM_6000007","CONTRACT_SIDE":"12345","UNTAX_AMOUNT":"300.000000","CONTRACT_VERSION":"V001","CONTRACT_NO":"no1513922344271","P_TRADE_ID":"1513922344273"},"gmtCreate":"2017-12-23 14:11:03","gmtModified":"2017-12-23 14:11:03","id":6235300020395,"indexNum":0,"innerId":6300120395,"innerTable":"SETTLE_DATA","isJoin":"FALSE","itemId":90000000007031,"mesId":3235,"mesReceiveTime":"2017-12-22 13:59:05","outBizId":"USER_ID==2049884395&&CONTRACT_NO==\"no1513922344271\"","pTradeId":3235,"priority":0,"proration":0.6,"quantity":476.000000,"rateDefineId":40000443,"rateParams":{"@type":"java.util.LinkedHashMap"},"status":"SUCCESS","tradeId":3761,"userId":2049884395,"userNick":"乙方","version":1}

![image](https://user-images.githubusercontent.com/35261582/34753314-48591e8c-f5f2-11e7-89a5-a82912547d33.png)

**Comment by kimmking** [comment]
hi, 能否给我一个testcase，kimmking@163.com

**Comment by ghostjuneyao** [comment]
@Test
    public void testFastJson() {
        try {
           ParserConfig.getGlobalInstance().setAutoTypeSupport(true);

            String event1 = "{\"@type\":\"com.taobao.huijin.hjbase.ratingdetail.dto.RatingDetailReadMTO\",\"amount\":285.600000,\"billId\":3945,\"bizId\":\"6000007==201712==USER_ID==2049884395&&CONTRACT_NO==\\\"no1513922344271\\\"\",\"bizTime\":\"2017-12-31 00:00:00\",\"bizType\":\"6000007\",\"currency\":\"CNY\",\"dealTime\":\"2017-12-23 14:11:03\",\"detailType\":\"CYCLE_CHARGING\",\"extendInfo\":{\"@type\":\"java.util.LinkedHashMap\",\"BUY_AMOUNT\":\"3\",\"P_BIZ_ID\":\"USER_ID==2049884395&&CONTRACT_NO==\\\"no1513922344271\\\"\",\"SETTLE_SIDE\":\"654321\",\"SETTLE_CYCLE_TYPE\":\"3\",\"AUCTION_PRICE\":\"119\",\"CALCULATE_RANGE\":\"STORE\",\"TOTAL_NUM\":\"1\",\"BILL_CYCLE\":\"201712\",\"IS_PRE_CHARGING\":\"false\",\"BRANCH_SHOP\":\"branchShop1\",\"CONTRACT_TYPE\":\"HEMA_CHARGING_PROD\",\"stepRateType\":\"3\",\"SOURCE_TYPE\":\"PURCHASE_ADJUST\",\"SETTLE_SIDE_NICK\":\"测试结算主体\",\"express_value\":\"USER_ID==2049884395&&CONTRACT_NO==\\\"no1513922344271\\\"\",\"BIZ_TIME\":\"2017-12-22 13:59:05\",\"TRADE_ID\":\"1513922344273\",\"QUANTITY\":\"3.000000\",\"MES_RECEIVE_TIME\":\"2017-12-22 13:59:05\",\"UN_TAX_UNIT_PRICE\":\"100.000000\",\"AUCTION_ID\":\"123\",\"AUCTION_NAME\":\"测试商品\",\"rate_value\":\"{\\\"extendInfo\\\":{},\\\"intervalValues\\\":[{\\\"max\\\":600.000000,\\\"min\\\":0.000000,\\\"rate\\\":0.600000},{\\\"max\\\":1000.000000,\\\"min\\\":600.000000,\\\"rate\\\":0.300000},{\\\"max\\\":999999999999.000000,\\\"min\\\":1000.000000,\\\"rate\\\":0.100000}]}\",\"CAT_ID\":\"16\",\"UNIT\":\"kilometer\",\"TERM_NAME\":\"盒马.合同返利.促销推广费\",\"USER_ID\":\"2049884395\",\"UNIT_PRICE\":\"119.000000\",\"tbRuleCode\":\"HM_SETTLE_CHARGING\",\"AMOUNT\":\"357.000000\",\"CAT_NAME\":\"水果\",\"EXTERNAL_NO\":\"HM==1513922344273\",\"CHANNEL\":\"online\",\"is_default_rate\":\"false\",\"CURRENCY\":\"CNY\",\"rate_rule_id\":\"300000531\",\"OTHER_USER_NICK\":\"甲方\",\"RATE_TYPE\":\"14\",\"ITEM_NAME\":\"盒马.促销推广费\",\"rate_rule_inst_id\":\"1009129180821\",\"TAX_RATE\":\"0.190000\",\"ITEM_CODE\":\"BILL_HM_6000007\",\"CONTRACT_SIDE\":\"12345\",\"UNTAX_AMOUNT\":\"300.000000\",\"CONTRACT_VERSION\":\"V001\",\"CONTRACT_NO\":\"no1513922344271\",\"P_TRADE_ID\":\"1513922344273\"},\"gmtCreate\":\"2017-12-23 14:11:03\",\"gmtModified\":\"2017-12-23 14:11:03\",\"id\":6235300020395,\"indexNum\":0,\"innerId\":6300120395,\"innerTable\":\"SETTLE_DATA\",\"isJoin\":\"FALSE\",\"itemId\":90000000007031,\"mesId\":3235,\"mesReceiveTime\":\"2017-12-22 13:59:05\",\"outBizId\":\"USER_ID==2049884395&&CONTRACT_NO==\\\"no1513922344271\\\"\",\"pTradeId\":3235,\"priority\":0,\"proration\":0.6,\"quantity\":476.000000,\"rateDefineId\":40000443,\"rateParams\":{\"@type\":\"java.util.LinkedHashMap\"},\"status\":\"SUCCESS\",\"tradeId\":3761,\"userId\":2049884395,\"userNick\":\"乙方\",\"version\":1}";
            Serializable obj = JSON.parseObject(event1, Serializable.class);
            System.out.println(obj);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

**Comment by ghostjuneyao** [comment]
@Test public void testFastJson() { try { ParserConfig.getGlobalInstance().setAutoTypeSupport(true); String event1 = "{\"@type\":\"com.taobao.huijin.hjbase.ratingdetail.dto.RatingDetailReadMTO\",\"amount\":285.600000,\"billId\":3945,\"bizId\":\"6000007==201712==USER_ID==2049884395CONTRACT_NO==\\\"no1513922344271\\\"\",\"bizTime\":\"2017-12-31 00:00:00\",\"bizType\":\"6000007\",\"currency\":\"CNY\",\"dealTime\":\"2017-12-23 14:11:03\",\"detailType\":\"CYCLE_CHARGING\",\"extendInfo\":{\"@type\":\"java.util.LinkedHashMap\",\"BUY_AMOUNT\":\"3\",\"P_BIZ_ID\":\"USER_ID==2049884395CONTRACT_NO==\\\"no1513922344271\\\"\",\"SETTLE_SIDE\":\"654321\",\"SETTLE_CYCLE_TYPE\":\"3\",\"AUCTION_PRICE\":\"119\",\"CALCULATE_RANGE\":\"STORE\",\"TOTAL_NUM\":\"1\",\"BILL_CYCLE\":\"201712\",\"IS_PRE_CHARGING\":\"false\",\"BRANCH_SHOP\":\"branchShop1\",\"CONTRACT_TYPE\":\"HEMA_CHARGING_PROD\",\"stepRateType\":\"3\",\"SOURCE_TYPE\":\"PURCHASE_ADJUST\",\"SETTLE_SIDE_NICK\":\"测试结算主体\",\"express_value\":\"USER_ID==2049884395CONTRACT_NO==\\\"no1513922344271\\\"\",\"BIZ_TIME\":\"2017-12-22 13:59:05\",\"TRADE_ID\":\"1513922344273\",\"QUANTITY\":\"3.000000\",\"MES_RECEIVE_TIME\":\"2017-12-22 13:59:05\",\"UN_TAX_UNIT_PRICE\":\"100.000000\",\"AUCTION_ID\":\"123\",\"AUCTION_NAME\":\"测试商品\",\"rate_value\":\"{\\\"extendInfo\\\":{},\\\"intervalValues\\\":[{\\\"max\\\":600.000000,\\\"min\\\":0.000000,\\\"rate\\\":0.600000},{\\\"max\\\":1000.000000,\\\"min\\\":600.000000,\\\"rate\\\":0.300000},{\\\"max\\\":999999999999.000000,\\\"min\\\":1000.000000,\\\"rate\\\":0.100000}]}\",\"CAT_ID\":\"16\",\"UNIT\":\"kilometer\",\"TERM_NAME\":\"盒马.合同返利.促销推广费\",\"USER_ID\":\"2049884395\",\"UNIT_PRICE\":\"119.000000\",\"tbRuleCode\":\"HM_SETTLE_CHARGING\",\"AMOUNT\":\"357.000000\",\"CAT_NAME\":\"水果\",\"EXTERNAL_NO\":\"HM==1513922344273\",\"CHANNEL\":\"online\",\"is_default_rate\":\"false\",\"CURRENCY\":\"CNY\",\"rate_rule_id\":\"300000531\",\"OTHER_USER_NICK\":\"甲方\",\"RATE_TYPE\":\"14\",\"ITEM_NAME\":\"盒马.促销推广费\",\"rate_rule_inst_id\":\"1009129180821\",\"TAX_RATE\":\"0.190000\",\"ITEM_CODE\":\"BILL_HM_6000007\",\"CONTRACT_SIDE\":\"12345\",\"UNTAX_AMOUNT\":\"300.000000\",\"CONTRACT_VERSION\":\"V001\",\"CONTRACT_NO\":\"no1513922344271\",\"P_TRADE_ID\":\"1513922344273\"},\"gmtCreate\":\"2017-12-23 14:11:03\",\"gmtModified\":\"2017-12-23 14:11:03\",\"id\":6235300020395,\"indexNum\":0,\"innerId\":6300120395,\"innerTable\":\"SETTLE_DATA\",\"isJoin\":\"FALSE\",\"itemId\":90000000007031,\"mesId\":3235,\"mesReceiveTime\":\"2017-12-22 13:59:05\",\"outBizId\":\"USER_ID==2049884395CONTRACT_NO==\\\"no1513922344271\\\"\",\"pTradeId\":3235,\"priority\":0,\"proration\":0.6,\"quantity\":476.000000,\"rateDefineId\":40000443,\"rateParams\":{\"@type\":\"java.util.LinkedHashMap\"},\"status\":\"SUCCESS\",\"tradeId\":3761,\"userId\":2049884395,\"userNick\":\"乙方\",\"version\":1}"; Serializable obj = JSON.parseObject(event1, Serializable.class); System.out.println(obj); } catch (Exception e) { System.out.println(e.getMessage()); } }


原始邮件
发件人:kimmkingnotifications@github.com
收件人:alibaba/fastjsonfastjson@noreply.github.com
抄送:姚君(德纯)dechun.yj@alibaba-inc.com; Authorauthor@noreply.github.com
发送时间:2018年1月10日(周三) 13:14
主题:Re: [alibaba/fastjson] FastJson升级到1.2.44报错 (#1699)


hi, 能否给我一个testcase，kimmking@163.com

**Comment by kimmking** [comment]
RatingDetailReadMTO code, thx.

**Comment by ghostjuneyao** [comment]
package com.taobao.huijin.hjbase.ratingdetail.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Currency;
import java.util.Date;
import java.util.Map;


enum FeeTypeMEnum {

    TRADE((byte) 0, "交易"),
    REFUND((byte) 1, "退款");

    private Byte type;

    private String remark;

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    private FeeTypeMEnum(Byte type, String remark) {
        this.type = type;
        this.remark = remark;
    }
}

 enum InnerTypeMEnum {

    SETTLE_DATA("hj_settle_data", "结算单据");


    private String type;

    private String remark;

    InnerTypeMEnum(String type, String remark) {
        this.type = type;
        this.remark = remark;
    }
}

public class RatingDetailReadMTO implements Serializable {

    private static final long serialVersionUID = 6413142622719509002L;

    /**
     * *
     */
    private Long id;

    /**
     * 用户ID
     */
    private Long userId;

    /**
     * 用户NICK
     */
    private String userNick;

    /**
     * 消息ID
     */
    private Long mesId;

    /**
     * 事件类型， 枚举值参照：ra_event_object.type
     */
    private String eventType;

    /**
     * 唯一去重号
     */
    private String bizId;

    /**
     * 序列号
     */
    private Integer indexNum;

    /**
     * 业务类型（同原始消息)
     */
    private String bizType;

    /**
     * 业务交易号
     */
    private String outBizId;

    /**
     * 主订单ID
     */
    private Long pTradeId;

    /**
     * 子订单ID
     */
    private Long tradeId;

    /**
     * 业务交易时间
     */
    private Date bizTime;

    /**
     * 消息接收时间
     */
    private Date mesReceiveTime;

    /**
     * 处理时间
     */
    private Date dealTime;

    /**
     * 详单科目编号
     */
    private Long itemId;

    /**
     * 详单类型： 1、普通详单 2、分成详单 3、预收分成详单
     */
    private RatingDetailTypeMEnum detailType;

    /**
     * 原始金额
     */
    private BigDecimal quantity;

    /**
     * 金额
     */
    private BigDecimal amount;

    /**
     * 费率编号
     */
    private Long rateDefineId;

    /**
     * 计费因子
     */
    private BigDecimal proration;

    /**
     * 产品编号
     */
    private Long prodId;

    /**
     * 扩展信息
     */
    private Map<String, String> extendInfo;

    private Map<String, String> rateParams;

    private Currency currency;

    private InnerTypeMEnum innerTable;
    private Long innerId;
    
    /**
     * 环境标识
     */
    private String ownSign;

    /**
     * 帐单ID， 记账结束后回写
     */
    private Long billId;

    /**
     * 版本编号
     */
    private Integer version;

    /**
     * 是否合并付款： 0、否 1、是
     */
    private RatingDetailIsJoinMEnum isJoin;

    /**
     * 优先级， 值越大，优先级越高
     */
    private Integer priority;

    /**
     * 状态： 0、初始 1、处理成功； 2、处理失败； 3、等待合并；
     */
    private RatingDetailStatusMEnum status;

    /**
     * 创建时间
     */
    private Date gmtCreate;

    /**
     * 修改时间
     */
    private Date gmtModified;

    /**
     * 交易项目：0、交易；1、退款
     */
    private FeeTypeMEnum feeType;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserNick() {
        return userNick;
    }

    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    public Long getMesId() {
        return mesId;
    }

    public void setMesId(Long mesId) {
        this.mesId = mesId;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getBizId() {
        return bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public String getBizType() {
        return bizType;
    }

    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    public String getOutBizId() {
        return outBizId;
    }

    public void setOutBizId(String outBizId) {
        this.outBizId = outBizId;
    }

    public Long getpTradeId() {
        return pTradeId;
    }

    public void setpTradeId(Long pTradeId) {
        this.pTradeId = pTradeId;
    }

    public Long getTradeId() {
        return tradeId;
    }

    public void setTradeId(Long tradeId) {
        this.tradeId = tradeId;
    }

    public Date getBizTime() {
        return bizTime;
    }

    public void setBizTime(Date bizTime) {
        this.bizTime = bizTime;
    }

    public Date getMesReceiveTime() {
        return mesReceiveTime;
    }

    public void setMesReceiveTime(Date mesReceiveTime) {
        this.mesReceiveTime = mesReceiveTime;
    }

    public Date getDealTime() {
        return dealTime;
    }

    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getRateDefineId() {
        return rateDefineId;
    }

    public void setRateDefineId(Long rateDefineId) {
        this.rateDefineId = rateDefineId;
    }

    public Long getProdId() {
        return prodId;
    }

    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    public String getOwnSign() {
        return ownSign;
    }

    public void setOwnSign(String ownSign) {
        this.ownSign = ownSign;
    }

    public Long getBillId() {
        return billId;
    }

    public void setBillId(Long billId) {
        this.billId = billId;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public RatingDetailTypeMEnum getDetailType() {
        return detailType;
    }

    public void setDetailType(RatingDetailTypeMEnum detailType) {
        this.detailType = detailType;
    }

    public RatingDetailIsJoinMEnum getIsJoin() {
        return isJoin;
    }

    public void setIsJoin(RatingDetailIsJoinMEnum isJoin) {
        this.isJoin = isJoin;
    }

    public RatingDetailStatusMEnum getStatus() {
        return status;
    }

    public void setStatus(RatingDetailStatusMEnum status) {
        this.status = status;
    }

    public FeeTypeMEnum getFeeType() {
        return feeType;
    }

    public void setFeeType(FeeTypeMEnum feeType) {
        this.feeType = feeType;
    }

    public Map<String, String> getExtendInfo() {
        return extendInfo;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getProration() {
        return proration;
    }

    public void setProration(BigDecimal proration) {
        this.proration = proration;
    }

    public Integer getIndexNum() {
        return indexNum;
    }

    public void setIndexNum(Integer indexNum) {
        this.indexNum = indexNum;
    }

    public Map<String, String> getRateParams() {
        return rateParams;
    }

    public void setRateParams(Map<String, String> rateParams) {
        this.rateParams = rateParams;
    }

    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public InnerTypeMEnum getInnerTable() {
        return innerTable;
    }

    public void setInnerTable(InnerTypeMEnum innerTable) {
        this.innerTable = innerTable;
    }

    public Long getInnerId() {
        return innerId;
    }

    public void setInnerId(Long innerId) {
        this.innerId = innerId;
    }

    public void setExtendInfo(Map<String, String> extendInfo) {
        this.extendInfo = extendInfo;
    }
}

**Comment by ghostjuneyao** [comment]
//FeeTypeMEnum
package com.taobao.huijin.hjbase.constants;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public enum FeeTypeMEnum {

    TRADE((byte) 0, "交易"),
    REFUND((byte) 1, "退款");

    private Byte type;

    private String remark;

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    private FeeTypeMEnum(Byte type, String remark) {
        this.type = type;
        this.remark = remark;
    }
}

**Comment by ghostjuneyao** [comment]
//InnerTypeMEnum
package com.taobao.huijin.hjbase.constants;

public enum InnerTypeMEnum {
     SETTLE_DATA("hj_settle_data", "结算单据");

    private String type;

    private String remark;

    InnerTypeMEnum(String type, String remark) {
        this.type = type;
        this.remark = remark;
    }
}

**Comment by ghostjuneyao** [comment]
我测试了下，问题应该是在枚举类上，如果枚举类作为内部类定义在RatingDetailReadMTO中，反序列化是没有问题的。

**Comment by ghostjuneyao** [comment]
这个问题能否尽快帮忙确认下。谢谢了！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.45
问题已修复，请用新版本
