### ISSUE TITLE
JSONPath能不能支持一下&&操作符,支持多条件筛选

### ISSUE THREAD

**Issue by kevin90828** [alibaba/fastjson#1733]
比如$.books[price>20&&category = '科幻']

**Comment by kimmking** [comment]
&& 不是jsonpath操作符

http://goessner.net/articles/JsonPath/index.html#e2

**Comment by kimmking** [comment]
jackson和gson都没有直接支持。
有一个思路就是，利用
https://github.com/json-path/JsonPath

额外添加fastjson的provider，我近期来做一下吧，看看本周是否能做出来。

**Comment by kimmking** [comment]
@kevin90828 
@wenshao 

这样fastjson里，可以考虑不再维护jsonpath模块。

**Comment by kevin90828** [comment]
嗯，我知道现在是不支持的，希望能做出来提供这个功能，很有用。

**Comment by wenshao** [comment]
后续会支持，争取在春节期间做完

**Comment by kevin90828** [comment]
期待！你们回复真快！现在用的是https://github.com/json-path/JsonPath，不知道性能会不会比这高

**Comment by wenshao** [comment]
@kevin90828 性能应该比JsonPath的实现更好，毕竟是内置支持的

**Comment by kevin90828** [comment]
1.2.47版本是已经完成了么？

**Comment by wenshao** [comment]
@kevin90828 已将完成了，预计下个周末发布（17日）

**Comment by kevin90828** [comment]
OK，多谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.47
问题已修复，请用新版本

**Comment by kevin90828** [comment]
收到，非常感谢！
