### ISSUE TITLE
unicode乱码

### ISSUE THREAD

**Issue by liubailin2017** [alibaba/fastjson#1742]
我在获得金山词典里的json数据时，英标乱码 原数据  h\u0259'l\u0259\u028a 解析出来 h?'l??
怎么fastjson不认识特殊字符吗? 请告诉我怎么解决。

**Comment by kimmking** [comment]
can you provide a complete json for reproducing the case?

**Comment by liubailin2017** [comment]
谢谢，问题解决了， 是windows的控制台的字符集用的是gbk所以乱码。 所以这个问题和fastjson 无关。
