### ISSUE TITLE
Something wrong with decoder for Map<Long, *>

### ISSUE THREAD

**Issue by hzxie** [alibaba/fastjson#1756]
There's something wrong with the following code:

```
long key = 1000;
String = "{1000: {"key#1": "value#1"}}";
Map<Long, Map<String, String>> codeSnippet = JSON.parseObject(str, Map.class);

System.out.println(codeSnippet.containsKey(key));
```

The expected output should be `true` but it outputted `false`.
Especially, there's a runtime error with following code:

```
for ( Long l : codeSnippet.keySet()  ) {
    // Do something
}
```

And I got an error saying `java.lang.ClassCastException: java.base/java.lang.Integer cannot be cast to java.base/java.lang.Long`.

Can you tell me what's wrong with it?

**Comment by hzxie** [comment]
Java Version:

```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by hzxie** [comment]
I solved it with following statements:

```
Map<Long, Map<String, String>> codeSnippet = JSON.parseObject(str,
	new TypeReference<Map<Long, Map<String, String>>>() {});
```

**Comment by kimmking** [comment]
you got it.
when you tell fastjson a map.class, it donn't understand you want a long type key.
