### ISSUE TITLE
继承后 父类属性上的JSONField 不起作用

### ISSUE THREAD

**Issue by LarryZhang** [alibaba/fastjson#176]
测试版本 fastjson-1.1.40.jar from maven repository
jdk sun 1.7
package json;

import org.testng.Assert;
import org.testng.annotations.Test;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.annotation.JSONField;

/**
- 
- @author LarryZ 用来测试继承类的json解析
  */
  public class FastJsonInheritTest {
  String text = "{\"content\":\"result\"}";
  @Test
  public void testParent() {
      ParentClass parentClass=JSON.parseObject(text, ParentClass.class);  
      Assert.assertEquals(parentClass.getTest(), "result");
  }
  
  @Test 
  public void testSub(){
      SubClass subClass=JSON.parseObject(text, SubClass.class);  
      Assert.assertEquals(subClass.getTest(), "result");
  }
  }
  class ParentClass {
  @JSONField(name="content")
  protected String test;
  
  public String getTest() {
      return test;
  }
  
  public void setTest(String test) {
      this.test = test;
  }

}

class SubClass extends ParentClass{

}

**Comment by chenssy89** [comment]
在1.2.0中测试，还是无法获取
