### ISSUE TITLE
com.alibaba.fastjson.JSONObject#getDoubleValue获取空字符串报空指针错误

### ISSUE THREAD

**Issue by csf-sqrt4** [alibaba/fastjson#1761]
我在用JSONObject的getDoubleValue方法获取下边数据的时候报空指针，而getDouble不会报空指针错误，请问是什么原因，代码示例如下：
JSONObject jsonObject = new JSONObject();
jsonObject.put("null","");
Double d = jsonObject.getDoubleValue("null")

**Comment by wenshao** [comment]
最新版是好的。
新服务器版本 http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.46/
Android新版本 http://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.68.android/
