### ISSUE TITLE
1.2.20 版本，TypeReference 初始化传 actualTypeArguments 被解析为 actualType导致抛ClassCastException

### ISSUE THREAD

**Issue by horsy945** [alibaba/fastjson#1768]
我们有这样一段代码
`    @Test
    public void test_parseObject() {
        String json = "{\"rdsSchemaName\":\"logistics_center\",\"add_mq_time\":1521446282282,\"binlogTime\":1521446282000,\"before\":{},\"binlogSequenceNo\":1521446281501002205,\"eventType\":\"INSERT\",\"schemaName\":\"logistics_center\",\"binlogOffset\":493653839,\"binlogTransactionNo\":1152144628200388,\"binlogTableName\":\"delivery_setting\",\"binlogFileName\":\"mysql-bin.002085\",\"binlogApplyTime\":1521446282282,\"after\":{\"kdt_id\":\"40532647\",\"updated_at\":\"2018-03-19 15:58:02\",\"offline_id\":\"\",\"is_local_in_time\":\"0\",\"created_at\":\"2018-03-19 15:58:02\",\"id\":\"2541463\",\"is_local\":\"0\",\"is_express\":\"1\",\"is_self\":\"0\",\"calc_type\":\"0\"},\"nsqTraceId\":1521446282282}";

        Class clazz = DeliverySettingDO.class;
        BinlogFullMsgBody<DeliverySettingDO> binlogContent;

        TypeReference<BinlogFullMsgBody<DeliverySettingDO>> typeReference = new TypeReference<BinlogFullMsgBody<DeliverySettingDO>>(clazz) {
        };

        binlogContent = JSON.parseObject(json, typeReference);

        Assert.assertNotNull(binlogContent);
    }`

执行时抛了ClassCastException

![image](https://user-images.githubusercontent.com/12403154/37588299-cbaa7828-2b9c-11e8-969f-415d408c13fb.png)

fastjson 版本号 1.2.20

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.47
能使用新版本试试看么？

**Comment by horsy945** [comment]
试过了，解决了，非常感谢。





|
姓名苏国庆
suguoqing83@163.com
公司名称：杭州有赞科技有限公司
地址：
手机：17706521075
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|

在 2018-03-20 00:19:23，"温绍锦" <notifications@github.com> 写道：


https://github.com/alibaba/fastjson/releases/tag/1.2.47
能使用新版本试试看么？
