### ISSUE TITLE
First letter lower case

### ISSUE THREAD

**Issue by ArnoldSpyros** [alibaba/fastjson#1784]
JSON.toJSONString converts the first letter of java variables to lower case. 

**JAVA**
![1](https://user-images.githubusercontent.com/21114687/38077409-8ab9cbe6-3341-11e8-8211-6b15ffca3c89.png)
**JSON**
![2](https://user-images.githubusercontent.com/21114687/38077410-8ad7b246-3341-11e8-8e21-f49cc26e3892.png)

**Comment by kimmking** [comment]
you can use jsonfield.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/PropertyNamingStrategy_cn
