### ISSUE TITLE
fastjson自动排序问题

### ISSUE THREAD

**Issue by andylee1890** [alibaba/fastjson#1787]
服务端组装好了LinkedHashMap : {"test": {"e": "","b": "","c": "","d": "","a": "",},....}  特定得Map,不需要再排序,
通过fastjson转换到客户端成了 : {"test": {"a": "","b": "","c": "","d": "","e": "",},....}

![image](https://user-images.githubusercontent.com/12568851/38186886-d1417f02-3687-11e8-9585-bcaf18cdb617.png)

**Comment by clodCode** [comment]
有解决这个问题吗？

**Comment by luohaoGit** [comment]
如何解决的

**Comment by chenzhixion** [comment]
我也出现了这种情况， 但是map的key 是数字类型  就会自动按小到大排序  转化LinkedHashMap 存放也没有用，不知道怎么去掉默认数字类型按小到大的排序  我这里投机取巧了下 key 前面加加了空格   解决了   key 也是展示 前端也不会复制  所以也不影响
