### ISSUE TITLE
JSON.parseObject(str, Bean.class)如何保留null字段

### ISSUE THREAD

**Issue by sclrl220** [alibaba/fastjson#1813]
String str = "{\"name\":\"测试\",\"desc\":{\"a\":1,\"b\":null}}";
Bean bean = JSON.parseObject(str, Bean.class)
转换后desc中的b字段不见了.
public class Bean {
     private String name;
     private String desc;
}

**Comment by huwei** [comment]
使用 SerializerFeature.IgnoreNonFieldGetter

**Comment by sclrl220** [comment]
good

**Comment by Marviszhao** [comment]
@huwei  @sclrl220  这种示例写法是错误的，请问一下在反序列化为bean 时如何保留为null 的key
```
Object jsonObject = JSON.parse(appParmsStr, SerializerFeature.IgnoreNonFieldGetter);
```
