### ISSUE TITLE
kotlin存在内部类对象时转JSON字符串空指针问题

### ISSUE THREAD

**Issue by Junw** [alibaba/fastjson#1814]
`
import com.alibaba.fastjson.JSONObject
import com.fasterxml.jackson.databind.ObjectMapper

class SpendLog(id: String) {
    var id: String? = id
    var event: Event? = null
    inner class Event internal constructor(var id: String)
    init {
        this.event = Event(id)
    }
}
fun main(args: Array<String>) {
    println(ObjectMapper().writeValueAsString(SpendLog("1")))
    println(JSONObject.toJSONString(SpendLog("2")))
}
`
引用了一个内部类对象时，jackson能正常转换，结果为{"id":"1","event":{"id":"1"}}，fastjson报空指针异常，是否用法有误？

**Comment by Junw** [comment]
fastjson版本为1.2.47

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本
