### ISSUE TITLE
@JSONField 是否可以添加defaultValue的支持?

### ISSUE THREAD

**Issue by guodage** [alibaba/fastjson#1816]
在issue中没有看到相关问题，大家没有这个需求吗。
类似jackson中 @JsonProperty(defaultValue="hello")

**Comment by vipcxj** [comment]
通过getter或setter方法，甚至直接在无参构造函数里赋默认值或者声明变量成员时赋个默认值就可以达到你需要的效果，而且明显比考什么@JSONField靠谱，毕竟就算@JSONField支持，也会让java bean和json的值不一致
