### ISSUE TITLE
fastjson生成的jsonString不符合JSON规范

### ISSUE THREAD

**Issue by fengtianxp** [alibaba/fastjson#182]
json.org明确定义了JSON String中不能含有\t  之类的特殊字符。fastJson没有做过任何处理。导致生成的JSONString只是文本而不是JSON String。
    private String name;
       public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public static void main(String[] args) {
        JsonTest jt = new JsonTest();
        jt.setName("test \t info");
        System.out.println(JSON.toJSONString(jt));  
    }
生成的输出是{"name":"test      info"}
然后把这个文本拷贝出来。放在chrome的控制台中。

var a = '{"name":"test   info"}';
undefined
var b = JSON.parse(a)
SyntaxError: Unexpected token

或者随便找个浏览器或者第三方的JSON 序列化jar都不支持。

**Comment by ulyn** [comment]
@fengtianxp 我也遇到同样的问题，升级了最新版本，转出来的字符串还是带着\t 导致浏览器无法解析，请问你是怎么成功解析的，升级到什么版本？
