### ISSUE TITLE
FastJson 在解析 <? extends Comparable>  泛型时报栈溢出的错误

### ISSUE THREAD

**Issue by TimeEraser** [alibaba/fastjson#1833]
fastjson版本是1.2.29在使用通配符<? extends Comparable> 进行解析时汇报栈溢出的错误
数据格式如图
![image](https://user-images.githubusercontent.com/12388190/39750219-417a3054-52e7-11e8-917c-e6d45e07d1ba.png)
错误异常如图
![image](https://user-images.githubusercontent.com/12388190/39750245-5441457e-52e7-11e8-9a4b-1b3da3f34da2.png)

但是如果使用 < ? extends Number >  或 < ? >      时则没有问题

**Comment by TimeEraser** [comment]
![image](https://user-images.githubusercontent.com/12388190/39750780-bdc25fa0-52e8-11e8-8ca8-036972e09258.png)
这样写也不行，同样的错误，是Comparable有特殊处理？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本
