### ISSUE TITLE
versions difference between 1.2.5 and lastest

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/fastjson#1835]
There is a running difference in SerializerFeature:

```java
public static final int WRITE_MAP_NULL_FEATURES
            = WriteMapNullValue.getMask()
            | WriteNullBooleanAsFalse.getMask()
            | WriteNullListAsEmpty.getMask()
            | WriteNullNumberAsZero.getMask()
            | WriteNullStringAsEmpty.getMask()
            ;
```

The lastest version will take WriteMapNullValue, WriteNullBooleanAsFalse, WriteNullListAsEmpty, WriteNullNumberAsZero, WriteNullStringAsEmpty as **WriteMapNullValue** while old version take SIMPLE WriteMapNullValue.

This will result different output when we set WriteNullStringAsEmpty with no WriteMapNullValue setted.
Nulled fields will be skipped in old versions but they will be "null" in newer versions.

Does it make sense?

**Comment by jasonjoo2010** [comment]
update:

I have seen the latest changes in **1.2.48** and it do make sense for BEANS serialization.

But it still don't make sense in serialization of Maps.
I make some small changes to make it in PR #1837

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本
