### ISSUE TITLE
反序列化英文格式时间异常

### ISSUE THREAD

**Issue by holdqv** [alibaba/fastjson#1841]
如果采用标准英文时间格式会提示 以下异常
`Caused by: java.lang.NumberFormatException: For input string: "Wed May 09 16:55:00 CST 2018"
`

**Comment by wenshao** [comment]
这是locale问题导致，将会在1.2.49中修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本

**Comment by holdqv** [comment]
👍
