### ISSUE TITLE
使用spring集成fastjson后，在发送post请求，里面包括byte[]数组，会将byte[]数组做一下base64，

### ISSUE THREAD

**Issue by haifeiWu** [alibaba/fastjson#1863]
使用spring集成fastjson后，在发送post请求，里面包括byte[]数组，会将byte[]数组做一下base64，请问该如何反序列化得到正确的byte[]数组

**Comment by sizzlecar** [comment]
BASE64Decoder decoder = new BASE64Decoder();
byte[] bytes2 = decoder.decodeBuffer(str);//str为byte[]转换后的字符串
