### ISSUE TITLE
resin 中重新部署后classloader错误

### ISSUE THREAD

**Issue by depyuka** [alibaba/fastjson#187]
请严格按以下步骤重现:
1)把fastjson.jar包放入resin\lib目录, resin是4.0以上.

2)建立类B 并继承类A

3)序列化B到文件中

4)从文件中反序列化B到类型是类A的变量.

5)修改任何代码,重新部署到resin中,此时会重新加载,但由于fastjson放在resin\lib目录下,导致
classloader没重新加载.

6)此时再试图步骤4,反序列化B到A变量中,反序列化是成功的,但无法赋值到A中,提示CastException,经分析,此时反序列化出来的对象还是原来的classloader,新旧无法兼容导致不能赋值.

我的解决方案是把fastjson.jar放回web-inf/lib,以上问题我只在eclipse环境下反复验证过,但在独立运行的resin上未试过,可能会有差异

**Comment by wenshao** [comment]
抱歉，太久了，还能使用最新版本1.2.8验证么？

**Comment by wenshao** [comment]
时间太久了，又无法重现，先关闭了，如果能帮忙找到原因，请重新提issue，谢谢！
