### ISSUE TITLE
LocalDateTime序列化问题

### ISSUE THREAD

**Issue by PuGuanyu** [alibaba/fastjson#1892]
![image](https://user-images.githubusercontent.com/6291759/40912231-8c4410ae-6823-11e8-8e51-52b5835fc929.png)

如图，同样是LocalDateTime，值的不同会导致序列化结果不一致

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本

**Comment by BoomManPro** [comment]
有个问题哈，如何设置返回时间戳，因为之前和前端沟通返回时间戳，现在用的版本返回字符串，如何返回时间戳呢。
