### ISSUE TITLE
日期解析问题

### ISSUE THREAD

**Issue by tonydzt** [alibaba/fastjson#1901]
我想要解析带有“Thu Mar 22 08:58:37 +0000 2018”这种Date输出格式的日期属性的类，但是解析异常，我配置的属性注解如下：

    @JSONField(format = "EEE MMM dd HH:mm:ss zzz yyyy")
    private Date time;

这么做不能解析成功，但我试着用这种格式生成日期json，结果是：“星期二 六月 12 13:04:10 +0000 2018”

为什么会是这样，fastjson现在支持这种格式的解析吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本
