### ISSUE TITLE
JSONPath后模糊匹配bug

### ISSUE THREAD

**Issue by runLiu** [alibaba/fastjson#1902]
`JSONPath.read("{\"table\":\"_order_base\"}", "[table LIKE 'order_base%']");`
table字段前面有_，LIKE表达式值前面没有_，期望结果不匹配，实际匹配。
看源码觉得JSONPath 1079行逻辑有问题。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本

**Comment by zhulc0914** [comment]
实际不应该不匹配吗？
