### ISSUE TITLE
假如泛型是list<>，而尖括号里包含了泛型

### ISSUE THREAD

**Issue by xx394984678** [alibaba/fastjson#1913]
如果解析泛型是list<>这种，我知道正常解法是这样
`BaseEntity<List<Cat>> entity = JSON.parseObject(response,
 new TypeReference< BaseEntity <List<Cat>>>() {});`
但是如果提取解析方式到callback基类，该如何写？
我尝试了
`BaseEntity<List<T>> entity = JSON.parseObject(response, new TypeReference<BaseEntity <List<T>>>() {});`
但是这样肯定是不对的，TypeReference是要传参的，那么传一个什么样的进去？
或者这种提取基类的方式根本不对～
题外话，处理不是list<>类型的泛型，我知道是这样
`BaseEntity<T> entity = JSON.parseObject(response, new TypeReference<BaseEntity<T>>(clazz) {});`
如果将List<Cat>作为泛型传到这种解析方式里，clazz我又不知道该传什么了～

**Comment by zhuyeqing5828** [comment]
使用TypeReference
