### ISSUE TITLE
addFilter没有效果

### ISSUE THREAD

**Issue by hqw5566** [alibaba/fastjson#1915]
public class Test {

    private BigDecimal b;

    public BigDecimal getB() {
        return b;
    }

    public void setB(BigDecimal b) {
        this.b = b;
    }

    public static void main(String[] args) {
        Test test = new Test();
        test.b = new BigDecimal("324.200");

        SerializeConfig.getGlobalInstance().addFilter(BigDecimal.class, new MValueFilter());
        System.out.println(JSON.toJSONString(test));
        System.out.println(JSON.toJSONString(test, new MValueFilter()));
  
    }

}

public class MValueFilter implements com.alibaba.fastjson.serializer.ValueFilter {

    @Override
    public Object process(Object object, String name, Object value) {
        if (null != value && value instanceof BigDecimal) {
            String str = ((BigDecimal) value).stripTrailingZeros().toPlainString();
            return new BigDecimal(str);
        }
        return value;
    }

}

输出结果：
{"b":324.200}
{"b":324.2}

预期结果
{"b":324.2}
{"b":324.2}

使用1.2.47

**Comment by cj96248** [comment]
@hqw5566 
Please help update your config code to below: 
SerializeConfig.getGlobalInstance().addFilter(Test.class, new MValueFilter());

Note that the Filter is the clazz you are serializing, not the aim clazz.

**Comment by hqw5566** [comment]
@cj96248  if i want to use all clazz, What shall I do?
