### ISSUE TITLE
在线等！！！！     JsonObject.parseObject() 乱码了

### ISSUE THREAD

**Issue by Angela-shi** [alibaba/fastjson#1963]
{"feature": "WARNING: 04-03 14:38:35: * 157521952 dict-set:[./plugin/dict/burst_gbdt_model]-line[9]: line is empty or too long! [X!\u8880+\u5fa6?gF5\ue4ca\u5b4e\u7e5d\u007f\u6774\u007f\u76ecX7\u2175?<;\u001c\u84c0?\u0002]"} 使用parseObject()后就乱码了 ：X!袀+徦?gF5孎繝\u007F杴\u007F盬X7ⅵ?<;\u001C蓀?\u0002

parseObject()能否保持X!\u8880+\u5fa6?gF5\ue4ca\u5b4e\u7e5d\u007f\u6774\u007f\u76ecX7\u2175?<;\u001c\u84c0?\u0002？

**Comment by wenshao** [comment]
乱码和fastjson无关，之前应该就乱了
