### ISSUE TITLE
JSON字段含有-号，JSONPATH读取不到

### ISSUE THREAD

**Issue by gabrywu** [alibaba/fastjson#1964]
例如json字符串
{
"field1":"value",
"field-a":"value2"
}
通过jsonpath读取field-a时，报空指针异常。

**Comment by wenshao** [comment]
使用转义符，比如：
```java
JSONPath.eval(obj, "$.field\\-a");
```

**Comment by gabrywu** [comment]
@wenshao 好的，多谢啦。只不过的JSONPATH是动态的，还需要在额外处理一下。
