### ISSUE TITLE
NULL to Empty的陈年问题JDK1.7|1.2.47版本，参数都已经加上

### ISSUE THREAD

**Issue by ArthurRyan** [alibaba/fastjson#1979]
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;

import java.util.Map;
import java.util.HashMap;

public class Main {
        public static void  main(String[] args){
            Map obj = new HashMap();
            obj.put("user", null);
            String text = JSON.toJSONString(obj,
                    SerializerFeature.WriteMapNullValue,
                    SerializerFeature.WriteNullListAsEmpty);
            System.out.print(text);
        }
    }

使用JDK1.7， Fastjson 1.2.47。 在我这里执行null并没有转化成“”

**Comment by ArthurRyan** [comment]
@zhuzhaoyuan

**Comment by ArthurRyan** [comment]
@wenshao  大神，我翻看了以往的issue，实在不明白为什么不可以....

**Comment by wenshao** [comment]
这个在JavaBean中才可以
