### ISSUE TITLE
JSONPath.contains()不支持中文key?

### ISSUE THREAD

**Issue by Mr-LiuDC** [alibaba/fastjson#1988]
fastjson版本1.2.33

 在使用fastjson判断json字符串某个节点是否存在时，JSONPath.contains()似乎不支持中文key，或者需要做特殊设置？
感谢。

`$.product.features.规格` ，这种方式会报错，错误如下：

`com.alibaba.fastjson.JSONPathException: illeal jsonpath syntax. $.product.features.规格`

`$.product.features.specification` ，这种方式就没问题。

@wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本

**Comment by Mr-LiuDC** [comment]
好的，谢谢。
