### ISSUE TITLE
如何进行实现类的反序列化？ 直接反序列化数据会丢失

### ISSUE THREAD

**Issue by leveychen** [alibaba/fastjson#2018]
`MsgAttachment` 是 interface
`CustomAttachment` implements `MsgAttachment`
直接进行JSON.parser( json, MsgAttachment.class)  会丢失 CustomAttachment 的属性。

请问如何进行ParserConfig设置，能够正确反序列化出 CustomAttachment ？

````
ParserConfig.getGlobalInstance().putDeserializer(MsgAttachment.class, new ObjectDeserializer() {
                        @Override
                        public <T> T deserialze(DefaultJSONParser parser, Type type, Object fieldName) {
                           //此处已经能正确获得 CustomAttachment 在序列化之后的 字符串了
                          //这里应该如何创建一个对象？
                            return null;
                        }

                    });
````

**Comment by kimmking** [comment]
new CustomAttachment
set fields and properties

**Comment by leveychen** [comment]
@kimmking 

是在什么地方处理？
这个 CustomAttachment 是在  MsgData 里面的一个属性。 CustomAttachment 本身还不是最外层
能否提供一个简单的示例？
谢谢

**Comment by kimmking** [comment]
the parser can't know a json should be processed as a CustomAttachment object when you pass a MsgAttachment type to it.

**Comment by kimmking** [comment]
you can use this: MsgData<T extends MsgAttachment>
also see:
JSON.parseObject(json, new TypeReference<MsgData<CustomAttachment>>() {});

**Comment by leveychen** [comment]
@kimmking   thanks ，直接用 jsonObj 逐个获取然后赋值给不同集成类解决了
