### ISSUE TITLE
混淆正常,混淆后报default constructor not found 

### ISSUE THREAD

**Issue by a1b22003001** [alibaba/fastjson#2033]
data class Token(var token_type:String=""
                  ,var expires_in:String=""
                  ,var access_token:String=""
                  ,var refresh_token:String="")

混淆前能正常使用，但是混淆后报 default constructor not found 
这个数据类已经 -keep 不混淆

运行这段代码
   val token = Token()
   token.access_token = "1"
   token.expires_in = "2"
   val tokenStr = JSON.toJSONString(token)
   val token_d =  JSON.parseObject(tokenStr,Token::class.java)
   
  tokenStr能正常打印
 但是运行到 JSON.parseObject(tokenStr,Token::class.java)就报default constructor not found 

试过implements IFastJson 这个方法，但是问题依在

**Comment by a1b22003001** [comment]
已解决，因为用了kotlin-reflect,添加kotlin-reflect不混淆就正常了

**Comment by MaosanDao** [comment]
> 已解决，因为用了kotlin-reflect,添加kotlin-reflect不混淆就正常了

请问有规则代码不？怎么添加不混淆呀
