### ISSUE TITLE
Java Long类型 如何通过fastjson，转为字符串格式输出？

### ISSUE THREAD

**Issue by shenzhenjia** [alibaba/fastjson#207]
http://stackoverflow.com/questions/15689790/parse-json-in-javascript-long-numbers-get-rounded
由于以上原因
希望通过fastjson，转为字符串格式，应如何处理?谢谢！

**Comment by doinfi** [comment]
为什么long类型的101264050346978242使用fastjson转换以后显示成101264050346978240了？

**Comment by grossshen** [comment]
Java long类型有64位，JS没有数字类型统一为Number，本质上相当于double。double类型虽然也是64位，但是精度就没有long高了
