### ISSUE TITLE
测试用例无法通过

### ISSUE THREAD

**Issue by harkue** [alibaba/fastjson#2100]
使用mvn test执行测试，测试用例有部分不通过，例如

-------------------------------------------------------------------------------
Test set: com.alibaba.json.bvt.android.AliUserTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.138 sec <<< FAILURE! - in com.alibaba.json.bvt.android.AliUserTest
test_for_ali_user(com.alibaba.json.bvt.android.AliUserTest)  Time elapsed: 0.063 sec  <<< ERROR!
com.alibaba.fastjson.JSONException: 
illegal identifier : \, pos 1085, json : {"id":0,"memo":"操作成功","result":{"code":"202","data":"{\"sid\":\"xxxxxxxxxxxxd4b68e23c7xxxxxx8020\",\"loginTime\":1971044435,\"phone\":\" \",\"ecode\":\"kYxxS\",\"ssoToken\":\"eBTebMxxxxXACzTBIHxxJxxxxxxRgpKo-999999xxxxxxxxxxxxxxxxxxxxxxxxx99\",\"autoLoginToken\":\"1_xxxxxxxxxxxxxx3100xx458c4xxxxxx42ce832c82e0571xxxxxxxx862e52ba6c6c4903120acc370dbc437475cf0b76494ddb7656xxxxxxxxca006734xxxxxxxx\",\"ssoTokenExt\":{\"ssoToken\":\"eBTxxXxxxxXACxTBIHlgJxxxxxxRxxKo-999999d8467e3f492e91fae61cdecf15\",\"ssoToken_expire_in\":1309990},\"havanaSsoToken\":\"XXxXxxxxXxXXXyINaGF2YW5hX21sb2dpbioJaGF2YW5hc3NvMgEBOI61o-jCKkABShA8geQUWoiHiTQdeu_CAekuol6jAxxxXxxxXxxX9vOfXXXX8Vk\",\"havanaSsoTokenExpiredTime\":900,\"expires\":1971130235,\"nick\":\"xxxxxxx9999\",\"email\":\"xxxxxxx1999@386.com\",\"extendAttribute\":{\"ssoDomainList\":[\".tmall.com\",\".tmall.hk\"]},\"userId\":1012623173,\"autoLoginToken_expire_in\":-1,\"loginServiceExt\":{\"1688ext\":\"{\\\"loginId\\\":\\\"xxxxxxx9999\\\",\\\"nick\\\":\\\"xxxxxxx9999\\\",\\\"email\\\":\\\"qqapple1986@126.com\\\",\\\"name\\\":\\\"范冰冰\\\",\\\"userId\\\":\\\"9999993173\\\",\\\"memberId\\\":\\\"xxxxxxx9999\\\",\\\"companyName\\\":\\\"有钱无限公司001\\\",\\\"mobile\\\":\\\"13999999900\\\"}\"},\"cookies\":[\"imewweoriw=3%2FxxRx99XXXxXX99XX99vFT%2Fzy7xx99X99CaBph2T60%3D; Domain=.m.taobao.com; Expires=Tue, 26-Apr-2016 08:33:33 GMT; Path=/\",\"XXXXXXXXXXX=%2B4cMKKP%2B8PI%2BJirmoo7icE463nuhs%2BxxxxxxXxxXXXxXxxXXxx%3D%3D; Domain=.m.taobao.com; Expires=Wed, 29-Apr-2017 08:33:33 GMT; Path=/\",\"_w_tb_nick=xxxxxxx9999; Domain=.m.taobao.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"ockeqeudmj=ha%2FXXZc%3D; Domain=.m.taobao.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"imewweoriw=3%2FsmRs99FUDeYQ94ML84vFT%2Fzy7ra47B91CaBph2T60%3D; Domain=.m.etao.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"WAPFDFDTGFG=%2B4cMKKP%2B8PI%2BJirmoo7icE463nuhs%2BqxxxxxRurNBYoYcuAGww%3D%3D; Domain=.m.etao.com; Expires=Wed, 19-Apr-2017 05:40:35 GMT; Path=/\",\"_w_tb_nick=xxxxxxx9999; Domain=.m.tmall.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"imewweoriw=3%2FsmRs99FUDeYQ94ML84vFT%2Fzy7ra47B91CaBph2T60%3D; Domain=.m.tmall.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"WAPFDFDTGFG=%2B4cMKKP%2B8PI%2BJirmoo7icE463nuhs%2BqxxxxxXxxNBYoYcuAGww%3D%3D; Domain=.m.tmall.com; Expires=Wed, 19-Apr-2017 05:40:35 GMT; Path=/\",\"_w_tb_nick=xxxxxxx9999; Domain=.m.etao.com; Expires=Tue, 26-Apr-2016 05:40:35 GMT; Path=/\",\"yryetgfhth=; Domain=.login.m.taobao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"yryetgfhth=; Domain=.login.m.etao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"yryetgfhth=; Domain=.login.m.tmall.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"_w_al_f=; Domain=.m.etao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"_w_al_f=; Domain=.m.tmall.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"_w_al_f=; Domain=.m.taobao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"uc1=cookie14=XxXxXXxxx0R35w%3D%3D&cookie21=UtASsssmfuQgf65h&cookie15=XX5X2XXxXXX7XX%3D%3D;Domain=.taobao.com;Path=/;\",\"uc3=sg2=W8yf2ppgZ6eBt%2BObneJW1OUnbaLUvKrr6n%2F2NlK7TP0%3D&nk2=GcA1v%2FFLaIzauhM%3D&id2=UoH%2B5KMpLPFcvA%3D%3D&vt3=F8dASm%2BznbXXxXxxXxE%3D&lg2=XxX3XXX9XXXxXX%3D%3D;Domain=.taobao.com;Path=/;Expires=Thu, 19-May-2016 05:40:35 GMT;HttpOnly\",\"skt=9xx9999247517bf7;Domain=.taobao.com;Path=/;HttpOnly\",\"lgc=xxxxxxx9999;Domain=.taobao.com;Path=/;Expires=Thu, 19-May-2016 05:40:35 GMT;\",\"_cc_=XxX3XXX9EA%3D%3D;Domain=.taobao.com;Path=/;Expires=Wed, 19-Apr-2017 05:40:35 GMT;\",\"t=999xx9993222968918a269de7102ffb5;Domain=.taobao.com;Path=/;Expires=Mon, 18-Jul-2016 05:40:35 GMT;\",\"unb=9999999999;Domain=.taobao.com;Path=/;HttpOnly\",\"_nk_=xxxxxxx9999;Domain=.taobao.com;Path=/;\",\"_l_g_=Ug%3D%3D;Domain=.taobao.com;Path=/;\",\"cookie1=XXXx%9X9Xx9XXX6r4SXXXnGUG4y3Tgaqs7oAfI6MvIg2M%3D;Domain=.taobao.com;Path=/;HttpOnly\",\"cookie2=xxxxxxxxx999d4b68e23c72b09918020;Domain=.taobao.com;Path=/;HttpOnly\",\"cookie17=XxX%2B5KMpXXXcvA%3D%3D;Domain=.taobao.com;Path=/;HttpOnly\",\"uss=XxXXx9X9zgNt2%2BPElXWMAaKMJxxxx7xxxXXxxlRIcDTudmRexGXSgRn%2B;Domain=.taobao.com;Path=/;Expires=Thu, 19-May-2016 05:40:35 GMT;HttpOnly\",\"tracknick=xxxxxxx9999;Domain=.taobao.com;Path=/;Expires=Wed, 19-Apr-2017 05:40:35 GMT;\",\"sg=731;Domain=.taobao.com;Path=/;\",\"cookie2=xx99999xx999xxxxxxxxxx2b09918020;Domain=.taobao.com;Path=/;HttpOnly\",\"ti=200001%40alibaba_android_6.8.9.100;Domain=.m.taobao.com;Path=/;Expires=Thu, 21-Apr-2016 05:40:35 GMT;HttpOnly\",\"_tb_token_=xXx9XX9kK1OXx9;Domain=.taobao.com;Path=/;\",\"cookie2=; Domain=.tmall.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"cookie2=; Domain=.etao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"cookie2=; Domain=.hitao.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"cookie2=; Domain=.yao.95095.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\",\"cookie2=; Domain=.tdd.la; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\"],\"headPicLink\":\"http://wwc.alicdn.com/avatar/getAvatar.do?userId=9999999999&width=160&height=160&type=sns\"}","headImg":"http://wwc.taobaocdn.com/avatar/getAvatar.do?userId=9999999999&width=120&height=120&type=sns","hid":1012623173,"msg":"成功","ssoToken":"eBTebMxxxxXACzTBIHxxJxxxxxxRxxKo-999999d8467e3f492e91fae61cdecf15","success":true,"taobaoNick":"xxxxxxx9999","taobaoUserId":9999999993,"tbLoginId":"xxxxxxx0907"},"resultStatus":2001}

	at com.alibaba.json.bvt.android.AliUserTest.test_for_ali_user(AliUserTest.java:18)

**Comment by harkue** [comment]
`public class AliUserTest extends TestCase {
    private String text;
    
    public void test_for_ali_user() throws Exception {
        InputStream is = AliUserTest.class.getClassLoader().getResourceAsStream("json/aliuser.json");
        text = IOUtils.toString(is);
        
        JSON.parse(text);
    }
    
  
}`

**Comment by harkue** [comment]
`
public class AliUserTest extends TestCase {
    private String text;
    
    public void test_for_ali_user() throws Exception {
        InputStream is = AliUserTest.class.getClassLoader().getResourceAsStream("json/aliuser.json");
        text = IOUtils.toString(is);
        
        JSON.parse(text);
    }
    
  
}
`

**Comment by wenshao** [comment]
现在呢？
