### ISSUE TITLE
@JSONField(format = "yyyy-MM-ddTHH:mm:ssZ") 时间序列化报错

### ISSUE THREAD

**Issue by zqr95518** [alibaba/fastjson#2103]
当时间格式设置为yyyy-mm-ddThh:mm:ssZ的时候，会报各种奇奇怪怪的错，有时候序列化出来是个null并不报错，有时候报“T”不能识别，反正不会报这个格式不合法，导致排查了很久。

**Comment by wenshao** [comment]
```java
yyyy-MM-dd'T'HH:mm:ssZ
```
正确的格式应该是这个

**Comment by zqr95518** [comment]
这里难到不应该是啥都可以填的么，万一有啥奇怪的需求，比如中间要塞符号什么的怎么办，不应该写死吧(*/ω＼*)

**Comment by wenshao** [comment]
请使用新版 https://github.com/alibaba/fastjson/releases/tag/1.2.52
