### ISSUE TITLE
转换Long错误

### ISSUE THREAD

**Issue by BoyK** [alibaba/fastjson#2104]
class A {
    List<Long> ids;
}
ids转换错误

**Comment by wenshao** [comment]
请提供详细报错信息

**Comment by BoyK** [comment]
抱歉我表达错误。
class A {
    List<Long> ids;
}
不是转换错误，不会报错，应该说是转换丢失经度，比如我1016981473968910338会转换成1016981473968910300，按理应该转成"1016981473968910338".

**Comment by BoyK** [comment]
抱歉我表达错误。
class A {
List<Long> ids;
}
不知怎么提交的时候github把我写的泛型那块弄丢了。
不是转换错误，不会报错，应该说是转换丢失经度，比如我1016981473968910338会转换成1016981473968910300，按理应该转成"1016981473968910338".
在2018年10月25日 16:09，温绍锦<notifications@github.com> 写道：

请提供详细报错信息

**Comment by wenshao** [comment]
使用JSON.toJSONString(obj, SerializerFeature.BrowserCompatible);
