### ISSUE TITLE
SerializeWriter的close()方法导致不必要的老年代垃圾对象

### ISSUE THREAD

**Issue by zhengdehui** [alibaba/fastjson#2108]
这是com.alibaba.fastjson.serializer.SerializeWriter.close()

```java

    /**
     * Close the stream. This method does not release the buffer, since its contents might still be required. Note:
     * Invoking this method in this class will have no effect.
     */
    public void close() {
        if (writer != null && count > 0) {
            flush();
        }
        if (buf.length <= 1024 * 128) {
            bufLocal.set(buf);
        }

        this.buf = null;
    }

```

SerializeWriter初始化的时候会从threadlocal中拿出或者初始化buf，buf是char[] 对象。
buf有可能在序列化的过程中不停的扩充空间。
每次SerializeWriter在close的时候都会判断当前的buf是否大于128K（旧版是64K），如果大于128K，则丢弃掉，否则把buf放回threadlocal中下次重用。
这里的问题是，如果序列化的数据大小，徘徊在这个临界值之间，比如说通常情况下是100K，但是偶尔会来个150K，很容易导致100K的buf经过了若干次ygc之后晋升到了老年代，这时被丢弃的话就会成为老年代的垃圾，从而影响应用的gc表现。这也正是我们生产环境遇到的现象。

建议把128K这个写死的值，通过-D的参数暴露出去作为可选配置，如 -Dserialize.writer.max.buf.size=131072

**Comment by wenshao** [comment]
请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.52
