### ISSUE TITLE
发现JSONPath对Json path的语法支持的不是太好

### ISSUE THREAD

**Issue by palagend** [alibaba/fastjson#2118]
您好：
我发现这个工具包很棒，对json字符串的解析很快，让我惊喜的还有JSONPath.set这个方法，这是[JsonPath](https://github.com/json-path/JsonPath)所没有的。

但是，在使用过程中也有些烦恼，我发现JSONPath好像只支持.号访问的json path语法，不支持[]访问的json path语法。

比如说，当我在[JsonPath](https://github.com/json-path/JsonPath)中使用`$['store']['book']['main.title']`语法时，是能够获取到book的`main.title`的值，但是使用JSONPath时，会出现解析错误，只有改成`$.store.book.main\\.title`才能正确解析。不知能否改进一下对json path语法的支持？

谢谢！

**Comment by wenshao** [comment]
已经在完善JSONPath的支持，代码已经提交，性能和功能都有很大进步，将在1.2.52中支持完善。jsonpath的支持一直在完善，你当前用的什么版本？越新的版本通常支持更好。

**Comment by palagend** [comment]
目前使用的版本是1.2.47

**Comment by wenshao** [comment]
请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.52
