### ISSUE TITLE
Float 转换错误

### ISSUE THREAD

**Issue by qw666** [alibaba/fastjson#2130]
目前遇到这么一个问题：在对象中存在Float类型字段，在调用JSON.parseObject()反序列化时，会出现解析异常的问题。
eg：
 传入json字符串为：{“score”:0.000099369485}，（没有使用科学计数法表示时）
 在解析完之后score值会变为：-0.1366129

查看相关源码发现可能是在Float类型转换时，小数位比较多情况，例如：0.000099369485，会导致power溢出。
![json](https://user-images.githubusercontent.com/44799742/48051664-b62b1200-e1e0-11e8-80b6-1bf03764c46e.PNG)

**Comment by wenshao** [comment]
请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.52
