### ISSUE TITLE
fastjson 如何防御 HASH COLLISION DOS 问题

### ISSUE THREAD

**Issue by qyvlik** [alibaba/fastjson#2141]
具体的 HASH COLLISION DOS 文章介绍在这里https://coolshell.cn/articles/6424.html。
在使用 `JSON.parseObject` 时，如果传入的 `text` 是被精心设计的 hash，那么就会出现 **cpu 占用过高**，或者**解析时间长** 的问题，有什么特别好的方式或者手段处理这种情况吗？

**Comment by wenshao** [comment]
使用JDK7及以上版本即可解决问题
