### ISSUE TITLE
fastjson是否支持jackson的JsonProperty注解

### ISSUE THREAD

**Issue by JoeMinty** [alibaba/fastjson#2187]
前端通过**form表单**POST请求传过来的json格式带有下划线{image_name: "xxx"},
java端定义了一个ImageVO类，
public @Data class ImageVO {
  @JSONField(name = "image_name")
  String imageName;
}

jsonfield注解只能解决后端给前端交互时的json串keyname的转换，但是前端传到后端时，Controller方法中的ImageVO的imageName属性值为null

**Comment by wenshao** [comment]
请使用@JSONField
