### ISSUE TITLE
jsonpath 1.2.54解析有问题

### ISSUE THREAD

**Issue by chimisgo** [alibaba/fastjson#2189]
例如：[{"id":"1","name":"a"},{"id":"2","name":"b"}]执行$.*[?(@.name=='b')].id结果是 [{"id":"2","name":"b"}]而不是2

**Comment by chimisgo** [comment]
例如：[{"id":"1","name":"a"},{"id":"2","name":"b"}]执行$.*[?(@.name=='b')].id结果是 [{"id":"2","name":"b"}]而不是2

**Comment by kimmking** [comment]
看起来是个bug，应该返回[2]

**Comment by chimisgo** [comment]
1.2.55 1.2.56依旧存在

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本
