### ISSUE TITLE
Provide type short name function

### ISSUE THREAD

**Issue by weipeng2k** [alibaba/fastjson#2201]
`@JSONType` is configured on the class name, but this invades the domain, is there a way to configure it on Config Class?

Form a form like `Config.register(Class clazz, String shortName)`.

When serializing and deserializing, fastjson can match according to the configured short name.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.56 
问题已解决，请用新版本
