### ISSUE TITLE
1.2.47 JSONException:java heap space

### ISSUE THREAD

**Issue by YuYuYan** [alibaba/fastjson#2205]
原来运行正常半年。突然出现JSONException:java heap space
       at.com.alibaba.fast.json.parse.DefaultJSONParser.parseObject(DefaultJSONParser.java:665)
，调用语句
JSONObject.parseObject(json,classType)

**Comment by wenshao** [comment]
能够提供更多堆栈信息么？

**Comment by YuYuYan** [comment]
![1](https://user-images.githubusercontent.com/18329773/50390017-845c1380-076c-11e9-84d3-809046f72991.jpg)
不好意思 只能先给你截个图

**Comment by YuYuYan** [comment]
修改一下具体的调用语句是这样的JSONObject.parseObject(json,classType)

**Comment by YuYuYan** [comment]
![11](https://user-images.githubusercontent.com/18329773/50391714-f4759400-0782-11e9-8d7b-0581dc717ab9.jpg)

**Comment by YuYuYan** [comment]
麻烦问一下是fastjson的问题吗
