### ISSUE TITLE
fastjson新版性能问题

### ISSUE THREAD

**Issue by myoss** [alibaba/fastjson#2208]
[某博主的性能测试文章](http://www.cnblogs.com/lightarc/p/jsontest.html?utm_source=tuicool&utm_medium=referral)

真的有这么差了么？gson在某些情况都能超过了么？jackson全面领先了？求官方验证下呀，来个新版性能比较测试

**Comment by gMan1990** [comment]
我之前测过Jackson>fastjson>gson，现在已经主用jackson了

**Comment by wenshao** [comment]
这个博主没有提供测试程序啊
