### ISSUE TITLE
请问 20181229162849000+0800 这样的时间解析错误 怎么处理

### ISSUE THREAD

**Issue by 502647092** [alibaba/fastjson#2216]
https://github.com/alibaba/fastjson/blob/72a2df2a64c2c09c4fdb96563362690449711b6b/src/main/java/com/alibaba/fastjson/util/TypeUtils.java#L342
这里应该是不能进判断的 这个时间格式是 阿里开放平台返回的时间格式 直接用 `yyyyMMddHHmmssSSSZ` 是可以解析成功的 但是FastJSON这里没有做处理

**Comment by 502647092** [comment]
补充一下 是 `jsonObject.getJSONArray("xxx").toJavaList()` 触发的 单独的解析好像是可以的

**Comment by wenshao** [comment]
通过JSONField配置format

**Comment by 502647092** [comment]
@wenshao 我配置过format了 但是你看上面的源码 没有进入format的格式化判断 因为字符串不包含 - 这个符号
