### ISSUE TITLE
序列化金额问题

### ISSUE THREAD

**Issue by xubihui** [alibaba/fastjson#2238]
程序  
请求1示例
@Test
    public  void  testMoney(){

        CapitalLimitMonenyDTO capitalLimitMonenyDTO =new CapitalLimitMonenyDTO();
        capitalLimitMonenyDTO.setMaxChargeMoney(new BigDecimal("200000"));
        capitalLimitMonenyDTO.setMinChargeMoney(new BigDecimal(0.01));
        capitalLimitMonenyDTO.setMaxWithdrawMoney(new BigDecimal(0.01));
        capitalLimitMonenyDTO.setMinWithdrawMoney(new BigDecimal("500000"));
        System.out.println(JSON.toJSONString(capitalLimitMonenyDTO));

    }

请求1结果
{"maxChargeMoney":200000,"maxWithdrawMoney":0.01000000000000000020816681711721685132943093776702880859375,"minChargeMoney":0.01000000000000000020816681711721685132943093776702880859375,"minWithdrawMoney":500000}

请求2示例
    @Test
    public  void  testMoney(){

        CapitalLimitMonenyDTO capitalLimitMonenyDTO =new CapitalLimitMonenyDTO();
        capitalLimitMonenyDTO.setMaxChargeMoney(new BigDecimal("200000"));
        capitalLimitMonenyDTO.setMinChargeMoney(new BigDecimal("0.01"));
        capitalLimitMonenyDTO.setMaxWithdrawMoney(new BigDecimal("0.01"));
        capitalLimitMonenyDTO.setMinWithdrawMoney(new BigDecimal("500000"));
        System.out.println(JSON.toJSONString(capitalLimitMonenyDTO));

    }

请求2结果
{"maxChargeMoney":200000,"maxWithdrawMoney":0.01,"minChargeMoney":0.01,"minWithdrawMoney":500000}

**Comment by wenshao** [comment]
这个是正常的，因为new BigDecimal(0.01) 这里输入0.01是double
