### ISSUE TITLE
反序列化死循环

### ISSUE THREAD

**Issue by ALittleDruid** [alibaba/fastjson#2254]
JSONLexerBase这个类里 scanFieldFloatArray2这个方法有问题

![default](https://user-images.githubusercontent.com/33475287/51392495-2c001200-1b70-11e9-835b-ba3c50b0ca83.png)

for (;;) {
            if (chLocal == '[') {
             //do sth
            }
}

如果chLocal不等于'['应该直接返回或者抛个异常出去,现在就在这无限循环了

**Comment by wenshao** [comment]
能提供重现问题的case么？

**Comment by ALittleDruid** [comment]
> 
> 
> 能提供重现问题的case么？

class TestClass {
    public float[][] a;
}

String jsonString = "{\"a\":[1.0,2.0]}";        //{"a":[1.0,2.0]}
TestClass testClass = JSON.parseObject(jsonString,TestClass.class);

**Comment by wenshao** [comment]
问题已修复，请用新版本 http://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.2.55/
