### ISSUE TITLE
javax.ws.rs.WebApplicationException: method (Ljava/lang/String;Ljava/lang/Throwable;)V not found

### ISSUE THREAD

**Issue by WolfgangFahl** [alibaba/fastjson#2256]
mvn dependency:tree shows
...
org.eclipse.persistence:eclipselink:jar:2.7.3:compile
[INFO] |  |  +- org.eclipse.persistence:commonj.sdo:jar:2.1.1:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  \- javax.json:javax.json-api:jar:1.1.2:compile
[INFO] |  +- org.eclipse.persistence:javax.persistence:jar:2.1.1:compile
[INFO] |  +- org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.7.3:compile
[INFO] |  |  \- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.7.3:compile
[INFO] |  |     \- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.7.3:compile
[INFO] |  +- com.sun.jersey:jersey-client:jar:1.19.4:compile
[INFO] |  |  \- com.sun.jersey:jersey-core:jar:1.19.4:compile
[INFO] |  |     \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  +- com.sun.jersey.contribs:jersey-moxy:jar:1.19.4:compile
[INFO] |  +- com.sun.jersey:jersey-grizzly2:jar:1.19.4:compile
[INFO] |  |  \- com.sun.jersey:jersey-server:jar:1.19.4:compile
[INFO] |  +- com.sun.jersey:jersey-grizzly2-servlet:jar:1.19.4:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:3.0.1:compile
[INFO] |  |  \- com.sun.jersey:jersey-servlet:jar:1.19.4:compile
[INFO] |  +- org.glassfish.grizzly:grizzly-http-server:jar:2.3.25:compile
[INFO] |  +- org.glassfish.grizzly:grizzly-http-servlet:jar:2.3.25:compile
[INFO] |  +- org.glassfish.grizzly:grizzly-http:jar:2.3.25:compile
[INFO] |  |  \- org.glassfish.grizzly:grizzly-framework:jar:2.3.25:compile
[INFO] |  +- org.glassfish:javax.json:jar:1.0.4:compile
[INFO] |  +- com.sun.jersey:jersey-json:jar:1.19.4:compile
...
 +- com.alibaba:fastjson:jar:1.2.54:compile

```
javax.ws.rs.WebApplicationException: method (Ljava/lang/String;Ljava/lang/Throwable;)V not found

     1: com.alibaba.fastjson.support.jaxrs.FastJsonProvider.readFrom(FastJsonProvider.java:373)
     2: com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
```

**Comment by WolfgangFahl** [comment]
not using the FastJsonProvider naturally worked around the problem.

**Comment by VictorZeng** [comment]
@WolfgangFahl   jsr311-api not compatible with FastJsonProvider, please use javax.ws.rs-api or upgrade jersey-client version to 2.x

**Comment by WolfgangFahl** [comment]
@VictorZeng there are already many reasons we never upgraded to 2.x - it is worse thean 1.x in our opinion and mostly unusable. We badly need a solution and I wonder why the upgrade on the FastJson must break things.

**Comment by VictorZeng** [comment]
@WolfgangFahl I am very sorry, that the main reason is that  jsr311-api is incompatible with  javax.ws.rs-api, and we have to make a choice.

**Comment by VictorZeng** [comment]
@WolfgangFahl I think I have a way to be compatible with jsr311-api, Please wait for the next version.

**Comment by WolfgangFahl** [comment]
Could there be two versions to be selected e.g. at runtime as a plugin or via dependency injection?
