### ISSUE TITLE
Error injecting constructor, java.lang.NoClassDefFoundError: java/sql/Clob

### ISSUE THREAD

**Issue by weijieliefu** [alibaba/fastjson#2257]
我使用1.2.55及使用的java11,报java.lang.NoClassDefFoundError: java/sql/Clob。如何解决，是java11把java/sql/Clob给删了吗。求指教。

**Comment by weijieliefu** [comment]
我换用了1.1.70.android，问题解决。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.56 
问题已解决，请用新版本

**Comment by sutra** [comment]
`java.sql.*`（`java.sql.Time.class`, `java.sql.Date.class`, `java.sql.Timestamp.class`）类型都有类似问题吧，See #2486
