### ISSUE TITLE
fastjson不支持类似xYname这样的属性名

### ISSUE THREAD

**Issue by abel533** [alibaba/fastjson#226]
这种属性名首先符合javabean规范。

但是属性名第二个字母大写的时候fastjson不支持。

因为这样的属性对应的getter和setter方法是类似这样的：

``` java
getxYname()

setxYname(...)
```

经过测试在下面代码中(`TypeUtils` 968行)：

``` java
if (methodName.startsWith("get")) {
    if (methodName.length() < 4) {
        continue;
    }

    if (methodName.equals("getClass")) {
        continue;
    }

    char c3 = methodName.charAt(3);

    String propertyName;
    if (Character.isUpperCase(c3)) {
        if (compatibleWithJavaBean) {
```

主要是下面这里的判断：

``` java
 if (Character.isUpperCase(c3)) {
```

这儿的判断有问题。。这不是一个小bug，希望能尽快解决。

**Comment by junfeng-feng** [comment]
private String flwNo;
    public void setflwNo(String flwNoString) {
        this.flwNo = flwNoString;
    }

    public String getflwNo() {
        return this.flwNo;
    }
也不支持，这种完全以fieldName拼写getter/setter的方法
