### ISSUE TITLE
把时间类型的转换不要设置限制1970年以上(Timestamp,Time,Date   java.sql包下的)

### ISSUE THREAD

**Issue by bee0045** [alibaba/fastjson#2260]
现在自动转换会报错,之前的版本只支持了 java.util 下面的 Date

**Comment by bee0045** [comment]
目前我自己的解决办法是把 fastjson的源码 copy一份到 自己项目下...然后在进行修改TypeUtils类

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本

**Comment by bee0045** [comment]
问题还是没修复
![image](https://user-images.githubusercontent.com/22829029/60961453-c6325d00-a33e-11e9-855f-26db0ad629f6.png)
