### ISSUE TITLE
setFeatures 过时了 请问改用哪个方法??

### ISSUE THREAD

**Issue by davichi11** [alibaba/fastjson#2274]
setFeatures 过时了 但是注释上并没有写明替代方法

**Comment by VictorZeng** [comment]
@davichi11  setFastJsonConfig(FastJsonConfig fastJsonConfig) see [FastJsonConfig](https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/support/config/FastJsonConfig.java)
