### ISSUE TITLE
spring boot 配置fastjson，内部类属性List<object> objectList 为null 时，序列化后包含该属性并且为null

### ISSUE THREAD

**Issue by freebird2016** [alibaba/fastjson#2283]

**Comment by freebird2016** [comment]
converters.add(0, converter); 使用spring boot 2.0.1以上，需要这样用才有用。

**Comment by qzmer1104** [comment]
wiki里有：
https://github.com/alibaba/fastjson/wiki/%E5%9C%A8-Spring-%E4%B8%AD%E9%9B%86%E6%88%90-Fastjson
