### ISSUE TITLE
json转换成对应的对象，如果是父类，希望根据规则转化成子类

### ISSUE THREAD

**Issue by z466459262** [alibaba/fastjson#2289]
我想根据btype 把json转换成对应的对象,有可能类的层次有点深，目前没有对应的api,目前我都是把json手动转的，很麻烦。
```
public class A {
    List<B>  bList;

    String bType;
}

interface B{

}
class B1 implements B{
    String a;
}
class B2 implements B{
    Integer bb;
}
```
已经内部咨询了温少，说会支持，谢谢哈

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本

**Comment by mominet** [comment]
并没有解决啊。这个需求要求转换成子类，而https://github.com/alibaba/fastjson/wiki/WriteAs_CN讲的是转换成父类。

**Comment by mominet** [comment]
另外，这个需求讲的是反序列化，而 https://github.com/alibaba/fastjson/wiki/WriteAs_CN  讲的则是序列化。完全不是一回事啊。

**Comment by mominet** [comment]
我发现Jackson支持这个，现在换成Jackson了。
https://my.oschina.net/u/3664884/blog/1932829
