### ISSUE TITLE
开启DisableCircularReferenceDetect导致JSONSerializer中conext为null

### ISSUE THREAD

**Issue by thrblock** [alibaba/fastjson#2317]
fastjson version:1.2.56
jdk version:1.8.0_144
我们目前使用了PropertyPreFilter以切入序列化过程进行字段的过滤；
通过PropertyPreFilter接口传入的name以及serializer参数中的context构造了当前待检测字段在json结构中的层次名称，举例说明：
{"id":123,"item":{"id":456,"itemdesc":"thisisitem"}}  中，我们使用"id"与"item.id"表示了所属不同层级的“id”；通过迭代context的parent，得到完整的层级结构；

而目前我们需要使用DisableCircularReferenceDetect特性，开启此特性将导致serializer参数中的context变为null，我不确定这是否是bug或是bydesign，或者是否存在其它低成本的方式获得当前待过滤字段的完整层次结构？

**Comment by wenshao** [comment]
这个是设计问题
