### ISSUE TITLE
TypeUtil下的kotlin_error什么时候会为true呢

### ISSUE THREAD

**Issue by imuto** [alibaba/fastjson#2330]
使用的版本是1.1.68.android版本。
发现解析model的时候，有时候会始终提示找不到默认构造方法。debug进去发现，TypeUtil中不知道何时kotlin_error变量被设置成了true。继续看代码，kotlin_error=true只有在发生exception的时候才会设置true。kotlin_error是私有的静态变量，只看到了设置为true，没看到设置为false的部分，如果一旦构造方法相关的参数解析失败，则除非杀死app，否则所有的解析都会直接返回null(TypeUtils.getKoltinConstructorParameters()方法中)。
什么情况下会出现param解析错误，从而设置kotlin_error呢？是基于什么考虑，直接使用了静态变量，从而导致，只要有param解析出现exception，之后就禁止使用了(因为=true会直接返回null)。这个有什么有效的解决办法么？
因为我们这是偶现这种情况，所以也不太知道出现的原因。

**Comment by imuto** [comment]
有大哥大姐遇到过的么？

**Comment by imuto** [comment]
@wenshao 有什么见解么

**Comment by wenshao** [comment]
如果kotlin lib不存在，就会kotlin_error为true
