### ISSUE TITLE
Date类型反序列化问题

### ISSUE THREAD

**Issue by rayliu8499** [alibaba/fastjson#2331]
在使用JSONObject.parseObject()的时候,当字段为" "的时候直接报错了...

**Comment by rayliu8499** [comment]
{"activeDate":" ","iccid":"898219C0000419","imsi":"46002100420","msisdn":"101210419","openDate":"2019-03-20 18:49:22"}

**Comment by jhoneybee** [comment]
@rayliu8499  根据你的描述我这边编写了关于此issues的测试用例代码如下


```java
       // https://github.com/alibaba/fastjson/issues/2331
	@Test
	public void test() {
		String json = "{\"activeDate\":\" \",\"iccid\":\"898219C0000419\",\"imsi\":\"46002100420\",\"msisdn\":\"101210419\",\"openDate\":\"2019-03-20 18:49:22\"}";
		
		JSONObject jsonObject = JSON.parseObject(json);
		assertEquals(jsonObject.getString("activeDate"), " ");
		System.out.println(JSON.toJSONString(jsonObject));
	}
```

## 运行环境
| 名称 |版本
|---     |---- 
|JDK   |java version "1.8.0_121"
|fastjson | 1.2.51
|junit | 4.+

## 结果

并未出现所描述的问题

**Comment by jhoneybee** [comment]
@rayliu8499  如果这对您有帮助,是否可以关闭此lssue
