### ISSUE TITLE
请问有文档吗

### ISSUE THREAD

**Issue by taoeer** [alibaba/fastjson#2332]
新手，看了半天还是不知道怎么用，api文档也没有找到！有没有quick start或者api文档

**Comment by rayliu8499** [comment]
https://www.w3cschool.cn/fastjson/fastjson-api.html

**Comment by jhoneybee** [comment]
@taoeer  相关文档链接

1. https://github.com/alibaba/fastjson/wiki 
2. https://github.com/alibaba/fastjson/blob/master/README.md

**Comment by jhoneybee** [comment]
@taoeer  如果这对您有帮助,是否可以关闭此issue
