### ISSUE TITLE
fastJson生成的@type jackson 可以解析么

### ISSUE THREAD

**Issue by hdz1807** [alibaba/fastjson#2336]
String bs = (String)JSONObject.toJSONString(tje , SerializerFeature.WriteClassName);
生成的json 串 通过@type 指定了关联对象 ，这个字符串用jackson 能解析么？需要做哪些处理

**Comment by jhoneybee** [comment]
JSONObject.toJSONString 方法将其转换成标准的JSON对象,```jackson``` 是否能解析具体参照jackson官网中的解析JSON例子理论上是可以性的. 

> 此issue建议在jackson 中询问, fastjson无法保证jackson是否可以解析,fastjson只保证标准JSON的解析与序列化

**Comment by wenshao** [comment]
不能
