### ISSUE TITLE
"{\"@type\":\"1234\"}"  解析报错异常

### ISSUE THREAD

**Issue by luckydzp** [alibaba/fastjson#2341]
String ss = "{\"@type\":\"1234\"}";
JSON.parseObject(ss)

Method threw 'java.lang.NullPointerException' exception.
Attempt to invoke virtual method 'boolean java.lang.Class.isAnnotationPresent(java.lang.Class)' on a null object reference

请问怎么关闭自省,将@type key解析为"@type"普通字符串

sdk版本: 1.1.70  android

**Comment by luckydzp** [comment]
请问怎么关闭自省,将@type key解析为"@type"字符串

**Comment by gitouyoung** [comment]
same problem

**Comment by sandogeek** [comment]
```java
JSON.parseObject(ss, Feature.IgnoreAutoType)
```

**Comment by luckydzp** [comment]
@sandogeek android库没有Feature.IgnoreAutoType,只有Feature.SupportAutoType,而且默认是开启的
