### ISSUE TITLE
BrowserCompatible在long类型时无效

### ISSUE THREAD

**Issue by jqncc** [alibaba/fastjson#2344]
当一个javabean中有long类型时使用BrowserCompatible并没有以字符串输出导致js精度丢失,而如果是包装类型Long时是正确的
版本1.2.41 ,1.2.49,1.2.55 都试过

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本
