### ISSUE TITLE
JSONField注解指定serialzeFeatures=SerializerFeature.WriteBigDecimalAsPlain不生效

### ISSUE THREAD

**Issue by yuruixin** [alibaba/fastjson#2355]
fastjson版本 1.2.55

```
@JSONField(serialzeFeatures = SerializerFeature.WriteBigDecimalAsPlain)
 private BigDecimal num;
```
如上，在实体类的属性上加了JSONField注解，并指定serialzeFeatures=SerializerFeature.WriteBigDecimalAsPlain不生效
试图解决的问题：
当num的值为0.00000001时，默认toString后的值为科学计数法1e-8，业务需要展示为0.00000001

采用SON.toJSONString(bean, SerializerFeature.WriteBigDecimalAsPlain)可以达到出预期结果
采用@JSONField(serialzeFeatures = SerializerFeature.WriteBigDecimalAsPlain)及JSON.toJSONString(bean)，无法达到预期效果

**Comment by AmuseBoy** [comment]
谢谢，这个蛋疼的fastjson
