### ISSUE TITLE
用JSONObject.parseArray反序列化非静态内部类时，异常信息有误

### ISSUE THREAD

**Issue by Horanol** [alibaba/fastjson#2358]
以下代码可复现

> public class TestJson {
    @NoArgsConstructor
    @Data
    public class TestJson2 {
        private String test1;
        private String test2;
    }
        public static void main(String args[]) {
        String str = "[{\n" +
                "  \"test1\":\"1\",\n" +
                "  \"test2\":\"2\"\n" +
                "},\n" +
                " {\n" +
                "   \"test1\":\"1\",\n" +
                "   \"test2\":\"2\"\n" +
                " }]";
        List<TestJson2> testJson2 = JSONObject.parseArray(str, TestJson2.class);
    }
}

此时报错信息为
`com.alibaba.fastjson.JSONException: create instance error, class com.meituan.evaluation.config.TestJson$TestJson2`
实际上应该报 can't create non-static inner class instance.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本

**Comment by xuchenchen** [comment]
此版本VIVOX9S Plus 7.1.2闪退
