### ISSUE TITLE
map中有重复引用时，反序列化后的对象，重复引用的部分是空的，why？

### ISSUE THREAD

**Issue by abcbuzhiming** [alibaba/fastjson#236]
Map<Integer, PlayerInfo>，得到的字符串是
{1:{"donateLevel":0,"goodsInfoInRoomMap":{102:2160,103:0},"goodsInfoMap":null,"headPhoto":null,"headPhotoId":0,"id":-569,"nickName":"啤酒兑咖啡的苦涩","sex":1,"vipLevel":0},2:{"donateLevel":0,"goodsInfoInRoomMap":{102:11000,103:0},"goodsInfoMap":null,"headPhoto":null,"headPhotoId":1,"id":18315,"nickName":"游客6083","sex":1,"vipLevel":0},3:{"donateLevel":0,"goodsInfoInRoomMap":{102:1940,103:0},"goodsInfoMap":null,"headPhoto":null,"headPhotoId":0,"id":-887,"nickName":"傻笑，那段情","sex":0,"vipLevel":0},5:{"$ref":"$[2]"}}

在客户端通过fastjson反序列化后，5:{"$ref":"$[2]"}这个代表的对象PlayerInfo里的所有的值变成了null值

补充:版本1.1.44

在补充:经过测试表明，该现象仅存在里map这种结构，如果把Playinfo全部放入list结构，得到的序列化字符是一样的，也是{"$ref":"$[2]"}，但是反序列化时能准确得到值

**Comment by wenshao** [comment]
很抱歉让你等这么久，已修复在1.2.9 & 1.1.49.android
