### ISSUE TITLE
当父类的父类定义了范型， 子类反序列化失败

### ISSUE THREAD

**Issue by wkkata** [alibaba/fastjson#2361]
public class SuperBaseReply<T> {
    private List<T> items;

    public List<T> getItems() {
        return items;
    }

    public void setItems(List<T> items) {
        this.items = items;
    }
}

public class BaseReply<T> extends SuperBaseReply<T> {

}

public class TestReply extends BaseReply<Msg> {

}

当反序列化TestReply的时候， getItems会报失败，JSONOBJECT无法转的问题

**Comment by timandy** [comment]
泛型参数没有继承到子类，导致编译擦除引起的。建议将泛型参数继承到子类反序列化时使用T ypeR eference

**Comment by TomYule** [comment]
springboot  可以如下配置  解决
```
@Configuration
@EnableWebMvc
public class Application extends WebMvcConfigurerAdapter {

    @Override
    public void configureMessageConverters(List<HttpMessageConverter < ? >> converters) {
        GsonHttpMessageConverter gsonHttpMessageConverter = new GsonHttpMessageConverter();
        converters.add(gsonHttpMessageConverter);
    }
}
```
