### ISSUE TITLE
希望统一Date和LocaleDate、LocaleTime、LocaleDateTime序列化格式

### ISSUE THREAD

**Issue by w-a-n-g-s-h-u-n** [alibaba/fastjson#2379]
希望统一Date和LocaleDate、LocaleTime、LocaleDateTime序列化格式为时间戳
比如增加一个SerializerFeature，开启后Date、LocaleDate、LocaleTime、LocaleDateTime则都以时间戳返回

**Comment by AthlonCC** [comment]
可以自己试着实现一个哈哈

**Comment by w-a-n-g-s-h-u-n** [comment]
> 可以自己试着实现一个哈哈
