### ISSUE TITLE
国产项目吃枣药丸

### ISSUE THREAD

**Issue by weluna** [alibaba/fastjson#2381]

**Comment by wenshao** [comment]
遇到什么问题了？

**Comment by greatflag** [comment]
ResponseEntity文件流的时候会报错，按照#1701的方法，也没用。

**Comment by wenshao** [comment]
能提供报错的堆栈信息么？

**Comment by greatflag** [comment]
温少 你好，根据#1701的方法，删除一项support Media Type，会报'Content-Type' cannot contain wildcard type '*'

**Comment by VictorZeng** [comment]
@greatflag see https://github.com/alibaba/fastjson/pull/2302/files#diff-8acefded13bb283eecf26bb4fe617cb0
