### ISSUE TITLE
JSON to Object：.Net Core 性能竟比 Java 快五倍？

### ISSUE THREAD

**Issue by Dogwei** [alibaba/fastjson#2396]
![QQ截图20190425181804](https://user-images.githubusercontent.com/14845492/56729163-2e819180-6787-11e9-8295-6b3690c364e6.png)

可能是某些不公平因素导致，但我没发现是啥原因。

**Comment by wenshao** [comment]
这个方法调用多几次试试看

**Comment by Dogwei** [comment]
![QQ截图20190428111347](https://user-images.githubusercontent.com/14845492/56858056-ed67c800-69a6-11e9-93a8-e08889b9e9e8.png)

确实多次调用后 Java 端提升了十倍的侠侣。
但我发现 .Net Core 端实体类中 Guid 值类型有瓶颈，所以开启了忽略默认值使不序列化 Guid，性能也提升很大。

其余代码没有改变， Java 端的 Guid 我定义的是 String 类型。
