### ISSUE TITLE
Srping4.0 mvc with FastJsonHttpMessageConverter

### ISSUE THREAD

**Issue by hexi** [alibaba/fastjson#241]
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.hexi.model.Person

为什么传给Controller的参数是JSONObject 而不是我指定的类型，配置如下：
<bean id="fastJsonHttpMessageConverter"  
        class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">  
        <property name="supportedMediaTypes">  
            <list>  
                <value>application/json;charset=UTF-8</value>  
            </list>  
        </property>  
    </bean>
    
	<bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
		<property name="messageConverters">
			<list>
				<ref bean="fastJsonHttpMessageConverter" />
			</list>
		</property>
	</bean>

**Comment by EvenGui** [comment]
<mvc:annotation-driven>
		  <mvc:message-converters register-defaults="true">
            <bean id="fastJsonHttpMessageConverter" 
class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">
                <property name="supportedMediaTypes">
                    <list>
                        <value>application/json</value>
                    </list>
                </property>
            </bean>       
        </mvc:message-converters>
    </mvc:annotation-driven>

Controller:
	@RequestMapping(value = "/dataRights",method = RequestMethod.POST)
	@ResponseBody
	public MessageTO saveDataRights(HttpServletRequest request,@RequestBody List<Base_CompInfo> dataRights)
	{
		MessageTO result = new MessageTO();
		List<Base_CompInfo> base_CompInfos = JSON.parseArray(dataRights.toString(), Base_CompInfo.class);
		。。。。
	return result;
	}

**Comment by EvenGui** [comment]
Controller:
	@RequestMapping(value = "/dataRights",method = RequestMethod.POST)
	@ResponseBody
	public MessageTO saveDataRights(HttpServletRequest request,@RequestBody List<Base_CompInfo> dataRights)
	{
		MessageTO result = new MessageTO();
		List<Base_CompInfo> base_CompInfos = JSON.parseArray(dataRights.toString(), Base_CompInfo.class);
		。。。。
	return result;
	}


	 <mvc:annotation-driven>
		  <mvc:message-converters register-defaults="true">
            <bean id="fastJsonHttpMessageConverter"  class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">
                <property name="supportedMediaTypes">
                    <list>
                        <value>application/json</value>
                    </list>
                </property>
            </bean>       
        </mvc:message-converters>
    </mvc:annotation-driven>

**Comment by EvenGui** [comment]
![image](https://cloud.githubusercontent.com/assets/8150427/5851233/e5bfba60-a23e-11e4-9752-d1472fa0a50b.png)


Controller里面，去打印dataRights这个list，其实打印的是一串字符串。我就直接toString了。再转换为List。是OK的，多写一句代码吧、

![image](https://cloud.githubusercontent.com/assets/8150427/5851245/1f333ba0-a23f-11e4-806c-41108cc3ae7a.png)

**Comment by wenshao** [comment]
那我先关闭issue啦，有问题欢迎再提
