### ISSUE TITLE
有几种非法json数据，能否考虑提供支持

### ISSUE THREAD

**Issue by yhonet** [alibaba/fastjson#242]
1、json数据中给 int、long类型的对象赋值为"NULL"、“null”等。
2、json数据中用来表示 null 的对象其书写为 NULL。

来只栗子：
```java
public class GoodsInfo
{
    public int our_price = -1;
    public int market_price = -1;
    public long begin_time = -1;
    public long end_time = -1;
}

final String text = "{our_price:\"NULL\",market_price:\"null\",begin_time:NULL,end_time:null}";
GoodsInfo info = JSON.parseObject(text, GoodsInfo.class);
```
上面情况都不是合法的json格式，但是项目中的确会遇到，也无法要求数据提供方处理这些数据，只能我们自己处理。
在 GSON 中可以通过设置参数自己进行int、long的解析以解决第一个问题。GSON在遇到第二个问题时没有出现错误。

在FastJson源代码中我找到了修改代码来解决上述2个问题的地方：
问题1：TypeUtils.castToInt()/castToLong()
问题2：JSONLexerBase.nextToken()

不过修改代码这种方式对于项目后期维护会带来很大问题，以前吃过亏，所以不希望再用这种方式。
希望评估一下是否可以在FastJson中提供合适的方式来支持这些异常情况的处理。

**Comment by ikkyu0319** [comment]
serializer 时 有个ValueFilter 
deserializer 是 能否有个类似的功能,

类似与 Gson 的 TypeAdapter registerTypeAdapter  ,可以自定义一些返回值
