### ISSUE TITLE
alternateNames不生效

### ISSUE THREAD

**Issue by jpsz01** [alibaba/fastjson#2424]
fastjson版本：com.alibaba:fastjson:1.2.57
使用：
1. @JSONField(name = "payment_way", alternateNames = ["payment_way_str"])
var payMethod: String?=""
2. inline fun <reified T> fromJson(data: Any): T = JSON.parseObject(data.toJson(), T::class.java)
3. fromJson<Order>(data)
结果：当后端返回字段为：payment_way_str时，字段解析数据为空，返回字段：payment_way时正常解析

**Comment by gaoxuefeng** [comment]
改为  @field:JSONField 可暂时解决

**Comment by bradley-wang** [comment]
fastjson版本：com.alibaba:fastjson:1.2.71
使用：
@ApiModelProperty("来源系统")
@NotEmpty
@JSONField(alternateNames = {"sourceSystemCode","SOURCESYSTEMCODE"})
private String sourceSystemCode;

传sourceSystemCode没问题，后面那个就有问题，是有格式限制吗？
