### ISSUE TITLE
JSON.toJSONString 同一个对象有多次引用的问题

### ISSUE THREAD

**Issue by xiyoufang** [alibaba/fastjson#244]
JSON.toJSONString 当需要转换成JSON字符串的JAVA对象中有一个对象存在多次引用，JSON.toJSONString 只能将第一个引用转成JSON字符串，后面的引用将成变成"$ref": "$.xxxxx"
{
    "aaData": [{
        "content": "<p>测试下代码<br/></p>",
        "createTime": "2014-11-13 23:09:26",
        "id": "4028818449a9a5d30149a9b3b07a0025",
        "status": 1,
        "user": {
            "createTime": "2014-11-04 19:51:38",
            "email": "951868171@qq.com",
            "groups": [],
            "id": "40288188497a7c6901497aa579970028",
        }
    }, {
        "content": "<p>我要评论下呀<br/></p>",
        "createTime": "2014-11-13 23:06:55",
        "id": "4028818449a9a5d30149a9b164c50023",
        "status": 1,
        "user": {
            "$ref": "$.aaData[0].user"
        }
    }],
    "iTotalDisplayRecords": 11,
    "iTotalRecords": 11,
    "sEcho": 1
}

**Comment by michelle-q** [comment]
但是是会出现新的错误，java.lang.StackOverflowError: null
