### ISSUE TITLE
属性名成第一个字母大小问题

### ISSUE THREAD

**Issue by wangqingyi2013** [alibaba/fastjson#246]
如果想要将一个对象转换成jsonstring   ，对象的属性名第一个字母大写，如果用  @JSONField(name="ID") 不好用，必须将 注解 放在get方法上面才可以。
fastjson 版本是1.2.1。

class User{

private String UserName;

public setUserName(String uname){
xxx
}
@JSONField(name="UserName") //转换成jsonstring 后 为 UserName=“”
public String getUserName(){
getxxxx
}
}

**Comment by mh494078416** [comment]
必须放在get方法上才好用，这个什么时候改进一下？

**Comment by wenshao** [comment]
```java
import com.alibaba.fastjson.serializer.PascalNameFilter;

JSON.toJSONString(obj, new PascalNameFilter());
```
