### ISSUE TITLE
如果字段是is开头的,JSONField无效

### ISSUE THREAD

**Issue by yizems** [alibaba/fastjson#2478]
比如
class A{
    var isFull;
}

加不加 @JSONField(name="isFull") 
在反序列化的时候和序列化的时候都有问题

虽然可以重写 set/get方法,但是这种应该默认支持的吧

**Comment by Omega-Ariston** [comment]
本地试了一下是可以的，能否给出你的详细JavaBean定义？或者完整的testcase？

**Comment by ZhangJian96** [comment]
fastjson即使是is开头的字段也需要使用set、get加完整字段，所以你这里就必须使用setIsFull()和getIsFull()，而不能用常规的setFull()和isFull()，我之前也遇到过这个问题，使用lombok后is开头的字段就解析不出来了。这个问题我提过一个issue，但是没得到官方回复
issue地址：
https://github.com/alibaba/fastjson/issues/1810

**Comment by ZhangJian96** [comment]
这里说的比较详细了：
https://github.com/alibaba/fastjson/issues/278
