### ISSUE TITLE
fastjson  源码导入时遇到 com.aliyun.odps 包 找不到。在maven 的代码库里面也没有这个包

### ISSUE THREAD

**Issue by veison** [alibaba/fastjson#249]
org.clojure 这个包也出错。在pom里面调用的是1.5.1版本的包，但是maven也没有导进去。不过我换成了1.6.0版本  maven就可以导进去了

**Comment by lhcpig** [comment]
我找到com.aliyun.odps 包了
http://help.aliyun.com/view/11108327_13506337.html

**Comment by veison** [comment]
@lhcpig   謝謝。找了好就呀，這東東

**Comment by winkeyzhao** [comment]
me too，could't find odps and plus
