### ISSUE TITLE
能不能提供一个java.nio.ByteBuffer的序列化和反序列化方式

### ISSUE THREAD

**Issue by sinlang** [alibaba/fastjson#251]
实现java.nio.ByteBuffer的序列化方式， 就像byte[]数组一样， 自己实现序列化好像挺简单， 但是反序列化挺麻烦的

**Comment by wenshao** [comment]
我修改了你做的实现，注册到ParserConfig.getGlobalInstance() 和 SerializeConfig.getGlobalInstance()上就可以了
