### ISSUE TITLE
JSONObject 1.2.57开始被重写的toJavaObject()方法

### ISSUE THREAD

**Issue by yl-yue** [alibaba/fastjson#2516]
**问题描述：**
经过详细的排查发现1.2.57开始，JSONObject类重写了toJavaObject()方法，被重写的方法不再支持转自身类型与JSONObject类型的转换。

**期望：**
去掉方法重写，或增强重写方法。如果为类型本身将不需要转换，如果是JSONObject类型，执行JSONObject转换操作。

**Comment by yl-yue** [comment]
![image](https://user-images.githubusercontent.com/39790401/60232833-5cdb3480-98d0-11e9-80c4-008ba7b1be35.png)
这里是有一套标准，或者新的思路么。

**Comment by wenshao** [comment]
能提供重现问题case么？

**Comment by yl-yue** [comment]
```java
JSONObject jsonObject = new JSONObject();
jsonObject.toJavaObject(JSONObject.class);
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.59
已修复，请用新版本
