### ISSUE TITLE
JSON.toJSONString 搞不懂

### ISSUE THREAD

**Issue by sunlva** [alibaba/fastjson#253]
JSON.class

 public static final String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features) {
        SerializeWriter out = new SerializeWriter();

        try {
            JSONSerializer serializer = new JSONSerializer(out);
            for (com.alibaba.fastjson.serializer.SerializerFeature feature : features) {
                serializer.config(feature, true);
            }

            serializer.config(SerializerFeature.WriteDateUseDateFormat, true); //为什么要加上这个呢？

public static final String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)
public static final String toJSONString(Object object, SerializerFeature... features) 
这二个方法可能会造成 Date对象输出值不一样

**Comment by wenshao** [comment]
已修复
