### ISSUE TITLE
com.alibaba.fastjson.JSONException: Rounding necessary

### ISSUE THREAD

**Issue by BryceLee** [alibaba/fastjson#2543]
同样的数据，
'com.alibaba:fastjson:1.2.58'正常解析；
'com.alibaba:fastjson:1.1.71.android'报错

**Comment by BryceLee** [comment]
'com.alibaba:fastjson:1.1.71.android'必现代码，
```
String s="{\"payment_num\":3.2}";
TestJson goodsDetailIntroEntity = JSON.parseObject(s, TestJson.class);
实体：
public class TestJson {
    private int payment_num;


    public int getPayment_num() {
        return payment_num;
    }

    public void setPayment_num(int payment_num) {
        this.payment_num = payment_num;
    }
}
```

**Comment by zilongGeneral** [comment]
不能用int类型接收 3.2啊。不报错才不正常了呢

**Comment by zilongGeneral** [comment]
> 'com.alibaba:fastjson:1.1.71.android'必现代码，
> 
> ```
> String s="{\"payment_num\":3.2}";
> TestJson goodsDetailIntroEntity = JSON.parseObject(s, TestJson.class);
> 实体：
> public class TestJson {
>     private int payment_num;
> 
> 
>     public int getPayment_num() {
>         return payment_num;
>     }
> 
>     public void setPayment_num(int payment_num) {
>         this.payment_num = payment_num;
>     }
> }
> ```

不能用int类型接收 3.2啊。不报错才不正常了呢
