### ISSUE TITLE
字段排序--Feature.OrderedField，只对第一层的key进行排序

### ISSUE THREAD

**Issue by ilaipi** [alibaba/fastjson#255]
排序会很影响性能吗？
当我尝试对第一层排序后的key遍历时，每个key下的对象的key是无序的了，而我需要第二层的key依然有序..希望提供支持啊

**Comment by RchBoy** [comment]
JSON.parseObject(JSON.toJSONString(map, SerializerFeature.MapSortField),LinkedHashMap.class, Feature.OrderedField);
