### ISSUE TITLE
带自定义类型map无法正常反序列化

### ISSUE THREAD

**Issue by imacback** [alibaba/fastjson#256]
List<AisleDeployInfo> list3 = new ArrayList<AisleDeployInfo>();
		AisleDeployInfo aisleDeployInfo = new AisleDeployInfo();
		aisleDeployInfo.setId(1L);
		aisleDeployInfo.setProvinceArea("3,4,5");
		list3.add(aisleDeployInfo);
		
		AisleDeployInfo aisleDeployInfo1 = new AisleDeployInfo();
		aisleDeployInfo1.setId(2L);
		aisleDeployInfo1.setProvinceArea("3,4,5");
		list3.add(aisleDeployInfo1);
		
		List<AisleDeployInfo> list4 = new ArrayList<AisleDeployInfo>();
		list4.add(aisleDeployInfo);
		
		Map<String, List<AisleDeployInfo>> map3 = new HashMap<String, List<AisleDeployInfo>>();
		map3.put("1", list3);
		map3.put("2", list4);
		
		String str = JSON.toJSONString(map3);
		Map<String, List<AisleDeployInfo>> map1 = JSON.parseObject(str, new TypeReference<Map<String, List<AisleDeployInfo>>>(){});
		List<AisleDeployInfo> aList = map1.get("1");
		
		if (aList != null && aList.size() > 0) {
			for (int i = 0; i < aList.size(); i++) {
				System.out.println(aList.get(i).getId());
			}
		}
无法正常解析，版本号：１.２.３

**Comment by wenshao** [comment]
最新版测试无问题，先关闭啦
