### ISSUE TITLE
将多个JSON字段映射到单个Java字段

### ISSUE THREAD

**Issue by protectedMan** [alibaba/fastjson#2575]
将多个JSON字段映射到单个Java字段
@JsonFiled只能实现一对一的映射，我需要的是多对一的映射。
如何实现这个需求 ，类似jackson的 @JsonAlias注解的作用
具体需求是这样的
https://blog.csdn.net/weilin705/article/details/88692132

**Comment by baizhanshuang** [comment]
在逆序列化过程中@JSONFiled中有个alternateNames属性，能够达到你要的效果

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/62747892-fded0b80-ba88-11e9-97b3-5332aba181c8.png)
赞，解决了
