### ISSUE TITLE
合法jsonString调整属性先后顺序解析出错

### ISSUE THREAD

**Issue by xuguoxiang** [alibaba/fastjson#2579]
以下json正常解析：
{"@type":"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1","date":1563867975335,"id":"0f075036-9e52-4821-800a-9c51761a727b","location":{"@type":"java.awt.Point","x":0,"y":0},"point":{"@type":"java.awt.Point","x":0,"y":0},"pointArr":[{"@type":"java.awt.Point","x":0,"y":0},{"@type":"java.awt.Point","x":0,"y":0}],"strArr":["te-st","tes-t2"],"x":0.0D,"y":0.0D}
调整"@type"与“date”属性位置j：
{"date":1563867975335,"@type":"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1","id":"0f075036-9e52-4821-800a-9c51761a727b","location":{"@type":"java.awt.Point","x":0,"y":0},"point":{"@type":"java.awt.Point","x":0,"y":0},"pointArr":[{"@type":"java.awt.Point","x":0,"y":0},{"@type":"java.awt.Point","x":0,"y":0}],"strArr":["te-st","tes-t2"],"x":0.0D,"y":0.0D}
调用方法JSON.parse(jsonString, Feature.SupportAutoType);解析报错，异常信息：com.alibaba.fastjson.JSONException: syntax error, expect ,, actual string

`public class MyPoint1 extends Point{
    private UUID id ;

    private Point point = new Point();

    private String[] strArr = {"te-st", "tes-t2"};

    private Date date = new Date();

    private Point[] pointArr = {new Point(), new Point()};

    public Point getPoint() {
        return point;
    }

    public void setPoint(Point point) {
        this.point = point;
    }

    public String[] getStrArr() {
        return strArr;
    }

    public void setStrArr(String[] strArr) {
        this.strArr = strArr;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Point[] getPointArr() {
        return pointArr;
    }

    public void setPointArr(Point[] pointArr) {
        this.pointArr = pointArr;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}
`

**Comment by Omega-Ariston** [comment]
从fastjson version 1.2.41-1.2.59，使用JDK8，均未复现，请提供更详细的信息，谢谢！
```java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.parser.Feature;

public class Issue2579 {

	public static void main(String[] args) {
		String str1 = "{\"date\":1563867975335,\"@type\":\"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1\",\"id\":\"0f075036-9e52-4821-800a-9c51761a727b\",\"location\":{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},\"point\":{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},\"pointArr\":[{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0}],\"strArr\":[\"te-st\",\"tes-t2\"],\"x\":0.0D,\"y\":0.0D}";
		String str2 = "{\"@type\":\"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1\",\"date\":1563867975335,\"id\":\"0f075036-9e52-4821-800a-9c51761a727b\",\"location\":{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},\"point\":{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},\"pointArr\":[{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0},{\"@type\":\"java.awt.Point\",\"x\":0,\"y\":0}],\"strArr\":[\"te-st\",\"tes-t2\"],\"x\":0.0D,\"y\":0.0D}";

		Object obj1 = JSON.parse(str1, Feature.SupportAutoType);
		Object obj2 = JSON.parse(str2, Feature.SupportAutoType);

		System.out.println(obj1);
		System.out.println(obj2);

	}

}
```

测试结果[相同]：
```
{"date":1563867975335,"strArr":["te-st","tes-t2"],"@type":"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1","x":0.0,"pointArr":[{"x":0,"y":0},{"x":0,"y":0}],"y":0.0,"location":{"x":0,"y":0},"id":"0f075036-9e52-4821-800a-9c51761a727b","point":{"x":0,"y":0}}
{"date":1563867975335,"strArr":["te-st","tes-t2"],"@type":"com.ruijie.rcos.base.sysmanage.module.impl.MyPoint1","x":0.0,"pointArr":[{"x":0,"y":0},{"x":0,"y":0}],"y":0.0,"location":{"x":0,"y":0},"id":"0f075036-9e52-4821-800a-9c51761a727b","point":{"x":0,"y":0}}

```
