### ISSUE TITLE
fastjson1.2.58:java.sql.Date序列化问题

### ISSUE THREAD

**Issue by songjg0423** [alibaba/fastjson#2580]

**Comment by songjg0423** [comment]
如果服务器的时区是GMT+00:00,此时时区的offset为0，java.sql.Date在序列化的时候会报除以0异常
if (clazz == java.sql.Date.class) {
            long millis = ((java.sql.Date) object).getTime();
            TimeZone timeZone = serializer.timeZone;
            int offset = timeZone.getOffset(millis);
            if (millis % offset == 0) {//此处会报除以0异常
                out.writeString(object.toString());
                return;
            }
        }

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.59
已修复，请用新版本
