### ISSUE TITLE
下划线转驼峰失效

### ISSUE THREAD

**Issue by Radicalpro** [alibaba/fastjson#2581]
String body = "{\n" +
                "    \"supplier_name\": \"AL\",\n" +
                "    \"inspection_type\": 2,\n" +
                "    \"supplier_id\": \"111\"\n" +
                "}";
        SerializeConfig config = new SerializeConfig();
        config.propertyNamingStrategy = PropertyNamingStrategy.CamelCase;
        String json = JSON.toJSONString(JSONObject.parseObject(body), config);
        System.out.println(json);

{"supplier_name":"AL","inspection_type":2,"supplier_id":"111"}

**Comment by Omega-Ariston** [comment]
```Java
String json = JSON.toJSONString(JSONObject.parseObject(body), config);
```
第一个参数是JSONObject对象。该对象中使用一个Map成员属性来存储所有键值对（而不像JavaBean对象中每个成员属性对应一个键值对），因此在序列化时无法从IdentityHashMap中找到对应的Serializer，转而使用了默认的MapSerializer来将键值对原封不动地输出。
可以改为传入事先定义好的JavaBean对象（注意getter方法名），如：
```Java
public class TestBean {
        String supplier_name;
        int inspection_type;
        String supplier_id;

        public TestBean(String supplier_name, int inspection_type, String supplier_id) {
            this.supplier_name = supplier_name;
            this.inspection_type = inspection_type;
            this.supplier_id = supplier_id;
        }

        public String getSupplierName() {
            return supplier_name;
        }

        public int getInspectionType() {
            return inspection_type;
        }

        public String getSupplierId() {
            return supplier_id;
        }
}
```
原来代码改为：
```Java
String json = JSON.toJSONString(JSON.parseObject(body, TestBean.class), config);
```

不知道有没有简便些的方法

**Comment by Radicalpro** [comment]
> ```java
> String json = JSON.toJSONString(JSONObject.parseObject(body), config);
> ```
> 
> 第一个参数是JSONObject对象。该对象中使用一个Map成员属性来存储所有键值对（而不像JavaBean对象中每个成员属性对应一个键值对），因此在序列化时无法从IdentityHashMap中找到对应的Serializer，转而使用了默认的MapSerializer来将键值对原封不动地输出。
> 可以改为传入事先定义好的JavaBean对象（注意getter方法名），如：
> 
> ```java
> public class TestBean {
>         String supplier_name;
>         int inspection_type;
>         String supplier_id;
> 
>         public TestBean(String supplier_name, int inspection_type, String supplier_id) {
>             this.supplier_name = supplier_name;
>             this.inspection_type = inspection_type;
>             this.supplier_id = supplier_id;
>         }
> 
>         public String getSupplierName() {
>             return supplier_name;
>         }
> 
>         public int getInspectionType() {
>             return inspection_type;
>         }
> 
>         public String getSupplierId() {
>             return supplier_id;
>         }
> }
> ```
> 
> 原来代码改为：
> 
> ```java
> String json = JSON.toJSONString(JSON.parseObject(body, TestBean.class), config);
> ```
> 
> 不知道有没有简便些的方法

这样子的方法，还是在java类中命名了下划线的变量
使用驼峰转下划线的config是可以正常使用的
后面我尝试了，如果下划线不转换，直接用相对应驼峰的变量去接受转换 也是可以的
```java 
public class TestBean {
      String supplierName;
      int inspectionType;
      String supplierId;
}
JSON.parseObject(body, TestBean.class);
```

**Comment by Omega-Ariston** [comment]
> > 这样的方法确实可行，主要是不想在java类中命名了下划线的变量
> > 后面我尝试了，直接用相对应驼峰的变量去接受转换 也是可以的
> 
> ```java
> public class TestBean {
>       String supplierName;
>       int inspectionType;
>       String supplierId;
> }
> JSON.parseObject(body, TestBean.class);
> ```

嗯嗯，能按照Java的驼峰命名规范去定义Bean属性是最好的 :)
