### ISSUE TITLE
对象属性中的enum类型序列化失败.

### ISSUE THREAD

**Issue by zycgit** [alibaba/fastjson#261]
示例:
enum MyEnum {
 x(1, "hello");
MyEnum(int i, String s){
  this.i = i;
 this.s = s;
}
private int i;
private String s;
}
class A{
    private MyEnum aa;
}
SerializeConfig config=new SerializeConfig();
config.put(MyEnum.class, new MyEnumAdapter());
A aaaa = new A();
aaaa.setAa(MyEnum.x);
System.out.println(JSON.toJSONString(aaaa , config));	         //未达到期望效果. 
System.out.println(JSON.toJSONString(MyEnum.x, config));	 //   达到期望效果

**Comment by yakolee** [comment]
MyEnumAdapter 是什么？给出完整的testcase

**Comment by wenshao** [comment]
无法重现，先关闭啦，有问题再反馈。
