### ISSUE TITLE
升级1.2.58后出现了报错...

### ISSUE THREAD

**Issue by 1369521908** [alibaba/fastjson#2626]
升级1.2.58后出现了报错... 之前版本是 1.2.47 
但是连续请求5次(每一次启动工程连续请求5次,或者怼5个接口)就没问题了

![image](https://user-images.githubusercontent.com/32727597/62820150-b652a680-bb92-11e9-824f-61e39dedf23b.png)

**Comment by Omega-Ariston** [comment]
确认下是否未执行mvn clean操作导致的？

**Comment by 1369521908** [comment]
用的是gradle ,clean了好几次了...
