### ISSUE TITLE
fastjson 处理枚举类型的问题

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson#264]
我使用的fastjson为最新的 1.2.3 (之前版本存在该问题，换到新版本也存在该问题) 。

如果对象的属性存在枚举类型，fastjson貌似只能输出为枚举常量的字面值(字符串)，而无法输出 int 类型的 ordinal() 值。无论是否使用 SerializerFeature.WriteEnumUsingToString 均是如此。

此外，我希望fastjson能够输出自定义枚举的指定属性值，而不是默认的 name() 或者ordinal() 。
建议fastjson提供该方面的支持。

例如：定义一个EnumValue的接口，其中有一个 Object getEnumValue()方法，如果枚举实现了该接口，则使用 getEnumValue() 方法 的返回值作为枚举输出。

**Comment by wenshao** [comment]
这个已经支持，请用新版本。SerializerFeature.WriteEnumUsingName或者SerializerFeature.WriteEnumUsingToString

**Comment by nnzbz** [comment]
新版本还不支持呀，楼上的并没看懂楼主的意思，请注意看最后一句话，我也想弄个接口，可是fastjson不知道怎么做

**Comment by piaoyaoi** [comment]
2020年了，还没有
