### ISSUE TITLE
BigDecimal序列化的时候空指针，导致jvm发生致命错误。程序直接宕机，后台无进程

### ISSUE THREAD

**Issue by slomhve** [alibaba/fastjson#2666]
![image](https://user-images.githubusercontent.com/23456052/63843145-7bd17200-c9b8-11e9-929c-1c277861d7fa.png)
fastjson1.2.58
JRE (1.8.0_131-b11)

**Comment by luke-huang666** [comment]
连个测试用例都没有，就一张图别人怎么定位？
