### ISSUE TITLE
反序列SMGPSubmitMessage的问题。

### ISSUE THREAD

**Issue by manyi100** [alibaba/fastjson#2685]
引入坐标：
        <dependency>
            <groupId>com.chinamobile.cmos</groupId>
            <artifactId>sms-core</artifactId>
            <version>2.1.9</version>
        </dependency>

测试代码：

        SMGPSubmitMessage smgpSubmitMessage=new SMGPSubmitMessage();
        smgpSubmitMessage.setSequenceNo(1);
        smgpSubmitMessage.setServiceId("hell");
        smgpSubmitMessage.setMsgContent(“hello”);   //注释掉可以正常
        smgpSubmitMessage.setChargeTermId("123555");
        smgpSubmitMessage.setSrcTermId("10086");
        CmppSubmitResponseMessage submitResponseMessage=new CmppSubmitResponseMessage(1);
        submitResponseMessage.setResult(0);
        submitResponseMessage.setMsgId(new MsgId());

        String smsMsg = JSON.toJSONString(smgpSubmitMessage);
        System.out.println(smsMsg);

        smgpSubmitMessage=JSON.parseObject(smsMsg,SMGPSubmitMessage.class);

        System.out.println(smgpSubmitMessage);

===============
把
        smgpSubmitMessage.setMsgContent(“hello”);   //注释掉可以正常运行，加上后报错：

Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 249, fieldName msgContent, fastjson-version 1.2.59

**Comment by Omega-Ariston** [comment]
因为msgConten入参需要的是SmsMessage对象，而序列化通过get方法拿到的是个String，所以反序列化就报错了。
解决方法:因为第三方类，无法加注解，我们可以通过使用新特性Mixin来给setMsgContent自定义反序列化器，可以看看这个用例 #2793
