### ISSUE TITLE
Fastjson新版本解析到特定字符后直接触发异常

### ISSUE THREAD

**Issue by yeweichen** [alibaba/fastjson#2689]
已fix

**Comment by yeweichen** [comment]
如果有fastjson的开发团队同学看到这个issue，帮忙复现确认一下。这个多半是源码的某处bug，希望能尽快的在某个版本修复掉。

**Comment by yeweichen** [comment]
仔细分析这个漏洞的影响，黑客们只需要构造一个特定的字符串流，发给各个服务的后台，任何基于fastjson的后台解析到这个数据都会被攻击，产生大量内存消耗OOM挂掉。希望fastjson开发团队重视这个问题，提高优先级修复。

**Comment by Omega-Ariston** [comment]
这个问题可以通过一个更简单的字符串复现（死亡字符串）：
`String DEATH_STRING = "{\"a\":\"\\x";`
只要`\x`出现在字符串尾部就会出现这个问题
已提交修复pr，感谢回馈。

**Comment by yeweichen** [comment]
> 这个问题可以通过一个更简单的字符串复现（死亡字符串）：
> `String DEATH_STRING = "{\"a\":\"\\x";`
> 只要`\x`出现在字符串尾部就会出现这个问题
> 已提交修复pr，感谢反馈。

 感谢社区小伙伴的快速响应！

**Comment by ljpsfree** [comment]
同一个文件的scanSymbol方法中有同样的逻辑，不需要一起改吗？

**Comment by Omega-Ariston** [comment]
> 同一个文件的scanSymbol方法中有同样的逻辑，不需要一起改吗？

如果从这个bug的角度来说的话，现版本采取的修复手段除了加强字符串格式的检验外，还加强了对反序列化结束条件的判断，所以通过输入精心构造字符串来触发这个漏洞的方式已经被永久封堵了。
如果从程序处理入参的角度来说的话，是的，一起改会好些，多谢反馈 :)

**Comment by qq1036916439** [comment]
最近fastjson的问题有点多哈
