### ISSUE TITLE
ISO8601日期反序列出错

### ISSUE THREAD

**Issue by yqeric** [alibaba/fastjson#269]
前几天从1.1.41升级到了1.2.3后出现了该错误，不能反序列化ISO8601格式的UTC时间，
如：2014-10-09T03:07:07.000Z，
换了多个版本测试，发现只有1.1.41可以正确反序列。

**Comment by erlooker** [comment]
1.2.5版本也出现了这个问题：
java.lang.NumberFormatException: For input string: "2015-05-12T18:16:24.91"
