### ISSUE TITLE
请问,非标准json字符串,键值都没有冒号包裹能解析吗?

### ISSUE THREAD

**Issue by jiash** [alibaba/fastjson#2699]
遇到一个很奇葩的json解析需求，想请教下目前fastjson是否具备这个功能：
1.一个非标准的json字符串，key和value都没有引号包裹。能用fastjson解析吗？
2.如果1.中的能够实现，在此基础上，如果value中存在未转义的特殊字符如："[,{"等能解析吗？

**Comment by Omega-Ariston** [comment]
1.2.60 版本增加了校验接口，建议先校验是否合法JSON字符串再进行解析，避免出现以上奇葩场景。

**Comment by jiash** [comment]
@Omega-Ariston 谢谢了，甲方这个需求真是能气死人。:joy:
