### ISSUE TITLE
JSON.toJavaObject(new JSONObject(), JSON.class)) 返回 null

### ISSUE THREAD

**Issue by jjm2473** [alibaba/fastjson#2703]
执行以下代码都会返回null:

1.
```java
JSON.toJavaObject(new JSONObject(), JSON.class);
```
2.
```java
new JSONObject().toJavaObject(JSON.class);
```

**Comment by Omega-Ariston** [comment]
期待的返回值是...?

**Comment by jjm2473** [comment]
JSON 是 JSONObject 的超类, 正常应该返回自己.
例如:
`JSON.toJavaObject(new JSONArray(), JSON.class);`
这行会正常返回自己.

**Comment by Omega-Ariston** [comment]
> JSON 是 JSONObject 的超类, 正常应该返回自己.
> 例如:
> `JSON.toJavaObject(new JSONArray(), JSON.class);`
> 这行会正常返回自己.

尝试着修复了一下，已提PR
