### ISSUE TITLE
1.2.58 JSONPath 中文key 无法过滤

### ISSUE THREAD

**Issue by 7743366427** [alibaba/fastjson#2721]

**Comment by Felicty** [comment]
可否给个testcase参考下？

**Comment by Zerounary** [comment]
**Json格式**
`
[{
	"名称": "脆皮青豆",
	"配料": ["豌豆", "棕榈油", "白砂糖", "食用盐", "玉米淀粉"]
}, {
	"名称": "绿葡萄干",
	"配料": ["无核葡萄干"]
}, {
	"名称": "素肉片",
	"配料": ["大豆分离蛋白", "水", "植物油", "酿造酱油", "白砂糖", "食用盐", "孜然", "香辛料"]
}]
`

**使用JSONPath查询**

Path=`$[名称]`时，可以过滤出名称：
`["脆皮青豆","绿葡萄干","素肉片"]`

Path=`$[名称 = '脆皮青豆']`时，可以过滤但没有结果：
`[]`

**将Json格式修改为**
`
[{
	"name": "脆皮青豆",
	"配料": ["豌豆", "棕榈油", "白砂糖", "食用盐", "玉米淀粉"]
}, {
	"名称": "绿葡萄干",
	"配料": ["无核葡萄干"]
}, {
	"名称": "素肉片",
	"配料": ["大豆分离蛋白", "水", "植物油", "酿造酱油", "白砂糖", "食用盐", "孜然", "香辛料"]
}]
`

Path=`$[name = '脆皮青豆']`时，可以过滤有结果：
`[{"name":"脆皮青豆","配料":["豌豆","棕榈油","白砂糖","食用盐","玉米淀粉"]}]`

其他很多过滤条件都一样
