### ISSUE TITLE
JSON.isValid("123")返回true，这个方法的正确使用方式是什么

### ISSUE THREAD

**Issue by nopol** [alibaba/fastjson#2727]
能否解释下这个方法是用来干嘛的，我的理解是判断是否是一个有效的json字符串。

**Comment by Omega-Ariston** [comment]
参考JSON [RFC标准](http://www.rfc-editor.org/rfc/rfc4627.txt)：
JSON can represent four primitive types (strings, numbers, booleans,
   and null) and two structured types (objects and arrays).

因此123是一个合法JSON.
