### ISSUE TITLE
com.alibaba.fastjson.JSONException: unclosed string : ^Z

### ISSUE THREAD

**Issue by drluorose** [alibaba/fastjson#273]
com.alibaba.fastjson.JSONException: unclosed string : ^Z

**Comment by yakolee** [comment]
使用哪个版本？如何重现？能否提供完整的信息？

**Comment by sandaobusi** [comment]
com.alibaba.fastjson.JSONException: unclosed string : ^Z

**Comment by sandaobusi** [comment]
我也复现了，com.alibaba.fastjson.JSONException: unclosed string : ^Z
1.2.6版本，看起来像特殊字符

**Comment by sandaobusi** [comment]
复现方法：vi模式按住ctrl，按v z就可以打出来这个字符，搜了下是一个文件结束符，json的字段出现这个字符反解析失败

**Comment by ChetWang** [comment]
用最新的fastjson 1.2.4仍有这个问题存在

**Comment by wenshao** [comment]
能否帮忙提供一个重现问题的testcase，要求java代码

**Comment by ChetWang** [comment]
我碰到问题时，都是个别客户端传上来的json数据引起的，最后带一个^Z的字符。从日志中复制粘贴出来都是正常的。

**Comment by wenshao** [comment]
已经解决，1.2.9 & 1.1.49.android版本中都会修复这个问题。

**Comment by msimw** [comment]
Exception in thread "main" com.alibaba.fastjson.JSONException: unclosed string : A

**Comment by warnerzz** [comment]
用了1.2.9，还是出现问题。
com.alibaba.fastjson.JSONException: unclosed string : ^Z

**Comment by warnerzz** [comment]
用了1.2.9，还是出现问题。
com.alibaba.fastjson.JSONException: unclosed string : ^Z

**Comment by musktime** [comment]
com.alibaba.fastjson.JSONException: unclosed.str

字符串长度为96767，解析时会失败

**Comment by qinpeng-qp** [comment]
com.alibaba.fastjson.JSONException: unclosed string : ^Z
