### ISSUE TITLE
SerializeConfig 删除put方法?

### ISSUE THREAD

**Issue by wuwenjie0506** [alibaba/fastjson#2731]
private SerializeConfig serializeConfig = new SerializeConfig();

    @PostConstruct
    public void init() {
        serializeConfig.put(byte[].class,new ObjectSerializer() {

            @Override
            public void write(JSONSerializer serializer, Object object, Object fieldName, Type fieldType, int features) throws
                    IOException {
                SerializeWriter out = serializer.getWriter();

                if (object == null) {
                    return;
                }

                out.write(new String((byte[])object));
            }
        });
    }
删除之后导致方法找不到，为什么要删除方法，怎么兼容使用？Commit是89663935d403f5e3b5132ba6f93659b7c2d488e2。

**Comment by Omega-Ariston** [comment]
误删了..已提修复pr，可以暂时先在byte[].class前加上(Type)，`serializeConfig.put((Type)byte[].class, new ObjectSerializer()`，sorry
