### ISSUE TITLE
json的key中有逗号取不到值

### ISSUE THREAD

**Issue by kevlxy** [alibaba/fastjson#2743]
json:

{"info":
    {"com.xxx.service.xxxServiceForOrder@queryGoodsV2(Long,Long,Long)": 
       [{"method":"queryPrepayGoodsV2"}]
    }
}

jsonpath:
$['info']['com.xxx.service.xxxServiceForOrder@queryGoodsV2(Long,Long,Long)']

用上述jsonpath取值时，返回[null，null，null],请问这种情况怎么处理？

**Comment by kimmking** [comment]
括号，@，和点，在jsonpath里都有特殊含义

**Comment by kevlxy** [comment]
> 括号，@，和点，在jsonpath里都有特殊含义

感谢回复。想问下，那需要怎么转义呢？返回的json就是这样的

**Comment by kimmking** [comment]
我搞错了，上面应该是合法的匹配。it;s a bug.
![image](https://user-images.githubusercontent.com/807508/65048802-4c020280-d997-11e9-9707-cc4f8c89761a.png)

**Comment by kevlxy** [comment]
> 我搞错了，上面应该是合法的匹配。it;s a bug.
> ![image](https://user-images.githubusercontent.com/807508/65048802-4c020280-d997-11e9-9707-cc4f8c89761a.png)

期待大佬尽快安排修复~
