### ISSUE TITLE
ParseObject对于\u的值解析乱码

### ISSUE THREAD

**Issue by se7en5** [alibaba/fastjson#2747]
@Test
    public void test2() {
        String message = "{\"test\":\"ftp://10.11.11.170/06\\u00e6\\u00b3\\u00b0\\u00e5\\u0090\\u0088\\u00e5\\u009f\\u00b9\\u00e8\\u00ae\\u00ad/.xml\"}";
        JSONObject o = JSONObject.parseObject(message, Feature.DisableSpecialKeyDetect);
        System.out.println(o);
    }

结果：
{"test":"ftp://10.11.11.170/06æ³°å\u0090\u0088å\u009F¹è®­/.xml"}
期望的结果是：
{"test":"ftp://10.11.11.170/06\u00e6\u00b3\u00b0\u00e5\u0090\u0088\u00e5\u009f\u00b9\u00e8\u00ae\u00ad/.xml"}
原因：
1、DefaultJsonParser-> line 483-> lexer.scanString();
2、JSONLexerBase->line 989 
3、对于u的处理结果是乱码
4、是否考虑提供对于scanString中的特殊符号是否做处理的接口，如果我设置成false,就不要自动帮我处理

**Comment by kimmking** [comment]
{test: "ftp://10.11.11.170/06æ³°åå¹è®­/.xml"}

这个显示是正常的。
跟你发的期望结果\uxxxx只是表示方式的不同。而且\u才是特殊的方式，正常的方式就应该是这样。

**Comment by se7en5** [comment]
@kimmking 解决了：用
String unescapeCode = StringEscapeUtils.unescapeJava(上述结果串);
        byte[] bytes = unescapeCode.getBytes(StandardCharsets.ISO_8859_1);
        String str = new String(bytes);
结果就不是乱码了
