### ISSUE TITLE
关于保持原属性大小写的问题

### ISSUE THREAD

**Issue by chuanqi** [alibaba/fastjson#275]
public static String decapitalize(String name) {
        if (name == null || name.length() == 0) {
            return name;
        }
        if (name.length() > 1 && Character.isUpperCase(name.charAt(1)) &&
                Character.isUpperCase(name.charAt(0))){
            return name;
        }
        char chars[] = name.toCharArray();
        chars[0] = Character.toLowerCase(chars[0]);
        return new String(chars);
    }
当设置 TypeUtils.compatibleWithJavaBean = true;时,为什么在判断第二个字母是不是大写呢?比如我的属性命名是 Name这样的,我想保留这样的命名.但通过上面这个方法里的判断,还是会被转为name.
请问这里是BUG还是出于什么样的考虑.

**Comment by wenshao** [comment]
当TypeUtils.compatibleWithJavaBean=true是，就是按照JavaBean的解析规范走，是遵从规范。
