### ISSUE TITLE
TypeUtils.castToBytes(Object) 异常信息中的提示可能存在错误

### ISSUE THREAD

**Issue by ejdbc** [alibaba/fastjson#2761]
hi, 我看到 com.alibaba.fastjson.util.TypeUtils#castToBytes 方法抛出的异常信息是 can not cast to int, value， 这个地方是写错了吗，提示同样信息的有 com.alibaba.fastjson.util.TypeUtils#castToInt这个方法

**Comment by ejdbc** [comment]
https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/util/TypeUtils.java
源文件 844行

**Comment by kimmking** [comment]
you are right.

**Comment by Omega-Ariston** [comment]
可以尝试提一个修复pr :)

**Comment by ejdbc** [comment]
> 可以尝试提一个修复pr :)

好的

**Comment by ejdbc** [comment]
> you are right.
