### ISSUE TITLE
SerializeWriter类中，writeFloat方法处理疑问

### ISSUE THREAD

**Issue by waterMeteors** [alibaba/fastjson#2795]
在此方法中判断if (value != value || value == Float.POSITIVE_INFINITY || value == Float.NEGATIVE_INFINITY) {
            writeNull();
        }
此判断中value != value中value是同一个值，此判断永远都是false。请问有什么意义在此处

**Comment by Omega-Ariston** [comment]
可以把value赋值为Float.NaN然后试试 :)

**Comment by wenshao** [comment]
Float.NaN == Float.NaN
返回的是false
