### ISSUE TITLE
当服务端返回的数据格式为空时，我使用TypeReference 去解析一个本来应该很复杂的数据报错

### ISSUE THREAD

**Issue by verybranch** [alibaba/fastjson#280]
01-21 10:38:37.413: W/System.err(7864): com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 19, fieldName data
01-21 10:38:37.414: W/System.err(7864): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
01-21 10:38:37.414: W/System.err(7864): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
01-21 10:38:37.414: W/System.err(7864): 	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
01-21 10:38:37.414: W/System.err(7864): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:420)
            01-21 10:38:37.415: W/System.err(7864): 	at              com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
01-21 10:38:37.415: W/System.err(7864): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
01-21 10:38:37.415: W/System.err(7864): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
01-21 10:38:37.415: W/System.err(7864): 	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:189)
01-21 10:38:37.416: W/System.err(7864): 	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:184)
01-21 10:38:37.416: W/System.err(7864): 	at cc.xiguo.xiguo.app.common.http.Controller.execute(Controller.java:139)
01-21 10:38:37.417: W/System.err(7864): 	at cc.xiguo.xiguo.app.common.http.StartHttpManager$GetJPushData.runHttpTask(StartHttpManager.java:2549)
01-21 10:38:37.417: W/System.err(7864): 	at cc.xiguo.xiguo.app.common.http.XGTask.run(XGTask.java:79)
01-21 10:38:37.417: W/System.err(7864): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
01-21 10:38:37.417: W/System.err(7864): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
01-21 10:38:37.417: W/System.err(7864): 	at java.lang.Thread.run(Thread.java:838)

这是服务器没有数据时返回的数据
{
    "code": "0",
    "data": "",
    "msg": ""
}

当有数据时data 是一个复杂的，并且解析不会有问题

**Comment by aoqianglin** [comment]
也就是data为空相当于就是一个String   所以使用TypeReference<Respone<User>> type= new TypeReference<Respone<User>>>() {};  解析报错，那么应该怎么解决这个问题呢

**Comment by wenshao** [comment]
1.2.9 & 1.1.49.android will fixed this bug.
