### ISSUE TITLE
JSON.toJSONString()对泛型为Collection或Map类型的Collection&Map object失效

### ISSUE THREAD

**Issue by BlackImpl** [alibaba/fastjson#281]
List<List<Integer>> lists = new ArrayList<List<Integer>>();
List<Integer> item = new ArrayList<Integer>();
		
item.add(1);
lists.add(item);
		
item.add(2);
lists.add(item);
String jsonWrong = JSON.toJSONString(lists);
System.out.println(jsonWrong);

输出的值为: [[1,2],{"$ref":"$[0]"}]

**Comment by BlackImpl** [comment]
done 有引用

**Comment by luffyke** [comment]
关闭循环引用可以解决。。
JSON.toJSONString(obj, SerializerFeature.DisableCircularReferenceDetect);

**Comment by zhihang777** [comment]
777
