### ISSUE TITLE
莫名其妙出现了 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by verybranch** [alibaba/fastjson#282]
01-21 21:02:18.840: W/System.err(26144): 	at java.lang.Thread.run(Thread.java:841)
01-21 21:02:18.840: W/System.err(26144): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=-1
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.JSONReaderScanner.charAt(JSONReaderScanner.java:126)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.JSONLexerBase.longValue(JSONLexerBase.java:2919)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.deserializer.LongFieldDeserializer.parseField(LongFieldDeserializer.java:29)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:420)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
01-21 21:02:18.840: W/System.err(26144): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:635)
01-21 21:02:18.845: W/System.err(26144): 	at com.alibaba.fastjson.parser.deserializer.CollectionDeserializer.deserialze(CollectionDeserializer.java:63)
01-21 21:02:18.845: W/System.err(26144): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)

	TypeReference<XGResponse<NoticListBean>> reference = new TypeReference<XGResponse<NoticListBean>>() {
			};
Reader reader = new InputStreamReader(inputStream);
					JSONReader jsonReader = new JSONReader(reader);
					response = jsonReader.readObject(typeReference);

**Comment by wenshao** [comment]
问题修复了，1.2.9中会修正这个bug。
