### ISSUE TITLE
JSON.parseObject(str) 报错 Failed to invoke public com.alibaba.fastjson.JSON() with no args

### ISSUE THREAD

**Issue by iyakexi** [alibaba/fastjson#2829]
JSON.parseObject(str) 报错 Failed to invoke public com.alibaba.fastjson.JSON() with no args

**Comment by crazy-91Q** [comment]
需要一个无参的构造函数

**Comment by iyakexi** [comment]
看了下fastjson的源码，JSON是abstractd的， 我的代码中由于在某个class中声明了一个JSON属性，在程序自动解析json的时候会发生错误。正确的方式是声明成JSONObject属性（JSONObject是继承自JSON的实体类）
