### ISSUE TITLE
CollectionDeserializer deserialze问题

### ISSUE THREAD

**Issue by BlackImpl** [alibaba/fastjson#283]
```java
String jsons = "[[1,1,1,2,3],[2,3,12,3,4],[1],[2]]";	
Collection<Collection<Integer>> collections = JSON.parseObject(jsons, new 
      TypeReference< Collection < Collection < Integer > > >(){});  
```

以上代码会出现元素丢失, 原因是因为泛型是Collection 的时候, bug导致默认的实现类型是HashSet。 CollectionDeserializer.deserialze() bug 代码如下:
```java       
        .........
        if (rawClass == AbstractCollection.class) {
            list = new ArrayList();
        } else if (rawClass.isAssignableFrom(HashSet.class)) {//判断条件有误, 应该是HashSet及HashSet的子类才能new HashSet, 否则, 所有的Set类型都会被此条件截断。
            list = new HashSet();
        } 
        ........
```

**Comment by BlackImpl** [comment]
A.isAssginableFrom(B) 是表示 A是否是A的父类或者是父接口, Set.class & Collection.Class 一定是HashSet.class 的父接口, 以下逻辑无效, 对于Set.class & Collection.class 永远会走第一个逻辑：
        if (rawClass == AbstractCollection.class) {
        	
        } else if (rawClass.isAssignableFrom(HashSet.class)) {
        	
        } else if (rawClass.isAssignableFrom(LinkedHashSet.class)) {
        	
        } else if (rawClass.isAssignableFrom(TreeSet.class)) {
        	
        } else if (rawClass.isAssignableFrom(ArrayList.class)) {
        	
        } else if (rawClass.isAssignableFrom(EnumSet.class)) {
        	
        } else {
        	
        }

**Comment by BlackImpl** [comment]
Collection<Collection<Integer>> collections = JSON.parseObject(jsons, new 
      TypeReference< Collection < Collection < Integer > > >(){});   

建议如果是泛型是Collection类型的时候, 默认的实例应该是ArrayList 这样避免出现数据丢失。

**Comment by wenshao** [comment]
谢谢反馈，问题已经修正。在1.2.9和1.1.49.android版本中都会修复这个问题。
