### ISSUE TITLE
数值字符串末尾带有小数点0转换为整数出现NumberFormatException

### ISSUE THREAD

**Issue by jsvnadmin** [alibaba/fastjson#2830]
直接看代码
`
JSONObject jsonObject = JSONObject.parseObject("{\"qty\":\"10.0\"}");

int qty = jsonObject.getIntValue("qty");
`
字符串转换为数值的时候，可不可以自动去掉后面是 .0 的，再转。这样就不怕有错误。

**Comment by biyanwen** [comment]
` JSONObject jsonObject = JSONObject.parseObject("{'qty':'10.0'}");
        double qty = jsonObject.getDoubleValue("qty");`
众所周知int是整数类型，不应该有小数位的。 而且高精度的数字类型也不应该转换成低精度的数字类型

**Comment by jsvnadmin** [comment]
嗯，没错，double是不应转成int。
这个场景中，这个值其实这个是int类型的，只是json是其它字符串发过来的，带多了个 .0。
如果可以去掉.0再格式化，对于使用方来说还是很方便的。
