### ISSUE TITLE
java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to java.util.ArrayList

### ISSUE THREAD

**Issue by yuankui** [alibaba/fastjson#284]
public static class Suitables extends HashMap<String, ArrayList<Suitables.Suitable>>{
		public static class Suitable {
			private String id;
			private String name;
		}
                public static Suitables parseFromJson(String text) {
			return JSON.parseObject(text, Suitables.class);
		}
	}
         // test
         for (Map.Entry<String, ArrayList<Solution.Suitables.Suitable>> stringListEntry : suitables.entrySet()) {
			System.out.println("Key = " + stringListEntry.getKey());
			for (Solution.Suitables.Suitable suitable : stringListEntry.getValue()) {
				System.out.println("id = " + suitable.getId());
				System.out.println("name = " + suitable.getName());
              }
       }

进行枚举输出的时候，报错：`java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to java.util.ArrayList`
用`org.codehaus.jackson.map.ObjectMapper.readValue(text, Suitables.class);`解析之后是没有问题的。

版本：1.2.1，1.2.4

**Comment by changwei0708** [comment]
解决了？

**Comment by seulfish** [comment]
我也遇到这种问题，使用Gson是没有问题的
