### ISSUE TITLE
我该怎么设置ParserConfig的propertyNamingStrategy为原封不动的把我变量名传过去?

### ISSUE THREAD

**Issue by Mairuis** [alibaba/fastjson#2864]
如题.. PropertyNamingStrategy里貌似并没有no_change这种选项

**Comment by Licker05** [comment]
不设置PropertyNamingStrategy不就可以了？

**Comment by Mairuis** [comment]
源码里不设置默认就是骆驼峰，现在只有给每个字段加上@JsonField(name = "xxx")才能解决，巨麻烦，我用模板生成器把旧POJO批量加上了注解，要不然估计现在都没下班。。。

**Comment by Licker05** [comment]
> 源码里不设置默认就是骆驼峰，现在只有给每个字段加上@JsonField(name = "xxx")才能解决，巨麻烦，我用模板生成器把旧POJO批量加上了注解，要不然估计现在都没下班。。。

版本问题吧，最新版的话不设置默认是不改变
