### ISSUE TITLE
@JSONField name 不支持 private 字段

### ISSUE THREAD

**Issue by wangjing112** [alibaba/fastjson#2866]
测试代码:
`	@Test
	public void testPrivate() {
		String json = "{\"A1\":1,\"A2\":2,\"A3\":3}";
		
		A a = JSON.parseObject(json, A.class, Feature.SupportNonPublicField);

		System.out.println(String.format("a1:%d,a2:%d,a3:%d",a.a1,a.A2,a.a3));
	}
	
	static class A{
		@JSONField(name="A1")
		int a1;
		int A2;
		@JSONField(name="A3")
		public int a3;
	}
`

输出:
a1:0,a2:2,a3:3

**Comment by Licker05** [comment]
JavaBeanInfo.java的821行改为
computeFields(clazz, type, propertyNamingStrategy, fieldList, declaredFields);
就支持你这种写法了

**Comment by biyanwen** [comment]
属性私有就必须有setter方法，否则无法反序列化。

**Comment by Licker05** [comment]
> 属性私有就必须有setter方法，否则无法反序列化。

那A2咋就可以反序列化成功，不是这个问题吧，我觉得就是个BUG
