### ISSUE TITLE
关于为对象属性null空指针添加默认值的支持

### ISSUE THREAD

**Issue by arthinking** [alibaba/fastjson#287]
希望增加这种支持的支持，当值为空的时候，返回字段的默认值，这样方便直接调用fastjson生成JSON对象时，返回给客户端接口的JSON数据属性个数都是一致的。

**Comment by zhengzhengfang** [comment]
用__SerializerFeature.WriteMapNullValue__
```java
JSON.toJSONString(yourObject, SerializerFeature.WriteMapNullValue);
```

**Comment by arthinking** [comment]
Thanks to zhengzhengfang.
