### ISSUE TITLE
SerializerFeature.WriteNullStringAsEmpty 失效

### ISSUE THREAD

**Issue by yzhang921** [alibaba/fastjson#2871]
貌似当前maven依赖最多的一个版本1.2.58，WriteNullStringAsEmpty属性失效了

**Comment by weiwensangsang** [comment]
能给一个demo，并且说明“失效”的具体报错情况吗？

**Comment by yzhang921** [comment]
没有报错, 我说错版本了，同样的用法1.2.58，序列化丢了null的属性，1.2.29就可以
```
public static String fastJson2StringWriteNullEmpty(JSONObject jo) {
        return JSON.toJSONString(jo, SerializerFeature.WriteNullStringAsEmpty);
    }
```

**Comment by yzhang921** [comment]
这个问题还处不处理啊，升级到1.2.73，之后值为空的属性，用上面的方法还是会把null属性丢掉  
![image](https://user-images.githubusercontent.com/6037522/95729661-c3e05080-0caf-11eb-9fdd-f238143ec10e.png)
![image](https://user-images.githubusercontent.com/6037522/95729893-1d487f80-0cb0-11eb-8992-1e66615330be.png)

**Comment by yzhang921** [comment]
不好意思，配置理解错了，搞反了，这应该是是旧版本的bug新版本1.2.29的bug，
SerializerFeature.WriteMapNullValue才是序列化null属性，WriteNullStringAsEmpty是null输出为空白的意思
