### ISSUE TITLE
Enum 序列化 ，无法得到下标

### ISSUE THREAD

**Issue by fengdu** [alibaba/fastjson#290]
JDK 1.7
fastJson 1.1.41 / 1.2.1

问题：
转换对象 到 string 时， Enum 类型无法输出下标

System.out.println("out="+JSON.toJSONString(Type.Big));
        System.out.println("out="+JSON.toJSONString(Type.Big,SerializerFeature.WriteEnumUsingToString));

enum Type {      Big, Medium, Small }

--------------------
均输出 Big， 而非我想要的 0

**Comment by zhengzhengfang** [comment]
有缺省值，先清掉：
```java
JSON.DEFAULT_GENERATE_FEATURE=0;
```
这坑，得赶紧修复...

**Comment by fengdu** [comment]
调用这个后
JSON.DEFAULT_GENERATE_FEATURE=0;
再d调用  JSON.toJSONString(object, SerializerFeature.WriteNullStringAsEmpty, SerializerFeature.WriteMapNullValue);

feature 不生效
还是等新版本吧

**Comment by wenshao** [comment]
用原来这个JSON.toJSONStringZ可以实现这个需求的，或者你看代码自己做一个，这个是静态方法，很简单，很好写的。

**Comment by eeve** [comment]
入坑
