### ISSUE TITLE
jsonDirect 对泛型无效

### ISSUE THREAD

**Issue by itellyou-com** [alibaba/fastjson#2905]
实体类：
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Result<T> {
    private Boolean result=true;
    private Integer status=200;
    private String message="Successful";
    @JSONField(jsonDirect = true)
    private T data;
    @JSONField(serialize = false)
    private String[] labes;

    private static final String OK = "OK";

    public Result(T data){
        this.data = data;
    }
}
```
使用：
```
Result<String> testResult = new Result<>("{}");
System.out.println(JSON.toJSONString(testResult));
// {"data":"{}","message":"Successful","result":true,"status":200}
```
data依然是字符串，不是json数据
在  private T data; 声明类型  private Sting data; 为String 的时候有效，但是在泛型的情况下无效

**Comment by hulog** [comment]
由于Java的泛型擦除，在构建data字段元信息（fieldInfo）的时候，这种方式拿不到泛型的具体类型。当Result<T> 定义成 Result<T extends String> 是可以的。
另： jsonDirect 本意是为String设计的，如果确实需要，建议如下方式。
```java
public class Issue2906Test {
    private class StringResult extends Result<String> {
        public StringResult(String data) {
            super(data);
        }
    }

    @Test
    public void test2906() {
        StringResult stringResult = new StringResult("{}");
        System.out.println(JSON.toJSONString(stringResult));
        // {"data":{},"message":"Successful","result":true,"status":200}
        
        
        Result<String> result = new StringResult("{}");
        System.out.println(JSON.toJSONString(result));
        // {"data":{},"message":"Successful","result":true,"status":200}
    }
}
```
自己研究的，不知是否正确，期待作者的解决方案

**Comment by itellyou-com** [comment]
> 由于Java的泛型擦除，在构建data字段元信息（fieldInfo）的时候，这种方式拿不到泛型的具体类型。当 `Result<T> ` 定义成 `Result<T extends String> ` 是可以的。
> 另： jsonDirect 本意是为String设计的，如果确实需要，建议如下方式。
> 
> ```java
> public class Issue2905Test {
>     private class StringResult extends Result<String> {
>         public StringResult(String data) {
>             super(data);
>         }
>     }
> 
>     @Test
>     public void test2905() {
>         StringResult stringResult = new StringResult("{}");
>         System.out.println(JSON.toJSONString(stringResult));
>         // {"data":{},"message":"Successful","result":true,"status":200}
>         
>         
>         Result<String> result = new StringResult("{}");
>         System.out.println(JSON.toJSONString(result));
>         // {"data":{},"message":"Successful","result":true,"status":200}
>     }
> }
> ```
> 
> 自己研究的，不知是否正确，期待作者的解决方案

嗯，差不多这样的解决方式吧，必须得再建个类了
