### ISSUE TITLE
为什么proguard配置中要加-keepattributes Signature

### ISSUE THREAD

**Issue by xyczero** [alibaba/fastjson#292]
Android 混淆代码之后，总是抛出ClassCastException，google之后发现解决方案
https://ticket.avosapps.com/tickets/543dd918e4b0bf1a918bf390/threads

请问这是为什么？

**Comment by gengjiawen** [comment]
加了这个果然可以了,多谢

**Comment by jaogoy** [comment]
我也找了好久的原因，看到后一试，世界安静了。
不过看英文说明也没看明白是啥意思，有些地方说是类型转换，有些说是泛型。。。

**Comment by gengjiawen** [comment]
@wenshao 你不考虑加到文档里面或者做出说明吗？就这样直接关闭这个Issue？
