### ISSUE TITLE
JSONPath不支持extract包含.的key

### ISSUE THREAD

**Issue by xiao-yun** [alibaba/fastjson#2926]
版本1.2.62 
`JSONPath.extract("{\"k1.1\": 1}", "$.\"k1.1\"")`
抛异常`illeal jsonpath syntax. $."k1.1"`

**Comment by hulog** [comment]
转义啊兄弟！！！

`.`是标识符，莫乱搞

**Comment by xiao-yun** [comment]
jsonPath是$."k1.1"，双引号括起来的"k1.1"作为一个key，是合法的key

**Comment by hulog** [comment]
`k1\\.1` 或者 `k\\\\.1` ,自己去试

**Comment by xiao-yun** [comment]
k1\\.1可以的，多谢
