### ISSUE TITLE
java 8 不支持?

### ISSUE THREAD

**Issue by yinheli** [alibaba/fastjson#295]
`java.lang.IllegalAccessError: tried to access class .... from class Serializer_7`

**Comment by wenshao** [comment]
能把JavaBean的代码贴出来么？

**Comment by dachuanz** [comment]
支持的

**Comment by wenshao** [comment]
支持的，这个应该是bug，希望能够提供重现问题的testcase.

**Comment by yinheli** [comment]
时间有点久了, 代码找不到了. 后来试了下, java 8 是可以的
这个问题我先关闭了
