### ISSUE TITLE
不能解析如下 引号里面有 冒号的 的 json 串

### ISSUE THREAD

**Issue by wary** [alibaba/fastjson#296]
{"downloadSpeed":631055,"responseTime":1.435,"url":"http://m2.music.126.net/xUqntwOHwpJdXsO_H-kHsw==/5817516022676667.mp3?v=50710699"}

容错能力比较差

相比之下 jackson 就可以解析

**Comment by yinheli** [comment]
@wary 能贴点异常吗? 经过测试, 没有发现这种问题

**Comment by wenshao** [comment]
bug fixed. i will include in 1.2.9 & 1.1.49.android

**Comment by wptree** [comment]
在fastjson-1.2.23仍旧出现这个问题。解析下面这个字符串的时候，fastjson不报错，解析过程正常运行，但就是解析失败。

"data": "{\"method\":\"POST\",\"httpStatus\":200,\"start\":1484537697659,\"end\":1484537697901,\"visiblePageId\":\"abc\",\"url\":\"http:\/\/abc.com\/trans\/users\/abc\/assets\/dividendMethod\/abc\/abc\",\"errorInfo\":\"\",\"requestId\":\"abc\"}",
