### ISSUE TITLE
Enum序列化 1.1.41之后的所有版本为什么都改成调用toString

### ISSUE THREAD

**Issue by yangjunqiu** [alibaba/fastjson#298]
Enum1.1.41之前的版本反序列化父类属性有问题
但是之后的所有版本序列化为什么都改成调用toString?能不能给个方法调用.name()?
这个改动对我们已有的系统影响很大,求解决

**Comment by bohrqiu** [comment]
如果enum重写了toString 方法，就是造成这个问题。其实SerializerFeature.WriteEnumUsingToString没有任何意义的。而且fastjson的大部分代码中，对于SerializerFeature.WriteEnumUsingToString的处理是用的枚举的name()。但是在com.alibaba.fastjson.serializer.EnumSerializer中对于启用SerializerFeature.WriteEnumUsingToString特性，却使用了枚举的toString方法。而且对于自定义toString的枚举根本没有办法反序列化。

这里建议参考jpa对于枚举的处理，提供name()和ordinal()两种方式。

**Comment by wenshao** [comment]
SerializerFeature.WriteEnumUsingName
