### ISSUE TITLE
android版本不支持注解JSONField#deserializeUsing

### ISSUE THREAD

**Issue by JiangBinbin1990** [alibaba/fastjson#2980]
我们产品正计划从fastjson标准版本切换到android版本，但是发现android版本不支持注解JSONField#deserializeUsing。
* 请问有其它方式可以实现对某个属性的反序列化的自定义吗？
* 如果没有，退而求其次，fastjson android版本支持对整个类的反序列化进行自定义吗？

**Comment by HiMovie** [comment]
请关闭issue，已经不再使用fastjson

**Comment by JiangBinbin1990** [comment]
请关闭issue，已经不再使用fastjson
