### ISSUE TITLE
序列化为 JSON 时，Long 型精度不足

### ISSUE THREAD

**Issue by oswayne** [alibaba/fastjson#3005]
当将 Java 对象转换为 JSON 时，如果 Java 对象中的 Long 类型数据长度较大时，会出现精度丢失

**Comment by githublaohu** [comment]
精度没有丢失，是json只支持52位，不支持64位。需要把弄转从字符串。fastjson，没有有这个配置吧

**Comment by githublaohu** [comment]
自己写一个拦截器处理下吧

**Comment by githublaohu** [comment]
可以关闭这个issues了哈。
