### ISSUE TITLE
使用 ISO8601 序列化日期类型, 结果JSON串中缺少时区段,导致浏览器中获取的时间出错

### ISSUE THREAD

**Issue by zlphoenix** [alibaba/fastjson#301]
按照https://github.com/alibaba/fastjson/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 文档中关于日期时间的处理,序列化时通过SerializerFeature.UseISO8601DateFormat 指定序列化配置,应该序列化为"2015-03-02T16:59:11.621+08:00"的数据被序列化为"2015-03-02T16:59:11.621"
缺少时区后缀,在反序列化时会被认为是 UTC 时间.反序列化为 Js 对象后跟原始数据相差8小时.

**Comment by jarry** [comment]
这个问题是时区造成的。前端JS只好做兼容：
// 北京为东8区时间，比伦敦时间早8小时，故需要加上8小时
// (传入毫秒 +  8 * 3600 * 1000);

或者在序列化时直接按照日期字符串转换，而不是拿到long型日期。
JSON.toJSONString(object, SerializerFeature.WriteDateUseDateFormat);

**Comment by wenshao** [comment]
bug fixed. i will include in 1.2.9 & 1.1.49.android
