### ISSUE TITLE
数组格式返回{},jackson报错，fastjson不报错，却返回一个对象属性为空，size＝1的list

### ISSUE THREAD

**Issue by Kingson4Wu** [alibaba/fastjson#3015]

**Comment by kiddingYang** [comment]
是最新版本吗？能提供一个复现的代码吗？

**Comment by Kingson4Wu** [comment]
`public class TestErrorArray {

    public static void main(String[] args) {

        //1.2.33 数组格式返回{},jackson报错，fastjson不报错，返回一个对象属性为空，size＝1的list
        B b = JSON.parseObject("{\"list\":{}}",B.class);

        System.out.println(b);

    }


    public static class B{
        List<A> list;

        public List<A> getList() {
            return list;
        }

        public void setList(List<A> list) {
            this.list = list;
        }
    }

    public static class A {

    }`
1.2.33版本，1.2.4已经没这个问题了
