### ISSUE TITLE
BigInteger类型会默认科学计数法，如何去掉啊？

### ISSUE THREAD

**Issue by andrew-qiu** [alibaba/fastjson#3026]
我看fastjson只提供了 WriteBigDecimalAsPlain 用于屏蔽BigDecimal类型的默认科学计数法，但是没有提供屏蔽BigInteger类型的默认科学计数法。我在最新的1.2.61上进行了试验，问题如下：

"activity_id": 2.020020700826004e+27,
"activity_template_id": 2.0190822e+31,

希望项目尽快提供解决方案，谢谢

**Comment by wenshao** [comment]
```java
BigInteger value = new BigInteger("2020020700826004000000000000");

Assert.assertEquals("2020020700826004000000000000", JSON.toJSONString(value));
Assert.assertEquals("2020020700826004000000000000", JSON.toJSONString(value, SerializerFeature.WriteBigDecimalAsPlain));
```

我测试了是没问题啊

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.66
