### ISSUE TITLE
预留反序列化的可扩展处理器

### ISSUE THREAD

**Issue by leizhiyuan** [alibaba/fastjson#3072]
目前，如果有一些安全类的反序列化漏洞，需要升级fastjson

是否可以考虑，开放一个spi，允许用户进行注册自己的处理器，在反序列化前，调用一下用户注册的处理器，来决定是否反序列化，这样用户可以根据自己的需求。扩展不同的黑名单处理。

而不需要通过升级fastjson来解决类似问题？

**Comment by kanwangzjm** [comment]
官方支持一下自定义扩展吧，别让大家再无奈升级了。。。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
问题已修复，请用新版本。新版本增加了一个safeMode，配置后无论黑名单或者白名单都不支持autoType。新版也支持配置AutoTypeHandler。
