### ISSUE TITLE
1.2.67版本增强autoType安全黑名单

### ISSUE THREAD

**Issue by bad-boy1** [alibaba/fastjson#3074]
您好，1.2.67版本增强了部分autoType安全黑名单，但发现仍有一些Gadgets还没有加入黑名单：shiro-core（org.apache.shiro.jndi.JndiObjectFactory）、ignite-jta（org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup）、shaded hikari-config

**Comment by Ramos-dev** [comment]
org.apache.cxf.jaxrs.utils.schemas.SchemaHandler
org.apache.commons.jelly.impl.Embedded
javax.swing.JEditorPane虽然是ssrf，也可以加入黑名单
@wenshao

**Comment by johnyannj** [comment]
无穷无尽啊~~~ 不是办法啊~

**Comment by qixiaobo** [comment]
强烈建议去除autotype功能 该功能通过扩展包提供
这样绝大部分用户都无需每次升级
https://github.com/alibaba/fastjson/issues/2759#issuecomment-533766639
安全来看黑名单策略只是死路 只有白名单才能万古长存

zhaoyan <notifications@github.com> 于2020年3月23日周一 下午8:54写道：

**Comment by johnyannj** [comment]
@qixiaobo  不如设计成这样：autoTpe功能，必须配白名单，如果发现没有配，fastjson直接不能使用autoType功能。也就是说白名单是autoType的开关。

**Comment by qixiaobo** [comment]
> @qixiaobo 不如设计成这样：autoTpe功能，必须配白名单，如果发现没有配，fastjson直接不能使用autoType功能。也就是说白名单是autoType的开关。

作为研发 很负责任的说大家只会偷懒的~白名单配很容易啊  不过终究是危险的 所谓的白名单是个类名 为什么可以认为这个版本的是好的 到下个版本还是OK的呢？？？

**Comment by T4di5** [comment]
> > @qixiaobo 不如设计成这样：autoTpe功能，必须配白名单，如果发现没有配，fastjson直接不能使用autoType功能。也就是说白名单是autoType的开关。
> 
> 作为研发 很负责任的说大家只会偷懒的~白名单配很容易啊 不过终究是危险的 所谓的白名单是个类名 为什么可以认为这个版本的是好的 到下个版本还是OK的呢？？？

没错，0信任机制

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
问题已修复，请用新版本。新版本增加了一个safeMode，配置后无论黑名单或者白名单都不支持autoType
