### ISSUE TITLE
JSONValidator 验证json时 是否能够不抛excetion,而是直接返回false.

### ISSUE THREAD

**Issue by stephenlam520** [alibaba/fastjson#3079]
JSONValidator validator = JSONValidator.from(value);
boolean valid = validator.validate();

如果待验证的json 字符串缺少":" 或 其他符号时不是返回false,而是直接抛excetion.如果返回false是否更为直观?

version:1.2.67

**Comment by wenshao** [comment]
能提供样本么？

**Comment by stephenlam520** [comment]
我更新到1.2.68 这个问题还是存在的.

String jsonStr = "{\"a\":a}";
String jsonStr2 = "";
String jsonStr3 = "\"a:\"test\"";

这些用JSONValidator.from(jsonStr).validate() 验证json 还是抛exception, 而不是返回false.
