### ISSUE TITLE
fastjson will parse field value one to zero

### ISSUE THREAD

**Issue by xiantang** [alibaba/fastjson#3081]
Os: OSX 10.14.6 
JDK:1.8.0_231
fastjson version: 1.2.61
reproduce code:

i have a easy example class like that to mock tcp packages:

```java
package info.xiantang.messagequeue.kafka;

import java.io.Serializable;

public class TcpPackage implements Serializable {
    private int seq;
    private int flagACK;
    private int flagSYN;
    private int ack;


    public int getSeq() {
        return seq;
    }

    public TcpPackage(int ack) {
        this.ack = ack;
    }

    public TcpPackage(int seq, int flagACK, int SYN, int ack) {
        this.seq = seq;
        this.flagACK = flagACK;
        this.flagSYN = SYN;
        this.ack = ack;
    }

    public void setSeq(int seq) {
        this.seq = seq;
    }

    public int getFlagACK() {
        return flagACK;
    }

    public void setFlagACK(int flagACK) {
        this.flagACK = flagACK;
    }

    public int getFlagSYN() {
        return flagSYN;
    }

    public void setFlagSYN(int flagSYN) {
        this.flagSYN = flagSYN;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = obj instanceof TcpPackage;
        if (!b) {
            return false;
        }
        TcpPackage that = (TcpPackage) obj;
        return that.flagACK == this.flagACK && that.seq == this.seq && that.flagSYN == this.flagSYN;
    }

    public int getAck() {
        return ack;
    }
}
```
and i use junit to test my code 
```java 
    @Test
    public void testParse() {
        TcpPackage expect = new TcpPackage(20, 0, 1,0);
        String jsonString = JSON.toJSONString(expect);
        TcpPackage actual = JSON.parseObject(jsonString, TcpPackage.class);
        assertEquals(expect, actual);
    }
```

but can't pass my test case.
and i use debugger find flagSYN will be parse to zero

![](https://tva1.sinaimg.cn/large/00831rSTly1gd53zso3iej30rg06qjs4.jpg)
![](https://tva1.sinaimg.cn/large/00831rSTly1gd53zvgkjdj30x003smye.jpg)

Is i using wrong api in fastjson? or it is a bug ?

if you want easily to reproduce this exception you can clone my code base project 

https://github.com/xiantang/codebase

and run this test case 

https://github.com/xiantang/codebase/blob/18cff46a598d7fd6b13ec4b6a387e5f7343f8315/messagequeue/src/test/java/info/xiantang/messagequeue/kafka/TcpClientTest.java#L57

**Comment by xiantang** [comment]
I dont know why github markdown can't rendering sina image.
https://tva1.sinaimg.cn/large/00831rSTly1gd53zso3iej30rg06qjs4.jpg
https://tva1.sinaimg.cn/large/00831rSTly1gd53zvgkjdj30x003smye.jpg

**Comment by wenshao** [comment]
TcpPackage need a default constructor
