### ISSUE TITLE
无法解析key为is开头的Bean

### ISSUE THREAD

**Issue by zwping** [alibaba/fastjson#3083]
` kotlin

    class TestBean {
        var is_subscribe = 0
        var subscribe = 0
        var isHave = 0
    }

    val s = "{'is_subscribe':1,'subscribe':1,'isHave':1}"
    val b = JSON.parseObject(s, TestBean::class.java)
    println("${b.is_subscribe}--${b.subscribe}--${b.isHave}")
`
> 运行结果 System.out: 0--1--0
> 预期结果 System.out: 1--1--1

**Comment by zwping** [comment]
对比Gson，Gson则不会出现该问题

**Comment by hais1992** [comment]
救救你~~~，  我经常碰到，后端又不肯改-.-
![1111123.png](https://i.loli.net/2020/04/02/28ihxcet7PEMwfg.png)

**Comment by zwping** [comment]
@hais1992 将bean退回至java语言，FastJson既可识别is开头的键值对
