### ISSUE TITLE
Fastjson 1.2.67版本刚刚发布即爆出严重漏洞

### ISSUE THREAD

**Issue by wchaowu** [alibaba/fastjson#3085]
https://www.csdn.net/article/a/2020-03-24/15989312

**Comment by LeadroyaL** [comment]
确定不是硬广？

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/77519410-64a92300-6eba-11ea-8bf7-64726507ecc1.png)

看起来已经有新的blacklist了

**Comment by rufushuang** [comment]
又是autotype
建议是否考虑直接创建一个，肯定无法开启autotype的分支算了？

**Comment by bad-boy1** [comment]
> 建议是否考虑直接创建一个，肯定无法开启autotype的分支算了

基于白名单方式，也有可能有影响，在将JNDI相关类配置到白名单中时，依赖相关组件同样可以造成反序列漏洞，只是这种场景比较少，但还是需要排查。

**Comment by huangxfchn** [comment]
一般框架都没有开启 autoType 的，不必恐慌

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
问题已修复，请用新版本

**Comment by huangxfchn** [comment]
温少辛苦了

**Comment by huangxfchn** [comment]
> https://github.com/alibaba/fastjson/releases/tag/1.2.68
> 问题已修复，请用新版本

温少辛苦了
