### ISSUE TITLE
低版本的不使用autoType功能的用户，需要做版本升级吗

### ISSUE THREAD

**Issue by songzhijian** [alibaba/fastjson#3086]
如果需要升级的话，60版本能直接升到67吗

**Comment by songzhijian** [comment]
如果需要升级的话，60版本能直接升到67吗

**Comment by threedr3am** [comment]
小于1.2.66非sec09版本的都存在DOS漏洞

**Comment by songzhijian** [comment]
> 小于1.2.66非sec09版本的都存在DOS漏洞

关闭autotype功能也不可以吗？ 67版本不是只增加了黑名单吗？

**Comment by gitworldhero** [comment]
> 如果需要升级的话，60版本能直接升到67吗

不使用autotype不受影响，1.2.60无需升级

**Comment by songzhijian** [comment]
> > 如果需要升级的话，60版本能直接升到67吗
> 
> 不使用autotype不受影响，1.2.60无需升级

多谢！！

**Comment by threedr3am** [comment]
@gitworldhero 不是说了1.2.66及以下存在DOS漏洞？怎么还建议别人不升级？？
