### ISSUE TITLE
Android混淆存在许多问题

### ISSUE THREAD

**Issue by huhuang03** [alibaba/fastjson#309]
如果将一个类混淆，如User
则Json.toJsonString(user),和Json.parseObject(userstring,User.class)存在一系列问题，完全不可以用

**Comment by KennethYo** [comment]
我觉得model不需要混淆吧，你混淆了，还怎么序列化和反序列化。

**Comment by LyndonChin** [comment]
```
parseObject(yourData, User.class)
```

这里的 `User.class` 一定要在 Proguard 中 keep -class，防止被混淆掉。
fastjson是通过反射拿到成员变量的，混淆过之后变量名都变了，还怎么反序列化啊。

**Comment by huhuang03** [comment]
额。那就是这个原因了，个人感觉为什么我的变量名变了，就不能使用反射了。我的理解是fastjson并不应该关注我的变量名是什么以及是否被混淆了，对fastjson来说变量名就是一个字符串。所以我混淆之后就不能正常工作了，对这点不是很理解。
当然，我只是一个小菜鸟，这只是个人的一点理解。。

**Comment by KennethYo** [comment]
例如如下这个json，是一个JsonObject，对应在如下的model,这是一种能够用fastjson解析的格式，如果model被混淆，就变成最下面的那份代码，fastjson就不能够用a去映射json中的name了。
```json
{
   name:"Kenneth",
   age:12
}
```
```java
//混淆前
class User{
  public String name;
  public int age;
}
//混淆后
class User{
  public String a;
  public int b;
}
```

**Comment by wenshao** [comment]
无法解决，先关闭啦

**Comment by fitseptor** [comment]
类似这样
-keep class your_project_package_name.model.**{*;}
