### ISSUE TITLE
JSONObject.containsKey判断问题

### ISSUE THREAD

**Issue by dugenkui03** [alibaba/fastjson#3093]
String jsonStr = "{1:1}";
        JSONObject jsonObject = JSONObject.parseObject(jsonStr);
        System.out.println(jsonObject.containsKey(1));//false
        System.out.println(jsonObject.get(1));//can get value

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
问题已修复，请用新版本
