### ISSUE TITLE
fastjson < 1.2.66 版本存在拒绝服务漏洞

### ISSUE THREAD

**Issue by iSafeBlue** [alibaba/fastjson#3096]
影响范围：**1.2.36 - 1.2.62**

只要使用版本在影响范围就存在漏洞，目前版本>=1.2.66不受影响。

漏洞分析过程：https://b1ue.cn/archives/314.html

**Comment by wenshao** [comment]
已知问题，已修复，谢谢反馈

**Comment by coffeehb** [comment]
哈哈，这个已知问题很强大。。需要预警了
