### ISSUE TITLE
使用StreamAPI情况下，无法序列化特殊字符的bug

### ISSUE THREAD

**Issue by locuslin** [alibaba/fastjson#310]
你好！
        我们在使用FastJSON作为我们内部RPC框架的JSON序列化方案的主要实现，现在发现线上偶然间会出现序列化失败的情况。我们将这些异常的对象从线上dump下来，然后本地重现debug了一下，发现了FastJSON可能存在BUG，特此向你反映,问题具体描述如下：
	
	运行环境如下
Mac OS X 10.10.2    	JDK 1.7.0_67-b01
CentOS release 6.5	       JDK  1.7.0_55-b13

序列化对象的代码如下
```java
	private String doStreamSerialization(Object obj) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        JSONWriter writer = new JSONWriter(new OutputStreamWriter(baos, Charset.forName("UTF-8").newEncoder()));
        writer.config(SerializerFeature.WriteNonStringKeyAsString, true);
        writer.config(SerializerFeature.SkipTransientField, true);
        writer.config(SerializerFeature.SortField, false);
        writer.config(SerializerFeature.WriteEnumUsingToString, true);
        writer.config(SerializerFeature.DisableCircularReferenceDetect, true);
        writer.config(SerializerFeature.WriteMapNullValue, true);
        writer.writeObject(obj);
        writer.flush();
        writer.close();
        return baos.toString("UTF-8");
    }

```

在序列化某一个特定对象的时候，出现异常的case如下

序列化方式	                 待序列化的对象	                 结果
doStreamSerialization	 Result,包含Map	                 异常
doStreamSerialization	Map,包含若干对象	                 异常
doStreamSerialization	Map，仅包含出现异常的XdItem对象	正常
doStreamSerialization	仅出现异常的XdItem对象	正常
JSON.toString	                 Map	                                 正常
JSON.toString	                 XdItem对象	                         正常

且异常并不是必现的，人肉估计有1/5的概率能够正常通过。
为了定位偶现的原因，做了以下case的测试

case	                                                          结果
单线程执行2000次	                                  全部异常或全部正常
多线程并行，每个线程执行2000次	          全部异常或全部正常
单线程间隔执行2000次	                          全部异常或全部正常
多线程并行，每个线程间隔执行2000次	  全部异常或全部正常

猜测可能跟线程或时间无关。

异常对象的相关信息如下:
	在Map中的key为: 210844777
	出现异常的字符为\u00A0 
	对应的为XdItem中的description字段的第13个字符

出现异常的异常栈为

java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:668) ~[fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValueStringWithDoubleQuote(SerializeWriter.java:1217) ~[fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValue(SerializeWriter.java:1185) ~[fastjson-1.2.4.jar:na]
	at Serializer_1.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:183) ~[fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:361) ~[fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.JSONWriter.writeObject(JSONWriter.java:61) ~[fastjson-1.2.4.jar:na]

	出现问题的代码在此处
```java
	                        if (ch < IOUtils.specicalFlags_doubleQuotes.length
	                            && IOUtils.specicalFlags_doubleQuotes[ch] != 0 //
	                            || (ch == '/' && isEnabled(SerializerFeature.WriteSlashAsSpecial))) {
	                            write('\\');
	                            write(replaceChars[(int) ch]);
	                            continue;
	                        }
```	
	replaceChars 中并没有ch=160时所对应要的转移好的字符。
	
	在不出现异常的情况下，发现调用栈与上述异常的调用栈不同。

	调试发现，关系异常是否出现的点在于此处：

	com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValueStringWithDoubleQuote() line:1213

```java
	 if (newcount > buf.length) {
            if (writer != null) {
                write(seperator);
                writeStringWithDoubleQuote(name, ':', checkSpecial);
                writeStringWithDoubleQuote(value, (char) 0, checkSpecial);
                return;
            }
            expandCapacity(newcount);
        }
```
	
若newcount 大于buf的长度时，则就会调用writeStringWithDoubleQuote方法，就会出现异常；当遇到包含会出错的字符串时，newcount 小于buf的长度，则不会出现异常。
	
如果需要dump出来的异常的case代码或是其他支持，请联系我:mozhu@mogujie.com。
	
希望能在百忙之中抽出时间解决该问题，并给我们一个答复，谢谢。

**Comment by wenshao** [comment]
谢谢反馈问题，会尽快推进解决

**Comment by wenshao** [comment]
如locuslin所反馈，问题已经修复，先关闭啦，如果哟问题再反馈
