### ISSUE TITLE
1.2.67版本java.lang.NoSuchMethodError: java.lang.reflect.Type.getTypeName异常

### ISSUE THREAD

**Issue by BarbaPedro** [alibaba/fastjson#3102]
在部分低版本手机上JDK是1.7，会出现如下异常，高版本的手机没问题，望能兼容提供修复版本，感谢。
03-30 14:44:22.994 E/AndroidRuntime( 2740): FATAL EXCEPTION: main
03-30 14:44:22.994 E/AndroidRuntime( 2740): Process: demo, PID: 2740
03-30 14:44:22.994 E/AndroidRuntime( 2740): java.lang.NoSuchMethodError: java.lang.reflect.Type.getTypeName
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:32)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:85)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:822)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:288)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:776)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:710)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:705)
03-30 14:44:22.994 E/AndroidRuntime( 2740): 	at com.alibaba.fastjson.JSON.parseArray(JSON.java:593)

**Comment by wenshao** [comment]
1.2.68已修复此问题，android版本建议使用1.1.71.android版本
