### ISSUE TITLE
移除了黑名单 0xD9C9DBF6BBD27BB1L ？ com.ibatis.sqlmap.engine.datasource

### ISSUE THREAD

**Issue by jax777** [alibaba/fastjson#3105]
移除了黑名单 0xD9C9DBF6BBD27BB1L ？ com.ibatis.sqlmap.engine.datasource

对比发现1.2.67  denyHashCodes 移除了 0xD9C9DBF6BBD27BB1L? 发生了什么

**Comment by jax777** [comment]
https://github.com/alibaba/fastjson/commit/78881ef57802eba763745882e0f62b3d9fe65407#diff-8530042da868de31d70b53576c1afdb2

**Comment by qixiaobo** [comment]
https://github.com/alibaba/fastjson/commit/90ded9e5b6c215a042673c8a7a2c30bc7c73bb1b#diff-8530042da868de31d70b53576c1afdb2L215

**Comment by wenshao** [comment]
做了更大范围的黑名单
