### ISSUE TITLE
can not cast to Timestamp, value : 1970-01-01 00:00:00

### ISSUE THREAD

**Issue by zhibo6** [alibaba/fastjson#3121]
`public class TimeDemo {
    public static void main(String[] args) {
        try {
            String time = "1970-01-01 00:00:00";
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("time", time);

            Timestamp timestamp = jsonObject.getTimestamp("time");
            System.out.println("time:" + timestamp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}`

执行如上代码，报错：
`com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 1970-01-01 00:00:00
	at com.alibaba.fastjson.util.TypeUtils.castToTimestamp(TypeUtils.java:665)
	at com.alibaba.fastjson.JSONObject.getTimestamp(JSONObject.java:339)
	at org.learn.time.TimeDemo.main(TimeDemo.java:21)`

根据 TypeUtils 源码发现，当时间为“1970-01-01 00:00:00”，则longValue =0，此时判定语句会抛出异常，当时的等于0是出于什么原因考虑的，是否可以改为小于0.
`        if(longValue <= 0){
            throw new JSONException("can not cast to Timestamp, value : " + value);
        }
`

**Comment by renyineng** [comment]
我也遇到了这样的问题

**Comment by zhibo6** [comment]
#3122

**Comment by sharpshoes** [comment]
阅读了源代码，不支持通过string转换成timestamp
