### ISSUE TITLE
JSON类中的toJSONString，某些方法里夹带私货。。。

### ISSUE THREAD

**Issue by axeon** [alibaba/fastjson#314]
私货如下：
serializer.config(SerializerFeature.WriteDateUseDateFormat, true);

我认为，一切预定义都应该存在于JSON.DEFAULT_GENERATE_FEATURE，因为上面那行私货，导致了很多麻烦！

建议去掉。

**Comment by wenshao** [comment]
已经解决，谢谢反馈
