### ISSUE TITLE
map 转json的时候 时间类型转成了 数字  不是时间字符串？

### ISSUE THREAD

**Issue by Dreampie** [alibaba/fastjson#316]
![t mx9 q z2e oea04 0p s](https://cloud.githubusercontent.com/assets/3667080/7106009/33352936-e166-11e4-8446-1d9ef9822ab2.jpg)

![aqk5 yhwn i 5 q8_v cp](https://cloud.githubusercontent.com/assets/3667080/7106090/ff83e94e-e168-11e4-99a7-fafcc593ad48.jpg)

**Comment by Dreampie** [comment]
是不支持 java.sql.Timestamp

**Comment by wenshao** [comment]
缺省就是这样，如果你需要输出字符串，参考这里 https://github.com/alibaba/fastjson/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 第8点
