### ISSUE TITLE
{"$ref":"$"}

### ISSUE THREAD

**Issue by leoye** [alibaba/fastjson#317]
{"children":[{"children":[],"create_date":1428854400000,"modified_date":1428854400000,"parent":{"$ref":"$"},"treeNodeName":"BB","tree_id":2,"valid":true},{"children":[],"create_date":1428854400000,"modified_date":1428854400000,"parent":{"$ref":"$"},"treeNodeName":"CC","tree_id":3,"valid":true}],"create_date":1428854400000,"modified_date":1428854400000,"treeNodeName":"AA","tree_id":1,"valid":true}
序列化

**Comment by nesuk** [comment]
序列号的对象引用层次比较深时会出现这种问题。 期待解决！

**Comment by wenshao** [comment]
```java
JSON.toJSONString(obj, SerializerFeature.DisableCircularReferenceDetect)
```
