### ISSUE TITLE
#

### ISSUE THREAD

**Issue by wcc526** [alibaba/fastjson#3187]
【安全通告】Fastjson <=1.2.68全版本远程代码执行漏洞通告

https://cloud.tencent.com/announce/detail/1112?from=timeline&isappinstalled=0

**Comment by fackjson** [comment]
太不要脸了  偷偷修 然后不告诉别人 是不是要入侵人家公司啊 自己写的后门么

**Comment by fackjson** [comment]
老哥咋怂了  律师函警告了么？

**Comment by fakejson** [comment]
律师函警告
