### ISSUE TITLE
不要个碧莲了  修复漏洞不公告留后门？ 大家别用了

### ISSUE THREAD

**Issue by fackjson** [alibaba/fastjson#3189]
太不要脸了  偷偷修 然后不告诉别人 是不是要入侵人家公司啊 自己写的后门么

**Comment by wenshao** [comment]
修复版本已经在验证，最近几天就会发布，预计在周一

**Comment by djsousuo** [comment]
没必要这么恶语相向吧

**Comment by fackjson** [comment]
@djsousuo   你来这当圣母来了   这叫恶语相向么  要是补天不发公告  大家都不知道  留着hw用吧  我看你们是一伙的吧

**Comment by fakejson** [comment]
@djsousuo 哪里来的圣母玛丽亚，只能说补天的牛逼啊，这都能知道

**Comment by huifrank** [comment]
> 修复版本已经在验证，最近几天就会发布，预计在周一

会有sec版本吗？ 全升级到最新版老系统怕是活不成啊

**Comment by wenshao** [comment]
fastjson安全公告
https://github.com/alibaba/fastjson/wiki/security_update_20200601
