### ISSUE TITLE
JSONReader从socket流中读取的问题

### ISSUE THREAD

**Issue by Kilnn** [alibaba/fastjson#319]
JSONReader在从文件流中读取readObject没有问题，但是从socket流读取的时候，因为socket连接后，服务端开始写数据。
客户端用JSONReader.readObject 获取，读到的数据总是延迟一帧。也就是说服务端写第二帧数据的时候，客户端才能readObject 到第一帧的数据。
我不知道用什么方法能解决这个问题。

**Comment by wenshao** [comment]
这个问题无法通过fastjson解决吧，先关闭啦
