### ISSUE TITLE
被爆出来就必须要修了，不然留着hw多舒服

### ISSUE THREAD

**Issue by fakejson** [alibaba/fastjson#3191]
被爆出来就必须要修了，不然留着hw多舒服

**Comment by prayjourney** [comment]
- [ ] 

- [ ] 这是什么梗？

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
