### ISSUE TITLE
请问1.2.69什么时候发布，HW准备来了

### ISSUE THREAD

**Issue by steward007** [alibaba/fastjson#3195]
请问1.2.69什么时候发布

**Comment by wenshao** [comment]
已经在验证，最近几天就会发布

**Comment by songjiang951130** [comment]
hw 是啥

**Comment by sevencitys** [comment]
> hw 是啥

huwang

**Comment by eric-wang95** [comment]
> 已经在验证，最近几天就会发布

序列化Iterable，传参 SerializerFeature.WriteClassName，导致空指针。这个问题有考虑修复吗：D

**Comment by MoonLord-LM** [comment]
> huwang

huwang 是啥

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
