### ISSUE TITLE
这个洞利用是不是可以绕过autotype关闭的情况？？

### ISSUE THREAD

**Issue by y360u** [alibaba/fastjson#3196]
看修复方式是设置safemode猜测

**Comment by 0linlin0** [comment]
看玄武发的公告的意思好像是，原本不能反序列化的类，链式的被反序列化了，黑名单里的类又活过来了？看了半天代码，不晓得大佬是怎么操作的....疯狂来刷新github....

**Comment by shadow-horse** [comment]
这就尴尬了~

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
