### ISSUE TITLE
升级1.2.68，开启 SafeMode后，JSON串包含@type会转换对象失败，如何处理

### ISSUE THREAD

**Issue by Liaozhi1994** [alibaba/fastjson#3201]
例如{"@type":"java.util.LinkedHashMap","barcode":"510998715202072226598","storeId":"20122707"}反序列化失败

**Comment by xukaixi11** [comment]
我也遇到这样的问题了，求解

**Comment by berekqu** [comment]
我也遇到这样的问题，1.2.68的修复方式直接抛出异常，含@type直接异常，看下来无解。修复得迁移数据删除@type。求解。

**Comment by dwangddd** [comment]
我也是，被困住了

**Comment by MHhw1234** [comment]
求解求解

**Comment by lvbowei123** [comment]
我也遇到这样的问题了，想早点下班，求解

**Comment by bad-boy1** [comment]
开启safemode后，本身就不能使用@type这个能力了。safemode的设计初衷就是这样，所以在安全公告的时候都会提示考虑业务本身的影响

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
