### ISSUE TITLE
升级1.2.68，开启 SafeMode后，JSON串包含@type会转换对象失败，如何处理

### ISSUE THREAD

**Issue by xukaixi11** [alibaba/fastjson#3202]

**Comment by xukaixi11** [comment]
例如{"@type":"java.util.LinkedHashMap","barcode":"510998715202072226598","storeId":"20122707"}反序列化失败

**Comment by dwangddd** [comment]
我也是

**Comment by huifrank** [comment]
autoType就是这个功能 json里面带一个@type属性，反序列化的时候可以直接转成对应的对象 。你开启SafeMode会把authType给禁用掉。

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
