### ISSUE TITLE
每隔几个月就曝一次安全漏洞,很心累

### ISSUE THREAD

**Issue by treeleafj** [alibaba/fastjson#3203]
温少大大麻烦安全这块多考虑考虑,这边存量项目使用了fastjson,这几年每隔几个月就要升级几十个不同客户几百台机器,很累的...

**Comment by johnyannj** [comment]
please consider change to jackson or gson

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
