### ISSUE TITLE
Fastjson <= 1.2.68远程代码执行漏洞

### ISSUE THREAD

**Issue by Zeeman206** [alibaba/fastjson#3204]
http://blog.nsfocus.net/fastjson-0528/

近日，绿盟科技监测到有消息称Fastjson<=1.2.68版本中存在一个高危漏洞。攻击者可以绕过autotype限制，但必须利用不在黑名单中的gadgets，实际造成的危害与利用的gadgets有关。

**Comment by coderlongren** [comment]
哈哈 阿里对fastJson漏洞早已见怪不怪了。

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
