### ISSUE TITLE
Fastjson means the json of need fast upgrade version???

### ISSUE THREAD

**Issue by SevenLM361** [alibaba/fastjson#3205]
wtf...

**Comment by jiaminghai** [comment]
haha

**Comment by furaul** [comment]
Congratulations! You got the point.

**Comment by wenshao** [comment]
安全公告 https://github.com/alibaba/fastjson/wiki/security_update_20200601
1.2.69 https://github.com/alibaba/fastjson/releases/tag/1.2.69
1.2.79 https://github.com/alibaba/fastjson/releases/tag/1.2.70
