### ISSUE TITLE
请问SafeMode的三种配置方法谁的优先级最高

### ISSUE THREAD

**Issue by k4n5ha0** [alibaba/fastjson#3211]
1. 在代码中配置
ParserConfig.getGlobalInstance().setSafeMode(true); 
2. 加上JVM启动参数
    -Dfastjson.parser.safeMode=true 

3. 通过fastjson.properties文件配置。
通过类路径的fastjson.properties文件来配置
fastjson.parser.safeMode=true

请问三种的配置优先度谁最高？
如果有些开发人员一会儿配个true，又在代码里false，有什么办法保证一定是打开safemode的配置方法？
谢谢

**Comment by 8caomei** [comment]
测试用了一下，好像-Dfastjson.parser.safeMode=true这个比代码里优先级高

**Comment by yejg** [comment]
【-Dfastjson.parser.safeMode=true】优先级高
这个 升级到 1.2.69 版本就可以了吧？
https://help.aliyun.com/noticelist/articleid/1060343604.html

**Comment by 8caomei** [comment]
> 【-Dfastjson.parser.safeMode=true】优先级高
> 这个 升级到 1.2.69 版本就可以了吧？
> https://help.aliyun.com/noticelist/articleid/1060343604.html
1.2.70升级、其他低版本可以考虑升级到sec10 安全补丁版本
https://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.70/

**Comment by zhangshuge** [comment]
fastjson.properties这个配置文件应该放在哪个路径下，跟路径都试了一遍，没有生效啊。

**Comment by liu-a-wei** [comment]
升级了版本这个还要配置么？

**Comment by forzjing** [comment]
> fastjson.properties这个配置文件应该放在哪个路径下，跟路径都试了一遍，没有生效啊。

同问

**Comment by beixiaolu** [comment]
fastjson升级到1.2.70版本，还有配置safeMode吗

**Comment by zhangshuge** [comment]
> > fastjson.properties这个配置文件应该放在哪个路径下，跟路径都试了一遍，没有生效啊。
> 
> 同问

放到web模块的resources/下面就可以了，我升级到1.2.69版本，通过fastjson.properties配置文件是生效了的。

**Comment by Doubiwan** [comment]
> > > fastjson.properties这个配置文件应该放在哪个路径下，跟路径都试了一遍，没有生效啊。
> > 
> > 
> > 同问
> 
> 放到web模块的resources/下面就可以了，我升级到1.2.69版本，通过fastjson.properties配置文件是生效了的。

请问您是如何验证safeMode已生效的

**Comment by xuhongliang1996** [comment]
> > > > fastjson.properties这个配置文件应该放在路径下，跟路径都试一遍，没有生效啊。
> > > 
> > > 
> > > 同问
> > 
> > 
> > 放到web模块的资源/下面就可以了，我升级到1.2.69版本，通过fastjson.properties配置文件是生效了的。
> 
> 请问您是如何验证safeMode已生效的@zhangshuge

boolean safeMode = ParserConfig.getGlobalInstance().isSafeMode();
