### ISSUE TITLE
开启safemode之后是不是就不需要升级版本了

### ISSUE THREAD

**Issue by bad-boy1** [alibaba/fastjson#3212]
开启safemode之后完全禁用autotype，近期的绕过黑名单gadgets和auotype bypass则都可以避免。不考虑新版本增加的功能和修复的bug，只关注安全漏洞的情况下，开启safemode是不是可以完全避免以前的问题？

**Comment by bad-boy1** [comment]
@wenshao 温少

**Comment by wenshao** [comment]
safeMode打开之后，不用因为安全原因升级新版本
