### ISSUE TITLE
1.2.70要不要开safemode？！

### ISSUE THREAD

**Issue by daisy-x** [alibaba/fastjson#3214]

**Comment by songjiang951130** [comment]
同问啊，我看1.2.69，默认没有打开safemode。有必要设置 safemode = true？

**Comment by wenshao** [comment]
safeMode都不是缺省打开的，1.2.69 & 1.2.70都修复了这次发现的高危漏洞，safeMode打开是完全关闭autoType功能，更加安全，预防后续有类似问题再次发生。
