### ISSUE TITLE
kotlin 1.2.70属性会为null

### ISSUE THREAD

**Issue by 900emperor** [alibaba/fastjson#3223]
kotlin在1.2.68的时候，反序列化成java对象正常。1.2.70版本，转为list和set类型的属性的时候会是null
有没有自测过？？有点责任好不好

**Comment by stirp** [comment]
帮忙提供一个复现方法：
class TestObj{
    var filterType: Int? = null
    var searchArg: JSONObject? = null
}

fun main() {
    println(JSON.toJSONString(JSON.parseObject("{\"M8\":\"Redmi 7A\",\"filterType\":2,\"searchArg\":{\"employeeID\":\"1065\",\"feedType\":0,\"limit\":10}}", TestObj::class.java)))
}

执行结果：

{"filterType":2}

**Comment by wenshao** [comment]
很抱歉，kotlin测试不充分，问题已修复，预计这个周末回发布新版本

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.71
