### ISSUE TITLE
1.2.69，1.2.70版本不用打开安全模式就能解决高危漏洞吧？

### ISSUE THREAD

**Issue by xychq00** [alibaba/fastjson#3229]
只升级版本就行了吧？

**Comment by qingdengyue** [comment]
还是要设置的、

**Comment by xychq00** [comment]
> 还是要设置的、

我看这个文档的意思是新版本已经解决高危漏洞了，要是打开safeMode（禁止了autoType）能更好的防止类似的漏洞。
https://github.com/alibaba/fastjson/wiki/security_update_20200601

**Comment by zhanjunfeng** [comment]
mark，看完了文档也不确定是不是升级后还要开启安全模式

**Comment by JalenLeeCN** [comment]
>=1.2.68的版本引入了safeMode, 可以通过这个模式禁止autoType, 但是还是需要配置, 可以用ParserConfig.getGlobalInstance().isSafeMode();验证

**Comment by wenshao** [comment]
1.2.69版本已经修复此次发现的高危漏洞，safeMode是提供完全关闭autoType的选项。

**Comment by Luke-Ruan** [comment]
可是我们项目升到70版本，还可以用@type来触发checkAutoType 函数，现在还在排查中呢
