### ISSUE TITLE
1.2.69和1.2.70不兼容jdk5的问题

### ISSUE THREAD

**Issue by geyaoAlone** [alibaba/fastjson#3230]
Java.lang.UnsupportedClassVersionError:Bad version number in .class file
就简单的使用JSON.parseObject或者JSON.toJSONString

**Comment by wenshao** [comment]
将会在这个周末发布版本修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.71
使用这个版本试试看
