### ISSUE TITLE
请问原地升级sec10版本，就是把fastjson的jar替换成fastjosn-sec10的jar包吗

### ISSUE THREAD

**Issue by frhui** [alibaba/fastjson#3233]
由升级到最新版本，导致有些功能无法使用，原地升级sec10版本，就是把fastjson的jar替换成fastjosn-sec10的jar包吗？

**Comment by guopengd** [comment]
如果你不是用maven管理依赖而是直接工程下copy依赖的jar包进lib的话，那是的，maven的话只要在版本后加.sec10

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/security_update_20200601
