### ISSUE TITLE
请问升级到了1.2.70还需要自己去显示设置打开安全模式才能避免漏洞问题吗

### ISSUE THREAD

**Issue by huzhekun1** [alibaba/fastjson#3236]
请问是否升级到1.2.70版本无需打开安全模式 也能避免漏洞问题

**Comment by wenshao** [comment]
1.2.70已经修复所有已知漏洞。safeMode是完全关闭autoType功能，避免类似问题再次发生。

**Comment by roneywei** [comment]
如果升级到1.2.70，就不需要去设置safeMode是吧
