### ISSUE TITLE
你好，我提两个问题，下划线无法关闭，1.2.61没有sec10版本

### ISSUE THREAD

**Issue by bigriverhorse** [alibaba/fastjson#3237]
问题一：
fastjson 1.2.62版本
支持$和_开头字段 [#2762](https://github.com/alibaba/fastjson/pull/2762)

这个问题导致我们无法升级到1.2.62+版本，有没有办法可以做个配置，可以选择性关闭这个功能

问题二：
如果不能升级1.2.62+版本，请在1.2.61提供sec10版本，2020-06-05时只有1.2.60的sec10版本

**Comment by wenshao** [comment]
https://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.2.61.sec10/
已提供1.2.61.sec10版本
