### ISSUE TITLE
建议发布一个fastjson空包

### ISSUE THREAD

**Issue by zhuhengwei** [alibaba/fastjson#3247]
项目引入该空包,以彻底杜绝fastjson代码的再次引入,给我们一个选择,谢谢

**Comment by ChangRuihe** [comment]
发生了什么？

**Comment by zhuhengwei** [comment]
开始推去fastjson了,为了杜绝意外的间接依赖

**Comment by c332030** [comment]
maven-enforcer-plugin 不是可以做到吗？

**Comment by fangjinuo** [comment]
空包不需要，你需要的是这个：
https://github.com/fangjinuo/easyjson

**Comment by zhuhengwei** [comment]
哎 官方那么随意的就关了issue?不给点解释?
