### ISSUE TITLE
这个项目已经到头了

### ISSUE THREAD

**Issue by lewe518** [alibaba/fastjson#3249]
每次出现漏洞都是我们一顿升级，项目稳定性太差了。

目前公司已经在全面去fastjson了，这个项目已经到头了。

**Comment by wenshao** [comment]
很抱歉给你带来麻烦，如果升级遇到问题来反馈

**Comment by wenshao** [comment]
新版本已经提供完全关闭autoType的功能 https://github.com/alibaba/fastjson/wiki/fastjson_safemode

关闭safeMode功能后，类似的问题就不会再发生，通过打开safeMode比更换类库应该是更好的解决方案。

**Comment by fangjinuo** [comment]
> 每次出现漏洞都是我们一顿升级，项目稳定性太差了。
> 
> 目前公司已经在全面去fastjson了，这个项目已经到头了。

了解一下这个：
https://github.com/fangjinuo/easyjson

**Comment by zhaohuihua** [comment]
我们也在讨论去fastjson了，客户方的领导不关心什么safeMode，只会看到通报出来的漏洞！

**Comment by zhaohuihua** [comment]
我们也在讨论去fastjson了，客户方的领导不太关心技术细节，只看到通报出来的漏洞

**Comment by ufan0** [comment]
国人出一款强大的开源软件着实不易，同时也需要更多的人参与进来维护啊。

**Comment by AlanSune** [comment]
抱怨归抱怨，人家开源的项目让你免费使用，说的什么鬼话，真是丢人。

**Comment by HarLin97** [comment]
没爆出来的时候，你怎么不测试，你自己都不去找问题，也不知道怎么修复，就来乱说一通
