### ISSUE TITLE
parseArray不支持传入ParserConfig

### ISSUE THREAD

**Issue by jiawulin001** [alibaba/fastjson#3254]
我现在只能拿出全局的修改了，反序列化完后又赶紧还原回去，但是当我另一个功能和这个同时被调用了就会报错，因为另一个功能不能使用这个设置，希望尽快开放接口允许传入ParseConfig

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.71
问题修复了
