### ISSUE TITLE
Kotlin fastjson 序列化有问题

### ISSUE THREAD

**Issue by hahalixiaojing** [alibaba/fastjson#3264]
class MyData(
        @JSONField(name = "is_test")
        var isTest: Boolean = false
    )

val also = MyData().also {
            it.isTest = true
        }

        val toJSONString = JSON.toJSONString(also)

toJSONString  序列化出来的是 {"test":true} ，不是is_test 了。你这bug也坑人了吧，没有测试吗？

**Comment by ZivYan** [comment]
能提供 version 么

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.72
问题已修复，请用新版本
