### ISSUE TITLE
Future Require: Better Enum Serialize & Deserialize

### ISSUE THREAD

**Issue by guyeu** [alibaba/fastjson#3266]
有一个常规需求，是在接口协议中定义枚举属性，但传输和数据落地时的数据中使用一个代表改枚举值的数字，如果使用jackson，我很容易就能实现这样的枚举。
举例如下：
```java
public enum SomeType {
    ;
    private final int code;
    @JsonValue
    public int getCode() {
        return code;
    }
    @JsonCreator
    public static SomeType from(int code) {
        for (var v : values()) {
            if (v.code == code) {
                return v;
            }
        }
        throw new IllegalArgumentException("code " + code);
    }
}
```

但使用fastjson，要实现这样的枚举就要额外编写很多的序列化和反序列化的垃圾代码，希望fastjson能提供类似的功能。

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.71

新的定制序列化反序列化方法：
https://github.com/alibaba/fastjson/wiki/enum_custom_serialization

具体看方法4和方法5
