### ISSUE TITLE
JSONValidator解析规则有遗漏

### ISSUE THREAD

**Issue by edeye** [alibaba/fastjson#3267]
代码:
		JSONValidator jv = JSONValidator.from("113{}[]");
		System.out.println(jv.validate()); //输出为true
		System.out.println(jv.getType()); //输出为Array

版本:
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.70</version>
		</dependency>

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/enum_custom_serialization
问题修复，请用新版本
