### ISSUE TITLE
1.2.60因漏洞想升级，升级哪个版本没有兼容性问题？

### ISSUE THREAD

**Issue by LeePui** [alibaba/fastjson#3270]

**Comment by LeePui** [comment]
我看到官方有一个1.2.60.sec10版本，我现在想升级这个版本，请问官方确认没有兼容性问题不？或者能否告知有无测试的方法？

**Comment by LeePui** [comment]
还有一个版本的问题也请教一下，1.2.41这个，是升级到1.2.4.sec10，还是1.2.48.sec10呢？最重要是升级哪个没有兼容性问题

**Comment by wenshao** [comment]
```java
1.2.60 -> 1.2.260.sec10
1.2.41 -> 1.2.48.sec10
```
提供小版本升级就是为兼容
