### ISSUE TITLE
如何解析字符串中带有反斜杠的情况

### ISSUE THREAD

**Issue by yinwenjian** [alibaba/fastjson#3275]
我接受到上游传输的数据是一个字符串，我需要把他转换成json遍历，但是字符串中包含反斜杠，所以在JSONObject.parseObject（）的时候抛出了异常，但是这是一个被认为正常的数据。
想知道怎么解决这个问题！
代码入下所示：
![image](https://user-images.githubusercontent.com/41369584/84756758-cbd7fe80-aff5-11ea-9a3d-f9eefe215141.png)
异常：
![image](https://user-images.githubusercontent.com/41369584/84756818-e14d2880-aff5-11ea-96a2-d157018d6066.png)

**Comment by WhaleFall22** [comment]
这个问题13年 就有人提出来了。。。
https://github.com/alibaba/fastjson/issues/103

**Comment by yinwenjian** [comment]
愚蠢的问题，可以反序列化的前提是没有语法错误。
