### ISSUE TITLE
从1.2.69版本开始，ParserConfig.getGlobalInstance().putDeserializer(String.class, new TrimStringDeserializer());失效了

### ISSUE THREAD

**Issue by llsi4275** [alibaba/fastjson#3279]
从1.2.69版本开始，在反序列化时，使用ParserConfig.getGlobalInstance().putDeserializer(String.class, new TrimStringDeserializer());方式对全局的字符串处理不生效了，调用不到了。。。

我们从1.2.60版本使用这个功能，最近换成新版本后，发现失效了...
试了1.2.60-1.2.68之间的所有版本都可以使用。但换成1.2.69之后，就无法使用了。

如果到每个字段上去写，太麻烦，也太low了一点，有没有其它办法呢？

**Comment by llsi4275** [comment]
在每个字段上加@JsonField(trimXX)的方式有点辍，而且也没法归一化处理.

**Comment by llsi4275** [comment]
@Omega-Ariston

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.72
问题已修复，请用新版本

**Comment by llsi4275** [comment]
@wenshao 
似乎没有启到作用：



json参数为：
![Uploading image.png…]()


传入参数：
{
	"name": "张三   ",
	"phone": "李四   ",
	"skill": "java   ",
	"recruitment": 4,
	"region": "Chengdu   ",
	"workingYears": "3.5    "
}，
仅recruitment进入了自定义的deserialze方法，当将4添加上""后，一个属性都没有进入

**Comment by llsi4275** [comment]
可参考测试代码：
https://github.com/llsi4275/fastjsonTest
