### ISSUE TITLE
JSON对象里嵌套对象反序列化时候为null

### ISSUE THREAD

**Issue by wycmiko** [alibaba/fastjson#3281]
已知对象：
![image](https://user-images.githubusercontent.com/34699047/85001453-446dc500-b186-11ea-9587-ce147d60eba1.png)
序列化成JSON String
`{"counterMap":{"0":0,"100":0,"200":0,"300":0,"400":0,"500":0,"600":0,"700":0,"800":0,"900":0,"1000":0},"formatDate":null,"modelName":"test","modelScores":{"Test1-1000":{"max":1.0997832999999515,"min":0.0,"recording":false}},"modelVersion":"1","pit":1592470429399,"useCaseName":"test","variableName":"v2"}`
再调用`ModelState modelState = JSON.parseObject(jsonString, ModelState.class);`
2个嵌套对象转不出来
![image](https://user-images.githubusercontent.com/34699047/85001893-cd84fc00-b186-11ea-9549-39ecff04086f.png)

请问是这么用的吗

**Comment by ZivYan** [comment]
json {"counterMap":{"0":0,"100":0},"id":1,"modelScores":{"Test1-1000":{"max":1.0997832999999515,"min":0.0,"recording":false}},"name":"ziv_yan"}

我这样操作是可以的，你再仔细看看怎么样
HashMap<String, Long> counterMap = new HashMap<String, Long>();
        counterMap.put("0", 0L);
        counterMap.put("100", 0L);

        HashMap<String, TGigest> tGigests = new HashMap<String, TGigest>();
        TGigest tGigest = TGigest.builder().max(1.0997832999999515).min(0.0).recording(false).build();
        tGigests.put("Test1-1000", tGigest);

        ModelState model = ModelState.builder().id(1L).name("ziv_yan")
                .counterMap(counterMap).modelScores(tGigests).build();
        String modelString = JSONObject.toJSONString(model);
        ModelState modelBack = JSON.parseObject(modelString, ModelState.class);
        Assert.assertEquals("nanqi", modelBack.getName());
        Assert.assertEquals(1L, modelBack.getId());
        Assert.assertNotNull(modelBack.getCounterMap());
        Assert.assertNotNull(modelBack.getModelScores());

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.72
问题已修复，请用新版本
