### ISSUE TITLE
version 1.2.70 com.alibaba.fastjson.JSONException: For input string: "2020-01-01 00:00:00 000"

### ISSUE THREAD

**Issue by haedrig** [alibaba/fastjson#3282]
version 1.2.70

```java
 public class Test {
    public static void main(String[] args) {
        Demo demo = JSON.parseObject("{'date':'2020-01-01 00:00:00 000'}", Demo.class);
    }
}

class Demo {
    public Date date;
 }
```

> Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "2020-01-01 00:00:00 000"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:693)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:300)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:573)

**Comment by ZivYan** [comment]
auto recognize date format as below when deserialize:

- ISO-8601 format
- yyyy-MM-dd
- yyyy-MM-dd HH:mm:ss
- yyyy-MM-dd HH:mm:ss.SSS
- miliseconds
- miliseconds string
- .NET JSON format
- new Date(198293238)

for example
`JSON.parseObject("{\"date\":\"2020-06-19 14:41:50.247\"}", Demo.class);`

**Comment by p0mp0k0** [comment]
also do not support yyyy-MM-ddTHH:mm:ss, example '2020-06-19T14:41:50'
