### ISSUE TITLE
1.2.71版本WriteDateUseDateFormat这个Feature不能正常工作

### ISSUE THREAD

**Issue by noobCoode** [alibaba/fastjson#3287]
详情见该库代码中的测试类JodaTest_1_LocalDateTime中的测试方法test_toJsonString_ofLong

**Comment by noobCoode** [comment]
text2的输出应该是不带T的，但是输出却带了T

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.72
问题已修复，请用新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本
