### ISSUE TITLE
spring 4.3版本初始化错误

### ISSUE THREAD

**Issue by lindow2009** [alibaba/fastjson#3290]
版本1.2.70

Caused by: java.lang.NoSuchFieldError: UTF8
	at com.alibaba.fastjson.support.config.FastJsonConfig.<init>(FastJsonConfig.java:86)
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.<init>(FastJsonHttpMessageConverter.java:73)
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4.<init>(FastJsonHttpMessageConverter4.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 47 more

**Comment by lindow2009** [comment]
<bean id="fastJsonHttpMessageConverter"
		class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4">
		<property name="supportedMediaTypes">
			<list>
				<value>text/html;charset=UTF-8</value>
				<value>application/json;charset=UTF-8</value>
			</list>
		</property>
		<property name="fastJsonConfig">
			<bean class="com.alibaba.fastjson.support.config.FastJsonConfig">
				<property name="serializerFeatures">
					<list>
						<value>WriteDateUseDateFormat</value>
						<value>BrowserCompatible</value>
					</list>
				</property>
				<property name="features">
					<list>
						<value>AllowArbitraryCommas</value>
						<value>AllowUnQuotedFieldNames</value>
						<value>DisableCircularReferenceDetect</value>
					</list>
				</property>
			</bean>
		</property>
	</bean>


配置如上，已排除包冲突，但是还是报UTF8错误

**Comment by lindow2009** [comment]
@wenshao @VictorZeng 麻烦看一下，感谢。版本已升级至最新的1.2.72，问题仍然存在

**Comment by VictorZeng** [comment]
应该还是包冲突问题，排除一下多余依赖

**Comment by lindow2009** [comment]
有什么比较好的办法排除多余依赖？

**Comment by VictorZeng** [comment]
```xml
<exclusions>
    <exclusion>
        <groupId>*</groupId>
        <artifactId>*</artifactId>
    </exclusion>
</exclusions>
```

**Comment by lindow2009** [comment]
按照上述方法排除过了的，通过mvn dependency:tree检查，也只有1个fastjson的jar，但是问题还是存在

**Comment by lindow2009** [comment]
再次使用enforcer检查了所有的重复依赖，去除后问题依旧

**Comment by lindow2009** [comment]
@wenshao @VictorZeng 麻烦看一下，感谢。这个问题排除了很久，依赖都全部检查了问题还是存在

**Comment by Zhengzh0** [comment]
> @wenshao @VictorZeng 麻烦看一下，感谢。这个问题排除了很久，依赖都全部检查了问题还是存在

您好，您最后是怎么解决这个问题的呢

**Comment by VictorZeng** [comment]
> > @wenshao @VictorZeng 麻烦看一下，感谢。这个问题排除了很久，依赖都全部检查了问题还是存在
> 
> 您好，您最后是怎么解决这个问题的呢

应该还是依赖冲突的问题，排一下依赖看看，再检查一下运行环境。

**Comment by Zhengzh0** [comment]
> > > @wenshao @VictorZeng 麻烦看一下，感谢。这个问题排除了很久，依赖都全部检查了问题还是存在
> > 
> > 
> > 您好，您最后是怎么解决这个问题的呢
> 
> 应该还是依赖冲突的问题，排一下依赖看看，再检查一下运行环境。

依赖都排除了，但还是报这个问题，SpringBoot版本是2.0.4.RELEASE

**Comment by VictorZeng** [comment]
> > > > @wenshao @VictorZeng 麻烦看一下，感谢。这个问题排除了很久，依赖都全部检查了问题还是存在
> > > 
> > > 
> > > 您好，您最后是怎么解决这个问题的呢
> > 
> > 
> > 应该还是依赖冲突的问题，排一下依赖看看，再检查一下运行环境。
> 
> 依赖都排除了，但还是报这个问题，SpringBoot版本是2.0.4.RELEASE

可以跟进源码里面看一下 UTF8 这个字段是否存在
