### ISSUE TITLE
fastjson在Android app中使用泛型嵌套解析失败

### ISSUE THREAD

**Issue by zhufuing** [alibaba/fastjson#330]
fastjson version : fastjson-1.1.45.android
example code :
```Java
class StatusBean<T> {
    private int code;
    private String msg;
    private T data;

    //getter and setter
    ....
}
```
```Java
public class WorkBean {
    private int hour;
    private String content;

    //getter and setter
    ....
}
```
```Java
try {
        bean = JSONObject.parseObject(jsonContent,
               new TypeReference<StatusBean<WorkBean>>() {
             });
    } catch (Exception e) {
         e.printStackTrace();
    }
```
结果只能解析出StatusBean的内容，无法解析出WorkBean的内容，debug发现WorkBean的内容会被转换成JSONObject类型，但并不能转换为相应的实体类，另外，这个错误并不是每次都发生的，在Activity中这段代码很少解析错误，但是在Fragment有很大的几率出现解析失败，我的应用中经常出现的解析失败场景出现于下面这种情况：我的APP主界面是一个使用FragmentTabHost的FragmentActivity，在上面的Fragment中点击操作按钮进入下一级Activity后，然后又返回到这个FragmentActivivy，切换Tab选项，几乎每次都在这个出现json解析失败的情况，还有在实际情况中我的实体类也是比较复杂的，WorkBean可能会有ArrayList列表数据或者其他的静态内部类。抱歉没有发现其它规律，谢谢。

**Comment by wenshao** [comment]
在Oracle JDK中是否能重现问题？

**Comment by liujmok** [comment]
我也遇到同样错误
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to ...WorkBean

**Comment by macleo** [comment]
Using proguard will throw Exception like bellow:

java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to XXXXXXXXXX

**Comment by lichangadd** [comment]
也遇到了同样的问题，目前先通过手动解析

**Comment by matbird** [comment]
我也遇到相同的问题，不只有没有解决方案

**Comment by jhanay** [comment]
我也遇到此问题，用的是1.1.45.android版本

**Comment by matbird** [comment]
应该是没办法了，只能在解析的时候传入class才行，泛型会在编译的时候被擦除

**Comment by TopJohn** [comment]
我也遇到了这个问题啊，fastJson不是号称最厉害的嘛，苍天呐

**Comment by matbird** [comment]
一般来说，返回的json数据需要符合一定的规范，返回的主题数据无疑要么是一个"{ }"包围的对象数据，要么就是"[ ]"包围的集合格式，直接分离开做不同的处理就行了，想要一个方法就解决所有json数据解析的解决方案还是不大现实啊。

**Comment by wenshao** [comment]
谢谢反馈，测试了最新版本不存在此问题，我先关闭啦
