### ISSUE TITLE
1.2.71版本升级导致json的key变的大小写敏感

### ISSUE THREAD

**Issue by colin-lee** [alibaba/fastjson#3312]
#3246 这次修改有bug。
![image](https://user-images.githubusercontent.com/14800684/86007217-aa413300-ba49-11ea-801c-064707b8aad2.png)
![image](https://user-images.githubusercontent.com/14800684/86007261-b5945e80-ba49-11ea-9920-7b04230f3347.png)

定义javabean： @JSONField(name="NPath") String name；
原本json的 {"npath": "xxxxx.jpg"} 是可以反解析的。

这次升级后就导致无法解析了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本

**Comment by brucelwl** [comment]
@wenshao 我觉得既然通过@JSONField(name="NPath")指定了具体json key, 区分大小写是合理的

**Comment by ListenBom** [comment]
我也认为既然指定了具体的jsonKey，区分大小写应该是对的
