### ISSUE TITLE
JSONField配置deserializeUsing在JSONObject.getObject(String, Class)时不生效

### ISSUE THREAD

**Issue by wenshao** [alibaba/fastjson#3313]
1.2.68~1.2.72版本，JSONField配置deserializeUsing在JSONObject.getObject(String, Class)时不生效

**Comment by ZivYan** [comment]
无视上面的 commit，手误 commit  Issue写错了
这个问题是不是目前 master 已经解决了，我发现是可以用得诶，温少提这个的意思是在 master 目前已经处理，后续 1.2.73 直接上线么？

**Comment by wenshao** [comment]
@ZivYan master上已经修复
