### ISSUE TITLE
1.2.71版本从redis取出反序列化问题safeMode not support autoType : java.lang.Integer/String....等等等

### ISSUE THREAD

**Issue by ggymzz** [alibaba/fastjson#3314]
在JSON串含有数组与safeMode为true从redis取出反序列化时，比如：{"name":"aaaa","sub":["1","2"],"sex":1}从redis取出会报错：safeMode not support autoType : java.lang.Integer/String/Long等等等
关键信息如下：
Caused by: com.alibaba.fastjson.JSONException: safeMode not support autoType : java.lang.Integer
	at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:1324)
	at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:1302)
	at com.alibaba.fastjson.JSONArray.readObject(JSONArray.java:488)
	... 109 common frames omitted
注：同样代码写测试用例不会出现该错误，在web容器中会产生该异常，具体原因不明。
当前解决办法添加AutoTypeCheckHandler，觉得这样太费事了，希望解惑
public Class<?> handler(String typeName, Class<?> expectClass, int features) {
		if ("java.lang.String/Integer/Long".equals(typeName)) {
            return java.lang.String.class;
        }
		return null;
	}

**Comment by ggymzz** [comment]
实在是项目紧急，当前临时解决办法如下：
`public class FastJsonAutoTypeCheckHandler implements AutoTypeCheckHandler {

	@Override
	public Class<?> handler(String typeName, Class<?> expectClass, int features) {
		if (typeName.startsWith("java.lang.")) {
            try {
				return Class.forName(typeName);
			} catch (ClassNotFoundException e) {
				e.printStackTrace();
			}
        }
		return null;
	}

}`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本
