### ISSUE TITLE
MonetaCodec序列化BigDecimal类型兼容问题

### ISSUE THREAD

**Issue by 0x1227** [alibaba/fastjson#3318]
com.alibaba.fastjson.support.moneta.MonetaCodec
在实现序列化的时候会把BigDecimal的2.0序列化成2；
{"numberStripped":2,"currency":"USD"}
反序列化的时候会把2反序列化成Integer，类型检查时导致UnsupportedOperationException
![image](https://user-images.githubusercontent.com/54664205/86203122-c30b2f00-bb96-11ea-9042-4e04f2336b10.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本
