### ISSUE TITLE
如果 Bean 里面字段类型是 LinkedHashMap<Integer, Number> 的话，Number 里面如果出现浮点型数值，还是会被转为 BigDecimal

### ISSUE THREAD

**Issue by asdf2014** [alibaba/fastjson#3326]
使用 `JSON.DEFAULT_PARSER_FEATURE &= ~Feature.UseBigDecimal.getMask()` 方式，正常是可以避免 double 转 BigDecimal 的，但是如果 Bean 里面字段类型是 `LinkedHashMap<Integer, Number>` 的话，Number 里面如果出现浮点型数值，还是会被转为 BigDecimal

![image](https://user-images.githubusercontent.com/8108788/86451162-18893c80-bd4d-11ea-83c8-3a86ea09a3cc.png)

版本：1.2.70

**Comment by asdf2014** [comment]
@wenshao PTAL

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本

**Comment by asdf2014** [comment]
@wenshao 赞啊，感谢大佬 :+1:
