### ISSUE TITLE
add ci(https://travis-ci.org/) for project

### ISSUE THREAD

**Issue by oldratlee** [alibaba/fastjson#333]

**Comment by jacktan1991** [comment]
这个项目好多issue，感觉ownner不是很上心，@wenshao好歹给个回应。

**Comment by wenshao** [comment]
@jacktan1991 过去两年特别忙，所以没有及时反馈社区。今年一定会尽快issue。fastjson issue争取控制在50个以内。

**Comment by wenshao** [comment]
good idea, done!
