### ISSUE TITLE
久未回复再发一次AfterFilter引用出现null属性名，Issues翻页后就不处理了吗？

### ISSUE THREAD

**Issue by supenBenny** [alibaba/fastjson#3342]
1.详情参见:  #3150 
2.是不是问题，要不要修复，烦请回复下；
3.不处理也请告知，关闭Issues，我们自己解决啊；
4.Issues多久不回复就等于不在处理了。
@wenshao

**Comment by wenshao** [comment]
问题已修复，我争取在周末发布新版本

**Comment by supenBenny** [comment]
> 问题已修复，我争取在周末发布新版本

辛苦了，可以不立即修改发布，但请知会下后续版本是否会修复，或者只是我们的使用问题。

**Comment by supenBenny** [comment]
> 问题已修复，我争取在周末发布新版本

@wenshao #1350 有两个问题,只修复了一个，用例再第二个回复里；afterFilter同时写两个对象会包空指针，SerializerFeature.DisableCircularReferenceDetect 禁用这个特性后，你新改的会有问题。
[RefAfterFilterTest-null.zip](https://github.com/alibaba/fastjson/files/4966616/RefAfterFilterTest-null.zip)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本
