### ISSUE TITLE
关于Map转JSON的问题

### ISSUE THREAD

**Issue by iyun1984** [alibaba/fastjson#3346]
JSON.toJSON(Map<Integer,String>)将Map转换为JSON后key值类型由Integer转换为String类型
这里各种key都被转换为了String类型，会出现信息丢失等问题

测试代码和输出结果如下：

    public static void main(String[] args) {
		Map<Integer,String> map = new HashMap<>();
		map.put(1, "hello");
		System.out.println(JSON.toJSON(map));
	}

输出结果：{"1":"hello"}

**Comment by eastFeng** [comment]
使用JSON.toJSONString(map)方法就好了。

**Comment by iyun1984** [comment]
谢谢你，了解了key的类型丢失无法避免只能尽量弥补
