### ISSUE TITLE
1.2.72关于Map转JSON串后解析的BUG

### ISSUE THREAD

**Issue by iyun1984** [alibaba/fastjson#3347]
转换为JSON字符串后，通过JSON.parse(String text)解析为Object时得到key值类型不一致。
1.2.60和1.2.72结果不一致
测试代码和输出结果如下：

	public static void main(String[] args) {
		Map<Integer,String> map = new HashMap<>();
		map.put(1, "hello");
		System.out.println(JSON.toJSONString(map));
		System.out.println(JSON.parse(JSON.toJSONString(map)));
	}
1.2.60结果如下：
{1:"hello"}
**{1:"hello"}**
1.2.72结果如下：
{1:"hello"}
**{"1":"hello"}**

**Comment by ZivYan** [comment]
#2736  因为之前的一个 BUG 导致你现在的问题，建议你如果要用 key 去做操作的话别直接用JSON.parse，用 JSONObject.parseObject(xxx, Map.class) 这样出来的 key 就是你传入的类型，否则会认为是 JSONObject，而 JSONObject 的 key 是强制的 String，希望可以帮助你解决这个问题

**Comment by iyun1984** [comment]
JSONObject为什么key要强制String而不保留原始的信息呢？

**Comment by iyun1984** [comment]
> 
> 
> #2736 因为之前的一个 BUG 导致你现在的问题，建议你如果要用 key 去做操作的话别直接用JSON.parse，用 JSONObject.parseObject(xxx, Map.class) 这样出来的 key 就是你传入的类型，否则会认为是 JSONObject，而 JSONObject 的 key 是强制的 String，希望可以帮助你解决这个问题

JSONObject为什么key要强制String而不保留原始的信息呢？

**Comment by iyun1984** [comment]
> 
> 
> #2736 因为之前的一个 BUG 导致你现在的问题，建议你如果要用 key 去做操作的话别直接用JSON.parse，用 JSONObject.parseObject(xxx, Map.class) 这样出来的 key 就是你传入的类型，否则会认为是 JSONObject，而 JSONObject 的 key 是强制的 String，希望可以帮助你解决这个问题

非常感谢！
JSONObject为什么key要强制String而不保留原始的信息呢？这个出于什么考虑呢？

**Comment by iyun1984** [comment]
> 
> 
> #2736 因为之前的一个 BUG 导致你现在的问题，建议你如果要用 key 去做操作的话别直接用JSON.parse，用 JSONObject.parseObject(xxx, Map.class) 这样出来的 key 就是你传入的类型，否则会认为是 JSONObject，而 JSONObject 的 key 是强制的 String，希望可以帮助你解决这个问题

beb

**Comment by iyun1984** [comment]
> 
> 
> #2736 因为之前的一个 BUG 导致你现在的问题，建议你如果要用 key 去做操作的话别直接用JSON.parse，用 JSONObject.parseObject(xxx, Map.class) 这样出来的 key 就是你传入的类型，否则会认为是 JSONObject，而 JSONObject 的 key 是强制的 String，希望可以帮助你解决这个问题

嗯，了解了，谢谢，转换为JSON串，类型总是会丢的，只能parseObject的时候指定Bean来保障value类型。key的类型无法进行保障。可以通过JSONObject的get和containsKey根据不同入参兼容的方式来得到对应正确的value值，以尽可能的保障存入、取出一致的问题
