### ISSUE TITLE
可选Spring依赖

### ISSUE THREAD

**Issue by microhello** [alibaba/fastjson#335]
在一些未使用spring的项目中，使用fastjson只为了json处理。希望对于spring framework的依赖是可选的。

**Comment by wenshao** [comment]
fastjson没有依赖spring framework啊

**Comment by microhello** [comment]
POM文件中写了spring依赖
https://github.com/alibaba/fastjson/blob/master/pom.xml#L188

2015-05-12 22:57 GMT+08:00 高铁 <notifications@github.com>:
