### ISSUE TITLE
JSONValidator 无法验证json格式是否正确

### ISSUE THREAD

**Issue by xinguangduan** [alibaba/fastjson#3351]
String respBody = "c1110"; 
boolean isCorrect = JSONValidator.from(respBody).validate();

String respBody = "{\"forecast\":\"sss\"}"; 
boolean isCorrect = JSONValidator.from(respBody).validate();

上面两段代码返回的值相同都是false，显然下面应该是true

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.73
问题修复，请用新版本

**Comment by xinguangduan** [comment]
ok
