### ISSUE TITLE
发生POST请求，请求体为一个10000层的对象，后端使用JSONObject报错

### ISSUE THREAD

**Issue by xutong8** [alibaba/fastjson#3366]
最近在做一个关于计算图可视化的项目，前端向后端发送了计算图有关的数据，格式大致为：
{
   "id": "root",
   "children": [
      {
          "id": "n1",
           "children": [
               ....
           ]
      },
      {
          "id": "n2",
          "children": [
             .....
           ]
      }
   ]
}
后端使用JSONOjbect接收却报错。
![image](https://user-images.githubusercontent.com/40812785/88500006-2f444b80-cffa-11ea-9fcb-947f2d31b554.png)

请问大家有啥解决方案嘛？

**Comment by xutong8** [comment]
![image](https://user-images.githubusercontent.com/40812785/88500137-72062380-cffa-11ea-9dfc-f17f69bb070d.png)
报错原因如图所示

**Comment by scvzerng** [comment]
> ![image](https://user-images.githubusercontent.com/40812785/88500137-72062380-cffa-11ea-9dfc-f17f69bb070d.png)
> 报错原因如图所示

可是这报错的包不是jackson的么

**Comment by xutong8** [comment]
closed.
