### ISSUE TITLE
反序列化JSON.parseArray希望传入ParserConfig, @JSONField希望配置序列化器

### ISSUE THREAD

**Issue by lysu** [alibaba/fastjson#337]
-  `JSON.parseObject`有重载支持传入ParserConfig从而支持定义Deserializer等。。但parseArray不支持。。。

因为不支持1所以只有尝试用注解入侵式的打到model。。但还是不行

-  `@JSONField `注解能否支持配置serializer或deserializer希望能这样

        @JSONField(deserializer=AppDateDeserializer.class)
        private Date createTime;
     
因为很多时候只指定format是不够的。。特别数据来源是外部的时候，需要做多种兼容处理， 希望能支持上面两功能~

谢谢~

**Comment by lysu** [comment]
目前自己尝试自己支持第一个问题(一个给别人用的基础jar包)， 代码如下

    private <T> List<T> parseArray(String json, Class<T> clazz, ParserConfig parsConfig) {
        DefaultJSONParser parser = new DefaultJSONParser(json, parsConfig);
        try {
            JSONLexer lexer = parser.getLexer();
            if (lexer.token() == JSONToken.NULL) {
                lexer.nextToken();
                return null;
            }
            List<T> list = new ArrayList<T>();
            parser.parseArray(clazz, list);
            JSONArray.handleResovleTask(parser, list);
            return list;
        } finally {
            parser.close();
        }
    }

但发现JSONLexer在不同fastjson版本中不同 之前是抽象类，新版本变成接口。。。所以我这包给别人时不时会有问题。。

所以这个功能感觉还是在fastjson中支持更好。。帮忙看下 谢谢

**Comment by wenshao** [comment]
用parseObject(json, new TypeReferenche<List<MyBean>>() {}, parseConfig);
