### ISSUE TITLE
JSON.parseObject  返回为null

### ISSUE THREAD

**Issue by aizhunimei** [alibaba/fastjson#341]
之前一直好好的，下午一看，报了空指针，
JSONObject jsonObject = JSON.parseObject((String) msg.obj);
这里边的jsonObject == null 不晓得是什么问题

**Comment by wenshao** [comment]
能否提供更详细的报错信息，这样无法诊断

**Comment by wenshao** [comment]
估计是字符串是空串，或者为null，先关闭啦，有问题再反馈

**Comment by huangsanm** [comment]
JSON.parseObject(str, obj)
str里面的字段有下划线_解析返回 null
1.+版本不会
