### ISSUE TITLE
JSONValidator.from().validate()  BUG 还是 需要配置?

### ISSUE THREAD

**Issue by stephenlam520** [alibaba/fastjson#3417]
验证json字符的方法可把我坑惨了. 项目更新时把fastjson 版本1..2.73 更新到了production. 害我查bug 查了一个多小时,才发现原来validate() 方法 在这个版本验证json 字符串时, 两个元素间存在空格是验证不成功的,我真佩服了.

版本:1..2.73 
String value = "{\\"s\\":\\"sssssss\\",\\"userId\\":\\"1111111\\", \\"v\\":\\"5.00.005\\"}";
System.out.println(JSONValidator.from(value).validate());
return false ??????????????   ("userid"元素后面的逗号 和 "v" 之间隔了个空格) 这样不能通过?

版本:1..2.72不存在这个问题.

**Comment by Ryyyc** [comment]
1.2.75版本该问题已修复~
