### ISSUE TITLE
怎么解决 循环引用 和 多次引用 同时存在的情况？

### ISSUE THREAD

**Issue by Dreampie** [alibaba/fastjson#344]
DisableCircularReferenceDetect 之后  循环引用不能解决了，不知道是否有好的方案，同时兼顾 循环引用和 多次引用的情况，或者 解析的 引用层级

**Comment by benx203** [comment]
https://github.com/benx203/fastjson  层级控制

**Comment by wenshao** [comment]
1.2.9已经实现这样的功能，在SimplePropertyPreFilter中增加了maxLevel，具体看这里 
https://github.com/alibaba/fastjson/wiki/%E4%BD%BF%E7%94%A8SimplePropertyPreFilter%E8%BF%87%E6%BB%A4%E5%B1%9E%E6%80%A7
