### ISSUE TITLE
JSON序列化去双引号，特殊字符处理的BUG

### ISSUE THREAD

**Issue by dingshuangxi888** [alibaba/fastjson#346]
SerializeWriter.writeKeyWithDoubleQuoteIfHasSpecial这个方法中，当text有特殊字符的时候（比如含"\r"字符），对buf数组进行字符拷贝有有问题，具体代码是：
System.arraycopy(buf, i + 1, buf, i + 3, end - i - 1);
System.arraycopy(buf, 0, buf, 1, i);
第二段代码，当第一个key有特殊字符没有问题，而后续的key如果有特殊字符，那么加上双引号就有问题了。应该改为如下代码：
System.arraycopy(buf, i + 1, buf, i + 3, end - i - 1);
System.arraycopy(buf, start, buf, start + 1, end - start);

可参考我这边的分支代码：https://github.com/dingshuangxi888/fastjson.git

**Comment by wenshao** [comment]
能否提交merge request？

**Comment by wenshao** [comment]
这个方法已经去掉，所以先关闭啦
