### ISSUE TITLE
自关联对象toJSONString时属性丢失

### ISSUE THREAD

**Issue by olddoor** [alibaba/fastjson#347]
entity代码如下
---------------------------------------------------------------------------
package com.zyl.entity;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.GenericGenerator;

/**
 * 用户组
 * @author Z10
 */
@Entity //声明为实体
@Table(name="T_Group")  //修改表名
public class Group {
	
	//配合前台对datatree的修改.支持平滑数据
	@Transient
	private String pid;// 虚拟属性，用于获得当前机构的父机构ID
	
	@Id  //标记为主键
	@GeneratedValue(generator="GroupGenerator") 
	@GenericGenerator(name = "GroupGenerator",strategy="uuid")//在JPA中使用Hibernate的uuid主键策略
	private String id;
	private String name;
	private String address;
	private String code;
	private String iconCls;
	
	@Column(nullable=false) //不可为空,类型为Time
	private Date updateDate;
	

	
	@ManyToOne
	@JoinColumn(name="fatherGroup_id")
	private Group fatherGroup;
	

	@OneToMany(mappedBy = "fatherGroup", cascade = CascadeType.ALL,fetch=FetchType.EAGER)//级联操作
	private Set<Group> children;
	
	@OneToMany(mappedBy="group") //维护关系交给User
	private Set<User> users;

	
	
	
	//getter&&setter
	
	
	public String getPid() {
		if (fatherGroup != null && !StringUtils.isBlank(fatherGroup.getId())) {
			return fatherGroup.getId();
		}
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	public Group getFatherGroup() {
		return fatherGroup;
	}
	public void setFatherGroup(Group fatherGroup) {
		this.fatherGroup = fatherGroup;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getIconCls() {
		return iconCls;
	}
	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}
	public Set<User> getUsers() {
		return users;
	}
	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Group> getChildren() {
		return children;
	}

	public void setChildren(Set<Group> children) {
		this.children = children;
	}
	
}
----------------
调用json = JSON.toJSONString(object, filter, SerializerFeature.WriteDateUseDateFormat, SerializerFeature.DisableCircularReferenceDetect,SerializerFeature.BrowserCompatible);
后有值的属性都能输出(如fatherGroup) 但无法输出children

**Comment by wenshao** [comment]
hibernate不会自动装载对象的，需要手动装载
