### ISSUE TITLE
map 无法序列化为 SnakeCase

### ISSUE THREAD

**Issue by fushengruomengzhang** [alibaba/fastjson#3496]
jdk version 1.8
fastjson 1.2.74
代码:
`
@Test
public void test() {
    SerializeConfig SNAKE_CASE_CONFIG = new SerializeConfig();
    SNAKE_CASE_CONFIG.setPropertyNamingStrategy(PropertyNamingStrategy.SnakeCase);
    HashMap<String, String> result = new HashMap<>(1);
    result.put("appName", "1");
    String s = JSON.toJSONString(result, SNAKE_CASE_CONFIG, SerializerFeature.WriteDateUseDateFormat);
    System.out.println(s);
}

`

运行结果

`
{"appName":"1"}
`

**Comment by Certseeds** [comment]
用法错了，建议直接用`PropertyNamingStrategy.values()[i].translate();`来实现对key的translate
