### ISSUE TITLE
JSON String里的key由驼峰命名转下划线

### ISSUE THREAD

**Issue by jjnnzb** [alibaba/fastjson#3511]
有没有可能在调用`public static String toJSONString(Object object, SerializerFeature... features)`时，指定一种feature，可以将我的object全部转化为我想要的以驼峰命名的方式，例如：
User实体类[userName='Tom Plaze', passWord='123456', roomId='201', roomKey='12345678']，
调用JSON.toJSONString之后生成的JSON串如下:
{"pass_word":"123456","room_id":"201","room_key":"12345678","user_name":"Tom Plaze"}

**Comment by XuCcc** [comment]
请问下最后有什么好的实现方式吗

我看`com.alibaba.fastjson.JSON#parseObject(java.lang.String, java.lang.reflect.Type, com.alibaba.fastjson.parser.ParserConfig, com.alibaba.fastjson.parser.deserializer.ParseProcess, int, com.alibaba.fastjson.parser.Feature...)` 也只支持三种`ParseProcess`

**Comment by jjnnzb** [comment]
没有用FastJson，用的Jackson Json实现的，参考我这篇帖子：[Java开发里遇到的奇奇怪怪的需求---JSON键值驼峰转下划线的实现](https://zhuanlan.zhihu.com/p/270875975)

**Comment by jjnnzb** [comment]
> 请问下最后有什么好的实现方式吗
> 
> 我看`com.alibaba.fastjson.JSON#parseObject(java.lang.String, java.lang.reflect.Type, com.alibaba.fastjson.parser.ParserConfig, com.alibaba.fastjson.parser.deserializer.ParseProcess, int, com.alibaba.fastjson.parser.Feature...)` 也只支持三种`ParseProcess`

没有用FastJson，用的Jackson Json实现的，参考我这篇帖子：[Java开发里遇到的奇奇怪怪的需求---JSON键值驼峰转下划线的实现](https://zhuanlan.zhihu.com/p/270875975)
