### ISSUE TITLE
Failure when trying to read an object larger than ~700MB

### ISSUE THREAD

**Issue by daniel-beck** [alibaba/fastjson#3540]
```
Caught: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:562)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:535)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:523)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:512)
```

https://github.com/alibaba/fastjson/blob/37ed66bcaa3b0c88c5f3f0b09e6b4029c72c14cd/src/main/java/com/alibaba/fastjson/JSON.java#L562

If an object is larger than `Integer.MAX_VALUE/3`, this goes into negative values, which seems earlier than necessary.

**Comment by hulog** [comment]
Yeah, you're right! It seems a change point which happens again #2911

**Comment by daniel-beck** [comment]
@hulog Thanks for the reference. I searched for the exception name but must have done it incorrectly, I did not find #2911.
