### ISSUE TITLE
JSONValidator 验证不对。。。

### ISSUE THREAD

**Issue by mlymark** [alibaba/fastjson#3552]
{"configId":"00acedb78cca41f3a75947b5b57b3fd5","id":"5e9691728acf4e0c985afb372ac2b14a"}这个字符串为什么验证不是json格式呢？而用其他验证方式就能验证通过。。使用的是com.alibaba:fastjson:1.2.71版本

**Comment by hulog** [comment]
请升级到最新版本 `1.2.75`
