### ISSUE TITLE
Can't output object that does not comply to Java beans spec

### ISSUE THREAD

**Issue by greenlaw110** [alibaba/fastjson#357]
Suppose I have a model class defined as follows:

```java
@Entity("todo")
public class TodoItem {
    @Id
    private ObjectId _id;

    private String desc;

    private TodoItem() {}

    public TodoItem(String desc) {
        this.desc = desc;
    }

    public String _id() {
        return _id.toString();
    }

    public String desc() {
        return desc;
    }

    public TodoItem desc(String desc) {
        this.desc = desc;
        return this;
    }
}
```

`JSON.toJSONString(List<TodoItem>)` call gives me `[{}]`, while I expect something like: `[{"_id": "5589341bb1964545f61bbe11", "desc": "Task 1"}]`:

![deepinscreenshot20150623210155](https://cloud.githubusercontent.com/assets/216930/8304666/549902ba-19eb-11e5-8e5d-89fe51abcfdf.png)

**Comment by wenshao** [comment]
这个是JPA的规范，只是和持久化到数据有关，fastjson不认这个，先关闭啦，有问题再提。
