### ISSUE TITLE
当返回给前端map<Integet,String>时候，json 的数字key 不带引号，导致解析失败

### ISSUE THREAD

**Issue by fengyaocheng** [alibaba/fastjson#3589]
首先上json配置
![image](https://user-images.githubusercontent.com/55734775/101894861-b711a780-3be1-11eb-9055-238813abd09d.png)
测试代码：
![image](https://user-images.githubusercontent.com/55734775/101895154-1ff91f80-3be2-11eb-98f0-477d34a28b97.png)

返回给前端的json为下图，json不可以正常解析：：
![image](https://user-images.githubusercontent.com/55734775/101895446-8120f300-3be2-11eb-836b-947674d536ab.png)

当去掉json配置，使用默认jackson返回前端的json格式为下图，json可以正常解析：
![image](https://user-images.githubusercontent.com/55734775/101896807-81ba8900-3be4-11eb-994f-f590d58229f2.png)

可见 两个fastJson的不同处为 数字两边的引号处。那么是我fastJson配置问题吗。

**Comment by fengyaocheng** [comment]
您好，十分抱歉。我已经找到了更改配置的方法。打扰了

**Comment by xtestw** [comment]
配置是啥？
