### ISSUE TITLE
问题版本 1.2.75  vaule值都等于null的时候 remove其中一个key 输出对象时候为空的json对象

### ISSUE THREAD

**Issue by lancefreestyle** [alibaba/fastjson#3592]
# 都是main 方法 copy 即可运行
fastjson结果不正确：
public static void main(String[] args) {
        String a="{\"110233002\": null, \"110296080\": null, \"110297066\": null, \"110297137\": null, \"110300015\": null, \"110310007\": null, \"110310008\": null, \"110310011\": null, \"110310013\": null, \"110310014\": null, \"110310015\": null, \"110310022\": null, \"110310025\": null, \"110310027\": null, \"110310028\": null, \"110310029\": null, \"110310030\": null, \"110310031\": null, \"110310032\": null, \"110310034\": null, \"110310035\": null, \"110310036\": null, \"110310037\": null, \"110310039\": null, \"110310040\": null, \"110310042\": null, \"110310043\": null, \"110310046\": null, \"110310050\": null, \"110310064\": null, \"110310065\": null, \"110310066\": null, \"110310067\": null, \"110310068\": null, \"110310069\": null, \"110310070\": null, \"110310071\": null, \"110310072\": null, \"110310073\": null, \"110310074\": null, \"110310075\": null, \"110311001\": null, \"110311002\": null, \"110311003\": null, \"110311004\": null, \"110311010\": null, \"110311012\": null, \"110311014\": null, \"110311015\": null, \"110311036\": null, \"110311037\": null, \"110312001\": null, \"110312002\": null, \"110312003\": null, \"110314002\": null, \"110314005\": null, \"110314014\": null, \"110314019\": null, \"110314020\": null, \"110315018\": null, \"110316052\": null, \"110316055\": null, \"110316056\": null, \"110317007\": null, \"110318006\": null, \"110318008\": null, \"110318010\": null, \"110318011\": null, \"110318018\": null, \"110320007\": null, \"110321001\": null, \"110321002\": null, \"110321015\": null, \"110322001\": null, \"110322002\": null, \"110322005\": null, \"110322006\": null, \"110323010\": null, \"110323012\": null, \"110324021\": null, \"110324031\": null, \"110326016\": null, \"110328005\": null, \"110329001\": null, \"110330006\": null, \"110330007\": null, \"110331023\": null, \"110332001\": null, \"110332004\": null, \"110333001\": null, \"110333002\": null, \"110333003\": null, \"110333004\": null, \"110333005\": null, \"110333006\": null, \"110333007\": null, \"110333008\": null, \"110333009\": null, \"110333010\": null, \"110333011\": null, \"110334001\": null, \"110334002\": null, \"110334003\": null, \"110334004\": null, \"110334005\": null, \"110334006\": null, \"110334007\": null, \"110334008\": null, \"110334009\": null, \"110334010\": null, \"110334011\": null, \"110334012\": null, \"110334013\": null, \"110334014\": null, \"110334015\": null, \"110334016\": null, \"110334017\": null, \"110334018\": null, \"110334019\": null, \"110334020\": null, \"110334021\": null, \"110334022\": null, \"110334023\": null, \"110334024\": null, \"110334025\": null, \"110334026\": null, \"110334027\": null, \"110334028\": null, \"110334029\": null, \"110334030\": null, \"110334031\": null, \"110334032\": null, \"110334033\": null, \"110334034\": null, \"110334035\": null, \"110334036\": null, \"110334037\": null, \"110334038\": null, \"110334039\": null, \"110334040\": null, \"110334041\": null, \"110334042\": null, \"110334043\": null, \"110334044\": null, \"110334045\": null, \"110334046\": null, \"110334047\": null, \"110334048\": null, \"110334049\": null, \"110334050\": null, \"110334051\": null, \"110334052\": null, \"110334053\": null, \"110334054\": null, \"110334055\": null, \"110334056\": null, \"110334057\": null, \"110334058\": null, \"110334059\": null, \"110334060\": null, \"110334061\": null, \"110334062\": null, \"110334063\": null, \"110334064\": null, \"110334065\": null, \"110334066\": null, \"110334067\": null, \"110334068\": null, \"110334069\": null, \"110334070\": null, \"110334071\": null, \"110334072\": null, \"110334073\": null, \"110334074\": null, \"110334075\": null, \"110334076\": null, \"110334077\": null, \"110334078\": null, \"110334079\": null, \"110334080\": null, \"110334081\": null, \"110334082\": null, \"110334083\": null, \"110334084\": null, \"110334085\": null, \"110334086\": null, \"110334087\": null, \"110334088\": null, \"110334089\": null, \"110334090\": null, \"110334091\": null, \"110334092\": null, \"110334093\": null, \"110334094\": null, \"110334095\": null, \"110334096\": null, \"110334097\": null, \"110334098\": null, \"110334099\": null, \"110334100\": null, \"110334101\": null, \"110334102\": null, \"110334103\": null, \"110334104\": null, \"110334105\": null, \"110334106\": null, \"110334107\": null, \"110334108\": null, \"110334109\": null, \"110334110\": null, \"110334111\": null, \"110334112\": null, \"110334113\": null, \"110334114\": null, \"110334115\": null, \"110334116\": null, \"110334117\": null, \"110334118\": null, \"110334119\": null, \"110334120\": null, \"110334121\": null, \"110334122\": null, \"110334123\": null, \"110334124\": null, \"110334126\": null, \"110334127\": null, \"110334128\": null, \"110334129\": null, \"110334130\": null, \"110334131\": null, \"110334132\": null, \"110334133\": null, \"110334134\": null, \"110334135\": null, \"110334136\": null, \"110334137\": null, \"110334138\": null, \"110334139\": null, \"110334140\": null, \"110334141\": null, \"110334143\": null, \"110334144\": null, \"110334145\": null, \"110334146\": null, \"110334147\": null, \"110334148\": null, \"110334149\": null, \"110334150\": null, \"110334151\": null, \"110334153\": null, \"110334154\": null, \"110334155\": null, \"110334156\": null, \"110334157\": null, \"110334158\": null, \"110334159\": null, \"110334160\": null, \"110334161\": null, \"110334162\": null, \"110334163\": null, \"110334164\": null, \"110334165\": null, \"110334166\": null, \"110334167\": null, \"110334168\": null, \"110334169\": null, \"110334170\": null, \"110334171\": null, \"110334172\": null, \"110334174\": null, \"110334175\": null, \"110334176\": null, \"110334177\": null, \"110334178\": null, \"110334179\": null, \"110334180\": null, \"110334181\": null, \"110334182\": null, \"110334183\": null, \"110334184\": null, \"110334186\": null, \"110334187\": null, \"110334189\": null, \"110334190\": null, \"110334191\": null, \"110334192\": null, \"110334193\": null, \"110334194\": null, \"110334195\": null, \"110334196\": null, \"110334198\": null, \"110334199\": null, \"110334200\": null, \"110334201\": null, \"110334202\": null, \"110334203\": null, \"110334204\": null, \"110334205\": null, \"110334207\": null, \"110334208\": null, \"110334209\": null, \"110334210\": null, \"110334211\": null, \"110334212\": null, \"110334213\": null, \"110334215\": null, \"110334217\": null, \"110334219\": null, \"110334220\": null, \"110334221\": null, \"110334223\": null, \"110334225\": null, \"110334226\": null, \"110334228\": null, \"110334231\": null, \"110334234\": null, \"110334237\": null, \"110334239\": null, \"110334240\": null, \"110334241\": null, \"110334243\": null, \"110334246\": null, \"110334248\": null, \"110334250\": null, \"110334253\": null, \"110334255\": null, \"110334257\": null, \"110334259\": null, \"110334262\": null, \"110334265\": null, \"110334267\": null, \"110334269\": null, \"110334271\": null, \"110334273\": null, \"110334274\": null, \"110334275\": null, \"110334277\": null, \"110334279\": null, \"110334281\": null, \"110334283\": null, \"110334285\": null, \"110334287\": null, \"110334289\": null, \"110334292\": null, \"110334294\": null, \"110334297\": null, \"110334299\": null, \"110334302\": null, \"110334305\": null, \"110334308\": null, \"110334311\": null, \"110334315\": null, \"110334318\": null, \"110334321\": null, \"110334325\": null, \"110334330\": null, \"110334335\": null, \"110334341\": null, \"110334348\": null, \"110334353\": null, \"110334359\": null, \"110334366\": null, \"110334374\": null, \"110334381\": null, \"110334388\": null, \"110334397\": null, \"110334408\": null, \"110334419\": null, \"110334430\": null, \"110334442\": null, \"110334455\": null, \"110334468\": null, \"110334482\": null, \"110334497\": null, \"110334513\": null, \"110334531\": null, \"110334550\": null, \"110334573\": null, \"110334601\": null, \"110334635\": null, \"110334677\": null, \"110334730\": null, \"110334798\": null, \"110334886\": null, \"110335001\": null, \"110335004\": null, \"110335005\": null, \"110336001\": null, \"110337003\": null, \"110338001\": null, \"110338002\": null, \"110338003\": null, \"110338004\": null, \"110342006\": null, \"110342007\": null, \"110342008\": null, \"110343002\": null, \"110343003\": null, \"110343004\": null, \"110343008\": null, \"110343009\": null, \"110343010\": null, \"110343011\": null, \"110343012\": null, \"110344002\": null, \"110344025\": null, \"110344029\": null, \"110345021\": null, \"110345023\": null, \"110346027\": null, \"110346069\": null, \"110346070\": null, \"110346071\": null, \"110349006\": null, \"110349025\": null, \"120266088\": null, \"120310044\": null, \"120310051\": null, \"120321016\": null, \"120326005\": null, \"120337002\": null, \"130318017\": null, \"130324014\": null, \"210289033\": null, \"210294001\": null, \"210294002\": null, \"210294004\": null, \"210310012\": null, \"210316042\": null, \"220326082\": null, \"220328006\": null, \"290335002\": null, \"310321030\": null, \"330309005\": null, \"330315005\": null, \"330330008\": null, \"330337004\": true, \"330342002\": null, \"330342003\": null, \"330342004\": null, \"330342005\": null, \"390321004\": null, \"390321006\": null, \"390321009\": null, \"390321024\": null, \"390321026\": null, \"520331017\": null, \"520331018\": null, \"520331021\": null, \"530331022\": null, \"1103341002\": null}";
        JSONObject contentJson = JSONObject.parseObject(a);
        for (String promotionId : Lists.newArrayList("330337004")) {
            if (contentJson.containsKey(promotionId)) {
                contentJson.remove(promotionId);
            }
        }
        System.out.println(contentJson.toJSONString());
    }

jackson 转换结果正确：
public static void main(String[] args) throws JsonProcessingException {
        String a="{\"110233002\": null, \"110296080\": null, \"110297066\": null, \"110297137\": null, \"110300015\": null, \"110310007\": null, \"110310008\": null, \"110310011\": null, \"110310013\": null, \"110310014\": null, \"110310015\": null, \"110310022\": null, \"110310025\": null, \"110310027\": null, \"110310028\": null, \"110310029\": null, \"110310030\": null, \"110310031\": null, \"110310032\": null, \"110310034\": null, \"110310035\": null, \"110310036\": null, \"110310037\": null, \"110310039\": null, \"110310040\": null, \"110310042\": null, \"110310043\": null, \"110310046\": null, \"110310050\": null, \"110310064\": null, \"110310065\": null, \"110310066\": null, \"110310067\": null, \"110310068\": null, \"110310069\": null, \"110310070\": null, \"110310071\": null, \"110310072\": null, \"110310073\": null, \"110310074\": null, \"110310075\": null, \"110311001\": null, \"110311002\": null, \"110311003\": null, \"110311004\": null, \"110311010\": null, \"110311012\": null, \"110311014\": null, \"110311015\": null, \"110311036\": null, \"110311037\": null, \"110312001\": null, \"110312002\": null, \"110312003\": null, \"110314002\": null, \"110314005\": null, \"110314014\": null, \"110314019\": null, \"110314020\": null, \"110315018\": null, \"110316052\": null, \"110316055\": null, \"110316056\": null, \"110317007\": null, \"110318006\": null, \"110318008\": null, \"110318010\": null, \"110318011\": null, \"110318018\": null, \"110320007\": null, \"110321001\": null, \"110321002\": null, \"110321015\": null, \"110322001\": null, \"110322002\": null, \"110322005\": null, \"110322006\": null, \"110323010\": null, \"110323012\": null, \"110324021\": null, \"110324031\": null, \"110326016\": null, \"110328005\": null, \"110329001\": null, \"110330006\": null, \"110330007\": null, \"110331023\": null, \"110332001\": null, \"110332004\": null, \"110333001\": null, \"110333002\": null, \"110333003\": null, \"110333004\": null, \"110333005\": null, \"110333006\": null, \"110333007\": null, \"110333008\": null, \"110333009\": null, \"110333010\": null, \"110333011\": null, \"110334001\": null, \"110334002\": null, \"110334003\": null, \"110334004\": null, \"110334005\": null, \"110334006\": null, \"110334007\": null, \"110334008\": null, \"110334009\": null, \"110334010\": null, \"110334011\": null, \"110334012\": null, \"110334013\": null, \"110334014\": null, \"110334015\": null, \"110334016\": null, \"110334017\": null, \"110334018\": null, \"110334019\": null, \"110334020\": null, \"110334021\": null, \"110334022\": null, \"110334023\": null, \"110334024\": null, \"110334025\": null, \"110334026\": null, \"110334027\": null, \"110334028\": null, \"110334029\": null, \"110334030\": null, \"110334031\": null, \"110334032\": null, \"110334033\": null, \"110334034\": null, \"110334035\": null, \"110334036\": null, \"110334037\": null, \"110334038\": null, \"110334039\": null, \"110334040\": null, \"110334041\": null, \"110334042\": null, \"110334043\": null, \"110334044\": null, \"110334045\": null, \"110334046\": null, \"110334047\": null, \"110334048\": null, \"110334049\": null, \"110334050\": null, \"110334051\": null, \"110334052\": null, \"110334053\": null, \"110334054\": null, \"110334055\": null, \"110334056\": null, \"110334057\": null, \"110334058\": null, \"110334059\": null, \"110334060\": null, \"110334061\": null, \"110334062\": null, \"110334063\": null, \"110334064\": null, \"110334065\": null, \"110334066\": null, \"110334067\": null, \"110334068\": null, \"110334069\": null, \"110334070\": null, \"110334071\": null, \"110334072\": null, \"110334073\": null, \"110334074\": null, \"110334075\": null, \"110334076\": null, \"110334077\": null, \"110334078\": null, \"110334079\": null, \"110334080\": null, \"110334081\": null, \"110334082\": null, \"110334083\": null, \"110334084\": null, \"110334085\": null, \"110334086\": null, \"110334087\": null, \"110334088\": null, \"110334089\": null, \"110334090\": null, \"110334091\": null, \"110334092\": null, \"110334093\": null, \"110334094\": null, \"110334095\": null, \"110334096\": null, \"110334097\": null, \"110334098\": null, \"110334099\": null, \"110334100\": null, \"110334101\": null, \"110334102\": null, \"110334103\": null, \"110334104\": null, \"110334105\": null, \"110334106\": null, \"110334107\": null, \"110334108\": null, \"110334109\": null, \"110334110\": null, \"110334111\": null, \"110334112\": null, \"110334113\": null, \"110334114\": null, \"110334115\": null, \"110334116\": null, \"110334117\": null, \"110334118\": null, \"110334119\": null, \"110334120\": null, \"110334121\": null, \"110334122\": null, \"110334123\": null, \"110334124\": null, \"110334126\": null, \"110334127\": null, \"110334128\": null, \"110334129\": null, \"110334130\": null, \"110334131\": null, \"110334132\": null, \"110334133\": null, \"110334134\": null, \"110334135\": null, \"110334136\": null, \"110334137\": null, \"110334138\": null, \"110334139\": null, \"110334140\": null, \"110334141\": null, \"110334143\": null, \"110334144\": null, \"110334145\": null, \"110334146\": null, \"110334147\": null, \"110334148\": null, \"110334149\": null, \"110334150\": null, \"110334151\": null, \"110334153\": null, \"110334154\": null, \"110334155\": null, \"110334156\": null, \"110334157\": null, \"110334158\": null, \"110334159\": null, \"110334160\": null, \"110334161\": null, \"110334162\": null, \"110334163\": null, \"110334164\": null, \"110334165\": null, \"110334166\": null, \"110334167\": null, \"110334168\": null, \"110334169\": null, \"110334170\": null, \"110334171\": null, \"110334172\": null, \"110334174\": null, \"110334175\": null, \"110334176\": null, \"110334177\": null, \"110334178\": null, \"110334179\": null, \"110334180\": null, \"110334181\": null, \"110334182\": null, \"110334183\": null, \"110334184\": null, \"110334186\": null, \"110334187\": null, \"110334189\": null, \"110334190\": null, \"110334191\": null, \"110334192\": null, \"110334193\": null, \"110334194\": null, \"110334195\": null, \"110334196\": null, \"110334198\": null, \"110334199\": null, \"110334200\": null, \"110334201\": null, \"110334202\": null, \"110334203\": null, \"110334204\": null, \"110334205\": null, \"110334207\": null, \"110334208\": null, \"110334209\": null, \"110334210\": null, \"110334211\": null, \"110334212\": null, \"110334213\": null, \"110334215\": null, \"110334217\": null, \"110334219\": null, \"110334220\": null, \"110334221\": null, \"110334223\": null, \"110334225\": null, \"110334226\": null, \"110334228\": null, \"110334231\": null, \"110334234\": null, \"110334237\": null, \"110334239\": null, \"110334240\": null, \"110334241\": null, \"110334243\": null, \"110334246\": null, \"110334248\": null, \"110334250\": null, \"110334253\": null, \"110334255\": null, \"110334257\": null, \"110334259\": null, \"110334262\": null, \"110334265\": null, \"110334267\": null, \"110334269\": null, \"110334271\": null, \"110334273\": null, \"110334274\": null, \"110334275\": null, \"110334277\": null, \"110334279\": null, \"110334281\": null, \"110334283\": null, \"110334285\": null, \"110334287\": null, \"110334289\": null, \"110334292\": null, \"110334294\": null, \"110334297\": null, \"110334299\": null, \"110334302\": null, \"110334305\": null, \"110334308\": null, \"110334311\": null, \"110334315\": null, \"110334318\": null, \"110334321\": null, \"110334325\": null, \"110334330\": null, \"110334335\": null, \"110334341\": null, \"110334348\": null, \"110334353\": null, \"110334359\": null, \"110334366\": null, \"110334374\": null, \"110334381\": null, \"110334388\": null, \"110334397\": null, \"110334408\": null, \"110334419\": null, \"110334430\": null, \"110334442\": null, \"110334455\": null, \"110334468\": null, \"110334482\": null, \"110334497\": null, \"110334513\": null, \"110334531\": null, \"110334550\": null, \"110334573\": null, \"110334601\": null, \"110334635\": null, \"110334677\": null, \"110334730\": null, \"110334798\": null, \"110334886\": null, \"110335001\": null, \"110335004\": null, \"110335005\": null, \"110336001\": null, \"110337003\": null, \"110338001\": null, \"110338002\": null, \"110338003\": null, \"110338004\": null, \"110342006\": null, \"110342007\": null, \"110342008\": null, \"110343002\": null, \"110343003\": null, \"110343004\": null, \"110343008\": null, \"110343009\": null, \"110343010\": null, \"110343011\": null, \"110343012\": null, \"110344002\": null, \"110344025\": null, \"110344029\": null, \"110345021\": null, \"110345023\": null, \"110346027\": null, \"110346069\": null, \"110346070\": null, \"110346071\": null, \"110349006\": null, \"110349025\": null, \"120266088\": null, \"120310044\": null, \"120310051\": null, \"120321016\": null, \"120326005\": null, \"120337002\": null, \"130318017\": null, \"130324014\": null, \"210289033\": null, \"210294001\": null, \"210294002\": null, \"210294004\": null, \"210310012\": null, \"210316042\": null, \"220326082\": null, \"220328006\": null, \"290335002\": null, \"310321030\": null, \"330309005\": null, \"330315005\": null, \"330330008\": null, \"330337004\": true, \"330342002\": null, \"330342003\": null, \"330342004\": null, \"330342005\": null, \"390321004\": null, \"390321006\": null, \"390321009\": null, \"390321024\": null, \"390321026\": null, \"520331017\": null, \"520331018\": null, \"520331021\": null, \"530331022\": null, \"1103341002\": null}";
        ObjectMapper OBJECT_MAPPER = new ObjectMapper();
        HashMap hashMap =  OBJECT_MAPPER.readValue(a, HashMap.class);
        for (String promotionId : Lists.newArrayList("330337004")) {
            if (hashMap.containsKey(promotionId)) {
                hashMap.remove(promotionId);
            }
        }
        String s = OBJECT_MAPPER.writeValueAsString(hashMap);
        System.out.println(s);
    }

**Comment by RussXia** [comment]
fastjson默认就是不输出value为null的字段，应该和你有没有remove也没关系。如果想输出value为null的属性，可以试试
`JSON.toJSONString(contentJson, SerializerFeature.WriteMapNullValue)`

**Comment by lancefreestyle** [comment]
好的。了解了
