### ISSUE TITLE
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 265 of the JSON data

### ISSUE THREAD

**Issue by WolfgangFahl** [alibaba/fastjson#360]
The reason seems to be a \n newline character in a string. I would have expected that this get's automatically escaped by fast json. Is fast json so fast that it doesn't do the necessary jobs?

**Comment by LQZYC** [comment]
i have a try as u say but no problem have been found   can u upload your code ,then i can try my best to fix it

**Comment by wenshao** [comment]
'\n' at the end string caused the error. bug fixed, i will include in 1.2.9 & 1.1.49.android
