### ISSUE TITLE
javaBean转换为json怎么实现指定属性名风格，如驼峰和下划线两种？

### ISSUE THREAD

**Issue by Dreampie** [alibaba/fastjson#361]
https://github.com/Dreampie/Resty/blob/master/resty-common/src/main/java/cn/dreampie/common/util/Stringer.java

**Comment by foxinmy** [comment]
自己写filter

UnderlineNameFilter

     public static class UnderlineNameFilter implements NameFilter {
		private final static UnderlineNameFilter instance = new UnderlineNameFilter();

		public static UnderlineNameFilter getGlobalInstance() {
			return instance;
		}
		@Override
		public String process(Object object, String name, Object value) {
			StringBuilder propertyName = new StringBuilder(name.length());
			propertyName.append(Character.toLowerCase(name.charAt(0)));
			for (int i = 1; i < name.length(); i++) {
				char c = name.charAt(i);
				if (Character.isUpperCase(c)) {
					propertyName.append(UNDERLINE);
				}
				propertyName.append(Character.toLowerCase(c));
			}
			return propertyName.toString();
		}
	}

CamelCaseFilter

    public static class CamelCaseFilter implements NameFilter {
		private final static CamelCaseFilter instance = new CamelCaseFilter();

		public static CamelCaseFilter getGlobalInstance() {
			return instance;
		}

		@Override
		public String process(Object object, String name, Object value) {
			StringBuilder propertyName = new StringBuilder(name.length());
			propertyName.append(Character.toLowerCase(name.charAt(0)));
			for (int i = 1; i < name.length(); i++) {
				char c = name.charAt(i);
				if (UNDERLINE == c && (i + 1) < name.length()) {
					propertyName.append(Character.toUpperCase(name
							.charAt(i + 1)));
					i++;
					continue;
				}
				propertyName.append(c);
			}
			return propertyName.toString();
		}
	}

case

     String camelcaseJson = JSON.toJSONString(javaBean,
				UnderlineNameFilter.getGlobalInstance());

     String camelcaseJson = JSON.toJSONString(javaBean,
				CamelCaseFilter.getGlobalInstance());

**Comment by Dreampie** [comment]
那json转对象呢  怎么弄 如果每个属性写注解  写这个filter也没意义了

**Comment by fivesmallq** [comment]
@foxinmy 另外一个问题。。https://github.com/alibaba/fastjson/issues/474 比较蛋疼，目前没有找到办法

**Comment by wenshao** [comment]
用@foxinmy 提供的办法能解决问题，我就先关闭issue啦，有问题再提

**Comment by qq123renmin** [comment]
用@foxinmy 提供的办法确实能解决问题！感谢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/PropertyNamingStrategy_cn
看这个是不是你要的
