### ISSUE TITLE
去掉 SerializeConfig.globalInstance  的 final 修饰符

### ISSUE THREAD

**Issue by timandy** [alibaba/fastjson#3630]
@wenshao 
对比 SerializeConfig vs ParserConfig , 希望可以去掉 final 修饰符, 以便设置全局使用 new SerializeConfig(true)  filedBased 模式序列化设置. 现在只能通过反射去掉 final 修饰符,然后修改值, 非常繁琐.

https://github.com/alibaba/fastjson/blob/b584203cf4d3969245ffc540fc6c51fc5e3b264e/src/main/java/com/alibaba/fastjson/serializer/SerializeConfig.java#L53

https://github.com/alibaba/fastjson/blob/b584203cf4d3969245ffc540fc6c51fc5e3b264e/src/main/java/com/alibaba/fastjson/parser/ParserConfig.java#L169

**Comment by YubingJiang** [comment]
nice
