### ISSUE TITLE
JSON.toJSONString不同overload对Date的处理不一致

### ISSUE THREAD

**Issue by marsqing** [alibaba/fastjson#367]
如以下几个方法不会调用serializer.config(SerializerFeature.WriteDateUseDateFormat, true);
toJSONString(Object object)
toJSONString(Object object, SerializeConfig config, SerializeFilter filter, SerializerFeature... features)

而以下会调用serializer.config(SerializerFeature.WriteDateUseDateFormat, true);
toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)

不一一列举。会导致不同签名的toJSONString方法序列化Date字段的结果不一致。对于Java问题不大，跨语言的时候可能会有问题。

**Comment by LQZYC** [comment]
这个SerializerFeature.WriteDateUseDateFormat需要的时候加上就可以了吧 如果对日期要求不是很严格 每次不管什么样子的序列化都加上这个也不大好吧

**Comment by wenshao** [comment]
修改了实现，如果没有调用toJSONStringWithDateFormat，就不会自动配置WriteDateUseDateFormat了。
