### ISSUE TITLE
JSON.toJSONString(obj, SerializerFeature.PrettyFormat)导致循环引用path异常

### ISSUE THREAD

**Issue by txgj** [alibaba/fastjson#3672]
IssueCR root = new IssueCR();
        IssueCA a = new IssueCA();
        IssueCB b= new IssueCB();
        IssueCC c = new IssueCC();
        IssueCD d = new IssueCD();

        root.setA(a);
        a.setB(Lists.newArrayList(b).toArray());
        b.setC(c);
        c.setD(d);
        d.setE(Lists.newArrayList(c));

        System.out.println(JSON.toJSONString(root, SerializerFeature.PrettyFormat, SerializerFeature.WriteMapNullValue));
        System.out.println(JSON.toJSONString(root));

    
   `第一个输出：
{
	"a":{
		"b":[
			{
				"c":{
					"d":{
						"e":[
							{"$ref":"$.a.b.null.c"}
						]
					}
				}
			}
		]
	}
}`

`第二个输出：
{"a":{"b":[{"c":{"d":{"e":[{"$ref":"$.a.b[0].c"}]}}}]}}
`

`因为使用SerializerFeature.PrettyFormat时，在处理数组的序列化时，走了不同的逻辑，导致出现{"$ref":"$.a.b.null.c"}
`

**Comment by Certseeds** [comment]
``` java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import com.google.common.collect.Lists;
import lombok.Data;
import org.junit.Test;

import java.util.ArrayList;

public class Issue3672 {
    @Test
    public void test1() {
        Issue3672Root root = new Issue3672Root();
        Issue3672A a = new Issue3672A();
        Issue3672B b = new Issue3672B();
        Issue3672C c = new Issue3672C();
        Issue3672D d = new Issue3672D();
        root.setA(a);
        a.setB(new Issue3672B[]{b});
        b.setC(c);
        c.setD(d);
        d.setE(Lists.newArrayList(c));
        System.out.println(JSON.toJSONString(root, SerializerFeature.PrettyFormat, SerializerFeature.WriteMapNullValue));
        System.out.println(JSON.toJSONString(root));
    }

    @Data
    private class Issue3672Root {
        private Issue3672A a;
    }

    @Data
    private class Issue3672A {
        private Issue3672B[] b;
    }

    @Data
    private class Issue3672B {
        private Issue3672C c;
    }

    @Data
    private class Issue3672C {
        private Issue3672D d;
    }

    @Data
    private class Issue3672D {
        private ArrayList<Issue3672C> e;
    }

}
```

运行输出如下

``` log
{
	"a":{
		"b":[{
			"c":{
				"d":{
					"e":[
						{"$ref":"$.a.b[0].c"}
					]
				}
			}
		}]
	}
}
{"a":{"b":[{"c":{"d":{"e":[{"$ref":"$.a.b[0].c"}]}}}]}}
```
没复现

**Comment by Certseeds** [comment]
PS:
`a.setB(new Issue3672B[]{b});` =>`a.setB(Lists.newArrayList(b).toArray(new Issue3672B[0]));`不会改变输出.
