### ISSUE TITLE
后台返回的数据不规范 

### ISSUE THREAD

**Issue by oooo7777777** [alibaba/fastjson#3681]
我是Android  后台返回的数据不规范 
int 返回 null 
Boolean 也返回 null 
请问这个有办法在解析的时候就处理吗?
如果int 返回 null 就改成0
Boolean 返回 null  就改成false

**Comment by miRUAcleInjoker** [comment]
int应该是返回0吧。
Boolean返回null也是应该的。 boolean默认值才是false

**Comment by pptom** [comment]
jackson能支持你这种需求
