### ISSUE TITLE
JSONException: syntax error, expect {, actual error, pos 1

### ISSUE THREAD

**Issue by gzu-liyujiang** [alibaba/fastjson#371]
报错：
JSONException: syntax error, expect {, actual error, pos 1。
内容：
{"code":1,"msg":"\u83b7\u53d6\u6570\u636e\u6210\u529f","data":{"versionName":"v1.0","versionCode":1,"content":"\u521d\u59cb\u7248\u672c","url":"http:\/\/***.apk"}}

**Comment by LQZYC** [comment]
能上完整的示例吗

**Comment by gzu-liyujiang** [comment]
问题已经解决了，好像是因为缓冲输出json时多加了header所致

**Comment by biaji** [comment]
遇到同样问题，经查，是utf-8字串开头的BOM没有正确识别导致。

lexar对于BOM直接parse成ERROR

**Comment by biaji** [comment]
result = {byte[52]@830027686176} 
 0 = -17
 1 = -69
 2 = -65
 3 = -17
 4 = -69
 5 = -65
 6 = 123
