### ISSUE TITLE
nested type arguments is derived to List type,actually not List

### ISSUE THREAD

**Issue by drgnchan** [alibaba/fastjson#3715]
exception message:
`Exception in thread "main" com.alibaba.fastjson.JSONException: exepct '[', but {, pos 21,`
this is the demo to reproduce the problem:
`https://github.com/drgnchan/fastjsonbugdemo.git`
i dont know if i am using the wrong style.

**Comment by Certseeds** [comment]
now this can close.
@drgnchan

**Comment by drgnchan** [comment]
> Has this problem been resolved? I found that using generics in List seems to cause problems.

[https://github.com/drgnchan/fastjsonbugdemo/pull/1](url)
@Certseeds provides another way to resolve the problem.
![image](https://user-images.githubusercontent.com/40224023/114528092-40fa7b80-9c7b-11eb-8560-ffa7c281933b.png)

**Comment by Ryyyc** [comment]
https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/parser/deserializer/ArrayListTypeFieldDeserializer.java#L163-L185

In **ArrayListTypeFieldDeserializer.java**, determine that the current character is `[` in line 164, get the next character in line 170, and then go to line 184, ready to parse an array.
<br>

https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/parser/deserializer/ArrayListTypeFieldDeserializer.java#L184

<br>

It jump to **CollectionCodec.java**;
https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/serializer/CollectionCodec.java#L110-L129

<br>

https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/serializer/CollectionCodec.java#L126

<br>

Then, jump to **DefaultJSONParser.java**.
https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/parser/DefaultJSONParser.java#L733-L742

<br>

In **DefaultJSONParser.java**, it again judges whether the current character is`[`, but the character position has been moved to the next of `[` above.

I don't quite understand this place.

**Comment by drgnchan** [comment]
>In DefaultJSONParser.java, it again judges whether the current character is[, but the character position has been moved to the next of [ above.

actually when deserialize the list item,the `itemTypeDeser` is derived to be `CollectionCodec`.so it again judges whether the current character is `[`.

https://github.com/alibaba/fastjson/blob/14a95cc5b07e76ab8c0c72192c1e739cb157c7fc/src/main/java/com/alibaba/fastjson/parser/deserializer/ArrayListTypeFieldDeserializer.java#L106-L111

in my opinion,it is odd.

**Comment by Certseeds** [comment]
PS:
in fact,
![image](https://user-images.githubusercontent.com/51754303/114572648-40c5a480-9caa-11eb-8abe-1debc492db10.png)
this can also solve the problem

**Comment by Certseeds** [comment]
问题不是出在解析上,而是typereference不带参数的初始化只针对单层泛型有效,多层嵌套就得像上图一样加参数

**Comment by Ryyyc** [comment]
> 问题不是出在解析上,而是typereference不带参数的初始化只针对单层泛型有效,多层嵌套就得像上图一样加参数

OK, Thanks.
