### ISSUE TITLE
为什么不开一个直接从InputStream反序列化成对象的接口呢？

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/fastjson#374]
例如：
parseObject(InputStream input, Type clazz)

**Comment by LQZYC** [comment]
这种需求很多吗

**Comment by foxinmy** [comment]
请使用

    <T> T com.alibaba.fastjson.JSON.parseObject(byte[] input, Type clazz, Feature... features)

**Comment by wenshao** [comment]
如果不是数十M以上的文本，readToString然后parse速度更快。不打算支持这个API，先关了啊

**Comment by zl7261** [comment]
com.alibaba.fastjson.JSON

  /**
     * @since 1.2.11
     */
    @SuppressWarnings("unchecked")
    public static <T> T parseObject(InputStream is, //
                                    Type type, //
                                    Feature... features) throws IOException {
        return (T) parseObject(is, IOUtils.UTF8, type, features);
    }
