### ISSUE TITLE
使用stringbuilder代替string提高效率

### ISSUE THREAD

**Issue by yinpeiqi** [alibaba/fastjson#3765]
类似JavaBeanSerializer，有一些地方使用了简单的字符串拼接。改为stringbuilder可提高效率。

**Comment by vipcxj** [comment]
我觉得你误解了stringbuilder所解决的性能问题~ 只有当特别多的字符串拼接，使用StringBuilder才是有意义的，这样可以避免频繁申请内存和内存浪费，但你改的地方完全没意义~ 只是为了用StringBuilder而用StringBuilder，性能提升什么的根本不存在~
