### ISSUE TITLE
Set 带类信息序列化的时候格式有问题，导致反序列化报错

### ISSUE THREAD

**Issue by huashanyu** [alibaba/fastjson#378]
代码
		
		Map<String, String> map = new HashMap<String, String>();
		map.put("name", "zhangsan");
		map.put("job", "software engineer");
		System.out.println(JSON.toJSONString(map, SerializerFeature.WriteClassName));
		
		HashSet<String> set = new HashSet<String>();
		set.add("java");set.add("oracle");
		System.out.println(JSON.toJSONString(set, SerializerFeature.WriteClassName));
		
输出
               {"@type":"java.util.HashMap","name":"zhangsan","job":"software engineer"}
               Set["java","oracle"]

Set["java","oracle"]  这种格式是JSON 吗？？

**Comment by qifanyang** [comment]
这个问题是生成反序列化的ASM代码有问题,手动生成asm代码很繁琐, 在JDK8上开启asm效率也不一定会提高.

使用:ParserConfig.getGlobalInstance().setAsmEnable(false);关闭asm.即可解决

你的代码在反序列化之前设置个全局的吧,也可以设置局部的.
:ParserConfig.getGlobalInstance().setAsmEnable(false);
ts = JSON.parseObject(jsonStr, TestClass.class);

**Comment by huashanyu** [comment]
使用:ParserConfig.getGlobalInstance().setAsmEnable(false);关闭asm.即可解决

反序列化是没有问题了，但是 json 的格式还是有问题啊

**Comment by qifanyang** [comment]
fastjosn带类名的json格式是自己特有的格式,不是标准的json格式, 如果其它地方需要使用序列化出来的json数据,你不应该使用SerializerFeature.WriteClassName, 这种["java","oracle"] 在json里表示数组,不是Set

**Comment by wenshao** [comment]
SerializerFeature.WriteClassName 设计成这样的，不是bug
