### ISSUE TITLE
fastjson应默认关闭autotype

### ISSUE THREAD

**Issue by k4n5ha0** [alibaba/fastjson#3788]
xstream 和 jackson 越来越注意安全性，都在主推白名单
fastjson应默认关闭autotype，单个接口需要使用时提供白名单校验的autotype的编码方式，可以参照 XStream 的 setupDefaultSecurity

**Comment by NS-Sp4ce** [comment]
> 你这种人就应该拉黑名单。自己不去仔细研读文档，跑来叽叽歪歪。

这句话笑死我 为你的无知感到悲哀 hhhhhhhhhh

**Comment by Certseeds** [comment]
建议block该用户,附上指南[block user from your org](https://docs.github.com/cn/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization)

**Comment by k4n5ha0** [comment]
> 你这种人就应该拉黑名单。自己不去仔细研读文档，跑来叽叽歪歪。

拉黑我没关系，但是有多少安全事件是因为默认开启@type导致的！？阿里巴巴内部使用的就是noneautotype你怎么解释？

**Comment by k4n5ha0** [comment]
> 建议block该用户,附上指南[block user from your org](https://docs.github.com/cn/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization)

拉黑我没关系，但是
1）我没有骂人，也没有说脏话！ 
2）我之前两次留言关于@type的安全性问题，作者一次都没有理我！一次都没有！

**Comment by harkue** [comment]
看看你的行为， Issue轰炸

**Comment by k4n5ha0** [comment]
> 看看你的行为， Issue轰炸。一次性发这么多Issue，这种攻击行为比骂人更恶劣。
> 
> 如果觉得fastjson不合适，可以使用别的。没人强迫你使用。

你除了贬低我你还会什么，我起码认为这样做是因为信息安全很重要。
1、你到现在不正面回答我问题
2、你除了不断重复我行为恶劣没有实质建设性行为，你比我还要恶劣

**Comment by RLin2015New** [comment]
> 温绍锦你能不能搞个没有autotype的fastjson！！！
> xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！

可以参考一下 https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）

**Comment by k4n5ha0** [comment]
> > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> 
> 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)

我愤怒是因为我昨天知道阿里巴巴内部使用的fastjson是默认没有autotype的！

**Comment by k4n5ha0** [comment]
> > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> 
> 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C)
> 作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（issue轰炸不礼貌，你还点名道姓的... ... 换位思考下，如果你在网上做开源，别人因为缺陷点名道姓说你，你也会不高兴吧。 做开源图啥呢）

我试图努力过了，你去搜索下我的历史留言，你再去搜索下其他程序员的留言。你再去了解下这几年的信息安全事件。你再去了解下最新的两个fastjson的漏洞构造。我昨天是良心实在看不下去了。你觉得我人品有问题都可以，真的。我不在乎！你们屏蔽我都不在乎，起码我最后努力这一次！

**Comment by RLin2015New** [comment]
> > > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > 
> > 
> > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> 
> 我愤怒是因为我昨天知道阿里巴巴内部使用的fastjson是默认没有autotype的！

没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用issue轰炸，也不要点名道姓哈。
国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。

**Comment by k4n5ha0** [comment]
> > > > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > > > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > > 
> > > 
> > > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> > 
> > 
> > 我愤怒是因为我昨天知道阿里巴巴内部使用的fastjson是默认没有autotype的！
> 
> 没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用issue轰炸，也不要点名道姓哈。
> 国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。

您能心平气和和我探讨我感觉自己确实做的过分了，您查一下历史上的留言就知道了，默认关闭@type不只是我一个人提出的建议。无奈官方不做任何处理。其实默认关闭autotype改一行代码就行了。

**Comment by NS-Sp4ce** [comment]
> > > > 温绍锦你能不能搞个没有 autotype 的 fastjson！！！
> > > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么 fastjson 一直故意不做这个措施！
> > > > 到现在这么多安全事故了！！！！！还在开放 @type！！！！！！！！！
> > > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > > 
> > > 
> > > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈～（尤其 issue 轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> > 
> > 
> > 我愤怒是因为我昨天知道阿里巴巴内部使用的 fastjson 是默认没有 autotype 的！
> 
> 没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用 issue 轰炸，也不要点名道姓哈。
> 国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。

以目前的行为和最初的仿照oracle的黑名单模式来看，就注定补丁是要被不断绕过的。而且1.2.42[把原本明文的黑名单改成了哈希过的黑名单](https://github.com/LeadroyaL/fastjson-blacklist)，防止安全研究者对其进行研究的行为来看，并不太像是要解决问题的样子。

**Comment by k4n5ha0** [comment]
> > > > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > > > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > > 
> > > 
> > > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> > 
> > 
> > 我愤怒是因为我昨天知道阿里巴巴内部使用的fastjson是默认没有autotype的！
> 
> 没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用issue轰炸，也不要点名道姓哈。
> 国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。

已经将观感不好的内容update了，最后一次期望官方能给个回应。

**Comment by RLin2015New** [comment]
> > > > > 温绍锦你能不能搞个没有 autotype 的 fastjson！！！
> > > > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么 fastjson 一直故意不做这个措施！
> > > > > 到现在这么多安全事故了！！！！！还在开放 @type！！！！！！！！！
> > > > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > > > 
> > > > 
> > > > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈～（尤其 issue 轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> > > 
> > > 
> > > 我愤怒是因为我昨天知道阿里巴巴内部使用的 fastjson 是默认没有 autotype 的！
> > 
> > 
> > 没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用 issue 轰炸，也不要点名道姓哈。
> > 国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。
> 
> 以目前的行为和最初的仿照oracle的黑名单模式来看，就注定补丁是要被不断绕过的。而且1.2.42[把原本明文的黑名单改成了哈希过的黑名单](https://github.com/LeadroyaL/fastjson-blacklist)，防止安全研究者对其进行研究的行为来看，并不太像是要解决问题的样子。

@wenshao 希望有空了能关注一下，一起参与下讨论。目前大家对于这个点确实很困惑~

**Comment by k4n5ha0** [comment]
> > > > > > 温绍锦你能不能搞个没有 autotype 的 fastjson！！！
> > > > > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么 fastjson 一直故意不做这个措施！
> > > > > > 到现在这么多安全事故了！！！！！还在开放 @type！！！！！！！！！
> > > > > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > > > > 
> > > > > 
> > > > > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈～（尤其 issue 轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> > > > 
> > > > 
> > > > 我愤怒是因为我昨天知道阿里巴巴内部使用的 fastjson 是默认没有 autotype 的！
> > > 
> > > 
> > > 没有谁做开源是想故意坑大家的。现在这状况可能是因为对外开源面对的情况和单一公司的情况不完全一样，而且用哪个版本是否升级这个也取决于各自团队的具体情况和想法，作者估计也没有料想到现在这个状况。可以理解你的愤怒，但是我觉得还是不要用 issue 轰炸，也不要点名道姓哈。
> > > 国人做开源本来就不容易，谁也不希望有问题，出了问题大家一起来解决。作者没有考虑到没有总结到的经验如果我们发现了，可以提的，本来社区就有讨论的空间。
> > 
> > 
> > 以目前的行为和最初的仿照oracle的黑名单模式来看，就注定补丁是要被不断绕过的。而且1.2.42[把原本明文的黑名单改成了哈希过的黑名单](https://github.com/LeadroyaL/fastjson-blacklist)，防止安全研究者对其进行研究的行为来看，并不太像是要解决问题的样子。
> 
> @wenshao 希望有空了能关注一下，一起参与下讨论。目前大家对于这个点确实很困惑~

呵呵，依旧是无视我们，连个表情都懒得发。

**Comment by whcrow** [comment]
> > > 温绍锦你能不能搞个没有autotype的fastjson！！！
> > > xstream 和 jackson 越来越注意安全性，都在主推白名单！为什么fastjson一直故意不做这个措施！
> > > 到现在这么多安全事故了！！！！！还在开放@type！！！！！！！！！
> > > 你真的是要故意制造网络安全问题才开心吗！！！！！！！！！！！！！！！！！
> > 
> > 
> > 可以参考一下 [https://github.com/alibaba/fastjson/wiki/enable_autotype，作者也在努力，作为开源包的使用者，我觉得我们还是一起来努力解决问题而不是只是抱怨哈~（尤其issue轰炸有点不礼貌）](https://github.com/alibaba/fastjson/wiki/enable_autotype%EF%BC%8C%E4%BD%9C%E8%80%85%E4%B9%9F%E5%9C%A8%E5%8A%AA%E5%8A%9B%EF%BC%8C%E4%BD%9C%E4%B8%BA%E5%BC%80%E6%BA%90%E5%8C%85%E7%9A%84%E4%BD%BF%E7%94%A8%E8%80%85%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E6%88%91%E4%BB%AC%E8%BF%98%E6%98%AF%E4%B8%80%E8%B5%B7%E6%9D%A5%E5%8A%AA%E5%8A%9B%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8F%AA%E6%98%AF%E6%8A%B1%E6%80%A8%E5%93%88~%EF%BC%88%E5%B0%A4%E5%85%B6issue%E8%BD%B0%E7%82%B8%E6%9C%89%E7%82%B9%E4%B8%8D%E7%A4%BC%E8%B2%8C%EF%BC%89)
> 
> 我愤怒是因为我昨天知道阿里巴巴内部使用的fastjson是默认没有autotype的！

你为fastjson做了什么贡献？
开源作者无偿服务，接不接受提议是作者的权利，选择用与不用也是你的权力，你在这直呼作者姓名，言辞愤慨，愤怒只是因为你无能，写不出fastjson这样的框架。
