### ISSUE TITLE
Undeclared exceptions thrown by JSON.parse

### ISSUE THREAD

**Issue by LandGrey** [alibaba/fastjson#3789]
I fuzz test fastjson version `1.2.76` and found 6 cases of undeclared exceptions (i.e., exceptions other than JSONException).

### Issue 1: `NumberFormatException`
```
try{
    JSON.parse("'\\u");
}catch (JSONException e){
}
```

### Issue 2: `NullPointerException`
```
try{
    JSON.parse("[TreeSet[NuLl");
    JSON.parse("TreeSet[NaN");
    JSON.parse("TreeSet[undefined");
}catch (JSONException e){
}
```

### Issue 3: `ArrayIndexOutOfBoundsException`
```
try{
    JSON.parse("{'\\x08\\x00\\t\\x\\xff\\xff\\xff\\xff\\xff'");
}catch (JSONException e){
}
```

### Issue 4: `ArithmeticException: Overflow`
```
try{
    JSON.parse("{'\\x08\\x00\\t\\x\\xff\\xff\\xff\\xff\\xff'");
}catch (JSONException e){
}
```

### Issue 5: `IllegalArgumentException`
```
String name = "java.sql.Time\"\"X";
String full = "{\"@type\":\"" + name + "\"}";
try{
    JSON.parse(full);
}catch (JSONException e){
}
```

### Issue 6: `ClassCastException`
```
String name = "java.util.concurrent.atomic.AtomicReference\"X";
name = "java.lang.ref.WeakReference\"X";
name = "java.lang.ref.SoftReference\"X";

String full = "{\"@type\":\"" + name + "\"}";
try{
    JSON.parse(full);
}catch (JSONException e){
}
```

**Comment by RLin2015New** [comment]
我个人觉得案例1-4的报错应该是合适的。
因为作为JSON的处理工具，fastjson应该本身预期就是处理正常的json格式字符串（这点感觉应该由使用者来保障），对于非json格式的字符串，该怎么报错就怎么报错（这样利于使用者自己看出来具体问题，而且也让fastjson要处理的字符串对象场景减少，比较利于高效处理）

对于5，报错的具体堆栈是
at java.sql.Time.valueOf(Time.java:110)
	at com.alibaba.fastjson.parser.deserializer.TimeDeserializer.deserialze(TimeDeserializer.java:77)
这里是因为TimeDeserializer转换时直接用的Time.valueOf的方法，而没有做格式校验，这里我个人的观点是，因为字符串格式已经符合json预期，但是值内容不符合Time的预期，既然已经定义了专门的转换器，应该在做值转换前做格式判断，或者是考虑转换函数会抛出异常转换成JSONException，这样更利于使用者来统一处理异常

对于6... 我不太懂你的预期是做什么转换...

**Comment by LandGrey** [comment]
Test Close
