### ISSUE TITLE
FastJsonHttpMessageConverter 跟springfox-swagger2一起使用有问题

### ISSUE THREAD

**Issue by wq163** [alibaba/fastjson#379]
访问/api-docs得到的结果是空的{} ，经排查发现是序列化springfox.documentation.spring.web.json.Json 对象的问题。而用 gson 序列化是没问题的。
```java
public class Json {
  private final String value;

  public Json(String value) {
    this.value = value;
  }

  @JsonValue
  @JsonRawValue
  public String value() {
    return value;
  }
}
```

**Comment by wq163** [comment]
兼容性方面一直没有 gson 等完善。希望增加对@JsonValue，@JsonRawValue，@JsonGetter等标准注解的支持

**Comment by lingzhm** [comment]
没有实现Serializable 接口无法对类的实例进行序列化。

**Comment by wenshao** [comment]
fastjson有JSONField字段啊，fastjson不能支持jackson的Annotation吧

**Comment by friedwm** [comment]
查了半天发现是fastjson的问题，找到这儿之前还以为是用的版本太旧还升级了版本，结果还是一样。 @wenshao 楼主贴出的代码是springfox-spring-web包里的，无法控制。

**Comment by friedwm** [comment]
https://github.com/springfox/springfox/issues/1339

**Comment by bianzhifu** [comment]
@friedwm 

```
public class SwaggerJsonSerializer implements ObjectSerializer {
    public void write(JSONSerializer serializer, Object object, Object fieldName, Type fieldType, int features) throws IOException {
        SerializeWriter out = serializer.getWriter();
        Json json = (Json) object;
        out.write(json.value());
    }
}
```

```
FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
FastJsonConfig fastJsonConfig = new FastJsonConfig();
fastJsonConfig.getSerializeConfig().put(Json.class,new SwaggerJsonSerializer());
converter.setFastJsonConfig(fastJsonConfig);
```

**Comment by yixblog** [comment]
> fastjson有JSONField字段啊，fastjson不能支持jackson的Annotation吧，上面的例子可以这样写：
> 
> ```java
> public class Json {
> private final String value;
> 
> public Json(String value) {
> this.value = value;
> }
> 
> @JSONField(name="value")
> public String value() {
> return value;
> }
> }
> ```

JSONField和JsonValue效果不同，@JsonValue是把这个field的值作为整个对象的值，也就是序列化这个Json对象的时候直接输出value字符串中的值如"a"，而不是{"value":"a"}...
