### ISSUE TITLE
How to don't serialize the class field in FastJson?

### ISSUE THREAD

**Issue by YataoWang** [alibaba/fastjson#3803]
Today I'm using FastJson, the following is my demo code.
`
class User {
  private final String name;
  private final int age;
  private final String birthday;
  private String password;

  public User(String name, int age, String birthday) {
    this.name = name;
    this.age = age;
    this.birthday = birthday;
  }

  public void setPassword(String pwd) {
    this.password = pwd;
  }

  public String getName() {
    return name;
  }

  public int getAge() {
    return age;
  }

  public String getBirthday() {
    return birthday;
  }

  public String getPassword() {
    return password;
  }

  @Override
  public String toString() {
    return "User{" +
            "name='" + name + '\'' +
            ", age=" + age +
            ", birthday='" + birthday + '\'' +
            ", password='" + password + '\'' +
            '}';
  }
}
`
It will serialize the field which has getXXX method. I do not want to serialize the password, and I will call the getPassword() to get the password value.

I do not want to rename the method getPassword and update the variable password to public.

Does anyone know how to ignore a field when serializing this class?

**Comment by wanghuzhou** [comment]
@JSONField(serialize = false)

**Comment by YataoWang** [comment]
Thanks for your answer. I got it from JSONField annotation yesterday. But I forgot to close this.
