### ISSUE TITLE
TypeUtils.castToJavaBean() 方法在Android Lollipop(ART)设备下耗时非常

### ISSUE THREAD

**Issue by yrom** [alibaba/fastjson#382]
上图为证
<img width="800" alt="qq20150731-1 2x" src="https://cloud.githubusercontent.com/assets/2888674/8999775/af019cfa-3771-11e5-828b-8aad28ea704c.png">

如图，关键点在于方法中的 `Type paramType = field.getGenericType();`这一行
改成直接从`FieldDeserializer`拿之后 `Type paramType = fieldDeser.getFieldType();`

<img width="597" alt="qq20150731-3 2x" src="https://cloud.githubusercontent.com/assets/2888674/8999845/5af84f9a-3772-11e5-94e3-d4bf06509a9c.png">

效果惊人！

**Comment by wenshao** [comment]
好主意，不过这个会影响到对泛形的支持吧

**Comment by yrom** [comment]
看源码`FieldDeserializer`的`FieldType`其实就是通过`field.getGenericType()`拿到的，而且经过测试，并没有问题
