### ISSUE TITLE
PropertyFilter by annotation

### ISSUE THREAD

**Issue by gitblit** [alibaba/fastjson#384]
I really like FastJSON even though I can't read half the issues or documentation.  :)  I'm happy to see that there is a PropertyFilter mechanism but I wish it was annotated/declarative like `@JSONField`.

Jackson offers `@JsonView` [1] which allows you to annotate property filters.  This is much less error-prone and refactor-safe since it does not rely on string field names.  I think FastJSON would benefit from a similar declarative mechanism.

- [1]: http://wiki.fasterxml.com/JacksonJsonViews

**Comment by wenshao** [comment]
Good idea！

**Comment by wenshao** [comment]
this feature has bean supported. Chinese Document: https://github.com/alibaba/fastjson/wiki/LabelFilter

test case : https://github.com/alibaba/fastjson/blob/master/src/test/java/com/alibaba/json/bvt/serializer/label/LabelIncludeTest3.java
