### ISSUE TITLE
fastjson在jdk1.8上面开启asm效率不如关闭高,默认该关闭了吧?

### ISSUE THREAD

**Issue by qifanyang** [alibaba/fastjson#385]
```java
		SerializeConfig config = new SerializeConfig();
		//config.setAsmEnable(false);//字关闭asm
		//long start = System.currentTimeMillis();

		//序列化一个200个属性的类,关闭asm用时大约0.160s,开启asm用时大约0.280s
		JSON.toJSONString(new _200FieldsBean(), config);
		
		//序列化三个200个属性的类,关闭asm用时大约0.214s,开启asm用时大约0.420s
//		JSON.toJSONString(new _200FieldsBean(), config);
//		JSON.toJSONString(new _201FieldsBean(), config);
//		JSON.toJSONString(new _202FieldsBean(), config);
		
		//序列化三个相同200个属性的类,关闭asm用时大约0.157s,开启asm用时大约0.280s
//		JSON.toJSONString(new _200FieldsBean(), config);
//		JSON.toJSONString(new _200FieldsBean(), config);
//		JSON.toJSONString(new _200FieldsBean(), config);

```

**Comment by wenshao** [comment]
跑一次预热不算啊

**Comment by qifanyang** [comment]
我的理解是跑第一次,asm创建字节码花费时间多.第一次创建会放入IdentityHashMap缓存,第二次直接使用.

但是我的测试使用一个带有200字段的类运行几次,在JDK8中开启asm花费大概是关闭的两倍,估计是JDK对反射做了优化,暂时没去读源码.

下面是测试代码:
		SerializeConfig config = new SerializeConfig();
		config.setAsmEnable(true);
		long start = System.currentTimeMillis();
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		System.out.println("open asm cost timeMillis: " + (System.currentTimeMillis() - start) + "ms");
		
		SerializeConfig config = new SerializeConfig();
		config.setAsmEnable(false);
		long start = System.currentTimeMillis();
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		JSON.toJSONString(new _200FieldsBean(), config);
		System.out.println("close asm cost timeMillis: " + (System.currentTimeMillis() - start) + "ms");

bean里面是200个int字段

**Comment by zhaiyuyong** [comment]
![Uploading image.png…]()
java version:1.8.0_40
jetty version:9.2.9.v20150224
fastjson version:1.2.3

现在老是出现metaspace oom 
打开jvm的-verbose:class

**Comment by qifanyang** [comment]
metaspace oom? 估计是fastjson创建字节码占用了太多metaspace, 你把空间设置大一些就不会OOM了

**Comment by zhaiyuyong** [comment]
但是metaspace是一直增长的，之前设置到512M OOM 现在设置到1G ，class load count也是一直增长unload 没有变化

**Comment by qifanyang** [comment]
[Loaded Serializer_3768 from file:/tmp/jetty-0.0.0.0-8080-bybev16.war-_bybev16-any-7392887708992491162.dir/webapp/WEB-INF/lib/fastjson-1.2.3.jar]

你这个估计是在不停的创建字节码,fastjson缓存的字节码没有使用到,你把JDK版本编程7或者6试试吧,然后再去看下jdk8 metaspace的模型这些, 我对jdk8 metaspace也不了解

**Comment by zhaiyuyong** [comment]
OK  我试试jdk7  但是这台机器上另外一个springboot应用也使用的fastjson同样版本没问题，出问题的是使用jetty启的war

**Comment by wenshao** [comment]
需要将SerializeConfig缓存起来，或者使用SerializeConfig.globalInstance
