### ISSUE TITLE
fastjson是否支持检测重复的key报错？

### ISSUE THREAD

**Issue by yaojuncn** [alibaba/fastjson#388]
版本：fastjson 1.2.6 如下代码输出woman， 
        String json = "{'a': 'man', 'a': 'woman'}";
        JSONObject o = JSON.parseObject(json);
        System.out.println(o.get("a"));
有时候希望对这样对json检测出有重复的key，报异常出来， 
不知道fastjson没有这样的feature？粗看了下好像fastjson不支持？
其他一些json库对这个有支持，如果fastjson目前不支持， fastjson能增加这个feature么？

ecma404没有说明重复key的情况
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
但是rfc7159有说到key不能重复
http://tools.ietf.org/html/rfc7159#section-4
谢谢

**Comment by qifanyang** [comment]
这个可以加,需要记录序列化了哪些key,有重复就报错

**Comment by wenshao** [comment]
```
Many implementations report the last name/value pair only.  Other implementations report an error or fail to parse the object, and some implementations report all of the name/value pairs, including duplicates.
```
rfc7159并没有说不能重复，所以这个特性不做。

**Comment by yaojuncn** [comment]
"The names within an object SHOULD be unique.", rfc7159说json本身应该是name unique的， 不是unique的情况的确行为未定义。 
但是作为一个json解析的库来说，如果能够支持这个特性， 那自然是一个‘good to have'的feature

**Comment by lemon-tree-sheng** [comment]
希望能加上这个特性
