### ISSUE TITLE
继承ArrayList的类的反序列化，元素类型不对

### ISSUE THREAD

**Issue by liujingjing5** [alibaba/fastjson#389]
```java
	   public static class User{
		String name;
		String value;
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		public String getValue() {
			return value;
		}
		public void setValue(String value) {
			this.value = value;
		}
		   
	   }
	   
	public static class Def extends ArrayList<User> {

	}

	public static void main(String[] args){
		Def def = new Def();
		def.add(new User());
		String defStr = JSON.toJSONString(def);

		Def _def = JSON.parseObject(defStr, new TypeReference<Def>() {});
		Object o = _def.get(0);   //这里得到的是JSONObject，应该返回一个User啊
		System.out.println("end");		   
        }
```

**Comment by qifanyang** [comment]
public static class Def<T> extends ArrayList<T> { }

    public static void main(String[] args){
        Def<User> def = new Def<User>();
        User user = new User();
        def.add(user);
        String defStr = JSON.toJSONString(def);
        
        //该这么用
        Def<?> _def = JSON.parseObject(defStr, new TypeReference<Def<User>>() {});
        Object o = _def.get(0);   //这里得到的是JSONObject，应该返回一个User啊
        System.out.println("end");         
        }

**Comment by wenshao** [comment]
bug fixed. i will include in 1.2.9 & 1.1.49.android
