### ISSUE TITLE
JDK11中，代码强制ParameterizedTypeImpl转换时出现异常，jdk8没有问题

### ISSUE THREAD

**Issue by qurenneng** [alibaba/fastjson#3890]
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class com.alibaba.fastjson.util.ParameterizedTypeImpl (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl is in module java.base of loader 'bootstrap'; com.alibaba.fastjson.util.ParameterizedTypeImpl is in unnamed module of loader 'app')

**Comment by qurenneng** [comment]
![image](https://user-images.githubusercontent.com/31475285/131485015-ac8dfa02-39d5-4146-a45f-bfbfb3313ae6.png)

**Comment by qurenneng** [comment]
Type[] actualTypeArguments = ((ParameterizedTypeImpl) method.getGenericParameterTypes()[i]).getActualTypeArguments();
这是项目中的转换的代码

**Comment by laoxu-83** [comment]
楼主解决问题了吗，我也遇到了类似的问题

**Comment by formingform** [comment]
我也碰到这个问题：
class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class com.alibaba.fastjson2.util.ParameterizedTypeImpl \u0028sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.util.ParameterizedTypeImpl is in unnamed module of loader 'app'\u0029
