### ISSUE TITLE
序列化时能够忽略伪getter方法: 不是getter method, 但名字是: getXXX()

### ISSUE THREAD

**Issue by theantway** [alibaba/fastjson#390]
序列化时能够忽略伪getter方法: 不是getter method, 但名字是: getXXX()

场景: 对应某些第三方系统或遗留系统, 有些类里面定义了 getXXX方法, 如果调用可能会出错(比如状态检查出错), 作为序列化的工具, 应该能够 支持忽略 这种方法, 比如增加新的Feature

**Comment by qifanyang** [comment]
@theantway  关于:如果调用可能会出错(比如状态检查出错)?什么意思呢

**Comment by wenshao** [comment]
我先关闭啦，有问题再反馈
