### ISSUE TITLE
请问一下为何纯数字是合法的JSON？

### ISSUE THREAD

**Issue by amosnothing** [alibaba/fastjson#3905]
![image](https://user-images.githubusercontent.com/24653016/134843396-594dba16-c926-4483-8834-2771fd871996.png)

**Comment by amosnothing** [comment]
v1.2.78

**Comment by wuare** [comment]
纯数字本来就是合法的json，json包括 对象、数组、字符串、true、false、null这几种值
@amosnothing

**Comment by amosnothing** [comment]
> 纯数字本来就是合法的json，json包括 对象、数组、字符串、数字、true、false、null这几种值 @amosnothing

3q
