### ISSUE TITLE
序列化对象时，结果中少了一个属性

### ISSUE THREAD

**Issue by lwj0216** [alibaba/fastjson#392]
// 用户id
private int id;
// 用户名
private String userName;
// 密码
private String password;
// 等级 
private int degree;
以上是类的属性，采用JSON.toJSONString(user)时，结果丢失了userName这一属性，但是，修改属性名userName为name时，重新调用该方法，结果返回正常。何解？

**Comment by qifanyang** [comment]
userName属性是否为空,为空可以开启SerializerFeature.WriteMapNullValue

或者贴出你的测试代码吧

**Comment by lwj0216** [comment]
谢谢，检查了一下，userName这个属性是null，所以导致了上述问题；有一个问题还要请教一下，序列化的时候，是否是按照类的字段名来生成json字符串的呢？
我的测试类如下：
public class User implements Serializable {
	private int id;
	private String userName;
	private String password;
	private int degree;
	public User() {
		
	}
	public User(int id, String userName, String password, int degree) {
		super();
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.degree = degree;
	}
}
有getters和setters，测试代码如下：

import com.alibaba.fastjson.JSON;

public static void main(String[] args) {
		User user = new User(1, "user", "password", 1);
		System.out.println(JSON.toJSONString(user));
}
打印结果为：{"degree":1,"id":1,"name":"user","password":"password"}
字段名是userName，而toJSONString之后，返回的json字符串中对应的属性名称变成了name

**Comment by qifanyang** [comment]
你的例子我这输出
```json
{"degree":1,"id":1,"password":"password","userName":"user"}
```

**Comment by lwj0216** [comment]
我把IDE里面的类文件删除了以后，再拷贝一模一样的进去，重新运行，结果正常了=.=，也许是哪个细微的地方我没注意到。还是要谢谢你。
