### ISSUE TITLE
1.2.77和1.2.78版本杀毒软件报毒

### ISSUE THREAD

**Issue by xiadr** [alibaba/fastjson#3965]
1.2.77和1.2.78版本杀毒软件报毒，1.2.76版本无问题，请确认是否被植入木马，多谢。
https://www.virustotal.com/gui/file/67d77f1cdab86d6b14cd5a1ada168bbf68179079975a16ec8efd07fc325d0cc0/detection
![image](https://user-images.githubusercontent.com/7677300/144233360-0a0a5065-a8c8-4295-a31b-ac80d61f0cd6.png)
https://www.virustotal.com/gui/file/40d72d8f0f1a99c83ec3ff3f48e99d3b280630105608997bafc2b0cb22f2adf3/detection
![image](https://user-images.githubusercontent.com/7677300/144233408-44b2af0f-6e37-43f8-96b2-fd199b34a489.png)

**Comment by wenshao** [comment]
已经和相关安全同学确认，是杀毒软件误报，并已反馈信息给安全厂商。
