### ISSUE TITLE
FastJsonHttpMessageConverter和springdoc-openapi冲突

### ISSUE THREAD

**Issue by 6543x1** [alibaba/fastjson#4011]
访问swagger-ui.html时发现无法正常显示
访问v3/api-docs，发现里面的json被异常转换，导致swagger-ui无法正常显示：
`"{\"openapi\":\"3.0.1\",\"servers\":[{\"url\":\"http://localhost:8099\",\"description\":\"Generated server url\"}],\"tags\":[{\"name\":\"申请方向\"}],\"paths\":{\"/apply\":{\"post\":{\"tags\":[\"申请方向\"],\"summary\":\"申请\",\"operationId\":\"applyForJobs\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/ApplicationBO\"}}}},\"responses\":{\"200\":{\"description\":\"OK\",\"content\":{\"application/json;charset=UTF-8\":{\"schema\":{\"$ref\":\"#/components/schemas/Result\"}}}}}}}},\"components\":{\"schemas\":{\"ApplicationBO\":{\"type\":\"object\",\"properties\":{\"no\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"campus\":{\"type\":\"string\"},\"grade\":{\"type\":\"object\"},\"profession\":{\"type\":\"string\"},\"access\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"},\"introduction\":{\"type\":\"string\"},\"mail\":{\"type\":\"string\"},\"phone\":{\"type\":\"string\"},\"updatetime\":{\"type\":\"string\",\"format\":\"date-time\"},\"jobs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}}},\"Result\":{\"type\":\"object\",\"properties\":{\"code\":{\"type\":\"integer\",\"format\":\"int32\"},\"status\":{\"type\":\"boolean\"},\"msg\":{\"type\":\"string\"},\"data\":{\"type\":\"object\"}}}}}}"`

converter配置如下，去掉下面配置后后swagger恢复正常
```
@Configuration
public class FastJsonConfiguration implements WebMvcConfigurer {
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        FastJsonHttpMessageConverter fastJsonHttpMessageConverter = new FastJsonHttpMessageConverter();
        FastJsonConfig fastJsonConfig = new FastJsonConfig();
        fastJsonConfig.setSerializerFeatures(
                SerializerFeature.DisableCircularReferenceDetect,
                SerializerFeature.WriteNullListAsEmpty,
                SerializerFeature.WriteNullStringAsEmpty,
                SerializerFeature.WriteMapNullValue
        );
        fastJsonHttpMessageConverter.setFastJsonConfig(fastJsonConfig);
        List<MediaType> fastMediaTypes = new ArrayList<>();
        fastMediaTypes.add(MediaType.APPLICATION_JSON);
        fastJsonHttpMessageConverter.setSupportedMediaTypes(fastMediaTypes);
        converters.add(0,fastJsonHttpMessageConverter);

    }
}
```

依赖如下：
```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.79</version>
        </dependency>
       <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.4</version>
        </dependency>

```

**Comment by 6543x1** [comment]
经过打断点分析，发现原来使用springfox时，传到`com.alibaba.fastjson.serializer.SerializeConfig#getObjectWriter(java.lang.Class<?>, boolean)` 这里时，class是`springfox.documentation.spring.web.json.Json`，fastjson对此作了特殊处理，因此可以保持原样。而改换springdoc时，此处传入的class却是String! 而fastjson默认会对String进行处理，加上转义符号，因此导致最终的结果出现异常。
解决办法：1、换成Jackson的converter（springboot默认就是Jackson）
2、自定义一个StringSerializer，覆盖掉fastjson的默认的StringSerializer
```
public class MyStringSerializer implements ObjectSerializer {
    public static final MyStringSerializer instance = new MyStringSerializer();
    @Override
    public void write(JSONSerializer serializer, Object object, Object fieldName, Type fieldType, int features) throws IOException {
        SerializeWriter out = serializer.getWriter();
        out.write(object.toString());
    }
}
```
然后在converter的配置文件中，如下使用
`fastJsonConfig.getSerializeConfig().put(String.class,MyStringSerializer.instance);`
即可覆盖掉fastjson默认的StringSerializer。
因为理解不是很透彻，不清楚fastjson为什么默认要对String进行字符转义处理，也不太清楚这样修改是否会导致其他后果，如果不妥希望能指出。

**Comment by 6543x1** [comment]
总算是明白为什么默认情况下是正常的，并不会触发Jackson的Serializer了。这和springboot中默认的converter顺序有关，如果像上面那样加到最前面，那么Fastjson会义无反顾的去帮你序列化所有标记为application/json的内容（因为我设置setSupportedMediaTypes为application/json，如果不设置的话默认是*/*，会对全部内容都进行json序列化处理)。
而springdoc中获取openapiJson源码如下：
```
@GetMapping(
        value = {"${springdoc.api-docs.path:#{T(org.springdoc.core.Constants).DEFAULT_API_DOCS_URL}}"},
        produces = {"application/json"}
    )
    public String openapiJson(HttpServletRequest request, @Value("${springdoc.api-docs.path:#{T(org.springdoc.core.Constants).DEFAULT_API_DOCS_URL}}") String apiDocsUrl, Locale locale) throws JsonProcessingException {
        return super.openapiJson(request, apiDocsUrl, locale);
    }
```
而springboot默认情况下，顺序是StringHttpMessageConverter在MappingJackson2HttpMessageConverter之前。StringHttpMessaghConverter支持的是text/plain, */*，因此当返回的内容为String类型时，只要类型是String.class并且类型不限（因为有个*/*），StringHttpMessaghConverter.canWrite就会返回true，因此默认情况下会使用StringHttpMessaghConverter。
但是如果是 FastJsonHttpMessageConverter放在最前面呢？嘿嘿，因为本来它的Content-type是application/json，所以content-type的检查通过，会进入类型是否支持的检查，而fastjson中：
`protected boolean supports(Class<?> clazz) {
        return true;
    }`
惊不惊喜，意不意外？
所以你的可怜的String类型的Json就被fastjson默认的String序列化器序列化了一遍，变成了上面提到的样子。
我顺便看了下AbstractJackson2HttpMessageConverter（也就是MappingJackson2HttpMessageConverter的父类）中对类型是否支持的检查，发现其对于类型是否支持的检查写了蛮多的，反正不是fastjson这么暴力的直接返回一个true。
那么最终解决办法是什么呢？个人有以下几种方法：
方法一：手动调整一下默认的converter的顺序，不要把fastjson塞最前面，这里就不赘述了。
方法二：fastjson依然塞最前面，但是手动修改fastjson默认的StringSerializer（楼上有提到），这样效果和方法一是一致的。（StringHttpMessageConverter类型检查就是检查是不是String，是就返回true）。
总之，如果你有多个converter需要使用，建议选择方法一。如果你觉得所有类型都可以交给fastjson去处理，可以选方法二。对于fastjson没法序列化或者序列化后结果不符合你要求的，可以手动添加自定义的Serializer。
方法三：抛弃fastjson（逃

**Comment by bncgnc** [comment]
细细细，赞
