### ISSUE TITLE
fastjson.serialize.SerializeConfig类中的343-347行代码表现的有些冗余？

### ISSUE THREAD

**Issue by coolqidedd** [alibaba/fastjson#403]
if (Proxy.isProxyClass(clazz)) {
                    put(clazz, createJavaBeanSerializer(clazz));
                } else {
                    put(clazz, createJavaBeanSerializer(clazz));
                }

空了看下，不胜感激。
version:1.2.6

**Comment by qifanyang** [comment]
#393  你有什么问题呢

**Comment by coolqidedd** [comment]
没有问题，学习代码看到这里。

**Comment by wenshao** [comment]
谢谢反馈，去掉了
