### ISSUE TITLE
序列化出不存在的字段

### ISSUE THREAD

**Issue by tangxuGoGoGo** [alibaba/fastjson#4030]
如果在一个对象中书写了诸如getMap（）、getAbc（）这样满足驼峰的函数，那么当进行序列化时，即使对象中并不存在map、Abc这样的字段，序列化的结果中也会包含此键。

**Comment by jet2you** [comment]
可以用这个SerializerFeature.IgnoreNonFieldGetter过滤，比如这样JSON.toJSONString(record, SerializerFeature.IgnoreNonFieldGetter)。默认的feature只有这四个：
![featrue](https://user-images.githubusercontent.com/8875647/153130070-e8fec3f6-d380-4e57-9a9d-d611a0428b0e.jpg)
解析的时候会根据这些feature来过滤
![ignoreGetter](https://user-images.githubusercontent.com/8875647/153130154-a6dfd729-0a77-4fef-8ba8-9df6feb9223c.png)
