### ISSUE TITLE
下划线字段_id和id只会序列化一个

### ISSUE THREAD

**Issue by pomole** [alibaba/fastjson#4059]
```java
public class main {
    public static void main(String[] args) {
        String value = "{\n" +
                "\t\"_id\": \"_id\",\n" +
                "\t\"id\": \"id\",\n" +
                "\t\"name\": \"name\"\n" +
                "}";

        Dto d = JSONObject.parseObject(value,Dto.class);
        System.out.println(JSONObject.toJSONString(d));
    }

    public static class Dto implements Serializable {
        @JSONField(name = "_id")
        private String _id;
        @JSONField(name = "id")
        private String id;
        private String name;

        public String get_id() {
            return _id;
        }

        public void set_id(String _id) {
            this._id = _id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

}

```

output:
```
{"_id":"_id","name":"name"}
```

**Comment by Koooooo-7** [comment]
当前的解决办法是把`@JSONField(name = "_id")` 放在`set_id`方法上。

**Comment by pomole** [comment]
> 当前的解决办法是把`@JSONField(name = "_id")` 放在`set_id`方法上。
都尝试过，还是不行
![image](https://user-images.githubusercontent.com/34085135/159468355-144abaf5-7769-4d90-9f89-670733cac58c.png)

**Comment by pomole** [comment]
> > 当前的解决办法是把`@JSONField(name = "_id")` 放在`set_id`方法上。
> > 都尝试过，还是不行
> 
> ```java
> public class main {
>     public static void main(String[] args) {
>         String value = "{\n" +
>                 "\t\"_id\": \"_id\",\n" +
>                 "\t\"id\": \"id\",\n" +
>                 "\t\"name\": \"name\",\n" +
>                 "\t\"_name\":\"_name\"\n" +
>                 "}";
>         Dto d = JSONObject.parseObject(value, Dto.class);
>         System.out.println(JSONObject.toJSONString(d));
> 
>     }
> 
>     public static class Dto implements Serializable {
>         @JSONField(name = "_id")
>         private String _id;
>         @JSONField(name = "id")
>         private String id;
>         private String name;
>         private String _name;
> 
>         public String get_name() {
>             return _name;
>         }
> 
>         public void set_name(String _name) {
>             this._name = _name;
>         }
> 
>         public String get_id() {
>             return _id;
>         }
> 
>         public void set_id(String _id) {
>             this._id = _id;
>         }
> 
>         public String getId() {
>             return id;
>         }
> 
>         public void setId(String id) {
>             this.id = id;
>         }
> 
>         public String getName() {
>             return name;
>         }
> 
>         public void setName(String name) {
>             this.name = name;
>         }
>     }
> 
> }
> ```
> 
> output
> 
> ```
> {"_name":"name","id":"_id"}
> ```

```b

**Comment by pomole** [comment]
```java
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.79</version>
        </dependency>

```
