### ISSUE TITLE
提一个小改进，如果感觉没有必要可以忽略

### ISSUE THREAD

**Issue by GinKoSen** [alibaba/fastjson#407]
使用场景：
开发过程中可能会遇到发送给客户端的数据中有使用@JSONField(serialize = false)注解的字段【如道具列表】。
这份数据服务端可能还要缓存到redis缓存服务器，缓存中使用的是json字符串，这时候就会发觉缓存的json字符串中使用注解的属性不会被序列化到json，反序列化，这些注解的字段也就没有了。

所以希望可以增加一个SerializerFeature枚举项，可以在JSON.parseObject("...", VO.class, Feature.DisableCircularReferenceDetect)调用时，跳过@JSONField(serialize = false)注解，使用完全序列化。

**Comment by qifanyang** [comment]
你这个需求可以不使用JSONField(serialize = false)注解.
当你需要发送数据到客户端时你使用Filter吧,忽略掉你前面注解的字段,
你反序列化也不会跳过某些数据了.暂时没看到忽略注解的的Feature设置

**Comment by GinKoSen** [comment]
嗯嗯，写filter来忽略注解字段的确是一种解决方案。但是这样处理起来，看起来不友好，一些使用了注解都需要来做。

**Comment by GinKoSen** [comment]
其实这种鞋filter的方式，和在发送数据层写一段vo转换，只发送必要字段一样了。所以感觉还是不是很好。

**Comment by qifanyang** [comment]
JSONField(serialize = false)一般不会写很多吧,如果你很多字段都使用了该注解,那的确该自己写个VO转换了.如果需要发送的字段很多而且需要忽略的字段也很多,的却是个问题,不过你可以自己修改下源码,把注解那修改下就ok了, 这个改动不大可以自己改的

**Comment by GinKoSen** [comment]
恩。用的是maven导包，而且害怕修改之后影响功能或者性能。
考虑准备自定义一套注解，传递给Filter，让filter把给定的数据跳过。

**Comment by qifanyang** [comment]
所以最终还是决定用filter了 :smile:

**Comment by GinKoSen** [comment]
暂时权衡之策，觉得官方如果做了在JSON.parseObject("...", VO.class, Feature.DisableCircularReferenceDetect)调用时，跳过@JSONField(serialize = false)注解，是最完美的解决。。哈哈哈。

**Comment by GinKoSen** [comment]
我关闭这个issues了哈。。
