### ISSUE TITLE
2.0.1版本JSON.parseObject方法如果参数为null服务直接down

### ISSUE THREAD

**Issue by 970263611** [alibaba/fastjson#4091]
版本是2.0.1
Map<String, String> userMap = JSON.parseObject(null, Map.class)
这段代码会导致服务直接down掉
经过测试低版本是没有这个问题的

**Comment by ziqingkeshi** [comment]
确实，代理里有JSON.parseObject(null)，直接JVM挂了

**Comment by neal-wyz** [comment]
同上

**Comment by wsxe9988** [comment]
已经修复，请使用2.0.2

**Comment by wenshao** [comment]
已经修复，请使用2.0,3
https://github.com/alibaba/fastjson2/releases/tag/2.0.3
