### ISSUE TITLE
关于Feature.DisableCircularReferenceDetect的问题。

### ISSUE THREAD

**Issue by GinKoSen** [alibaba/fastjson#412]
目前使用中对Feature.DisableCircularReferenceDetect
个人理解是，在反转json过程禁用循环引用检查。
业务参考的api文档，可否说下这个是什么作用。

**Comment by wenshao** [comment]
可以提升性能

**Comment by GinKoSen** [comment]
刚登陆看到。抱歉。

我想说明下我的问题。

代码截图：
![Image of GinKo](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/sp.png)

对于参数Feature.DisableCircularReferenceDetect表示不解。
