### ISSUE TITLE
1.2.6为啥这个反序列化报错JSON.parseObject(JSON.toJSONString(1))

### ISSUE THREAD

**Issue by yangl** [alibaba/fastjson#413]
如题，必须要指定反序列化的类型才可以！
JSON.parseObject(JSON.toJSONString(1), BigDecimal.class)

**Comment by dachuanz** [comment]
肯定的啊，JSON.toJSONString(1)的结果是1

**Comment by wenshao** [comment]
JSON.parse(JSON.toJSONString(1));
