### ISSUE TITLE
android studio 怎么引用fastjson

### ISSUE THREAD

**Issue by a1018875550** [alibaba/fastjson#416]
androidStudio 的build.gradle 里怎么引用fastjson

**Comment by hamsik2046** [comment]
同问  只能下载jar包  放到Libs包下面么

**Comment by andywj** [comment]
compile 'com.alibaba:fastjson:1.2.6'

**Comment by zuoyi001** [comment]
导入.jar
app目录build.gradle
dependencies {
    implementation files('libs/fastjson-1.2.7.jar')
}

**Comment by minirain2000** [comment]
@zuoyi001 
Build file 'F:\jack\2022\aip-ocr-android-sdk-2.0.0\aip-ocr-android-sdk-2.0.0\OCRDemo\build.gradle' line: 45

A problem occurred evaluating root project 'OCRDemo'.
> **Could not find method implementation() for arguments** [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
