### ISSUE TITLE
fastjson处理字典项，有什么好的办法么？

### ISSUE THREAD

**Issue by WangYu-Li** [alibaba/fastjson#417]
表里某些字段如性别，存的值是1，对应字典表里是男，然后hql后直接返回成实体类了，然后再用JSON.toJSONString()传给EasyUI的datagrid了，所以想问下，整个过程中，从哪一步处理把1替换成男最好？当然尽量不要说循环实体类好吧，先谢谢各位智慧的网友了。

**Comment by GinKoSen** [comment]
建议你看下，https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96这个。

**Comment by wenshao** [comment]
请参考GinKoSen给的连接
