### ISSUE TITLE
建议为FastJsonHttpMessageConverter增加dateFormatPattern变量注入

### ISSUE THREAD

**Issue by jadyer** [alibaba/fastjson#418]
当使用com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter进行fastjson与SpringMVC集成时，如果想自定义Date类型的Field序列化格式，目前只能参照FastJsonHttpMessageConverter自己写一个MessageConverter（默认的WriteDateUseDateFormat使用的是yyyy-MM-dd HH:mm:ss）。
我目前的集成方式详见https://github.com/jadyer/JadyerEngine/blob/master/JadyerEngine-web/src/main/resources/applicationContext.xml

**Comment by wenshao** [comment]
supported. it will included in 1.2.9.
