### ISSUE TITLE
反序列化日期和Byte  类型字段不得行

### ISSUE THREAD

**Issue by rw12306** [alibaba/fastjson#4181]
使用版本：fastjson2-2.0.4.jar ，1.2.83 版本也有这个问题
![image](https://user-images.githubusercontent.com/42023195/170903416-ea183b33-5760-41ef-94b1-69d238c4a08e.png)
这个日期是Date类型,直接给我序列化为Long了，结果再反序列化的时候就报错了
![image](https://user-images.githubusercontent.com/42023195/170903509-b8d9549c-7b3d-4eea-9539-d47d946a6fe1.png)

使用Byte类型也是，反序列化出来成Integer 了，反序列化回来Byte 的字段变成了Integer ， 也是直接报Integer  不能强制转换为Byte

**Comment by wenshao** [comment]
怎么用的？能提供更多信息么
