### ISSUE TITLE
1.2.69升级为1.2.70_noautotype会有什么影响吗

### ISSUE THREAD

**Issue by seMiColon777** [alibaba/fastjson#4184]

**Comment by j-tyuan** [comment]
通过打印：ParserConfig.getGlobalInstance().isAutoTypeSupport() 返回false证明项目中没有使用AutoType，只需要修改pom升级一下就行了

**Comment by seMiColon777** [comment]
好的，感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 凌晨1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson] 1.2.69升级为1.2.70_noautotype会有什么影响吗 (Issue #4184)





 
通过打印：ParserConfig.getGlobalInstance().isAutoTypeSupport() 返回false证明项目中没有使用AutoType，只需要修改pom升级一下就行了
