### ISSUE TITLE
使用的时候报错 java.lang.NoClassDefFoundError: com/alibaba/fastjson2/modules/ObjectReaderModule

### ISSUE THREAD

**Issue by SinnyLang** [alibaba/fastjson#4188]
类的加载路径和包导入的路径不一致。我在编辑器里面使用fastjson是 
import com.alibaba.fastjson.JSONObject
但是在运行时，加载类的路径是 com/alibaba/fastjson2/modules/ObjectReaderModule
这个问题怎么解决  :-(
![image](https://user-images.githubusercontent.com/61444970/171213954-019a43cc-ecc6-4fc7-8eae-e8852ad1f067.png)
![image](https://user-images.githubusercontent.com/61444970/171214055-59bdc354-dc2f-4fcf-8765-b4ead2b16e66.png)

**Comment by wenshao** [comment]
这个是2.0的问题，请到这里报issue
https://github.com/alibaba/fastjson2/issues/
