### ISSUE TITLE
如何将xml字符串转化为json对象？

### ISSUE THREAD

**Issue by 805728578** [alibaba/fastjson#419]
String result = "<?xml version='1.0'?><MatchedEvents><id>roche.com_32343434313231373637@resource.calendar.google.com</id><uid>ep8o7fbj30rubqe5a96f35e378@google.com</uid><entryID>ep8o7fbj30rubqe5a96f35e378_20141127T120000Z</entryID><startTime>2014-11-27T20:00:00+08:00</startTime><endTime>2014-11-27T21:00:00+08:00</endTime><title>gongc4 google l15</title><location>ROCMR-L15-Meeting Room 1'6-Shanghai</location><author>Cheng Shi Gong</author></MatchedEvents>";

JSONArray json = (JSONArray)new XMLSerializer().read(result);//org.net.json的jar实现

fastjson里如何实现？

**Comment by wenshao** [comment]
不支持，不想支持和xml之间的转换，请专注使用json，远离xml

**Comment by 805728578** [comment]
可是许多接口API常常使用xml形式，是否考虑以后扩展？
