### ISSUE TITLE
1.2.75升级1.2.83后，反序列化不兼容，TypeReference获取不到具体的类型

### ISSUE THREAD

**Issue by liuyuzhuo** [alibaba/fastjson#4194]
![image](https://user-images.githubusercontent.com/2143288/172287348-673dcd45-de90-4885-8b7a-1901295a7094.png)
```java
@JsonIgnoreProperties(ignoreUnknown = true)
public class BaseModel {
    private Integer rowIndex;

    public Integer getRowIndex() {
        return rowIndex;
    }

    public BaseModel setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
        return this;
    }
}
```
```java
public class DataRow <T extends BaseModel>{
    private String sampleNum;
    private T model;

    public String getSampleNum() {
        return sampleNum;
    }

    public DataRow<T> setSampleNum(String sampleNum) {
        this.sampleNum = sampleNum;
        return this;
    }

    public T getModel() {
        return model;
    }

    public DataRow<T> setModel(T model) {
        this.model = model;
        return this;
    }
}
```
```java
public class SubModel extends BaseModel{
    private int age;

    public int getAge() {
        return age;
    }

    public SubModel setAge(int age) {
        this.age = age;
        return this;
    }
}
```
```java
@SpringBootTest(classes = TypeReferenceTest.class)
public class TypeReferenceTest {

    @Test
    public void typeRefTestCase(){
        DataRow<SubModel> dataRow = new DataRow<>();
        dataRow.setSampleNum("22B00123");
        SubModel subModel = new SubModel();
        subModel.setRowIndex(1);
        subModel.setAge(30);
        dataRow.setModel(subModel);

        String jsonString = JSON.toJSONString(dataRow);
        System.out.println(jsonString);

        JSONObject jsonObject = JSON.parseObject(jsonString);
        DataRow<SubModel> parseDataRow = jsonObject.toJavaObject(new TypeReference<DataRow<SubModel>>() {});
        SubModel model = parseDataRow.getModel();
        System.out.println(model.getAge());
    }
}
```

**Comment by liuyuzhuo** [comment]
1.2.75不报错。

**Comment by liang2h** [comment]
我从1.2.70升级到1.2.83也遇到这个问题。

**Comment by liuyuzhuo** [comment]
> 我从1.2.70升级到1.2.83也遇到这个问题。

你怎么解决的

**Comment by AsideIsImp** [comment]
换成这个写法可以解决
DataRow<SubModel> parseDataRow = JSON.parseObject(jsonString, new TypeReference<DataRow<SubModel>>() {});

但我在生产上出现了 is not an interface异常，从1.2.70升到1.2.83后才出现下面的报错
![image](https://user-images.githubusercontent.com/28892298/172358383-60250714-ba98-4f5a-b9f4-43af7691238d.png)

**Comment by liang2h** [comment]
> 

没有升级版本，添加参数 -Dfastjson.parser.safeMode=true 解决漏洞问题。

**Comment by liang2h** [comment]
> JSON.parseObject(jsonString, new TypeReference<DataRow>() {});

我使用的就是这种写法，也出现了java.lang.ClassCastException

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.7-SNAPSHOT/
问题已经重现并修复，你可以用2.0.7-SNAPSHOT版本先验证下么？

**Comment by liuyuzhuo** [comment]
我已经使用下面的方式了
DataRow<SubModel> parseDataRow = jsonObject.toJavaObject(new TypeReference<DataRow<SubModel>>() {});
2.0.7-SHAPSHOT版本有太多API不兼容，我的项目报错的地方太多。

**Comment by liuyuzhuo** [comment]
哎，我用这个方法，有时候报错，有时候不报错，迷之操作，生产出问题了。。。。。。

**Comment by wenshao** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.75_noneautotype/
这个版本也是安全的

**Comment by wenshao** [comment]
> 

希望把不兼容的问题反馈过来帮助我改进

**Comment by fangyueqiang** [comment]
我们也遇到了一样的问题，我把泛型<A extend B>改成<B>就神奇般的可以了

**Comment by fangyueqiang** [comment]
我们也遇到了一样的问题，你可以试下把泛型`<T extends BaseModel>`改成`<T>`，或许就和我们一样神奇般的可以了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
2.0.7版本问题已经修复该问题，请用新版本

**Comment by fangyueqiang** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.7 2.0.7版本问题已经修复该问题，请用新版本

请问1.2.84后续会有版本修复这个问题吗，我们的项目不适合升级到2.x的版本，而且必须使用autotype，所以也没法用noneautotype的版本。
