### ISSUE TITLE
如何把多个json数组放到fastson

### ISSUE THREAD

**Issue by liyihongcug** [alibaba/fastjson#420]
后台的数据如下
'{"info":[{"name":"Tom"},{"name":"Jack"},{"name":"jony"}],
"class":[{"level":"基,础,日,语"},{"category":"中,级,日,语"}]}';

第一个是json数组
第二个是另外不同类型的json数组
有没有办法JSON.toJSONString(map);   一次性多个性解析？？？

**Comment by wenshao** [comment]
放在一起，然后调用JSON.toJSONString就OK了，没啥特别啊。
