### ISSUE TITLE
List 里 有指针相同的元素的时候无法解析

### ISSUE THREAD

**Issue by zywskm** [alibaba/fastjson#421]
Obj obj = new Obj("abc");
List<Object> List = new ArrayList<>();
List.add(obj);
List.add(obj);
String json = JSON.toJSONString(List);

json是 [{"Text":"abc"},{"$ref":"$[0]"}]
List 里 有指针相同的元素 (obj) 的时候无法解析

**Comment by GinKoSen** [comment]
这是你的用法不对。fastjson中$表示对象引用，这样可以减少存储或者传递的数据量，但在js层，没有对fastjson进行$特殊应对处理（如果使用fastjson提供的类，是可以翻转的），如果发送给前端的使用JSON.toJSONString(object, SerializerFeature.DisableCircularReferenceDetect)来禁用list内部的对象引用。
