### ISSUE TITLE
低版本升级1.2.83后反序列化问题

### ISSUE THREAD

**Issue by raoxiao12138** [alibaba/fastjson#4215]
低版本支持json串中的属性名是驼峰命名，@JSONField是下划线方式命名的反序列化。升级1.2.83后反序列化会取不到值，1.2.83能否恢复该支持？
如：
json串为{"errorCode":"001","errorMessage":"error message","createTime":1655947753214}
```
    @Data
    static class ResultDTO implements  Serializable {

        @JSONField("error_code")
        private String errorCode;

        @JSONField("error_message")
        private String errorMessage;

    }
```
JSONObject.parseObject(jsonStr, ResultDTO) 的反序列化结果：ResultDTO(errorCode=null, errorMessage=null)
项目中使用@JSONField的地方很多，升级后隐患很大

**Comment by ffismine** [comment]
请问您这边怎么解决这个问题的？

**Comment by Eric-rx** [comment]
> 请问您这边怎么解决这个问题的？

低版本会自动兼容驼峰命名和下划线命名的json串反序列化，fastjson在1.2.71版本中修改了反序列化动作导致该问题：[相关issue](https://github.com/alibaba/fastjson/issues/3452)
安全的做法是在@JSONField注解中增加alternateNames配置，如：`@JSONField(name = "error_code", alternateNames = "errorCode")`
其实只要保证序列化和反序列化的命名规范一致，就没这个问题了。但我们的项目时间跨度比较久，涉及的服务也比较多，为了安全起见把所有使用`@JSONField`并且是下划线命名的都加上了alternateNames，消除潜藏隐患。
