### ISSUE TITLE
fastjson 2.0.7反序列化的时候null不再是null

### ISSUE THREAD

**Issue by Coloryr** [alibaba/fastjson#4220]
直接上图看吧
![QA)EB0 X@9)5WI`}U@ A{CY](https://user-images.githubusercontent.com/26276037/175904622-22082f0c-926e-4320-8166-8d20dfe4af81.png)
2.0.6无此问题
2.0.8问题依旧存在

**Comment by wenshao** [comment]
能帮忙提供重现问题的testcase么？

**Comment by Coloryr** [comment]
我把issue挪fastjson2去
