### ISSUE TITLE
如何能让JSON.parse转化出来的数组默认是Object[] 而非JSONArray

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/fastjson#423]
项目需要有类似如下的转换， 序列化和反序列化Object[]，此数组里又可能有嵌套Object[]，比如以下array:
```java
Object[] cell = { 1, "a", 122 };
Object[] array = { 2, cell, 4 };

String content = JSON.toJSONString(array);//序列化
Object o = JSON.parse(content );//反序列化
```
出来的结果为
![array](https://cloud.githubusercontent.com/assets/5009933/10409122/ecb33288-6f44-11e5-91f3-42ff96bdbacc.png)
凡是数组的都变成了JsonArray类型而非Object[],

为了最终的结果中数组是Object[],我不得不写个工具类去强转型
```java

public class JsonUtil {
	public static Object toJavaObject(Object obj) {
		if (obj != null) {
			if (obj instanceof JSONArray) {
				Object[] array = ((JSONArray) obj).toArray();
				int size = array.length;
				for (int i = 0; i < size; i++) {
					array[i] = toJavaObject(array[i]);
				}
				obj = array;
			}
		}
		return obj;
	}
	public static void main(String[] args) {
       Object[] cell = { 1, "a", 122 };
        Object[] array = { 2, cell, 4 };

         String content = JSON.toJSONString(array);//序列化
         Object o = JSON.parse(content );//反序列化
	Object result=JsonUtil.toJavaObject(o);
	}
}

```
![array2](https://cloud.githubusercontent.com/assets/5009933/10409159/a48d4370-6f46-11e5-8e95-ece07dd37140.png)

不知有没有在生成JSonArray的时候，默认替换生成Object[]类型的实现，求教？

**Comment by jiangguilong2000** [comment]
@stepinto 
@zhuzhaoyuan 
@pentiumao 
@kiminotes 
@vbauer

**Comment by wenshao** [comment]
Object[] items = JSON.parseObject("[...]", Object[].class);

**Comment by jiangguilong2000** [comment]
@wenshao 谢谢回复！
1.用JSON序列化和反序列化我是在消息底层处理的，所以并不知道，这个消息是Object[]类型还是其他类型；
2.消息实体里还多层嵌套有JsonArray的也希望能反序列化成Object[]

也就是如果遇到JsonArray类型的，反序列化出来，希望能有办法Object[]来替换，很困惑~~

**Comment by generalthink** [comment]
@jiangguilong2000   fastjson中应该没有提供此种功能，我估计也不会提供这个功能，也没有必要提供这个功能。

所以，你现在只能通过自己写util来完成这个功能。

**Comment by wenshao** [comment]
为什么一定要用Object[]？

**Comment by jiangguilong2000** [comment]
@wenshao  我们和游戏客户端之间传输都是Object[]对象传输，客户端不认JSONArray,所以服务器之间的序列化反序列化最好也是Object[] A server-->B server-->client ,A到B的过程反序列化目前是解析出来JSONArray,还要做一次遍历，包装成Object[] 然后再转发给客户端，如果能通过FASTJSON直接反序列化出来是Object[]就更好了

**Comment by wenshao** [comment]
新加了一个Feature.UserObjectArray，1.2.9版本会带上这个功能。

**Comment by shapowang** [comment]
why can't I find this feature at any version,any where?
