### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: com.alibaba.fastjson.JSON.writeJSONStringWithFastJsonConfig(Ljava/io/OutputStream;Ljava/nio/charset/Charset;Ljava/lang/Object;Lcom/alibaba/fastjson/serializer/SerializeConfig;[Lcom/alibaba/fastjson/serializer/SerializeFilter;Ljava/lang/String;I[Lcom/alibaba/fastjson/serializer/SerializerFeature;)I

### ISSUE THREAD

**Issue by wt-sp** [alibaba/fastjson#4231]
springweb依赖writeJSONStringWithFastJsonConfig

升级1.2.83缺失，原版本1.2.65

如何解决？

**Comment by sunilnjc** [comment]
hi,
can you explain me this issue. I would like to work on it, I'd like to learn how to contribute and work on open source projects :)

**Comment by wt-sp** [comment]
> hi, can you explain me this issue. I would like to work on it, I'd like to learn how to contribute and work on open source projects :)

our group has an old project using spring-webmvc model,  fastjson prject provides a httpMessageConverter 'FastJsonHttpMessageConverter' (com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter)

extends AbstractHttpMessageConverter(org.springframework.http.converter.AbstractHttpMessageConverter), 

the issue occurs at 'FastJsonHttpMessageConverter' source code line 312 using method 'JSON. writeJSONStringWithFastJsonConfig';

it seems at  method 'JSON. writeJSONStringWithFastJsonConfig' was deleted after 1.2.65


we have solved the issue by using special version of fastjson,  this version uses 'JSON.writeJSONString' instead of 'JSON. writeJSONStringWithFastJsonConfig'

by the way , it is not a release version
