### ISSUE TITLE
请问有没有1.1.26-noneautotype版本

### ISSUE THREAD

**Issue by shoulzai** [alibaba/fastjson#4234]
项目里用的1.1.26版本，这次漏洞升级换了各种版本都遇到兼容性问题，请问有1.1.26-noneautotype版本支持吗

**Comment by littlePoBoy** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.26/
没有这个版本的noneautotype版本

**Comment by shoulzai** [comment]
> https://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.26/ 没有这个版本的noneautotype版本
> 
> 但是我看到1.1.31有noneautotype版本版本的 https://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.31_noneautotype/ 小版本升级兼容性应该不会有太大问题吧，还是测试一下比较好。

感谢，亲测可用
