### ISSUE TITLE
1.2.73升级到2.0.10，JSONArray.toJSONString()找不到方法

### ISSUE THREAD

**Issue by cl7106786** [alibaba/fastjson#4247]
fastjson版本1.2.73升级到2.0.10

Caused by: java.lang.NoSuchMethodError: com.alibaba.fastjson.JSONArray.toJSONString()Ljava/lang/String;

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases
请用2.0.19版本
