### ISSUE TITLE
2.0.10 JSONArray.toJavaList() String异常

### ISSUE THREAD

**Issue by ZhoChoran** [alibaba/fastjson#4248]
**JDK版本:** OPENJDK  Corretto-17.0.4.8.1

**执行如下代码:**
```
String data = "[{\"fileName\":\"expert_info.csv\",\"columns\": [\"person_name\",\"card_number\"]}]";
JSONObject json = JSONArray.parseArray(data).toJavaList(JSONObject.class).get(0);
List<String> list = json.getJSONArray("columns").toJavaList(String.class);
System.out.println(list.size());
```
**触发异常:**
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: class java.lang.String cannot be converted to class java.lang.String
	at com.alibaba.fastjson.JSONArray.toJavaList(JSONArray.java:817)
	at com.dnect.portrait.service.graph.GraphInfoService.main(GraphInfoService.java:79)
```
上述异常在2.0.7 2.0.10均触发

**Comment by yyuyitian** [comment]
`public static void main(String[] args) {
        String data = "[{\"fileName\":\"expert_info.csv\",\"columns\": [\"person_name\",\"card_number\"]}]";
        JSONObject json = JSONArray.parseArray(data).toJavaList(JSONObject.class).get(0);
        List<String> list = json.getJSONArray("columns").toJavaList(String.class);
        System.out.println(list.size());

    }`

正常输出2，使用openjdk1.8.0_201
![image](https://user-images.githubusercontent.com/95139110/181518780-e3fee6b8-6f7d-4257-b15e-77a694ce456f.png)
