### ISSUE TITLE
toJSONString Map key is Integer

### ISSUE THREAD

**Issue by coolme200** [alibaba/fastjson#425]
```
    Map<Integer, String> map = new HashMap<Integer, String>();
    map.put(1, "2");

    String s = JSONObject.toJSONString(map);
    System.out.println(s);

>  {1:"2"}

 // But brower Error
JSON.parse('{1:"2"}');
(program):1 Uncaught SyntaxError: Unexpected number(…)
```

**Comment by generalthink** [comment]
**属性名必须遵循以下准则:**

1. 属性名应该是具有定义语义的有意义的名称。
2. 属性名必须是驼峰式的，ASCII码字符串。
3. 首字符必须是字母，下划线(_)或美元符号($)。
4. 随后的其他字符可以是字母，数字，下划线(_)或美元符号($)。

应该避免使用Javascript中的保留关键字
这些准则反映JavaScript标识符命名的指导方针。使JavaScript的客户端可以使用点符号来访问属性。

**Comment by generalthink** [comment]
@coolme200 如果属性名称没有遵守以上准则，那么你的key值最好加上双引号。
```javascript
var txt = '{"1":"abc"}';
var abc = JSON.parse(txt);
console.info(abc['1']);
```

**Comment by generalthink** [comment]
@coolme200 
```java
Map<Integer, String> map = new HashMap<Integer, String>();
   map.put(1, "abc");
   System.out.println(JSON.toJSONString(map,SerializerFeature.WriteNonStringKeyAsString));

输出:{"1":"abc"}

```
```text
我的fastjson版本:1.2.4,WriteNonStringKeyAsString特性是从1.1.37开始
```

**Comment by coolme200** [comment]
:+1:

**Comment by TianShiHeiDe** [comment]
> @coolme200
> 
> ```java
> Map<Integer, String> map = new HashMap<Integer, String>();
>    map.put(1, "abc");
>    System.out.println(JSON.toJSONString(map,SerializerFeature.WriteNonStringKeyAsString));
> 
> 输出:{"1":"abc"}
> ```
> 
> ```
> 我的fastjson版本:1.2.4,WriteNonStringKeyAsString特性是从1.1.37开始
> ```

请教一下如何在反序列化为原来的Map对象？Map<Integer, String>
