### ISSUE TITLE
字符串中含“<font color=.*?>|<\\/font>”时，parse抛异常

### ISSUE THREAD

**Issue by HowardXu107** [alibaba/fastjson#4258]
1.报错信息如下：
JSONArray growthList = JSON.parseArray(str);
异常信息：com.alibaba.fastjson.JSONException: syntax error, position at 0, name name

2.验证字符串如下：
[{"name":"<font color=\\"#F93A49\\">+4.28%</font>","desc":"近一年涨跌幅"},{"name":"<font color=\\"#F93A49\\">+0.01%</font>","desc":"日涨跌幅"},{"name":"1.0526","desc":"净值08-08"}]

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases
请用新版本
