### ISSUE TITLE
1.2.79版本 safemode设置为true后，反序列化时对于部分@type依然支持

### ISSUE THREAD

**Issue by wk4212** [alibaba/fastjson#4269]
官方在发布1.2.68版本时说明：
**在1.2.68中引入一个safeMode的配置，配置safeMode后，无论白名单和黑名单，都不支持autoType。**

但是在1.2.79版本，配置了 fastjson.parser.safeMode=true，下面的代码中含有 @type，依然可以反序列化，和官方说明不一致。
JSONObject obj2 = JSON.parseObject("{\"@type\":\"java.util.HashMap\",\"a\":100,\"name\":\"demo\"}");

![图片](https://user-images.githubusercontent.com/3138968/186295678-9c7dac2f-27ea-4d35-8ca0-e5a21413e843.png)

**Comment by wenshao** [comment]
这个是忽略掉的，不会影响安全
