### ISSUE TITLE
feature request: JSON.setCustomTypeKey(String typeKey); additional to JSON.DEFAULT_TYPE_KEY="@type"

### ISSUE THREAD

**Issue by 089apps** [alibaba/fastjson#429]
I'd kindly ask you to provide a way to set a custom DEFAULT_TYPE_KEY, in case the backend delivers "class":"com.foo.FooModel"

JSON.setCustomTypeKey(String typeKey);

Also I'd suggest a way to add a "class" (or "@type") mapping.
e.g. the backend delivers a generic type like "class":"article" (or "@type":"article")
so I need a mapping for "article" => "com.foo.ArticleModel", "song" => "com.foo.SongModel", ...

(the background is that namespaces could be different on multiplatform solutions)

**Comment by wenshao** [comment]
got it

**Comment by wenshao** [comment]
it's supported since 1.2.8, but 1.2.9 & 1.2.10 & 1.2.11 has a bug, will fixed in 1.2.12.
```java
SerializeConfig config = new SerializeConfig();
config.setTypeKey("%type");
```

**Comment by 089apps** [comment]
for android 1.1.51 it's gone too?

**Comment by wenshao** [comment]
fastjson-1.1.51.android not support customType key, it will support in 1.1.52.android version, may be release on May 22.

**Comment by 089apps** [comment]
by the way:
currently my backend delivers i.e. "@type":"article" and we have to replace the json-response by "@type":"com.foo.api.model.ArticleModel" before parsing.

is it possible to pass a Mapping to the SerializeConfig like:
```
HashMap<String, String> typeMapping = new HashMap<>();
typeMapping.put("article", "com.foo.api.model.ArticleModel");
typeMapping.put("videos", "com.foo.api.model.VideoModel");

SerializeConfig config = new SerializeConfig();
config.setTypeMapping(typeMapping);
```

**Comment by wenshao** [comment]
fastjson 1.2.11 support 'seeAlso', and will backport to 1.1.52.android. This is the introduction 'seeAlso' :
https://github.com/alibaba/fastjson/wiki/JSONType_seeAlso_cn

**Comment by wenshao** [comment]
1.1.52.android released. https://github.com/alibaba/fastjson/releases/tag/1.1.52.android
