### ISSUE TITLE
2.0.14版本 java Pair类型中使用Boolean作为key时序列化出非json结果

### ISSUE THREAD

**Issue by ConquerMyHer** [alibaba/fastjson#4295]
使用的Pair类型 （org.apache.commons.lang3.tuple.Pair）
使用的fastjson版本（2.0.14测试结果不通过，2.0.8测试通过）

代码如下：
——————————————————————
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import org.apache.commons.lang3.tuple.Pair;

public class TestJson {
    public static void main(String[] args) {
        Pair<Boolean, Boolean> pair = Pair.of(true, true);
        String json = JSON.toJSONString(
                pair,
                SerializerFeature.DisableCircularReferenceDetect,
                SerializerFeature.WriteNonStringKeyAsString,
                SerializerFeature.WriteNonStringValueAsString
        );
        System.out.println(json);
    }
}

——————————————————————
2.0.14测试结果：
{true:true}
2.0.8测试结果：
{"key":true,"left":true,"right":true,"value":true}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
