### ISSUE TITLE
JSON.toJSONString有时候输出{"$ref":"$[0]"}

### ISSUE THREAD

**Issue by dousee163** [alibaba/fastjson#4298]
以下代码运行在fastjson各版本上的区别
```		
List<Object> list = new ArrayList<>();
list.add("RE1220045");
list.add("203");
list.add(1);
list.add("RE1220045");

System.out.println(JSON.toJSONString(list));
```
在fastjson 2.0.14环境下
> ["RE1220045","203",1,{"$ref":"$[0]"}]

在fastjson 1.2.83环境下
> ["RE1220045","203",1,"RE1220045"]

在fastjson2 2.0.14环境下
> ["RE1220045","203",1,"RE1220045"]

是否为bug，还是我的用法不对？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.15
问题已修复，请用2.0.15版本
