### ISSUE TITLE
当日期长度为9时，反序列化BUG

### ISSUE THREAD

**Issue by stone222** [alibaba/fastjson#4299]
当日期长度为9时，例如2022-10-1，当对它进行反序列化到对象时，会报异常

```json
{"testDate":"2022-10-1"}
```

```java
public class DemoDto implements java.io.Serializable {
    private Date testDate;
}
```

```java
DemoDto dto = JSON.parseObject(strjson, DemoDto.class);
```

为修复此问题，我提交了一个PR

#4297

**Comment by wenshao** [comment]
2.0.15版本已经支持，请升级到2.0.15版本
https://github.com/alibaba/fastjson2/wiki/fastjson_1_upgrade_cn

**Comment by stone222** [comment]
1.x版本不再更新了吗？必须升级到2.x版本吗？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
1.x不再更新，请用2.0.19版本
