### ISSUE TITLE
Bug: CollectionDeserializer with empty {"collection":null}  vs. {"collection":[]}

### ISSUE THREAD

**Issue by 089apps** [alibaba/fastjson#430]
I stumbled over a bug with empty (null) collections. Thanks for your kind support.
```java
FooModel:
@JSONField(name = "fooCollection")
public ArrayList<FooCollectionModel> fooCollection;

null doesn't work, see exception below:
[{"@type": "com.foo.FooModel", "fooCollection": null}, {"@type": "com.foo.FooModel", "fooCollection": null}]

[] works:
[{"@type": "com.foo.FooModel", "fooCollection": []}, {"@type": "com.foo.FooModel", "fooCollection": []}]
```

10-18 21:52:32.714 11339-11432/com.foo.testapplication W/System.err: com.alibaba.fastjson.JSONException: not match : - "
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithChar(JSONLexerBase.java:376)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithColon(JSONLexerBase.java:358)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseExtra(JavaBeanDeserializer.java:407)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:389)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:306)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:115)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:292)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:115)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:632)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.deserializer.CollectionDeserializer.deserialze(CollectionDeserializer.java:63)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:548)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:215)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:191)
10-18 21:52:32.715 11339-11432/com.foo.testapplication W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:161)

**Comment by wenshao** [comment]
bug can not be reproduced in last version (1.2.9 & 1.1.49.android), so i closed this issue. if you have any question, please create new issue. thank you!
