### ISSUE TITLE
fastjson's  exception?

### ISSUE THREAD

**Issue by Kasarulor** [alibaba/fastjson#4301]
if  i have a  object A  extends  b   , i  has a get/set method  and init parent  value  ; i  found  when  parse  object  ,this  set method  dont  invoke? 
![image](https://user-images.githubusercontent.com/30746370/194733967-11efbbb7-8437-46e0-99df-5ee22df1c863.png)
note:  when  I   use  "    minifyEnabled true"  for  android

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
please use new version
