### ISSUE TITLE
2.20版本中 JsonUnwrapper失效

### ISSUE THREAD

**Issue by FuYouJ** [alibaba/fastjson#4335]
我照着文档运行代码，都没过测试。
https://github.com/alibaba/fastjson/wiki/JSONField_unwrapped_cn

**Comment by FuYouJ** [comment]
简单来说 就是反序列的场景下，测试用例都过不了。
属性并没有按照期望的方式设置到对象里面去

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
可以提issue到这里么？
