### ISSUE TITLE
TypeUtils.setAccessible 发生异常导致 setAccessibleEnable字段被设置为false

### ISSUE THREAD

**Issue by graceyu-own** [alibaba/fastjson#4338]
TypeUtils.setAccessible 发生异常导致 setAccessibleEnable字段被设置为false，从而导致之后的FieldInfo并无法设置field/method的accessible，引发反射异常。
TypeUtils.setAccessible发生的异常并不清楚，可能是由于工程内部的一些特殊操作导致的，我希望能够定位一下真实的异常信息，以供排查与分析
![image](https://user-images.githubusercontent.com/44594974/210931415-893951be-9316-406d-be04-6ed8c8e6ce0e.png)
但是方法里捕捉的异常并未通过日志框架输出或向上抛出。

fastjson version=1.2.83

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
可以用2.0版本么？

**Comment by graceyu-own** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.23 可以用2.0版本么？

好的，我正在尝试从1.x迁移到2.x版本，如后续存在问题我再来反馈，谢谢。
