### ISSUE TITLE
在解析如{value:["null"]}的json数组时，返回长度为1的JSONArray

### ISSUE THREAD

**Issue by mawer111** [alibaba/fastjson#434]
public static void main(String[] args) {
		String json = "{value:[\"null\"]}";
		JSONObject parse = JSONObject.parseObject(json);
		JSONArray jsonArray = parse.getJSONArray("value");
		System.out.println(jsonArray.size()+"");
	}

**Comment by wenshao** [comment]
符合期待，就应该是1啊
