### ISSUE TITLE
我放弃fastjson

### ISSUE THREAD

**Issue by fysu** [alibaba/fastjson#4345]
一堆问题 刚用了几天
对基本类型转换一塌糊涂
我注意到fastjson保存json的时候都会带上"@type"字段
关闭写入classname的配置后直接拉胯
那ok我用默认的
但是又有问题了,fastjson对基础类型存储比如Long的序列化反序列之后直接就变成Integer
redis存储返回数据库数量统计类型就是Long
在fastjson中基础类型又是自己瞎转换的
直接爆炸,没法用
还有就是对tree结构转换自己调用自己的转换也是直接递归死循环
我没看作者源码,我想用的只是个开箱就用了,项目换上fastjson之后各种问题
fastjson我放弃了,估计以前的安全漏洞也是自己瞎转换导致的
到fastjson2也是感觉拉胯

**Comment by wenshao** [comment]
不喜欢用没人强迫你，如果继续用，有问题就提可重现问题描述的issue
