### ISSUE TITLE
反序列化  float 类型值为null，反序列化失败

### ISSUE THREAD

**Issue by w4lle** [alibaba/fastjson#435]
版本 1.2.7

1.2.1 的changelog
修复数值类型byte、short、int、long、float、double、boolean的值为null时，反序列化失败的问题。

但是float类型貌似并没有生效

**Comment by dachuanz** [comment]
用最新版本肯定改好了，我已经测试过了

**Comment by wenshao** [comment]
新版本没问题，先关闭啦
