### ISSUE TITLE
FastJson转换BigDecimal为BigInteger

### ISSUE THREAD

**Issue by littlestar2125** [alibaba/fastjson#4352]
您好，我现在在转换为json字符串与转出出现了BigDecimal属性变为BigInteger属性的问题
背景：我做了一个对象比较的功能，旧对象与新对象为同一个类，转换为json字符串通过消息队列发送到对象比对服务，消息比对抓换成JsonObject，再进行拆分变成基础对象进行比较，现在同一字段都是BigDecimal，一个前端输入，一个数据库中查询出来的数据精度不同，数据库中查询的数据在消息服务能正常获取到类为BigDecimal,但前端传入的转为了BigInteger,想请教一下怎么不丢失类型，有尝试过SerializerFeature.WriteClassName，但消息服务中不存在父类导致转成JsonObject报错

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/issues

**Comment by littlestar2125** [comment]
> https://github.com/alibaba/fastjson2/issues 可以提issue到这里么？
ok
