### ISSUE TITLE
json转为Map时 指定泛型无效以及带来的一些问题

### ISSUE THREAD

**Issue by zhugw** [alibaba/fastjson#436]
String json = "{1:2,3:4}";
    Map<Long, Short> map = JSON.parseObject(json, Map.class);
    System.out.println(map);// {1=2, 3=4}
    System.out.println(map.get(1L));// null

    Map<String, Short> map2 = JSON.parseObject(json, Map.class);
    System.out.println(map2);// {1=2, 3=4}
    System.out.println(map2.get("1"));// null

好像Map中的泛型指定了没有效果， 默认key和value就是int 假如超过Integer.maxValue会不会报错呢
    json = "{9223372036854775807:2,9223372036854775806:4}";
    Map<Long, Short> map3 = JSON.parseObject(json, Map.class);
    System.out.println(map3);// {9223372036854775807=2, 9223372036854775806=4}
    System.out.println(map3.get(9223372036854775807L));// 2

也不会报错 
看来Map中的类型是由JSON自动指定的。

    json = "{9223372036854775807:2,2:4}";
    Map<Long, Short> map4 = JSON.parseObject(json, Map.class);
    System.out.println(map4);// {9223372036854775807=2, 2=4}
    System.out.println(map4.get(9223372036854775807L));// 2
    System.out.println(map4.get(2L));// null
    System.out.println(map4.get(2));// 4

    map4.forEach((k, v) -> map4.get(k)); //java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Short

假如我就想强制为Map （long - short） 该怎么做呢？

**Comment by zhugw** [comment]
抱歉！ WIKI常见问题中已说明了如何泛型反序列化
import com.alibaba.fastjson.TypeReference;
List<VO> list = JSON.parseObject("...", new TypeReference<List<VO>>() {});

json = "{1:2,3:4}";
Map<Long, Short> map7 = JSON.parseObject(json, new TypeReference<Map<Long, Short>>() {});
System.out.println(map7);
System.out.println(map7.get(1L));// 2
System.out.println(map7.get(1L).getClass());// class java.lang.Short

**Comment by chenguandong** [comment]
zhugw  正解 完美解决
