### ISSUE TITLE
fastjson从1.x升级到2.x后，全局配置蛇形命名不生效了，必须强制使用@JSONField，是什么原因？

### ISSUE THREAD

**Issue by ShisanXing** [alibaba/fastjson#4360]
`// 驼峰转下划线
SerializeConfig serializeConfig = new SerializeConfig();
serializeConfig.propertyNamingStrategy = PropertyNamingStrategy.SnakeCase;
fastJsonConfig.setSerializeConfig(serializeConfig);`
以上这个配置，把fastjson的版本号从1.x升级到2.x后，这个配置就失效了，是什么原因呢？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
问题已修复，请用新版本
