### ISSUE TITLE
序列化为字符串时，能不能默认按照原有字段顺序输出？

### ISSUE THREAD

**Issue by Helen-Guo** [alibaba/fastjson#437]
现在只能通过加@JSONType（orders）和@JSONField(ordinal )解决排序问题，如果只有2、3个字段还可以手动加，要是字段有几十个就太麻烦了，能不能把各种排序模式代码嵌入库里面，到时只是加个参数选择一下就可以了，不知可以实现吗？

**Comment by Muyv** [comment]
同问

**Comment by wenshao** [comment]
toJSONString(object, SerializeConfig.globalInstance, null, null, 0);

**Comment by hinadong** [comment]
这时候我需要传入filter参数怎么办，给出的示例只能null?
