### ISSUE TITLE
无法解析具有注释的json字符串

### ISSUE THREAD

**Issue by Helen-Guo** [alibaba/fastjson#439]
已经添加了Feature.AllowComment属性，但还是报错
Caused by: com.alibaba.fastjson.JSONException: illegal identifier : /
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbolUnQuoted(JSONLexerBase.java:847)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:267)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseExtra(JavaBeanDeserializer.java:435)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:413)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:251)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:227)
10-28 15:49:26.506 12675-12675/com.kuaila.lockscreen E/AndroidRuntime:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:186)

**Comment by wenshao** [comment]
使用 Feature.AllowComment

**Comment by wenshao** [comment]
请提供能重现问题的testcase

**Comment by wenshao** [comment]
1.1.49.android将会修复这个问题
