### ISSUE TITLE
[BUG] 识别Gson的SerializedName问题

### ISSUE THREAD

**Issue by biubiubiu3971** [alibaba/fastjson#4412]
版本：2.0.32

属性名上用Gson的@SerializedName，竟然被识别了。竟然还能跨平台的吗？这个是bug还是特性？
用1.X的没有识别，用2.x的识别了

<img width="827" alt="WechatIMG203" src="https://github.com/alibaba/fastjson/assets/36981492/29187696-e0a3-4f42-82fd-eda1fbbea554">
<img width="385" alt="WechatIMG204" src="https://github.com/alibaba/fastjson/assets/36981492/1835d930-1cc4-421f-a022-0f0d76b36270">

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/issues
请到这里提issue
