### ISSUE TITLE
fastjson反序列化内部类报错

### ISSUE THREAD

**Issue by iluvsnail** [alibaba/fastjson#444]
如题所示，报的错误是构造方法参数不匹配

**Comment by zhaiyuyong** [comment]
把错误代码贴出来

**Comment by iluvsnail** [comment]
public class A{
public String a;
Class B{
  public String b;
}
}

//main 方法
JSON.paseArray("[['b':'bb']]",B.class);

大概是这样的

**Comment by zhaiyuyong** [comment]
写完整一点吧 内部类scope是什么？  贴完整一点好分析

**Comment by nistal97** [comment]
class TestObj {
        class SubObj { double d = 12.34d;
            public double getD() {
                return d;
            }
            public void setD(double d) {
                this.d = d;
            }
        }
        int a = 0;
        String b = "abc";
        Collection<Float> c = Collections.unmodifiableList(new ArrayList<Float>());
        SubObj s = new SubObj();

        public int getA() {
            return a;
        }
        public void setA(int a) {
            this.a = a;
        }
        public String getB() {
            return b;
        }
        public void setB(String b) {
            this.b = b;
        }
        public Collection<Float> getC() {
            return c;
        }
        public void setC(Collection<Float> c) {
            this.c = c;
        }
        public SubObj getS() {
            return s;
        }
        public void setS(SubObj s) {
            this.s = s;
        }
    }

@Test
    public void testJSON2Obj() throws JSON.JSONException {
        String str = "{\"a\":0,\"b\":\"abc\",\"c\":[],\"s\":{\"d\":12.34}}";
        Assert.assertTrue(JSON.deserialize(TestObj.class, str) instanceof TestObj);
        TestObj obj = (TestObj)JSON.deserialize(TestObj.class, str);
        Assert.assertTrue(obj.a == 0);
        Assert.assertTrue(obj.b.equals("abc"));
        Assert.assertTrue(obj.c.isEmpty());
        Assert.assertTrue(obj.s.d == 12.34d);
    }

com.alibaba.fastjson.JSONException: create instance error, class com.dy.apollo.util.JSONTest$TestObj

fastjson是不是不支持内部类？？？

**Comment by nistal97** [comment]
public static Object deserialize(Class clazz, String str) throws JSONException {
        Object ret = null;
        try {
            if (str != null) {
                ret = com.alibaba.fastjson.JSON.parseObject(str, clazz);
            }
        } catch (com.alibaba.fastjson.JSONException e){
            throw new JSONException(e);
        }
        return ret;
    }

**Comment by coolmaxter** [comment]
这个问题我这里也存在，可以把内部类变成内部静态类。

**Comment by wenshao** [comment]
无法实现的，先关闭啦，有问题再提吧

**Comment by lytofb** [comment]
这个我也遇到了，建议将这个特性/缺点写到wiki中
