### ISSUE TITLE
关于SerializerFeature.UseISO8601DateFormat和Feature.AllowISO8601DateFormat的bug？？？！！

### ISSUE THREAD

**Issue by GinKoSen** [alibaba/fastjson#447]
#### **测试的案例**
```java
public class TestMsk {
	public static void main(String[] args) {
		Calendar calendar = Calendar.getInstance();
		calendar.set(Calendar.HOUR_OF_DAY, 0);
		calendar.set(Calendar.MINUTE, 0);
		calendar.set(Calendar.SECOND, 0);
		calendar.set(Calendar.MILLISECOND, 0);
		Foo foo = new Foo();
		foo.setCreateDate(calendar.getTime());
		String date = JSON.toJSONString(foo, SerializerFeature.UseISO8601DateFormat);
		System.err.println(date);
		Foo foo2 = JSON.parseObject(date, Foo.class, Feature.AllowISO8601DateFormat);
		System.err.println(JSON.toJSONString(foo2, SerializerFeature.WriteDateUseDateFormat));
	}
	public static class Foo {
		private String name;
		private Date createDate;
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		public Date getCreateDate() {
			return createDate;
		}
		public void setCreateDate(Date createDate) {
			this.createDate = createDate;
		}

	}

}
```
#### **运行结果**
![run result](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/sp1.png)

通过对源码的阅读定位，得知对于[2015-10-10 00:00:00:00](#)这样的时间，
如果使用了[SerializerFeature.UseISO8601DateFormat](#)会自动跳过值为0的一部分格式
![codec](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/sp2.png)

然后对使用[Feature.AllowISO8601DateFormat](#)翻转，发现没有对时区前边 **[+/-]** 号特殊处理实现，只有对**(")**
![codec](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/sp3.png)

尝试把输出时间json中的+替换解析，依然报错。

##### 从github down下代码尝试修改，修改后运行测试案例，everything is ok ! (修改处如下)
![codec](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/sp4.png)

**Comment by wenshao** [comment]
bug fixed. it will include in 1.2.9 & 1.1.49.android
