### ISSUE TITLE
反序列化超大json时，数组越界length=8192; index=-1

### ISSUE THREAD

**Issue by shonenight** [alibaba/fastjson#448]
代码如下：//json小的时候没问题，json很大的时候（测试数据1M）就会数组越界
ResultObject ro = new ResultObject();
String json = getResources().getString(R.string.json);
StringReader stringReader = new StringReader(json);
JSONReader jsonReader = new JSONReader(stringReader);

jsonReader.startObject();

while (jsonReader.hasNext()){
    String key = (String) jsonReader.readObject();
            if (key.equals("data")) {
                ro.setData(jsonReader.readObject(DataEntity.class));
            } else if (key.equals("code")) {
                String value = jsonReader.readString();
                ro.setCode(Integer.parseInt(value));
            } else if (key.equals("message")) {
                String value = jsonReader.readString();
                ro.setMessage(value);
            }
}

jsonReader.endObject();
jsonReader.close();

json结构如下：
{
    "code": 0,
    "data": {
        "keywordList": [
            {
                "houseCount": 8,
                "id": "1",
                "keyword": "哈哈哈",
                "keywordFirstLetter": "LHY",
                "keywordId": 123,
                "keywordSpelling": "LANHUAYUAN",
                "keywordType": 3,
                "lastModifyTime": "2015-10-2615: 01: 28",
                "lastModifyTimeL": 1445842888506
            },
            {
                "houseCount": 8,
                "id": "1",
                "keyword": "哈哈哈",
                "keywordFirstLetter": "LHY",
                "keywordId": 123,
                "keywordSpelling": "LANHUAYUAN",
                "keywordType": 3,
                "lastModifyTime": "2015-10-2615: 01: 28",
                "lastModifyTimeL": 1445842888506
            }
        ]
    },
    "message": "获取关键词列表成功"
}

报错信息如下：
E/AndroidRuntime(  811): Caused by: com.alibaba.fastjson.JSONException: length=8192; index=-1

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:547)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:515)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:204)

E/AndroidRuntime(  811): 	at com.meican.Demo.fastjson.MainActivity.onCreate(MainActivity.java:60)

E/AndroidRuntime(  811): 	at android.app.Activity.performCreate(Activity.java:5231)

E/AndroidRuntime(  811): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)

E/AndroidRuntime(  811): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)

E/AndroidRuntime(  811): 	... 11 more

E/AndroidRuntime(  811): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=-1

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.JSONReaderScanner.charAt(JSONReaderScanner.java:126)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.JSONLexerBase.longValue(JSONLexerBase.java:1745)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.LongFieldDeserializer.parseField(LongFieldDeserializer.java:29)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:396)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:306)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:115)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:627)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.ArrayDeserializer.deserialze(ArrayDeserializer.java:69)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:396)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:306)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:115)

E/AndroidRuntime(  811): 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:543)

**Comment by wenshao** [comment]
bug fixed. 1.2.9版本中会修复这个bug。
