### ISSUE TITLE
 @JSONField(name = "Mg2+")

### ISSUE THREAD

**Issue by zhangtaoeasy** [alibaba/fastjson#449]
@JSONField(name = "Mg2+")
  private List<String> mg;

类似的还有

  @JSONField(name = "Na+")
  private List<String> na;

  @JSONField(name = "Cl-")
  private List<String> cl;

mg是null,有办法解决吗？

**Comment by zhaiyuyong** [comment]
你是序列化失败还是反序列化失败？

**Comment by zhaiyuyong** [comment]
String ddd = "{\"Mg2+\":[{\"age\":12,\"name\":\"zhaiyuyong\",\"phone\":\"15221553374\"}]}";
		B bb = JSONObject.parseObject(ddd, B.class);
		System.out.println(bb.getA().size());
		System.out.println(bb.getA());

{"Mg2+":[{"age":12,"name":"zhaiyuyong","phone":"15221553374"}]}
1
[A [name=zhaiyuyong, age=12, phone=15221553374]]

**Comment by zhaiyuyong** [comment]
那个version？

**Comment by zhangtaoeasy** [comment]
你好，我用的版本是 1.2.7

**Comment by zhangtaoeasy** [comment]
现象是发生在 反序列化的时候，对方传过来类似这样

http://his.com/HMSSERVER/WnxCheck?chkresult={ "Mg2+": "1435555992",  "Na+": " 02570","cl-": "150501" ,"panellot": "150501" }

我们 Java 端接收类似这样：

 String chkresult = request.getParameter("chkresult");
 ExaminationPojo examinationPojo = JSONObject.parseObject(chkresult, ExaminationPojo.class);

public class ExaminationPojo {

         @JSONField(name = "Mg2+")
	   private String mg;
	   @JSONField(name = "Na+")
	   private String na;
	   @JSONField(name = "Cl-")
	   private String cl;
          @JSONField(name = "panellot")
	   private String panellot;
        //....get set
}

现象就是 带 +-号的属性应该是没映射上是null,panellot是正常的

**Comment by wenshao** [comment]
用你的testcase在最新版本中发现问题不存在，先关闭啦，有问题再提。
