### ISSUE TITLE
[bug]JSONPath.eval取不到值

### ISSUE THREAD

**Issue by Ryoui** [alibaba/fastjson#4493]
`    public static void main(String[] args) {
        String data = "{\"userName\":\"zhangsan\"}";
        Object userName1 = JSONPath.read(data, "$.userName");
        Object userName2 = JSONPath.eval(data, "$.userName");
        System.out.println(userName1);
        System.out.println(userName2);
    }`
上述代码，在1.2.83版本输出：
zhangsan
zhangsan
在2.0.47输出
zhangsan
null

**Comment by swapdewalkar** [comment]
Can you create ticket here
https://github.com/alibaba/fastjson2/issues/
I will post a workaround here, but create a ticket here, fix will go there.

**Comment by swapdewalkar** [comment]
Created the issue https://github.com/alibaba/fastjson2/issues/2387

**Comment by swapdewalkar** [comment]
`JSONPath.eval(JSONObject.parseObject(data), "$.userName");`
Use this for work around
