### ISSUE TITLE
对类或enum的序列化可否加入自定义序列化的方法

### ISSUE THREAD

**Issue by shougaoshougao** [alibaba/fastjson#455]
对类或enum的序列化可否加入自定义序列化的方法?
对于enum的序列化，虽然现在已经支持了使用enum的toString方法，但是也只能输出一个字符串，假如想同时输出enum的name和ordinal，就没有办法，即使在toString方法里面拼{name: 'name()', ordinal: 'ordinal()'}也不行，因为toString返回的是字符串，输出出来的外面会加上单引号活双引号导致无法识别成json object。
在将来的版本中，可否支持annotation自定义序列化方法返回Map类型(或其他类型)？或者是简单点实现的话，加annotation可以标识返回string的方法外面不需要加引号。
同样的，在类的序列化里面也可能有类似这样的需求，可以更自由地定义需要被序列化的map类型里面包含的key和value，而不仅仅是通过@Jsonfield去定义。

**Comment by terensu** [comment]
enum枚举类，可以像class那样同等方式序列化/反序列化吗，因为enum也有field需要展示的

**Comment by terensu** [comment]
可以尝试： enum添加Getter, Setter方法，再设置SerializeConfig.getGlobalInstance()设置Serializer为JavaBeanSerializer

**Comment by wenshao** [comment]
可以通过SerializeConfig. getGlobalInstance() 或者 ParserConfig.getGlobalInstance() 注册自己实现的ObjectSerializer & ObjectDeserializer
