### ISSUE TITLE
对象属性中enum类型字段序列化/反序列化失败问题

### ISSUE THREAD

**Issue by terensu** [alibaba/fastjson#457]
class VO {
  private MyEnum myEnum;
  public void setMyEnum(MyEnum myEnum){this.myEnum = myEnum;}
  public MyEnum getMyEnum(){ return myEnum;}
}
配合自定义的EnumSerDeserializer方式，
序列化|反序列时候：
当设置asm=false，才能成功执行
当设置asm=true，失败

fastJson版本：1.4.2

**Comment by wenshao** [comment]
Enum的类和自定义的EnumSerDeserializer方便贴上来么？

**Comment by wenshao** [comment]
bug fixed. it will include in 1.2.9 & 1.1.49.android
