### ISSUE TITLE
建议增加选择是否使用BigInteger的功能

### ISSUE THREAD

**Issue by ghost** [alibaba/fastjson#462]
像巨杉数据库、mongodb这种nosql，不支持BigInteger和BigDecimal的数据类型，希望能增加参数、配置选择 是否使用BigInteger的功能。
由于项目需要修改了部分源码，请斧正：
Feature中新增：UseBigInteger；
JSONLexerBase中增加方法：
    public final Number integerValue(boolean useBigInteger) throws NumberFormatException {
        Number num = integerValue();
        if (num instanceof BigInteger) {
            num = num.doubleValue();
        }
        return num;
    }
然后在DefaultJSONParser中调用该方法。

**Comment by wenshao** [comment]
都大于Long.MAX_VALUE了，不使用BigInteger怎么行啊？

**Comment by wenshao** [comment]
测试过了，没问题
