### ISSUE TITLE
当bean中存在重载方法的时候，parseObject会随机选择一个方法解析导致异常

### ISSUE THREAD

**Issue by zzxzz12345** [alibaba/fastjson#464]
如果存在以下两个重载方法
setTest(TestBean bean);
setTest(String str);
要解析这样一个对象 Test:[]
本意是把[]作为一个字符串然后进行自定义解析
结果使用JSON.parseObject的时候会随机调用两个方法中的一个
建议在装配前进行检查 检查到两个符合装配要求的重载方法时抛出异常
或者根据实际情况判断调用哪个方法

**Comment by wenshao** [comment]
在1.2.9中将会使用固定的顺序
