### ISSUE TITLE
使用 SerializerFeature.NotWriteDefaultValue 时的bug

### ISSUE THREAD

**Issue by zephyrleaves** [alibaba/fastjson#467]
有个字段 protected boolean success = true;
当我设置success = false 时则不会被序列化

在代码

                if (propertyValue != null && serializer.isEnabled(SerializerFeature.NotWriteDefaultValue)) {
                    Class<?> fieldCLass = fieldSerializer.fieldInfo.getFieldClass();
                    if (fieldCLass == byte.class && propertyValue instanceof Byte
                        && ((Byte) propertyValue).byteValue() == 0) {
                        continue;
                    } else if (fieldCLass == short.class && propertyValue instanceof Short
                               && ((Short) propertyValue).shortValue() == 0) {
                        continue;
                    } else if (fieldCLass == int.class && propertyValue instanceof Integer
                               && ((Integer) propertyValue).intValue() == 0) {
                        continue;
                    } else if (fieldCLass == long.class && propertyValue instanceof Long
                               && ((Long) propertyValue).longValue() == 0L) {
                        continue;
                    } else if (fieldCLass == float.class && propertyValue instanceof Float
                               && ((Float) propertyValue).floatValue() == 0F) {
                        continue;
                    } else if (fieldCLass == double.class && propertyValue instanceof Double
                               && ((Double) propertyValue).doubleValue() == 0D) {
                        continue;
                    } else if (fieldCLass == boolean.class && propertyValue instanceof Boolean
                               && !((Boolean) propertyValue).booleanValue()) {
                        continue;
                    }
                }

只判断了默认0 没有判断实际的默认值 导致的错误!

**Comment by dachuanz** [comment]
这个特性性该是java语言的默认值，也就是不初始化的时候，虚拟机给的默认值。

**Comment by zephyrleaves** [comment]
@dachuanz  不是这个意思  ...我是指定了默认值是true 但是代码里只处理了默认值是false的情况 
导致的结果就是 我默认值指定是true 但是实际值是false的时候 false 没有被序列化, 然后在反序列化的时候就变成true了 出现错误了

**Comment by dachuanz** [comment]
估计遇到这样的情况，fastjson 就爱莫能助了

**Comment by zephyrleaves** [comment]
@dachuanz 这个可以改的啊
现在的代码
```java
if (propertyValue != null && serializer.isEnabled(SerializerFeature.NotWriteDefaultValue)) {
                Class<?> fieldCLass = fieldSerializer.fieldInfo.getFieldClass();
                if (fieldCLass == byte.class && propertyValue instanceof Byte
                    && ((Byte) propertyValue).byteValue() == 0) {
                    continue;
                } else if (fieldCLass == short.class && propertyValue instanceof Short
                           && ((Short) propertyValue).shortValue() == 0) {
                    continue;
                } else if (fieldCLass == int.class && propertyValue instanceof Integer
                           && ((Integer) propertyValue).intValue() == 0) {
                    continue;
                } else if (fieldCLass == long.class && propertyValue instanceof Long
                           && ((Long) propertyValue).longValue() == 0L) {
                    continue;
                } else if (fieldCLass == float.class && propertyValue instanceof Float
                           && ((Float) propertyValue).floatValue() == 0F) {
                    continue;
                } else if (fieldCLass == double.class && propertyValue instanceof Double
                           && ((Double) propertyValue).doubleValue() == 0D) {
                    continue;
                } else if (fieldCLass == boolean.class && propertyValue instanceof Boolean
                           && !((Boolean) propertyValue).booleanValue()) {
                    continue;
                }
            }
```
就是只判断了 值是不是0  这样不对么
应该判断值是不是和默认值一样,这样比较好, 如果可以new 对象 然后取得默认值 作为对比值来判断 而不是直接和0判断

**Comment by dachuanz** [comment]
只判断了是不是jvm 的默认值，哪还有new 对象的

**Comment by wenshao** [comment]
new对象的默认值不好实现，你有好办法么？
