### ISSUE TITLE
Hibernate Set to json

### ISSUE THREAD

**Issue by blokwap** [alibaba/fastjson#468]
public Class B {
    @Column
    private String name;
    private Set<A> values;
    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(FetchMode.JOIN)
    public Set<A> getValues() {//manytomany
      return values;
    }
    public void setValues(Set<A> values) {
      this.values = values;
    }
}

I use alibaba fastjson to serialize Entity B and I got result
{ "name":"blokwap" }
the Set is lost, in debug I see Hibernate transform Set into PersistentSet, and PersistentSet will not be serialized, I want to get the result like this:
{ "name":"blokwap", "values":[ {"x":"y1"},{"x":"y2"} ] }
plz tell me how to get the correct result, thx

**Comment by dachuanz** [comment]
set内容没有正常填充

**Comment by wenshao** [comment]
需要手动装载该对象，fastjson不会自动装载

**Comment by blokwap** [comment]
能否具体些，如何进行手动装载
