### ISSUE TITLE
fastjson的解析bug

### ISSUE THREAD

**Issue by newpanjing** [alibaba/fastjson#469]
对象中名为sPhotoUrl的字段，是不为null，有值，结果解析出来的json字符串，这个字段就不见了~

改了个名字，又可以了~

**Comment by dachuanz** [comment]
是不是忘了写get 方法

**Comment by newpanjing** [comment]
写了的哦~ 都是用ide 自动生成get set的~ 也检查过的~ 后来把这个字段名字改为其他的 又可以了。

**Comment by dachuanz** [comment]
你把测试代码提供一下

**Comment by wenshao** [comment]
最新版本是好的，建议升级新版
