### ISSUE TITLE
关于循环引用 SerializerFeature.DisableCircularReferenceDetect 的建议

### ISSUE THREAD

**Issue by ptma** [alibaba/fastjson#47]
提一个“重复引用” 情形：
Class B {
  ..
}

Class A {
  B b;
  ...
}

B b = new B();
A a1 = new A();
A a2 = new A();
a1.setB(b);
a2.setB(b);

a1,a2 里面的 b 指向同一个对象；

这就是所谓的重复引用； 

我想“重复引用”跟“循环引用”还是不一样，没有导致引用的回路（或递归），这种情况我想应该是允许的，实际应用中这种情况也挺多的（比如 hibernate  中的一对多，多对多）

如果把这种情况也 $ref 掉的话，无疑是增加了前端的代码量，所以建议这种情况按正常处理；

虽然可以加 DisableCircularReferenceDetect， 但总是不怎么保险

**Comment by olddoor** [comment]
soga.源码看不太懂. 原来是用DisableCircularReferenceDetect 来解决.
