### ISSUE TITLE
使用 JSONArray 的 getObject(int index, Class<T> clazz) 方法时反序列化错误

### ISSUE THREAD

**Issue by ScienJus** [alibaba/fastjson#470]
版本为`1.2.7`
当反序列化的字段为`boolean`类型，并且 JSON 中的值为`null`时，使用`JSONArray`的`getObject(int index, Class<T> clazz)`方法会报解析错误。

原因是`TypeUtils`的`866`行的：

```
method.invoke(object, new Object[] { value });
```

将`null`传入了以基本类型为参数的方法中，导致自动拆箱报错。

但是使用`JSON`的`parseObject(String text, Class<T> clazz, Feature... features)`方法则不会报错。

**Comment by wenshao** [comment]
测试过新版本这个bug不存在了，请等待1.2.9版本吧
