### ISSUE TITLE
是否考虑对Immutable Object的序列化支持

### ISSUE THREAD

**Issue by peero** [alibaba/fastjson#473]
传统基于JavaBean规范来定义Value Object不是很合适，主要是这种类型它的特点是，只需要实例化一次，类似singleton，而通过set/get方法有可变状态的风险，赋值也比较繁琐，构造器更乏味。而Value Object在实际应用中使用非常常见，比如：接收入参，存储查询结果返回等，全局共享信息等，在多线程场景下也非常安全。 而其传值的场景恰恰与fastjson的使用场景很一致。另外，第三方Jackson／Gson都已经支持这种类型的序列号，所以fastjson也需要考虑起来。谢谢！
目前对Value Object类型好的建模实践是Immutable，Guava对这种集合类型支持的比较完善。
参考：http://immutables.github.io/json.html

**Comment by wentch** [comment]
RedKale-Convert 支持  http://www.redkale.org/convert.html

**Comment by wenshao** [comment]
已支持
