### ISSUE TITLE
FastJson  有没有 这样的 注解  ，当 某个字段 为 NULL 或 “”  ，不序列化 此字段

### ISSUE THREAD

**Issue by misty-rain** [alibaba/fastjson#477]
FastJson  有没有 这样的 注解  ，当 某个字段 为 NULL 或 “”  ，不序列化 此字段

**Comment by dachuanz** [comment]
默认就不序列化啊

**Comment by wenshao** [comment]
null默认不序列化，长度为0的字符串可以使用ValueFilter做过滤。https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by wxainn** [comment]
springboot配置全局序列化null，对于特殊类想使用不序列化null，怎么处理呢
