### ISSUE TITLE
It doesn't support Iterable serialization

### ISSUE THREAD

**Issue by greenlaw110** [alibaba/fastjson#478]
Test case: https://gist.github.com/greenlaw110/bd773f1a283ec079102f

**Comment by wenshao** [comment]
已经支持，请等待1.2.9版本发布吧

**Comment by greenlaw110** [comment]
我等不及了，就自己写了一个：
https://github.com/actframework/actframework/blob/master/src/main/java/act/util/FastJsonIterableSerializer.java
