### ISSUE TITLE
可否根据Class，定制toJSONString行为？

### ISSUE THREAD

**Issue by ybbpgfjtey** [alibaba/fastjson#481]
例如Oracle驱动中的oracle.sql.TIMESTAMP这种字段，如果直接toJSONString会变成这样：
{"bytes":"d6oBAQEBAQAAAAA=","length":11,"stream":{}}
而且由于这个对象是包在Map中的，外部不知道key是什么。
能否有个全局定义，在外部设置此类数据的toJSONString的行为？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/commit/ec44a23d75bade5cd4cf969069e4e5d7c26e73c7
fastjson-1.2.8版本将会直接支持oracle.sql.Date和oracle.sql.TIMESTAMP类型。

之前定制序列化的方法看这里：https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by ybbpgfjtey** [comment]
这几个filter都不是我想要的，因为1. 我转义的对象可能有hashmap； 2. 通用的序列化，没法约束对方一定写注解，上游也没法根据属性名称另行定义filter。
filter根本没法配，不过我已经找到怎么弄了：SerializeConfig + ObjectSerializer搞定。

文档真心有点少，这个还得看源码自己想办法T.T。

建议加上可以根据class等其他属性处理的filter。


 
发件人： 高铁
发送时间： 2016-02-28 16:49
收件人： alibaba/fastjson
抄送： ybbpgfjtey
主题： Re: [fastjson] 可否根据Class，定制toJSONString行为？ (#481)
ec44a23
fastjson-1.2.8版本将会直接支持oracle.sql.Date和oracle.sql.TIMESTAMP类型。
之前定制序列化的方法看这里：https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96
