### ISSUE TITLE
使用JSON.toJSONString序列化时如何将javabean中的BigDecimal字段转化为string类型

### ISSUE THREAD

**Issue by blessyezi** [alibaba/fastjson#486]
请问一下使用JSON.toJSONString序列化时如何将javabean中的BigDecimal字段转化为string类型。
比如javabean中有两个字段id:BigDecial和name:String。我想序列化成{"id":"12345678","name":"test"}这样。但是默认序列化时12345678是没有双引号的。

**Comment by wenshao** [comment]
JSON.toJSONString(obj, SerializerFeature.WriteNonStringKeyAsString)

**Comment by jiayeee** [comment]
应该是WriteNonStringValueAsString，会把所有的类型都转成String
