### ISSUE TITLE
fastjson 1.2.x 以后的版本不再出android版了么？

### ISSUE THREAD

**Issue by OhmygodWorks** [alibaba/fastjson#488]
如题，请问fastjson 1.2.x 以后的版本不再出android版了么？
或者说fastjson 1.2.x 以后的版本已经不需要在意什么android版不android版的，
照用都可以了？
毕竟 1.2.x 以后的版本有很多有用的BugFix，但是又没有宣布有android版，
不好判断适不适合用。

**Comment by wenshao** [comment]
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.46.android/ 目前所有的bug fixed都back port到1.1.46的

**Comment by OhmygodWorks** [comment]
谢谢。我想再问一下，1.2.x以后增加的新功能会有back port到1.1.46.android的计划么？

**Comment by wenshao** [comment]
新加功能不会

**Comment by wenshao** [comment]
新功能，如果不是大的改变，部分会backport到1.1.x.android上

**Comment by wenshao** [comment]
最新版本1.1.48.android已经发布，请使用。
