### ISSUE TITLE
JSONArray.<T> T getObject 以及 JSONObject.<T> T getObject 不支持@JSONCreator注解

### ISSUE THREAD

**Issue by OhmygodWorks** [alibaba/fastjson#489]
如题，直接使用JSON. <T> T parseObject 方法是支持@JSONCreator注解的，
但是使用JSONArray.<T> T getObject 以及 JSONObject.<T> T getObject 就不支持了。
个人在运用上感觉@JSONCreator还是挺有用的，所以请问能否让那两个方法，
或者直接让TypeUtils里面的方法支持@JSONCreator注解？
又或者说其实你们打算要淘汰掉@JSONCreator注解的？

**Comment by wenshao** [comment]
收到，能否提供重现问题的testcase代码？

**Comment by OhmygodWorks** [comment]
public final class Foo {
public final String bar;
@JSONCreator
public Foo(@JSONField(name = "foo") final String bar) {
this.bar = bar;
}
}
Foo ok = JSON.parseObject("{\"foo\":\"bar\"}", Foo.class);
Foo ng = JSON.parseArray("[{\"foo\":\"bar\"}]").getObject(0, Foo.class);

**Comment by wenshao** [comment]
问题将会在1.2.9 & 1.1.49.android上修复
