### ISSUE TITLE
Can not parse a json string from Okhttp's example instead of using fastjson?

### ISSUE THREAD

**Issue by LiHanGuang** [alibaba/fastjson#490]
Hi dev @wenshao:

** Json source: **
https://api.github.com/gists/c2a7c39532239ff261be

** Example: **
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/ParseResponseWithGson.java

But Gson work!

**Comment by LiHanGuang** [comment]
ok, nobody answer me?

**Comment by LiHanGuang** [comment]
@myself
Gist's member is not **public access permission**, fastson donnot modify its member's access permission,   but Gson do this.

If member not public,  add the **getter and setter**.

**Comment by wenshao** [comment]
import com.alibaba.fastjson.*;

JSONReader jsonReader = new JSONReader(new InputStreamReader(response.body().charStream()));
Gist  gist = jsonReader.readObject(Gist.class);

**Comment by wenshao** [comment]
fastjson only support public field & public getter/setter method, it's different to gson.
