### ISSUE TITLE
 JSON.parseObject(json, new TypeReference<Map<String, V>>() make a error when the value includes number.

### ISSUE THREAD

**Issue by MarkHsiu** [alibaba/fastjson#491]
* the code is follow
 ![code](https://cloud.githubusercontent.com/assets/12731489/12602882/eba12582-c4e7-11e5-90f5-a1e2d7a584b0.png)

* error tibs:
<pre>
<code>
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
 
</code>
</pre>

**Comment by LiHanGuang** [comment]
@MarkHsiu

you should  

new TypeReference<Map<String, Object>>() {})

**Comment by MarkHsiu** [comment]
@LiHanGuang  the markdown edior cant show the  Java  Generic well.so I replace it with a picture

**Comment by wenshao** [comment]
已经增加了相关API，文档看这里 https://github.com/alibaba/fastjson/wiki/TypeReference
