### ISSUE TITLE
适合使用Fastjson解析json得到某一属性的列表吗？

### ISSUE THREAD

**Issue by zhugw** [alibaba/fastjson#492]
```
[
    {
        "category": "tag_foo", 
        "tagPrice": [
            {
                "activeTagDictId": 370, 
                "activePrice": 39
            }, 
            {
                "activeTagDictId": 371, 
                "activePrice": 68
            }, 
            {
                "activeTagDictId": 372, 
                "activePrice": 99
            }
        ]
    }
]
```
解析上面的json得到activeTagDictId列表
```
List<JSONObject> joList = JSON.parseArray(json, JSONObject.class);
List<Long> list = joList.stream().flatMap(o -> o.getJSONArray("tagPrice").stream())
				.map(o -> ((JSONObject)o).getLong("activeTagDictId")).collect(toList());
System.out.println(list); // [370, 371, 372]
```
感觉还是很麻烦 不直观 JSONObject JSONArray经常分不清 并且还涉及到强转

不知Fastjson有没更简单健壮的方式 可以实现上述功能

是不是这种场景就不适合使用Fastjson了， 而应该使用JsonPath

**Comment by jialechan** [comment]
建立两个pojo:
```java
public class CategoryPojo {
    private String category;
    private List<ActiveItem> tagPrice;
    ...
```
```java
public class ActiveItem {
    private Integer activeTagDictId;
    private Integer activePrice;
    ...
}
```
然后直接调用：
```java
public class MyMain {
    public static void main(String[] args) {
        String json = "[{\"category\": \"tag_foo\", \"tagPrice\": [{\"activeTagDictId\": 370, \"activePrice\": 39}, {\"activeTagDictId\": 371, \"activePrice\": 68}, {\"activeTagDictId\": 372, \"activePrice\": 99}]}]";
        List<CategoryPojo> list = JSON.parseObject(json, ArrayList.class);
        System.out.println(list);
    }
}
```
输出：
```shell
[{"tagPrice":[{"activePrice":39,"activeTagDictId":370},{"activePrice":68,"activeTagDictId":371},{"activePrice":99,"activeTagDictId":372}],"category":"tag_foo"}]
```

**Comment by zhugw** [comment]
谢谢 但我觉得定义额外的对象真的很不方便 尤其是你只想抽取某一元素列表 或 只想得到某一个标签的价格 这种场景下使用JsonPath非常方便 如
List<String> idList = JsonPath.read(json, "$..activeTagDictId"); // all activeTagDictId 

List<String> priceList = JsonPath.read(json, "$..tagPrice[?(@.activeTagDictId==371)].activePrice"); //查询activeTagDictId为371对应的价格

**Comment by wenshao** [comment]
可以用fastjson的JSONPath啊
https://github.com/alibaba/fastjson/wiki/JSONPath

**Comment by zhugw** [comment]
但好像只能操作对象 而不能解析json串 如
List<String> idList = (List<String>) JSONPath.eval(json, "$..activeTagDictId");

并且不如java8的streams直观 如
 List<String> names = (List<String>)JSONPath.eval(entities, "$.name"); // 返回enties的所有名称
用java8实现的话
 List<String> names = entities.stream().map(e->e.getName()).collect(toList());

**Comment by fivesmallq** [comment]
@zhugw 可以用其他库，https://github.com/jayway/JsonPath

```
String json = "...";

List<String> authors = JsonPath.read(json, "$.store.book[*].author");
```

**Comment by wenshao** [comment]
新加api
```java
public class JSONPath {
    /**
     * @since 1.2.9
     */
    public static Object read(String json, String path);
}
```

**Comment by yaolei313** [comment]
目前还不支持json array的形式的json path么
` [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]`
表达式为
`$[?(@.type=="home")]`
会报UnsupportedOperationException
