### ISSUE TITLE
JSON.toJSON序列化List的时候出现多余字段callbacks

### ISSUE THREAD

**Issue by ReconcileMySelf** [alibaba/fastjson#494]
```java
public class SubShop implements Serializable{
	private static final long serialVersionUID = 30775904309277L;
	
	private java.lang.Long id;
	private java.lang.Long sid;
	private java.lang.String shortName;
	private java.lang.String fullName;
	private java.lang.String shopDesc;
	private java.lang.Double lng;
	private java.lang.Double lat;
	private java.lang.Integer shopType;
	private java.lang.String source;
	private java.lang.Integer status;
	private java.lang.String platform;
	private java.lang.String tel;
	private java.util.Date createTime;
	private java.util.Date modifyTime;`
```

上面是实体类，
```java
List<SubShop> lists = subShopService.selectSubShopBySelective(subShop);

if(lists != null && lists.size() > 0){
       resultJson.put("code", "success");
      resultJson.put("message", "success");
      resultJson.put("SubShops", JSON.toJSON(lists));
}else{
	resultJson.put("code", "success");
	resultJson.put("message", "success");
	resultJson.put("SubShops", new JSONArray());
}
```

使用上面的代码通过JSON.toJSON序列化的时候，会出现多余的字段callbacks是一个数组型的。

{"message":"success","SubShops":[{"id":1,"createtime":1454308690000,"sid":1,"platform":"cdcsd","shopType":1,"source":"xianxiaditui","status":0,"callbacks":[{}],"shopDesc":"æ\u009D\u009Cç\u0094«1","lng":104.067191,"fullName":"æ\u009D\u009Cç\u0094«1","shortName":"æ\u009D\u009Cç\u0094«1","lat":30.575094}],"code":"success"}

但是当通过`JSON.parseArray(JSON.toJSONString(lists))`解析得到时，就没有了，callbacks字段。一开始我以为是实体类实现了Serializable的原因，但当我去掉Serializable的时候，还是会出现callbacks字段，List集合是查询数据库后得到的结果并且实体类也没有callbacks字段，为什么使用JSON.toJSON()会出现多余的呢？

**Comment by wenshao** [comment]
用的hibernate框架？

**Comment by ReconcileMySelf** [comment]
用的是Mybatis框架。

**Comment by wenshao** [comment]
针对mybatis org.apache.ibatis.javassist.util.proxy.ProxyObject做了处理

**Comment by ReconcileMySelf** [comment]
哦哦，好的，谢谢！
