### ISSUE TITLE
syntax error, expect ], actual int

### ISSUE THREAD

**Issue by cbyniiaii** [alibaba/fastjson#496]
# 使用以下代码：
List<Goods> datas = new ArrayList<Goods>();
JSONReader reader = null;
try {
		reader = new JSONReader(new FileReader("b.txt"));
		reader.startArray();
		while(reader.hasNext()) {
				Goods a = reader.readObject(Goods.class);
				System.out.println(a);
				datas.add(a);
		}
} catch (Exception e) {
		e.printStackTrace();
}
reader.endArray();
reader.close();
System.out.println(datas);

# 报如下错误：
com.alibaba.fastjson.JSONException: -1
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:523)
	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:204)
	at cn.com.efuture.utils.Test.main(Test.java:36)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.alibaba.fastjson.parser.JSONReaderScanner.charAt(JSONReaderScanner.java:126)
	at com.alibaba.fastjson.parser.JSONLexerBase.longValue(JSONLexerBase.java:2919)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:22)
	at Fastjson_ASM_Goods_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 3 more
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect ], actual int
	at com.alibaba.fastjson.parser.DefaultJSONParser.accept(DefaultJSONParser.java:1317)
	at com.alibaba.fastjson.JSONReader.endArray(JSONReader.java:71)
	at cn.com.efuture.utils.Test.main(Test.java:44)

# 附b.txt文本内容：
[{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000100002       ","cost":4.50000000,"deptID":"10202","deptName":"三鸟            ","dms":0.053,"enddate":1454401881780,"goodsID":"1","goodsName":"购销测试商品0111","goodsStatus":0,"goodsTypeID":0,"inventoryQty":4180.999,"logistics":3,"manageID":1,"manageName":"食品1a          ","memberPrice":0E-8,"monthSaleQty":2.000,"normalPrice":5.00000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":745.000,"pKName":"1*24        ","pKNum":10,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":5.00000000,"promFlag":0,"promotionName":"无促销","rNName":"个      ","rNum":10,"rNumSpec":"1*24        ","rationLockQty":0.000,"receiptdate":1445583240373,"runType":0,"spec":"1*2","startdate":1454401881780,"stockQty":2151.999,"todaySaleQty":0.000,"unitName":"个","venderID":"1","venderName":"公用测试供应商01aaaa                              ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":1.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000200009       ","cost":16.00000000,"deptID":"10202","deptName":"三鸟            ","dms":0.050,"enddate":1414598400000,"goodsID":"2","goodsName":"购销测试商品02  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":271.000,"logistics":3,"manageID":1,"manageName":"食品1a          ","memberPrice":25.00000000,"monthSaleQty":0.000,"normalPrice":28.00000000,"openMakeupQty":13.000,"openOrderQty":0.000,"openRationQty":646.000,"pKName":"1*6*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":28.00000000,"promFlag":0,"promotionName":"无促销","rNName":"件      ","rNum":1,"rNumSpec":"1*6*1       ","rationLockQty":0.000,"receiptdate":1445583255110,"runType":0,"spec":"1*1","startdate":1412092800000,"stockQty":1270.000,"todaySaleQty":0.000,"unitName":"件","venderID":"61","venderName":"购销供应商1-lzc                                   ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000300006       ","cost":10.00000000,"deptID":"10104","deptName":"test02          ","dms":0.052,"enddate":1414598400000,"goodsID":"3","goodsName":"购销测试商品03  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":1676.000,"logistics":1,"manageID":1,"manageName":"食品1a          ","memberPrice":0E-8,"monthSaleQty":0.000,"normalPrice":0.99000000,"openMakeupQty":10.000,"openOrderQty":-25.000,"openRationQty":440.000,"pKName":"1*12*1      ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":0.99000000,"promFlag":0,"promotionName":"无促销","rNName":"件      ","rNum":1,"rNumSpec":"1*12*1      ","rationLockQty":0.000,"receiptdate":1451441141817,"runType":0,"spec":"1*12","startdate":1412092800000,"stockQty":1755.000,"todaySaleQty":0.000,"unitName":"件","venderID":"7","venderName":"测试供应商2                                       ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000400003       ","cost":2.10000000,"deptID":"10104","deptName":"test02          ","dms":0.050,"enddate":1414598400000,"goodsID":"4","goodsName":"购销测试商品04  ","goodsStatus":1,"goodsTypeID":0,"inventoryQty":1288.000,"logistics":2,"manageID":1,"manageName":"食品1a          ","memberPrice":0.50000000,"monthSaleQty":0.000,"normalPrice":0.50000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":7.000,"pKName":"1*1*1       ","pKNum":24,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":0.50000000,"promFlag":0,"promotionName":"无促销","rNName":"ge      ","rNum":1,"rNumSpec":"1*1*1       ","rationLockQty":0.000,"receiptdate":1411608376827,"runType":0,"spec":"1*1","startdate":1412092800000,"stockQty":865.000,"todaySaleQty":0.000,"unitName":"ge","venderID":"9","venderName":"测试供应商4                                       ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000500000       ","cost":6.30000000,"deptID":"10103","deptName":"饮料            ","dms":0.050,"enddate":1414598400000,"goodsID":"5","goodsName":"购销测试商品05  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":300.000,"logistics":1,"manageID":1,"manageName":"食品1a          ","memberPrice":0E-8,"monthSaleQty":0.000,"normalPrice":10.30000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":30.000,"pKName":"1*3*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":10.30000000,"promFlag":0,"promotionName":"无促销","rNName":"jian    ","rNum":1,"rNumSpec":"1*3*1       ","rationLockQty":0.000,"receiptdate":1414653159217,"runType":0,"spec":"1*8","startdate":1412092800000,"stockQty":377.000,"todaySaleQty":0.000,"unitName":"jian","venderID":"10","venderName":"测试代销供xx                                      ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000600007       ","cost":12.00000000,"deptID":"10103","deptName":"饮料            ","dms":0.050,"enddate":1414598400000,"goodsID":"6","goodsName":"购销测试商品06  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":548.000,"logistics":2,"manageID":1,"manageName":"食品1a          ","memberPrice":14.50000000,"monthSaleQty":0.000,"normalPrice":15.00000000,"openMakeupQty":15.000,"openOrderQty":0.000,"openRationQty":16.000,"pKName":"1*6*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":15.00000000,"promFlag":0,"promotionName":"无促销","rNName":"jian    ","rNum":1,"rNumSpec":"1*6*1       ","rationLockQty":0.000,"receiptdate":1413452620903,"runType":0,"spec":"1*6","startdate":1412092800000,"stockQty":628.000,"todaySaleQty":0.000,"unitName":"jian","venderID":"8","venderName":"测试供应商3                                       ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000700004       ","cost":10.00000000,"deptID":"10103","deptName":"饮料            ","dms":0.050,"enddate":1414598400000,"goodsID":"7","goodsName":"代销测试商品01  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":294.000,"logistics":3,"manageID":1,"manageName":"食品1a          ","memberPrice":0E-8,"monthSaleQty":0.000,"normalPrice":14.00000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":17.000,"pKName":"1*1*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":14.00000000,"promFlag":0,"promotionName":"无促销","rNName":"个      ","rNum":1,"rNumSpec":"1*1*1       ","rationLockQty":0.000,"receiptdate":1413523335407,"runType":0,"spec":"1*1","startdate":1412092800000,"stockQty":294.000,"todaySaleQty":0.000,"unitName":"KG","venderID":"11","venderName":"测试代销供应商02                                  ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"2100000800001       ","cost":43.00000000,"deptID":"10103","deptName":"饮料            ","dms":0.050,"enddate":1414598400000,"goodsID":"8","goodsName":"代销测试商品02  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":13.000,"logistics":3,"manageID":1,"manageName":"食品1a          ","memberPrice":0E-8,"monthSaleQty":0.000,"normalPrice":14.00000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":6.000,"pKName":"1*3*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":14.00000000,"promFlag":0,"promotionName":"无促销","rNName":"个      ","rNum":1,"rNumSpec":"1*3*1       ","rationLockQty":0.000,"receiptdate":1309231502050,"runType":0,"spec":"1*3","startdate":1412092800000,"stockQty":13.000,"todaySaleQty":0.000,"unitName":"个","venderID":"127","venderName":"lhltest进货成本扣项                               ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000},{"autoMakeupQty":0.000,"badQty":0.000,"barCode":"880000000000        ","cost":80.00000000,"deptID":"10103","deptName":"饮料            ","dms":0.050,"enddate":1414598400000,"goodsID":"9","goodsName":"代销测试商品03  ","goodsStatus":0,"goodsTypeID":0,"inventoryQty":903.000,"logistics":1,"manageID":1,"manageName":"食品1a          ","memberPrice":14.00000000,"monthSaleQty":0.000,"normalPrice":14.00000000,"openMakeupQty":0.000,"openOrderQty":0.000,"openRationQty":0.000,"pKName":"1*4*1       ","pKNum":1,"pKNumSpec":" ","palletStockBadQty":0.000,"palletStockQty":0.000,"price":14.00000000,"promFlag":0,"promotionName":"无促销","rNName":"jian    ","rNum":1,"rNumSpec":"1*4*1       ","rationLockQty":0.000,"receiptdate":1428631121133,"runType":0,"spec":"1*4","startdate":1412092800000,"stockQty":903.000,"todaySaleQty":0.000,"unitName":"he","venderID":"10","venderName":"测试代销供xx                                      ","weekSaleQty":0.000,"weekSaleQty1":0.000,"weekSaleQty2":0.000,"weekSaleQty3":0.000,"weekSaleQty4":0.000}]

[b.txt](https://github.com/alibaba/fastjson/files/113614/b.txt)

**Comment by dachuanz** [comment]
问题可能在这里:0E-8

**Comment by wenshao** [comment]
什么版本？
