### ISSUE TITLE
spring mvc msg-converter 整型精度问题

### ISSUE THREAD

**Issue by myshzzx** [alibaba/fastjson#498]
js 能精确处理的整型数值上限是 2^53-1, 大约16个有效数字, 超出部分无法保存, 比如 1454469996415019862 会变成 1454469996415019800, 浏览器直接从服务端取json数据并转换会得到错误的结果.
`FastJsonHttpMessageConverter` 能考虑增加将大整型数值转换成字符串的功能吗? 比如加到 `BrowserCompatible` feature 里.

**Comment by wenshao** [comment]
哇，这么大的数字，用在什么场景？

**Comment by myshzzx** [comment]
用在库表主键, 懒得用序列生成主键, 用基于时间的方式生成主键, 冲突的概率很小, 用在管理系统是可以接受的. 结果丢到页面发现出问题了, 服务端返回json数据, 页面渲染后id太大, 值就变了

**Comment by wenshao** [comment]
已经解决，请等待1.2.8版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/pull/499/files
