### ISSUE TITLE
转化时怎么样指定特定的TimeZone

### ISSUE THREAD

**Issue by LostKe** [alibaba/fastjson#503]
日期转化的时候找了一圈结果转化的都是CST格式的，能否指定特定的时区呢

**Comment by LostKe** [comment]
找到了，实现ObjectSerializer就好了

**Comment by lilasxie** [comment]
> 找到了，实现ObjectSerializer就好了

你好，请问具体是怎么实现ObjectSerializer的呢，能否提供下示例呢~
