### ISSUE TITLE
fastjson可以自定义反序列化吗？

### ISSUE THREAD

**Issue by jialechan** [alibaba/fastjson#507]
fastjson可以自定义反序列化吗？有例子吗？
比如pojo如下：
```java
public class UserInfo {
    private List<String> attr1;
    ...
}
```
json如下：
```json
String str = "{\"attr1\":\"abc,def,efg\"}";
```
我想自定义反序列化，把字符串“abc,def,efg”以逗号为分割符，绑定到attr1的这个list里面

**Comment by sunbeams001** [comment]
May be help
https://github.com/alibaba/fastjson/wiki/ParseProcess

**Comment by jialechan** [comment]
@sunbeams001 Very useful and Thx!
我的demo例子：https://gist.github.com/jialechan/794dd90697f90abadf8f

**Comment by wnli350** [comment]
@jialechan 
demo打不开了
