### ISSUE TITLE
对于变量名类似为pId类的变量，用33版本的fastjson转换后会变成PId，用23版本的fastjson正常

### ISSUE THREAD

**Issue by rill** [alibaba/fastjson#51]
用了最新的33版本的fastjson后，对于一个小写字母加大写字母组合的变量，fastjson转换后会把首字母转成大写。之前是用23版本的是正常的

测试类如下：
public class FastJsonTest {
    public static void main(String[] args){
        FastJsonTest jsonTest = new FastJsonTest();
        TestInfo ts = jsonTest.new TestInfo();
        ts.setPId("aa");
        System.out.println(JSON.toJSONString(ts));
        System.out.println(ts.getPId());
    }

```
private class TestInfo{
    String pId="1";
    String t_id="2";
    String uName="abc";
    public String getPId() {
        return pId;
    }
    public void setPId(String pId) {
        this.pId = pId;
    }
    public String getT_id() {
        return t_id;
    }
    public void setT_id(String t_id) {
        this.t_id = t_id;
    }
    public String getUName() {
        return uName;
    }
    public void setUName(String uName) {
        this.uName = uName;
    }

}
```

}

**Comment by yanyinxi** [comment]
public class RestResHeaderDomain {

    private String method;

    @JSONField(name = "Ver")
    private String Ver;


public static void main(String[] args) {
        //com.alibaba.fastjson.util.TypeUtils.compatibleWithJavaBean = true;
        String str= JSON.toJSONString(new RestResHeaderDomain());

        System.out.println(str);
    }

结果：
{"ver":"2.0"}


不知道这个怎么用啊？
com.alibaba.fastjson.util.TypeUtils.compatibleWithJavaBean = true;

**Comment by yanyinxi** [comment]
@wenshao
