### ISSUE TITLE
修改JSON.DEFAULT_TYPE_KEY之后 序列化javabean报错

### ISSUE THREAD

**Issue by lhkzh** [alibaba/fastjson#512]
JSON.DEFAULT_TYPE_KEY = “@$”;
JSON.toJSONString(new User());

错误原因：
SymbolTable.java 长度定常了，而JSON.DEFAULT_TYPE_KEY又是可修改的。
this.addSymbol(JSON.DEFAULT_TYPE_KEY, 0, 5, JSON.DEFAULT_TYPE_KEY.hashCode());

**Comment by wenshao** [comment]
为啥要改这个啊。。。

**Comment by lhkzh** [comment]
这个-。- 你设置final 我就不改了哈哈。
当时该是，觉得 @ type字符有点长，手贱，试试改成自定义短点的--。
