### ISSUE TITLE
@JSONField(deserialize=false)注解的问题

### ISSUE THREAD

**Issue by xusheng1987** [alibaba/fastjson#517]
我是这样用的:List<WeightDto> list = JSON.parseArray(weightList, WeightDto.class);weightList是传递过来的json串,WeightDto中有一个属性我不想反序列化,然后用了@JSONField(deserialize=false),但是必须放在set方法上才起作用,看文档,JSONField配置在字段或者getter/setter方法上都可以.用的是1.2.8的版本,不知道算不算bug

**Comment by wenshao** [comment]
放在getter上是对序列化起作用，放在setter上是对反序列化起作用。
