### ISSUE TITLE
boolean类型字段JSONField指定name无效

### ISSUE THREAD

**Issue by phoenix** [alibaba/fastjson#52]
``` java
@JSONField(name = "is-abc")
private boolean isAbc;

public boolean isAbc() {
     return isAbc;
 }
```

最后序列化出来的不是is-abc，而是abc。
在TypeUtils中根据方法名猜测属性名的时候，对boolean类型以is开头的方法，是否可以先直接查找等于方法名的属性名，然后再去掉is查找属性名？另外，定义在属性上面的@JSONField是否可以直接读取属性相关信息进行序列化，不从相应方法中获取信息再进行序列化？
这个场景中，如果fastjson不做修改，有两种办法可以使@JSONField生效，1是将isAbc属性改成abc，2是将注解放到方法上面，都有点强制约定的感觉了。

**Comment by mh494078416** [comment]
有时候需要isXxx，这时应该怎么用呢？
parse出来的对象属性是xxx，希望是isXXX。
