### ISSUE TITLE
当有同名set方法时,JSONObject.parseObject多次执行行为不一致

### ISSUE THREAD

**Issue by gongweixin** [alibaba/fastjson#521]
```code
public class EnumTest {

    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public void setStatus(Status status) {
        this.status = status.code;
    }

    public static void main(String[] args) {
        for (int i = 0; i < 100; i++) {
            try {
                EnumTest enumTest = new EnumTest();
                enumTest.setStatus(3);
                String json = JSONObject.toJSONString(enumTest);
                JSONObject.parseObject(json, EnumTest.class);
            } catch (Exception e) {
                System.out.println(i);
            }
        }
    }

    public enum Status {
        ENABLE(1);

        private Integer code;
        Status(Integer code) {
            this.code = code;
        }
    }
}
```
运行上面代码,有一定概率成功,一定概率失败,概率5:5
如果成功,循环的100次都成功,如果失败循环的100次都失败
查看源码发现是
DeserializeBeanInfo.computeSetters(Class<?> clazz, Type type)方法中获取set方法,如果发现同名的方法只会保留第一个,而Class.getMethods() 是不保证方法的返回顺序的, 当setStatus(Integer status)先返回的时候就运行正常,而setStatus(Status status)先返回的时候会获取枚举Status中排位第3的元素,获取失败抛出了异常.
根据实验的现象可以推测,虽然Class.getMethods()不保证返回的方法数组中的顺序,但顺序应该在编译的时候已经确定了,所以同一次运行中,多次也不会出现不同的现象.

提两个解决建议:
1.根据字段值(这是数字3),选择更优的set方法,setStatus(Integer status)比setStatus(Status status)合理的多.  当然无法保证用户真正的想法到底是setStatus(Integer status)还是setStatus(Status status)

2.有固定的调用优先性, 保证多次运行结果的唯一性, 要么每次都是setStatus(Integer status),要么每次都是setStatus(Status status)

**Comment by wenshao** [comment]
收到，有一定道理

**Comment by wenshao** [comment]
采取你建议中的第二点，实现代码在这个commit https://github.com/alibaba/fastjson/commit/81315ee0a94d9414b174fe36f5d390ae627dc8e6 中。
