### ISSUE TITLE
JSON.toJSONString()序列化下划线开头的变量时，下划线消失，这算bug吗？

### ISSUE THREAD

**Issue by Forgus** [alibaba/fastjson#526]
![image](https://cloud.githubusercontent.com/assets/9947778/13979149/540cb46a-f111-11e5-93d3-f7b3abd2ea0b.png)
![image](https://cloud.githubusercontent.com/assets/9947778/13979175/87d239be-f111-11e5-8a63-fa947b0b4087.png)
![image](https://cloud.githubusercontent.com/assets/9947778/13979186/9a8c4a54-f111-11e5-8421-53ca011939d7.png)

**Comment by comcp** [comment]
你用 注解 @JSONField(name="_embedded") 试试

**Comment by wenshao** [comment]
因为有get _embedded()方法存在，自动识别为embedded了，设计就是这样的，不算bug
