### ISSUE TITLE
序列化能自动trim掉末尾的回车换行符吗

### ISSUE THREAD

**Issue by OurInterestSystem** [alibaba/fastjson#527]
序列化的时候，由于用户误操作后面多加了回车换行符“xxx\n\n”，导致序列化出来，浏览器报错，这不是严格的json，请问fastjson本身有相关的featrue处理吗？
btw，
BrowserCompatible
BrowserSecure
这两个feature分别是什么意思，能帮我解决这个问题吗？作者能在代码上加点注释吗？文档能加上对所有feature的一个解释吗？

**Comment by wenshao** [comment]
加上BrowserSecure，\n输出的"\u000A"，缺省输出"\n"，浏览器都不应该报错啊

**Comment by wenshao** [comment]
也可以使用ValueFilter处理多余的字符。比如 https://github.com/alibaba/fastjson/wiki/%E5%AE%9A%E5%88%B6%E5%BA%8F%E5%88%97%E5%8C%96
