### ISSUE TITLE
map 序列化出bug了啦~~~~~~~~~！

### ISSUE THREAD

**Issue by chenhaipeng** [alibaba/fastjson#529]
user
`public class User {

        private Long id;
        private String name;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
}`

以下 系测试：
`    @Test
    public void testString2GenericCollection() {
        List<User> list = new ArrayList<User>();
        User user = new User();
        user.setId(1l);
        user.setName("xiaoming");
        User user2 = new User();
        user2.setId(2l);
        user2.setName("xiaoming2");
        list.add(user);
        list.add(user2);

        Map<String,User> map = new HashMap<String, User>();
        map.put("a",user);
        map.put("b",user2);
        map.put("c",user);

        String s2 = FastJsonUtils.object2String(list);
        System.out.println(s2);
//        String mapstr = FastJsonUtils.object2String(map);
        String mapstr = JSON.toJSONString(map);

//        Map<String,User> map1 = (Map<String,User>)JSON.parse(mapstr);
        Map<String,User> map1 = JSON.parseObject(mapstr, new TypeReference<Map<String, User>>() {});
        for (String key : map1.keySet()) {
            System.out.println(key+":============="+map1.get(key));
        }
        System.out.println(mapstr);
//        System.out.println(listUser.get(0).getName());

    }`

结果：
`[{"id":1,"name":"xiaoming"},{"id":2,"name":"xiaoming2"}]
b:=============org.fastjson.entity.User@57b5b346
c:=============org.fastjson.entity.User@5a0ce5a6
a:=============org.fastjson.entity.User@5a0ce5a6
{"b":{"id":2,"name":"xiaoming2"},"c":{"id":1,"name":"xiaoming"},"a":{"$ref":"$.c"}}`

以下系同样的代码:
jackson的结果
`[{"id":1,"name":"xiaoming"},{"id":2,"name":"xiaoming2"}]
b:=============com.pp.commons.loan.User@57c70722
c:=============com.pp.commons.loan.User@4ba57633
a:=============com.pp.commons.loan.User@5bf33511
{"b":{"id":2,"name":"xiaoming2"},"c":{"id":1,"name":"xiaoming"},"a":{"id":1,"name":"xiaoming"}}`

**Comment by wenshao** [comment]
这是特性，如果想关闭这个特性：JSON.toJSONString(object, SerializerFeature.DisableCircularReferenceDetect)
