### ISSUE TITLE
序列化字符串为JSONObject中如果key类型为数字报CastException

### ISSUE THREAD

**Issue by JeryZeng** [alibaba/fastjson#53]
关于_DefaultJSONParser_这个类的parseObject方法在下有一点建议，因为今天用fastjson反序列化为JSONObject的时候遇到这样一个问题，就是如果key如果为数字类型的话，就会报类型转换错误，因为JSONObject只支持String的key类型，所以我想387行处，将new JSONObject()的功能放开，让子类去选择生成一个什么样的Map，希望这个功能能够加入到fastjson中，这将对我们很有用，谢谢

**Comment by nqdy666** [comment]
楼主，您的这个问题解决了么？
我使用1.2.3版本的fastJson，还是会报错。
JSONObject.parseObject("0:test")
报错信息：com.alibaba.fastjson.JSONException: error parse true
