### ISSUE TITLE
关于FastJson容错机制的问题

### ISSUE THREAD

**Issue by YongHuiLuo** [alibaba/fastjson#530]
关于fastJson使用的问题，需要请教一下
问题描述： 我有一个model，结构如下
public class User{
    public void name;
    public School school;
}

public class School{
   public void id;
   public void address;
}

当我的Json返回值为     {"name":“tiny.luo”,"school":""}  注：school返回的不是一个对象，而是一个“”。

此时，fastjson会给我返回一个Exception ： syntax error, expect {, actual  , pos  148, fieldName school
然后我的页面加载不出来任何信息。

我想达到的效果是 ： 
当school 的key和value值类型不能对应的时候，默认给school附一个null对象，其余可以正常解析的字段，能正常显示。

我尝试过的方法：
1） JSON.parseObject(text, clazz,new Feature[]{Feature.IgnoreNotMatch})
网上有资料说 Feature可以解决这个问题，IgnoreNotMatch，忽略掉不提配的字段，但是没有成功。
2） 源码中`if (lexer.token() != JSONToken.LBRACE && lexer.token() != JSONToken.COMMA) {`这段代码如果返回true，则报上面的异常信息。

请问一下，有什么方法能够好的解决这个问题。

**Comment by runweok** [comment]
同问此问题～

**Comment by YongHuiLuo** [comment]
@wenshao   @axmanwang

**Comment by pcwang** [comment]
我也有此问题，对于序列化时同样，能否做到对于某个属性序列化失败就忽略，但是不要整个方法报错

**Comment by xinghui0000** [comment]
为了这个问题整个项目的json解析都换成gson了

**Comment by wenshao** [comment]
收到，会尽快支持

**Comment by wenshao** [comment]
为什么会生成这么特别的字符？

**Comment by wenshao** [comment]
我测试过了，gson不支持""变为空对象哦，但支持中文双引号
```java
import com.google.gson.Gson;
import junit.framework.TestCase;

public class TestChineseQuote extends TestCase {
    public void test_chinese_quote() throws Exception {
        String text = "{\"name\":“tiny.luo”,\"school\":\"\"}";

        Gson gson = new Gson();
        User user = gson.fromJson(text, User.class);
    }

    public static class User {

        public String name;
        public School school;
    }

    public static class School {
        public int    id;
        public String address;
    }
}
```

**Comment by xinghui0000** [comment]
对 gson也不支持""变为空对象，
如果json串为：
```
{
        "name": "user1",
        "school": ""
   }
```
用gson：
```
try {
            GsonBuilder builder = new GsonBuilder();
            builder.registerTypeAdapter(School.class, new JsonDeserializer<School>() {
                @Override
                public School deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
                    if (!json.isJsonObject()) {
                        return null;
                    }
                    Gson gson = new Gson();
                    return gson.fromJson(json.getAsJsonPrimitive().getAsString(), School.class);
                }
            });
            User user = builder.create().fromJson(strJson, User.class);
        } catch (Exception e) {
            mResultTextView.setText("Catch a exception:" + e.getMessage());
        }
```
像上面这个样子是能解析成功的。
如果返回的json：
```
[
    {
        "name": "user1",
        "school": ""
    },
    {
        "name": "user2",
        "school": ""
    }
]
```
将上面的`gson.fromJson(json.getAsJsonPrimitive().getAsString(), School.class);`替换成 `builder.create().fromJson(strJson, new TypeToken<List<User>>(){}.getType());`就可以解析成数组。
但是如果用fastjson解析，如果返回的第一种json串，用ParseProcess也能解决，但是如果返回类似于第二种数组形式的json格式，我没找到能解决的办法

**Comment by YongHuiLuo** [comment]
感谢 @wenshao 回答此问题，我自己也试验过，Gson确实也不支持""变为空对象，另外我的实验结果，当"{\"name\":“tiny.luo”,\"school\":“”}"，school为中文的双引号的时候，也会报`IllegalStateException： Expected BEGIN_OBJECT but was STRING at line 1 column 29 path $.school`异常，但是在开发的过程中，要需要面临这种容错的需求，最近也在学习FastJson的代码，确实写的很赞。 也感谢 @xinghui0000 提供的方案。

**Comment by wenshao** [comment]
已经支持长度为0的字符串读取为空对象。1.2.9 & 1.1.49.android中带这个功能。

**Comment by MRCHENDQ** [comment]
我想问一下 当一个属性id类型为Integer时候， 数据出现错误 id 变成了“abcd”  我使用JSON.parseObject 时候 会报错 parseInt error, field : id  请问如何处理这个设置为空呢？或者其他的容错设置

**Comment by neil4dong** [comment]
@MRCHENDQ  把这个Integer字段的setter方法写成接收String字符串的， 然后自己判断一下
