### ISSUE TITLE
对java.sql.Time的反序列化支持不够好啊

### ISSUE THREAD

**Issue by cnlizhen** [alibaba/fastjson#532]
java.sql.Time可以用Time.valueOf("17:00:00")生成对象，但JSON.parseObject(String text, Class<T> clazz)却不能反序列化"17:00:00"。
翻了一下源码，是因为TimeDeserializer不支持“HH:mm:ss”格式数据的反序列化，再往下翻是因为
JSONScanner的scanISO8601DateIfMatch方法不支持。
希望下一版加入对HH:mm:ss的反序列化支持。

**Comment by wenshao** [comment]
bug fixed，请等fastjson-1.2.9版本发布
