### ISSUE TITLE
问下，能支持遇到不是符合javaBean的字段时，有提供类转换器吗

### ISSUE THREAD

**Issue by wangsuicheng** [alibaba/fastjson#538]
比如我一个bean类的里有个变量是个特殊的类，fastjson有提供转换器让我遇到这样的类时，可以转换成像String这样的吗？

**Comment by wenshao** [comment]
能提供更详细的信息么？

**Comment by wangsuicheng** [comment]
比如我的bean类里有个A类，想把这个A类变成String输出到jsonString里 
------------------ Original ------------------

**Comment by wenshao** [comment]
参考这个 https://github.com/alibaba/fastjson/wiki/SerializeFilter
