### ISSUE TITLE
自省功能

### ISSUE THREAD

**Issue by mrdaios** [alibaba/fastjson#539]
@wenshao 你好，有方法关闭fastjson的自省功能吗？我这边有个需求需要list里面的元素都带上@type，不然是list还是list<A>都能带上，有什么办法可以配置吗？谢谢

**Comment by wenshao** [comment]
parse还是toJSONString时的需求？

**Comment by wenshao** [comment]
已经有这样的功能Feature.DisableSpecialKeyDetect，在1.2.5之后就有了。

**Comment by mrdaios** [comment]
@wenshao 你好，之前问题没描述清楚。
我的意思是toJSONString的时候JavaBean里面的有属性是List或者List<TestModel>,json后的数据都带上{"@type":"xx.TestModel"}吗？刚刚查询了DisableSpecialKeyDetect这个是解析的时候用的呢？谢谢

**Comment by mrdaios** [comment]
@wenshao 你好，
我现在的处理方式是把ASMSerializerFactory.java的_list方法中
//  if (elementType instanceof Class<?>) {
//            elementClass = (Class<?>) elementType;
//        }
把elementClass默认为null。这样下面的逻辑就生成了@type

**Comment by wenshao** [comment]
可以使用com.alibaba.fastjson.serializer.BeforeFilter来实现你的需求。
