### ISSUE TITLE
fastjson1.1.48.android会包含gson2.6.2

### ISSUE THREAD

**Issue by jklwan** [alibaba/fastjson#540]
你好，从1.1.47.android升级到1.1.48.android后打包，会把gson2.6.2打包到apk文件中。使用方式是gradle：compile 'com.alibaba:fastjson:1.1.48.android'

**Comment by wenshao** [comment]
这是一个打包错误，悲剧了，请先做exclude处理吧，我会尽快发布新版修正这个问题。
