### ISSUE TITLE
utf-8+BOM头，解析出错的问题！

### ISSUE THREAD

**Issue by ada-android** [alibaba/fastjson#545]
json带有bom头时，JSONObject.parseObject(jsonStr)报错
W/System.err( 1559): com.alibaba.fastjson.JSONException: TODO error 
W/System.err( 1559): 	at com.alibaba.fastjson.parser.AbstractJSONParser.parse(AbstractJSONParser.java:188)
W/System.err( 1559): 	at com.alibaba.fastjson.JSON.parse(JSON.java:84)
W/System.err( 1559): 	at com.alibaba.fastjson.JSON.parse(JSON.java:75)
W/System.err( 1559): 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:142)

但是当我用new org.json.JSONObject(jsonStr)进行解析时，正常。
是fastjson没有进行过滤么？

**Comment by wenshao** [comment]
什么版本？

**Comment by ada-android** [comment]
@wenshao 2015.7.30之前的版本 具体版本号不清楚

**Comment by wenshao** [comment]
最新版本都是支持的'\ufeff' 这样的utf-8 bom的，我先关闭啦
