### ISSUE TITLE
fastJSON在springMVC 3.2.0.RELEASE下输出JSON报406错误

### ISSUE THREAD

**Issue by zhaohaolin** [alibaba/fastjson#55]
SpringMVC配置文件如下
<bean 
 class="org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter">
        <property name="messageConverters">
            <list>
                <ref bean="mappingFastJsonHttpMessageConverter" />
            </list>
        </property>
    </bean>

```
<bean id="mappingFastJsonHttpMessageConverter"
    class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">
</bean>
```

在Controller中输出如下示：
@RequestMapping(value = "/hello1")
    @ResponseBody
    public List<String> json() {
        LOG.info("will response json data.");
        return new ArrayList<String>() {
            /**
             \* 
             */
            private static final long   serialVersionUID    = 1L;

```
        {
            add("我爱中国");
            add("我有我有祖国");
            add("Hello");
            add("Hello");
            add("我爱中华人民共和国");
            add("Hello");
        }
    };
}
```

**Comment by biezhi** [comment]
同遇到该问题，在springmvc 4.3版本中，解决方法如下：
```xml
<mvc:annotation-driven>
    <mvc:message-converters register-defaults="true">
        <bean class="com.bbs.converter.CustomerFastJsonHttpMessageConverter">
            <property name="supportedMediaTypes">
                <list>
                    <value>application/json;charset=UTF-8</value>
                    <value>text/html;charset=UTF-8</value>
                    <value>text/xml;charset=UTF-8</value>
                    <value>text/plain;charset=UTF-8</value>
                </list>
            </property>
        </bean>
    </mvc:message-converters>
</mvc:annotation-driven>
```
