### ISSUE TITLE
Version 1.2.x build for Android

### ISSUE THREAD

**Issue by kirisetsz** [alibaba/fastjson#552]
There are binaries of android version in maven repository as of version 1.1.48. 
Will android build available again in future release?

**Comment by wenshao** [comment]
i already back port some new feature & bug fixed to 1.1.49.android version. why not use 1.1.49.android?

**Comment by kirisetsz** [comment]
That is, 1.1.x and 1.2.x are just different release branches?

**Comment by wenshao** [comment]
the method 'com.alibaba.fastjson.serializer.ObjectSerializer.write' signature changed.

```java
// 1.1.x
void write(JSONSerializer serializer, 
                Object object, 
                Object fieldName, 
               Type fieldType) throws IOException;

// 1.2.x
void write(JSONSerializer serializer, 
                Object object, 
               Object fieldName, 
               Type fieldType, 
               int features // added in 1.2.x
) throws IOException;
```
