### ISSUE TITLE
JSON特殊场景问题(不想反序列化的实现json中的json)

### ISSUE THREAD

**Issue by yu120** [alibaba/fastjson#564]
场景class A{
		private String a="123";
		private int b=21;
		private String c="{"mm":"sd"}";//json字符串
	}
预期效果：{"a":"123","b":21,"c":{"mm":"sd"}}。因为c的数据有可能很大，所以我不想动c的实现类最终的json字符串，如何实现？

**Comment by wenshao** [comment]
收到，我想想怎么实现啊

**Comment by wenshao** [comment]
已经实现
https://github.com/alibaba/fastjson/wiki/JSONField_jsonDirect_cn

**Comment by yu120** [comment]
@wenshao 你好，这个功能虽然已经实现，但可以做得更灵活点吗？
public static class Model {
    public int id;
    @JSONField(jsonDirect=true)
    public String value;
}
比如说value自动适配，如果value是一个json字符串就会自动适配该功能，实现标准json化；如果value不是一个json，则直接作为String类型输出，而不是直接抛异常。
