### ISSUE TITLE
1.2.10 NOT compatible with Spring MVC 4.2+

### ISSUE THREAD

**Issue by XiaoSK** [alibaba/fastjson#574]
See [commitcomment-17226726](https://github.com/alibaba/fastjson/commit/fe32c149ebfb83e3fbbe7c5c55e918c96937d064#commitcomment-17226726).

**Comment by VictorZeng** [comment]
Thank u for your advice, I will add the new Converter for Spring framework 4.2+.

**Comment by VictorZeng** [comment]
@XiaoSK Please see #575

**Comment by VictorZeng** [comment]
fixed in #579

**Comment by wenshao** [comment]
1.2.1发布了，问题已经解决。请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.11_release
