### ISSUE TITLE
反序列化是否支持这种.Net生成的日期格式？

### ISSUE THREAD

**Issue by johnshen1990** [alibaba/fastjson#586]
对于下面这种.Net生成的日期格式，fastjson是否默认支持反序列化呢？
```"StartDateTime": "/Date(1461081600000-0000)/"```
文档里的.NET JSON日期格式具体指哪一种呢？
> 反序列化能够自动识别如下日期格式：
> - ISO-8601日期格式
> - yyyy-MM-dd
> - yyyy-MM-dd HH:mm:ss
> - yyyy-MM-dd HH:mm:ss.SSS
> - 毫秒数字
> - 毫秒数字字符串
> - .NET JSON日期格式
> - new Date(198293238)

**Comment by wenshao** [comment]
可以，下个版本1.2.11将会支持

**Comment by johnshen1990** [comment]
太感谢了，只是现在有个紧急的需求需要先解决这个问题～
能不能告诉我，目前可以如何来解决这个问题呢？就是如何使用自定义的日期格式进行反序列化？

**Comment by wenshao** [comment]
现在就差.NET的不支持吧，我5.1期间发布新版，将支持，能等几天么？

**Comment by johnshen1990** [comment]
嗯，那我先反序列化成字符串，简单粗暴地转吧，回头发新版后再改～

**Comment by wenshao** [comment]
.NET格式现在是
```
/Date(1461081600000)/
```
不支持这种把：
```
/Date(1461081600000-0000)/
```

**Comment by johnshen1990** [comment]
支持的。 请参考：https://msdn.microsoft.com/en-us/library/bb412170.aspx

**Comment by wenshao** [comment]
已支持，请等五一期间发布1.2.11版本

**Comment by wenshao** [comment]
1.2.1发布了，问题已经解决。请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.11_release
