### ISSUE TITLE
服务端序列化时，get方法抛异常，导致序列化失败

### ISSUE THREAD

**Issue by hahahallllllllll** [alibaba/fastjson#590]
服务端使用fastJson序列化时，get方法抛异常，导致序列化失败。希望能吃掉异常，继续序列化其他get方法。系统中曾经因为序列化时get方法抛异常，导致故障。

**Comment by wenshao** [comment]
已经支持，文档在这里：
https://github.com/alibaba/fastjson/wiki/SerializerFeature_IgnoreErrorGetter_cn

**Comment by wenshao** [comment]
1.2.1发布了，问题已经解决。请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.11_release

**Comment by Larnoo** [comment]
是否可以配置不序列化getter方法 @wenshao 。
在Android中，属性都是public的，然后有一些getter是根据几个属性生成的，不想序列化增加序列化和反序列化的开销
