### ISSUE TITLE
在整合Spring Boot中FastJsonHttpMessageConverter的错误

### ISSUE THREAD

**Issue by boomyamm** [alibaba/fastjson#591]
1.2.10版本的jar包中FastJsonHttpMessageConverter类缺失canWrite相关的方法实现, 导致在与spring boot整合的过程中报错, java.lang.AbstractMethodError: `com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.canWrite(Ljava/lang/reflect/Type;Ljava/lang/Class;Lorg/springframework/http/MediaType;)Z`
但是在master分支的源码中却是包含canWrite相关方法的实现, 这是什么原因导致的?
@wenshao

**Comment by VictorZeng** [comment]
FastJson 1.2.10 目前不兼容 Spring 4.2+ 
下一版本中将进行更新

**Comment by wenshao** [comment]
@VictorZeng 准备五一期间发布1.2.11版本，麻烦发布前再看看是否会有BUG和兼容问题

**Comment by VictorZeng** [comment]
@wenshao okay

**Comment by wenshao** [comment]
1.2.1发布了，问题已经解决。请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.11_release
