### ISSUE TITLE
com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4 如何配置

### ISSUE THREAD

**Issue by zzone** [alibaba/fastjson#601]
配置一番总是出错 有哦没有文档介绍。
java.lang.NoSuchMethodError: com.alibaba.fastjson.JSON.writeJSONString(Ljava/io/OutputStream;Ljava/nio/charset/Charset;Ljava/lang/Object;Lcom/alibaba/fastjson/serializer/SerializeConfig;[Lcom/alibaba/fastjson/serializer/SerializeFilter;Ljava/lang/String;I[Lcom/alibaba/fastjson/serializer/SerializerFeature;)I

**Comment by wenshao** [comment]
是不是fastjson版本并存了？

**Comment by zzone** [comment]
没有，只引入了1.1.12版本，配合spring mvc4.2+

**Comment by zzone** [comment]
好吧 大神 是多引入了1.1.10

**Comment by wenshao** [comment]
那我关闭啦
