### ISSUE TITLE
当枚举的原始值小于枚举类枚举的个数时解析枚举类型抛出错误

### ISSUE THREAD

**Issue by igordonxiao** [alibaba/fastjson#602]
Hi wenshao:

我们有枚举类：

```
 public enum ResultCode {
    SUCCESS(1), ERROR(-1), UNKOWN_ERROR(999), LOGIN_FAILURE(8),  INVALID_ARGUMENT(0), SIGN_ERROR(17);
    private final int value;
    ResultCode(int value) {
        this.value = value;
    }
     public int getValue() {
        return value;
    }
 }
```

当我们后台返回JSON数据   {"resultCode":8,"resultMsg":"\u767b\u5f55\u5931\u8d25"}   用fastJSON解析时，在com.alibaba.fastjson.parser.deserializer.EnumDeserializer类的36行有如下抛错：

```
 if (intValue < 0 || intValue > values.length) {
                     throw new JSONException("parse enum " + enumClass.getName() + " error, value : " + intValue);
                  }
```

intValue就是后面返回的数字8，但我的整个枚举类中定义的枚举个数只有6个，枚举值8大于6就报出了这个错误，我知道我们这边的枚举值定义也有不妥之处，但都已经是跑了很久的后台，且是用PHP写的，改起来会比较麻烦。您看这个问题可以在下个版本中支持这种枚举值不必大于枚举个数的情况么？

**Comment by wenshao** [comment]
fastjson解析枚举类型时，如果遇到数值，就以为是ordinal，而不是你其中的value，于是悲剧了。能否让服务器返回字符串或者ordinal，而不是你定义的value？

**Comment by wenshao** [comment]
你参考这个文档自定义反序列化吧 https://github.com/alibaba/fastjson/wiki/ObjectDeserializer_cn
