### ISSUE TITLE
1.2.11版FastJsonHttpMessageConverter里setContentLength无效

### ISSUE THREAD

**Issue by tenwx** [alibaba/fastjson#605]
FastJsonHttpMessageConverter和FastJsonHttpMessageConverter4类里的writeInternal方法目前采用writeJSONString方法后，导致OutputStream先于headers设置，进行了write（writeToEx方法内）操作，导致setContentLength无效。
原来我提交的一次merge就是为了解决ContentLength缺失问题：https://github.com/alibaba/fastjson/pull/544

**Comment by wenshao** [comment]
你重新提交一个patch吧

**Comment by tenwx** [comment]
https://github.com/alibaba/fastjson/pull/606

**Comment by tenwx** [comment]
#625
