### ISSUE TITLE
在Linux下fastjson取key不正确

### ISSUE THREAD

**Issue by HeMing16** [alibaba/fastjson#611]
json:{"priority":1}

json.getIntegerValue("priority");此句取出的却是0

**Comment by wenshao** [comment]
fastjson没有这样的api啊

**Comment by HeMing16** [comment]
是我写错了   是这个      getIntValue("priority");

**Comment by wenshao** [comment]
不可能啊，回归测试都在linux上跑的

**Comment by HeMing16** [comment]
但确实是这样的，我们的服务器就是Linux环境，执行此代码时就是取不到值，还有下面这些：
int isOpenSwitch = jsonResult.getIntValue("isInOpenHourSwitch");//取不到正确的值，默认取0
int isNearShopSwitch = jsonResult.getIntValue("isNearShopSwitch");//取不到正确的值，默认取0
Boolean isOpenSwitch = jsonResult.getBoolean("isInOpenHourSwitch");//取出的值为null

注：{"isInOpenHourSwitch":1,"isNearShopSwitch":0}

**Comment by wenshao** [comment]
JSONObject中就是一个HashMap或者LinkedHashMap，获取不到是不应该的啊

**Comment by HeMing16** [comment]
字符串转json是这样的，结果取值就是取不到正确的了
com.alibaba.fastjson.JSONObject jsonResult = com.alibaba.fastjson.JSONObject.parseObject("{\"isInOpenHourSwitch\":1,\"isNearShopSwitch\":0}");

**Comment by wenshao** [comment]
诡异，并且无法重现，你自己先找找原因吧，我也做不了啥

**Comment by HeMing16** [comment]
嗯，这种现象确实不好定位，目前解决方案是将参数封装为对象，然后json字符串转位对象实体再取参。
ParamConfigInfo configInfo = jsonResult.getObject("data",ParamConfigInfo.class);
package com.qbao.store.view;

public class ParamConfigInfo {

	private Integer priority;
	private Integer isInOpenHourSwitch;
	private Integer isNearShopSwitch;
	private Long distanceToShop;

	/**
	 * @return the priority
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * @param priority
	 *            the priority to set
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * @return the isInOpenHourSwitch
	 */
	public Integer getIsInOpenHourSwitch() {
		return isInOpenHourSwitch;
	}

	/**
	 * @param isInOpenHourSwitch
	 *            the isInOpenHourSwitch to set
	 */
	public void setIsInOpenHourSwitch(Integer isInOpenHourSwitch) {
		this.isInOpenHourSwitch = isInOpenHourSwitch;
	}

	/**
	 * @return the isNearShopSwitch
	 */
	public Integer getIsNearShopSwitch() {
		return isNearShopSwitch;
	}

	/**
	 * @param isNearShopSwitch
	 *            the isNearShopSwitch to set
	 */
	public void setIsNearShopSwitch(Integer isNearShopSwitch) {
		this.isNearShopSwitch = isNearShopSwitch;
	}

	/**
	 * @return the distanceToShop
	 */
	public Long getDistanceToShop() {
		return distanceToShop;
	}

	/**
	 * @param distanceToShop
	 *            the distanceToShop to set
	 */
	public void setDistanceToShop(Long distanceToShop) {
		this.distanceToShop = distanceToShop;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ParamConfigInfo [priority=" + priority
				+ ", isInOpenHourSwitch=" + isInOpenHourSwitch
				+ ", isNearShopSwitch=" + isNearShopSwitch
				+ ", distanceToShop=" + distanceToShop + "]";
	}

}

**Comment by wenshao** [comment]
我猜测是你测试场景有问题，存在大小写不匹配的情况
