### ISSUE TITLE
希望增加对Java8中的LocalDateTime等类的格式化支持，目前只是json为toString输出，谢谢

### ISSUE THREAD

**Issue by tspoison** [alibaba/fastjson#612]
对LocalDateTime等类的解析也仅仅调用了LocalDateTime.parse(text)
未支持不同格式的时间解析，希望增加，谢谢

[https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/parser/deserializer/Jdk8DateCodec.java](url)

**Comment by wenshao** [comment]
这个不好支持其他格式吧？

**Comment by wenshao** [comment]
现在修改了，如果nano为0，缺省使用JSON.DEFFAULT_DATE_FORMAT的配置yyyy-MM-dd HH:mm:ss

**Comment by tspoison** [comment]
请问现在字符串转为JSON和JSON转为字符串都支持格式“yyyy-MM-dd HH:mm:ss”吗？还有就是您最新的commit我本地是怎样才能检出为jar呢？是删除以前的jar重新导入还是有另外的快照版本？ 谢谢

**Comment by wenshao** [comment]
fastjson是标准的maven工程，你可以执行如下命令获得最新的jar
```
mvn clean package
```

**Comment by tspoison** [comment]
maven central 中是5月2日的版本，请问怎样才能获取到最新的版本？
![the central repository search engine](https://cloud.githubusercontent.com/assets/10725601/15064352/f08b3b7c-1385-11e6-812a-4620f74b7513.png)

**Comment by wenshao** [comment]
fastjson当前在公网没有快照仓库，你只能自行编译

**Comment by tspoison** [comment]
好的，下一个realease版本大概什么时候发布？我好到时更换为realease版本。

**Comment by wenshao** [comment]
预计到6月初

**Comment by tspoison** [comment]
好的，再次感谢 :joy:
