### ISSUE TITLE
JSONObject,JSONArray 只能通过遍历生成集合吗？

### ISSUE THREAD

**Issue by lixi0912** [alibaba/fastjson#622]
比如 json 格式为 {"page":1,"list":[{"title":"title","images":["",""]}]}
而整个 json 因为某些需求，需要先解析成 JSONObject ，之后要拿 list 集合 是不是只能通过遍历的方式了？

**Comment by wenshao** [comment]
目前是这样的，你也可以了解fastjson实现的JSONPath https://github.com/alibaba/fastjson/wiki/JSONPath
