### ISSUE TITLE
fastjson如何处理某处有可能是Bean有可能是List的情况

### ISSUE THREAD

**Issue by Liubey** [alibaba/fastjson#626]
首先想说的是这个json不规范，可是我想问问有没有处理方法？
比如正常是个这样的json结构：
`{"ResultCode":"0","HallSiteAreas":[{"HallSiteArea":{"SeatPieceNo":"01","SeatPieceName":"\u5168\u5385"}},{"HallSiteArea":{"SeatPieceNo":"01","SeatPieceName":"\u5168\u5385"}}]}`

但是有时候会返回：
`
{"ResultCode":"0","HallSiteAreas":{"HallSiteArea":{"SeatPieceNo":"01","SeatPieceName":"\u5168\u5385"}}}`

这种怎么搞？

**Comment by wenshao** [comment]
我没想好该怎么设计API，你也想想？

**Comment by wenshao** [comment]
在已发布的1.2.12中已经解决
