### ISSUE TITLE
使用BeanToArray和SupportArrayToBean出现异常

### ISSUE THREAD

**Issue by lwlzpn84** [alibaba/fastjson#630]
Model model = new Model();
    model.setId(123);
    model.setName("gaotie");
    
    String str = JSON.toJSONString(model, SerializerFeature.BeanToArray);
    System.out.println(str);
    JSON.parseObject(str, Feature.SupportArrayToBean);

[123,"gaotie"]
Exception in thread "main" java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject

序列化的过程中使用了SerializerFeature.BeanToArray，反序列化的时候如何才能还原成原对象呢？

**Comment by wenshao** [comment]
```java
JSON.parseObject(str, Model.class, Feature.SupportArrayToBean);
```

**Comment by lwlzpn84** [comment]
谢谢，这样可以了。另外，对于包含嵌套对象的VO，是不是不支持BeanToArray的方式？

**Comment by lwlzpn84** [comment]
我自己写了一个嵌套的VO，测试了下，是可以使用BeanToArray方式的。项目中的VO使用BeanToArray方式，在反序列化时候提示语法错误，可能是项目中的VO比较复杂，某些字段有问题。

**Comment by lwlzpn84** [comment]
public class Model {
  private int id;
  private String name;
  private String modelName;
  private boolean isFlay;
  private List<Person> persons;
}

    Model model = new Model();
    model.setId(123);
    model.setName(null);
    model.setModelName(null);
    model.setIsFlay(false);
   **## model.setPersons(null);**
    
    String str = JSON.toJSONString(model, SerializerFeature.BeanToArray);
    System.out.println(str);
    JSON.parseObject(str, Model.class, Feature.SupportArrayToBean);

   测试中发现，当persons字段值为null的时候，JSON.parseObject(str, Model.class, Feature.SupportArrayToBean);出提示语法错误

**Comment by wenshao** [comment]
什么版本？1.2.11应该是好的啊

**Comment by lwlzpn84** [comment]
我用的是1.2.11，JDK 8

**Comment by wenshao** [comment]
问题重现并解决，谢谢反馈，将会1.2.11 & 1.1.52.android版本中修复此问题，预计在5月22日发布

**Comment by lwlzpn84** [comment]
赞
