### ISSUE TITLE
解析字段为null的会出错

### ISSUE THREAD

**Issue by vs791019223** [alibaba/fastjson#632]
要怎么解析字段为null的 ， 解析会出错

**Comment by wenshao** [comment]
应该不会的啊，你能提供重现问题的testcase么？

**Comment by uuttxtgyf** [comment]
我也遇到了，json是   { "msg": "", "code": 0, "data": null}
public abstract class Entity implements Serializable {
	public Entity(){
	}
	public int code;
	public String msg;
}

      Entity entity= JSONObject.parseObject(json, Entity.class);
这样解析出来的entity就是null
