### ISSUE TITLE
Spring Data JPA 创建的Page<T>对象无法转换成 JsonObject

### ISSUE THREAD

**Issue by CharonS** [alibaba/fastjson#638]
```
Page<Post> postList = postService.getPostList(pageable);
JSONObject obj = (JSONObject) JSON.toJSON(postList);
```
使用这样的方法 获得的obj为null，但是postList 却是一个非null对象

**Comment by jacking124** [comment]
你什么的是什么版本的！

**Comment by CharonS** [comment]
@jacking124 
com.alibaba:fastjson:1.2.11

**Comment by sequarius** [comment]
遇到了同样的问题 1.2.8可以序列化org.springframework.data.domain.Page<T>，但是1.2.11返回的json为null~

**Comment by wenshao** [comment]
原因是org.springframework.data.domain.Page是一个java.lang.Iterable，被特别处理了
