### ISSUE TITLE
反序列化出错

### ISSUE THREAD

**Issue by androidImp** [alibaba/fastjson#644]
FATAL EXCEPTION: OkHttp Dispatcher
                                                                 Process: cn.bmob.android, PID: 23278
                                                                 com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0
                                                                     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:240)
                                                                     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:126)
                                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:597)
                                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:569)
                                                                     at com.alibaba.fastjson.JSON.parseObject(JSON.java:257)
                                                                     at com.alibaba.fastjson.JSON.parseObject(JSON.java:227)
                                                                     at com.alibaba.fastjson.JSON.parseObject(JSON.java:186)
                                                                     at com.alibaba.fastjson.JSON.parseObject(JSON.java:310)
                                                                     at com.niuniumei.intelligentalarmclock.Activities.WeatherActivity$2.onResponse(WeatherActivity.java:91)
                                                                     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:170)
                                                                     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by JavaSuperior** [comment]
{
"resultcode":"200",
"reason":"successed!",
"result":{
"sk":{
"temp":"23",
"wind_direction":"东风",
"wind_strength":"2级",
"humidity":"95%",
"time":"23:50"
},
"today":{
"temperature":"22℃~27℃",
"weather":"阴转多云",
"weather_id":{
"fa":"02",
"fb":"01"
},
"wind":"微风",
"week":"星期一",
"city":"厦门",
"date_y":"2016年05月23日",
"dressing_index":"热",
"dressing_advice":"天气热，建议着短裙、短裤、短薄外套、T恤等夏季服装。",
"uv_index":"弱",
"comfort_index":"",
"wash_index":"较适宜",
"travel_index":"较适宜",
"exercise_index":"较适宜",
"drying_index":""
},
"future":{
"day_20160523":{
"temperature":"22℃~27℃",
"weather":"阴转多云",
"weather_id":{
"fa":"02",
"fb":"01"
},
"wind":"微风",
"week":"星期一",
"date":"20160523"
},
"day_20160524":{
"temperature":"22℃~29℃",
"weather":"多云转阴",
"weather_id":{
"fa":"01",
"fb":"02"
},
"wind":"微风",
"week":"星期二",
"date":"20160524"
},
"day_20160525":{
"temperature":"23℃~29℃",
"weather":"多云",
"weather_id":{
"fa":"01",
"fb":"01"
},
"wind":"微风",
"week":"星期三",
"date":"20160525"
},
"day_20160526":{
"temperature":"23℃~30℃",
"weather":"多云",
"weather_id":{
"fa":"01",
"fb":"01"
},
"wind":"微风",
"week":"星期四",
"date":"20160526"
},
"day_20160527":{
"temperature":"24℃~31℃",
"weather":"多云转阴",
"weather_id":{
"fa":"01",
"fb":"02"
},
"wind":"微风",
"week":"星期五",
"date":"20160527"
},
"day_20160528":{
"temperature":"23℃~29℃",
"weather":"多云",
"weather_id":{
"fa":"01",
"fb":"01"
},
"wind":"微风",
"week":"星期六",
"date":"20160528"
},
"day_20160529":{
"temperature":"23℃~30℃",
"weather":"多云",
"weather_id":{
"fa":"01",
"fb":"01"
},
"wind":"微风",
"week":"星期日",
"date":"20160529"
}
}
},
"error_code":0
}

**Comment by JavaSuperior** [comment]
package com.niuniumei.intelligentalarmclock.Bean;

import java.util.List;

/**
 * Created by niuniumei on 16/5/2.
 */
public class Weather {


    private String resultcode;
    private String reason;


    private ResultBean result;
    private int error_code;

    public String getResultcode() {
        return resultcode;
    }

    public void setResultcode(String resultcode) {
        this.resultcode = resultcode;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public ResultBean getResult() {
        return result;
    }

    public void setResult(ResultBean result) {
        this.result = result;
    }

    public int getError_code() {
        return error_code;
    }

    public void setError_code(int error_code) {
        this.error_code = error_code;
    }

    public static class ResultBean {


        private SkBean sk;


        private TodayBean today;


        private List<FutureBean> future;

        public SkBean getSk() {
            return sk;
        }

        public void setSk(SkBean sk) {
            this.sk = sk;
        }

        public TodayBean getToday() {
            return today;
        }

        public void setToday(TodayBean today) {
            this.today = today;
        }

        public List<FutureBean> getFuture() {
            return future;
        }

        public void setFuture(List<FutureBean> future) {
            this.future = future;
        }

        public static class SkBean {
            private String temp;
            private String wind_direction;
            private String wind_strength;
            private String humidity;
            private String time;

            public String getTemp() {
                return temp;
            }

            public void setTemp(String temp) {
                this.temp = temp;
            }

            public String getWind_direction() {
                return wind_direction;
            }

            public void setWind_direction(String wind_direction) {
                this.wind_direction = wind_direction;
            }

            public String getWind_strength() {
                return wind_strength;
            }

            public void setWind_strength(String wind_strength) {
                this.wind_strength = wind_strength;
            }

            public String getHumidity() {
                return humidity;
            }

            public void setHumidity(String humidity) {
                this.humidity = humidity;
            }

            public String getTime() {
                return time;
            }

            public void setTime(String time) {
                this.time = time;
            }
        }

        public static class TodayBean {
            private String city;
            private String date_y;
            private String week;
            private String temperature;
            private String weather;
            /**
             * fa : 00
             * fb : 53
             */

            private WeatherIdBean weather_id;
            private String wind;
            private String dressing_index;
            private String dressing_advice;
            private String uv_index;
            private String comfort_index;
            private String wash_index;
            private String travel_index;
            private String exercise_index;
            private String drying_index;

            public String getCity() {
                return city;
            }

            public void setCity(String city) {
                this.city = city;
            }

            public String getDate_y() {
                return date_y;
            }

            public void setDate_y(String date_y) {
                this.date_y = date_y;
            }

            public String getWeek() {
                return week;
            }

            public void setWeek(String week) {
                this.week = week;
            }

            public String getTemperature() {
                return temperature;
            }

            public void setTemperature(String temperature) {
                this.temperature = temperature;
            }

            public String getWeather() {
                return weather;
            }

            public void setWeather(String weather) {
                this.weather = weather;
            }

            public WeatherIdBean getWeather_id() {
                return weather_id;
            }

            public void setWeather_id(WeatherIdBean weather_id) {
                this.weather_id = weather_id;
            }

            public String getWind() {
                return wind;
            }

            public void setWind(String wind) {
                this.wind = wind;
            }

            public String getDressing_index() {
                return dressing_index;
            }

            public void setDressing_index(String dressing_index) {
                this.dressing_index = dressing_index;
            }

            public String getDressing_advice() {
                return dressing_advice;
            }

            public void setDressing_advice(String dressing_advice) {
                this.dressing_advice = dressing_advice;
            }

            public String getUv_index() {
                return uv_index;
            }

            public void setUv_index(String uv_index) {
                this.uv_index = uv_index;
            }

            public String getComfort_index() {
                return comfort_index;
            }

            public void setComfort_index(String comfort_index) {
                this.comfort_index = comfort_index;
            }

            public String getWash_index() {
                return wash_index;
            }

            public void setWash_index(String wash_index) {
                this.wash_index = wash_index;
            }

            public String getTravel_index() {
                return travel_index;
            }

            public void setTravel_index(String travel_index) {
                this.travel_index = travel_index;
            }

            public String getExercise_index() {
                return exercise_index;
            }

            public void setExercise_index(String exercise_index) {
                this.exercise_index = exercise_index;
            }

            public String getDrying_index() {
                return drying_index;
            }

            public void setDrying_index(String drying_index) {
                this.drying_index = drying_index;
            }

            public static class WeatherIdBean {
                private String fa;
                private String fb;

                public String getFa() {
                    return fa;
                }

                public void setFa(String fa) {
                    this.fa = fa;
                }

                public String getFb() {
                    return fb;
                }

                public void setFb(String fb) {
                    this.fb = fb;
                }
            }
        }

        public static class FutureBean {
            private String temperature;
            private String weather;
            /**
             * fa : 00
             * fb : 01
             */

            private WeatherIdBean weather_id;
            private String wind;
            private String week;
            private String date;

            public String getTemperature() {
                return temperature;
            }

            public void setTemperature(String temperature) {
                this.temperature = temperature;
            }

            public String getWeather() {
                return weather;
            }

            public void setWeather(String weather) {
                this.weather = weather;
            }

            public WeatherIdBean getWeather_id() {
                return weather_id;
            }

            public void setWeather_id(WeatherIdBean weather_id) {
                this.weather_id = weather_id;
            }

            public String getWind() {
                return wind;
            }

            public void setWind(String wind) {
                this.wind = wind;
            }

            public String getWeek() {
                return week;
            }

            public void setWeek(String week) {
                this.week = week;
            }

            public String getDate() {
                return date;
            }

            public void setDate(String date) {
                this.date = date;
            }

            public static class WeatherIdBean {
                private String fa;
                private String fb;

                public String getFa() {
                    return fa;
                }

                public void setFa(String fa) {
                    this.fa = fa;
                }

                public String getFb() {
                    return fb;
                }

                public void setFb(String fb) {
                    this.fb = fb;
                }
            }
        }
    }
}

**Comment by JavaSuperior** [comment]
我之前提过这个问题,之前温少您给出的意见是网络不好导致内容被截断.但是我通过4G/WIFI测试过多次,都会报错,还望温少能够重新看一下,谢谢.
