### ISSUE TITLE
使用最新的fastjson序列化javaBean时使用ValueFilter没有任何内容输出了

### ISSUE THREAD

**Issue by suciver** [alibaba/fastjson#645]
public class User{
   private String id;
   private String name;
   public User(String id,String name){
      this.id=id;
      this.name=name;
   }
   //setter,getter;
}
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.time.DateFormatUtils;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import com.alibaba.fastjson.serializer.ValueFilter;

public class AppTest {
	public static void main(String[] args) throws IOException {
		User user=new User("1","b");
		System.out.println(user);
		String theJson=JSON.toJSONString(user,new ValueFilter(){
			@Override
			public Object process(Object object, String name, Object value) {
				if(value instanceof Date){
					return DateFormatUtils.format((Date)value,JSON.DEFFAULT_DATE_FORMAT);
				}
				return value;
			}
		},SerializerFeature.WriteClassName,SerializerFeature.UseSingleQuotes);
		System.out.println(theJson);//没有任何内容去掉这个ValueFilter就可以了
	}
}

**Comment by wenshao** [comment]
什么版本？这个问题1.2.11 & 1.2.12应该都修复了的啊？

**Comment by suciver** [comment]
之前用1.2.9在最新版本确实已经修复
