### ISSUE TITLE
求一个 jax-rs Provider

### ISSUE THREAD

**Issue by icode** [alibaba/fastjson#65]
jackson有jax-rs的支持 fastjson没有啊，想上fastjson，可惜缺乏jax-rs支持，望温少可以提供支持，fastjson的支持类库太少了，只支持spring，spring太肿了不喜欢。

**Comment by bankly** [comment]
@smallnest 能完整的例子吗，Android怎么引用呢

**Comment by wenshao** [comment]
我从 @smallnest 代码拷贝一份内置在1.2.9中了，希望 @smallnest 帮忙维护啊

**Comment by smallnest** [comment]
Sure!
