### ISSUE TITLE
当key为数字时,json序列化后出错

### ISSUE THREAD

**Issue by seavers** [alibaba/fastjson#66]
参考以下代码

``` java
public static void main(String[] args) {
    Map<Integer, String> map = new HashMap<Integer, String>();
    map.put(1512, "手机");
    map.put(1101, "笔记本电脑");
    System.out.println(JSON.toJSONString(map), SerializerFeature.QuoteFieldNames);
}
```

输出为

```
{1101:"笔记本电脑",1512:"手机"}
```

而使用浏览器能接受的正确写法应该是:

``` javascript
JSON.parse('{"1101":"笔记本电脑","1512":"手机"}')
```

即使加上
SerializerFeature.BrowserCompatible
也不成功

**Comment by wychenlong** [comment]
spring  配置了<value>WriteNonStringKeyAsString</value>，但是 if (out.isEnabled(SerializerFeature.BrowserCompatible)
                        || out.isEnabled(SerializerFeature.WriteNonStringKeyAsString)) {
                        String strEntryKey = JSON.toJSONString(entryKey);
                        serializer.write(strEntryKey);
                    }

toJsonString还是没有使用该特性，这是为什么呢

**Comment by irwinai** [comment]
WriteNonStringKeyAsString 这个属性具体意思是干嘛？我也没找到文档里有介绍这个属性的用法
