### ISSUE TITLE
com.alibaba.fastjson.JSONObject排序问题，如何避免

### ISSUE THREAD

**Issue by aircjm** [alibaba/fastjson#660]
如何实现序列化或者反序列化时不排序，在使用过程中我这边只需要对一级key进行排序，fastjson会对整个结构都进行排序，这个如何避免？谢谢
先转换为JSONObject，然后通过JSONObject.get方法获取对象

**Comment by wenshao** [comment]
不是很懂你的意思

**Comment by aircjm** [comment]
字符串转换成JSONObject时，对key会进行排序，如何避免排序？？

**Comment by wenshao** [comment]
什么版本？能否提供重现问题的testcase？

**Comment by aircjm** [comment]
String jsonParams = "{\"name\":\"Tom\",\"age\":20,\"height\":180.5,\"gender\":\"Male\",\"weight\":80.5}";
        JSONObject jsonObject = JSON.parseObject(jsonParams);
        System.out.println(jsonObject.toJSONString());
        // 输出结果为{"age":20,"gender":"Male","height":180.5,"name":"Tom","weight":80.5}
        // 对按照键的顺序进行了排序操作，如何越过排序，让jsonObject还是按照{"name":"Tom","age":20,"height":180.5,"gender":"Male","weight":80.5}该顺序输出

**Comment by githublaohu** [comment]
提升你的版本，就可以了。
1.1,的好像默认是排序。

**Comment by aircjm** [comment]
@githublaohu 

        String jsonParams = "{\"name\":\"Tom\",\"age\":20,\"height\":180.5,\"gender\":\"Male\",\"weight\":80.5}";
        JSONObject jsonObject = JSON.parseObject(jsonParams);
        System.out.println(jsonObject.toJSONString());
        // 输出结果为{"age":20,"gender":"Male","height":180.5,"name":"Tom","weight":80.5}
        // 我想要的输出结果按照键的顺序进行了排序操作，如何忽略掉默认的缺省field排序，让jsonObject还是按照{"name":"Tom","age":20,"height":180.5,"gender":"Male","weight":80.5}该顺序输出，而不是上面的结果

**Comment by aircjm** [comment]
没有结果了吗？？

**Comment by wenshao** [comment]
使用Feature.OrderedField
```java
JSON.parseObject("...", Feature.OrderedField);
```

**Comment by aircjm** [comment]
非常感谢，我在使用的1.1.41不支持JSON.parseObject("...", Feature.OrderedField);，已经升级为最新版本1.2.12了
