### ISSUE TITLE
注解混淆后不好使

### ISSUE THREAD

**Issue by chenchongyu** [alibaba/fastjson#663]
使用注解@JSONField(name="user_xid")且混淆后，该注解未生效！不知道混淆文件应该怎么写？

**Comment by githublaohu** [comment]
实体类需要混淆吗？
这个是没有必要的。

**Comment by chenchongyu** [comment]
是的！我已经在混淆配置文件里添加了实体类的keep，但是还是不好使！后来我改用了fastjson-android版就可以了！

**Comment by wenshao** [comment]
既然android版本能用，我就关闭issue啦？
