### ISSUE TITLE
流式解析超大JSON，内存溢出

### ISSUE THREAD

**Issue by qule510** [alibaba/fastjson#664]
Model vo = reader.readObject(Model.class);
如果解析数组中Model对象（22个字段）有10W的时候，解析一半就会内存溢出，包括计数，每解析1000使用过休眠都是一样。测试过程中，只做纯粹的解析。 可以帮忙看看是为什么吗
PS:json文件中有两种数据类型。文件 超过50MB。

**Comment by foxty** [comment]
对于大json文件的解析，建议使用Streaming API。或者增大你JVM的heap大小。

**Comment by qule510** [comment]
@foxty  我是使用数据流 读取的，如果是实体只有3个字段，读取10W数量是没有问题的。但是字段多了，就只能读取三四万就会内存移除了。

**Comment by qule510** [comment]
主要代码如下：
JSONReader reader = new JSONReader(new FileReader( "huge.json"));
//如果是下面传递class就会解析超大json时候解析一半内存爆掉。
Model m= reader.readObject(Model.class);
//下面这种方式传递对象的解析方式就不会
Model m = new Model();
  reader.readObject(vo);

可以说说为什么会这样吗？

**Comment by foxty** [comment]
第二段代码有完整点的吗？vo是什么？你read完之后做了什么？ 建议可以做个内存分析，看看是哪里占用的内存比较多。

**Comment by HVking** [comment]
麻烦问下，最终是怎么解决的内存溢出呢 @qule510

**Comment by qule510** [comment]
@HVking 因为内存存不了，这么大的数据对象列表，比如，我的应用里面是几十万的对象。目的是要解析保存入库。
最后的解决方案是：边解析边保存。
`
//记录解析的总数量
int count = 0;
//根据key，创建不同的对象
BaseDataType type = getBaseDataType(key);
reader.startArray();
while (reader.hasNext()) {
	BaseModel m = type.getModel();
	reader.readObject(m);
	list.add(m);
	count++;
	if (count % 2000 == 0) {
		//每两千保存一次
		savaData(list);
		list.clear();
	}
}
//2000的余数保存一次
savaData(list);
list.clear();
reader.endArray();

`
