### ISSUE TITLE
前端js long类型过长导获取导致错误

### ISSUE THREAD

**Issue by Shadowsay** [alibaba/fastjson#669]
服务端输出   867462718502938217,因超出js类型过长，接收的是867462718502938200， 不知道fastjson有没有合适的办法可以搞定这个坑爹的问题。整串{"userId":867462718502938217}

**Comment by githublaohu** [comment]
你可以让long 变成 string 就可以解决了。
js不支持，真正的long型。

**Comment by Shadowsay** [comment]
@githublaohu  这个我知道的，  fastjson这里方便扩展改变类型吗？我们这里接口统一掉了。

**Comment by githublaohu** [comment]
有两个方法，
第一个是 有个序列化变量，可以把所有的 数字类型，转成 string
第二个是 有一个value拦截器，可以修改value的值

**Comment by Shadowsay** [comment]
好的， thks
