### ISSUE TITLE
FastJsonHttpMessageConverter4使用jquery的ajax会有异常

### ISSUE THREAD

**Issue by ydq** [alibaba/fastjson#671]
fastjson官方推荐说spring4.2x以上使用FastJsonHttpMessageConverter4。

但是使用**FastJsonHttpMessageConverter4**会有一个问题。
当使用jquery执行ajax请求的时候，如果不设置**dataType**（`请求头中的Accept:*/*`）的话就会报**500**
后台提示`'Content-Type' cannot contain wildcard type '*'`，设置dataType之后则可以正常的ajax请求了。虽然不算什么问题，但是还是希望官方能解决一下这个问题。

spring4.2（4.3）反而使用FastJsonHttpMessageConverter则没这个问题。

Fastjson版本号为1.2.12
Spring版本号4.2.6/4.3.0

**Comment by VictorZeng** [comment]
报错是正确的 因为SpringConverter需要知道前台传送数据的类型 然后绑定实体类

**Comment by ydq** [comment]
原来是这样啊，感谢解答！
