### ISSUE TITLE
反序列化时遇到 Date格式中带T的要怎么处理

### ISSUE THREAD

**Issue by sunshine4Cpic** [alibaba/fastjson#678]
"creatDate":"2016-06-15T10:49:46.91"
这种格式的数据 在反序列化时会报错 有什么办法吗?

**Comment by xiongchen2012** [comment]
用Feature.AllowISO8601DateFormat可以反序列化
`JSON.parseObject(str, YourEntity.class, Feature.AllowISO8601DateFormat);`
