### ISSUE TITLE
json 中带有\r\n的数据被强制转义了

### ISSUE THREAD

**Issue by sunshine4Cpic** [alibaba/fastjson#684]
我是安卓版本:
```
 compile 'com.alibaba:fastjson:1.1.52.android'
```
```java
 String str = "{\"Body\":\"测试一下\\r\\n\"}";
 topicModel tm = JSON.parseObject(str, topicModel.class);
```

```java
public class topicModel {
    private String Body;

    public String getBody() {
        return Body;
    }

    public void setBody(String body) {
        Body = body;
    }
}
```
tm.Body 的字符集为
![image](https://cloud.githubusercontent.com/assets/9856250/16223514/3285fb8e-37d0-11e6-996e-b02caf8ed8e0.png)
而我想得到的是 
![image](https://cloud.githubusercontent.com/assets/9856250/16223525/4df84e44-37d0-11e6-9609-587cceff88d7.png)

**Comment by githublaohu** [comment]
麻烦提供完整的 问题，数据。与问题测试代码。

**Comment by sunshine4Cpic** [comment]
@githublaohu 

```java
 String str = "{\"Body\":\"测试一下\\r\\n\"}";
 topicModel tm = JSON.parseObject(str, topicModel.class);
```
tm.Body 的字符集为
![image](https://cloud.githubusercontent.com/assets/9856250/16223514/3285fb8e-37d0-11e6-996e-b02caf8ed8e0.png)
而我想得到的是 
![image](https://cloud.githubusercontent.com/assets/9856250/16223525/4df84e44-37d0-11e6-9609-587cceff88d7.png)

**Comment by sunshine4Cpic** [comment]
查看了 相关的源码 是否转义和  JSONLexer.hasSpecial 有关,但我没有找到相关的设置点

**Comment by wenshao** [comment]
这个解析是正确的啊，如果是你希望得到的结果，应该如下这样写：
```java
String str = "{\"Body\":\"测试一下\\\\r\\\\n\"}";
```
