### ISSUE TITLE
A JSONField format Exception occurs in parsing "yyyy-MM-dd'T'HH:mm:ss.SSS"

### ISSUE THREAD

**Issue by Andecy** [alibaba/fastjson#685]
* fastjson version：
1.1.52.android

* java code：
```java
@JSONField(format= "yyyy-MM-dd'T'HH:mm:ss.SSS")
public Date publishTime;
```
* JSONString：
"publishTime": "2016-06-14T20:59:05.963"

* Exception：
com.alibaba.fastjson.JSONException: Unknown pattern character 'T'

**Comment by Andecy** [comment]
@JSONField(format= "yyyy-MM-dd'T'HH:mm:ss.SSS")

**Comment by Andecy** [comment]
This bug occurs in ver.1.1.52.android

**Comment by ningsia** [comment]
I encountered this issue as well. in version 1.2.12. rollback to 1.2.11 and waiting for bug fixing.
