### ISSUE TITLE
FASTJSON 对unicode编码处理的bug

### ISSUE THREAD

**Issue by lyings** [alibaba/fastjson#690]
System.out.println(JSON.toJSONString("`      "));打印结果为："\u00A0\u00A0    "

其实我们希望打印结果为："      ";

当我们调用JSON.toJSONString("      ",SerializerFeature.BrowserCompatible);的时候才希望打印"\u00A0\u00A0    "

` Map map=new HashMap();
        map.put("method","安徽省滁州市南谯区test tomorrow  I      你好");
        System.out.println(JSON.toJSON(map).toString());`

打印结果  ：{"method":"安徽省滁州市南谯区test tomorrow  I\u00A0\u00A0    你好"}

**Comment by lyings** [comment]
上面复制的都没有问题。只有部分Android手机浏览器提交后才会出现此问题。

**Comment by wenshao** [comment]
什么场景有这需求呢？\u00A0也是符合规范的字符串啊

**Comment by lyings** [comment]
fastjson 对网页   不间断空格(\u00A0)    没有处理。

**Comment by z172362753** [comment]
我也碰到这个问题了，\u00A0造成freemark解析json出错

**Comment by lyings** [comment]
还没有处理哦。随便android 手机浏览器的一个空格，就有这个问题。
