### ISSUE TITLE
只想反序列化一部分内容，解析不到数据

### ISSUE THREAD

**Issue by PittyXu** [alibaba/fastjson#691]
服务器端的json增加字段，客户端的JavaBean没有变，导致客户端解析不到数据。
需要解析的数据：
```json
{"a": "a", 
"b": "b"}
```
JavaBean:
```java
class A {
    public String a;
}
```
使用
```java
A objectA = JSON.parseObject(data, A.class);
```
解析，结果 objectA的参数 a 为 null.

**Comment by githublaohu** [comment]
你好！我写的测试代码没有发现问题。
fastjson的版本是 1.2.7
下面是我的测试代码。
`package com.micromews.user.test.json;

public class TestJsonOne {

	
	private String str;

	public String getStr ( ) {
		return str ;
	}

	public void setStr ( String str ) {
		this.str = str ;
	}
	
	
}
`

`package com.micromews.user.test.json;

public class TestJsonTwo {

	
	private String str;
	
	private String st;

	public String getStr ( ) {
		return str ;
	}

	public void setStr ( String str ) {
		this.str = str ;
	}

	public String getSt ( ) {
		return st ;
	}

	public void setSt ( String st ) {
		this.st = st ;
	}
	
	
}
`
`package com.micromews.user.test.json;

import org.junit.Test ;

import com.alibaba.fastjson.JSON ;

public class TestJson {

	@Test
	public void json(){
		TestJsonOne tjo =  new TestJsonOne ( );
		tjo.setStr ( "111" );
		String str = JSON.toJSONString ( tjo );
		System.out.println ( "TestJsonOne 序列化字符串 ： " + str ) ;
		TestJsonTwo tjt = JSON.parseObject ( str , TestJsonTwo.class );
		
		System.out.println ("TestJsonTwo de str 属性 ： "  + tjt.getStr ( ) ) ;
	}
	
}
`
