### ISSUE TITLE
ParserConfig 类getDeserializer(Class<?> clazz, Type type)方法缓存导致反序列化泛型类时解析失败

### ISSUE THREAD

**Issue by javaday2014** [alibaba/fastjson#695]
测试代码：
```java
public static void main(String[] args) throws Exception {
        String msg = "{\"code\":\"0\",\"message\":\"OK\"}";
        I18nResponse<?> res = JSON.parseObject(msg, I18nResponse.class);
        System.out.println(res.getData());

        String msg2 = "{\"code\":\"0\",\"message\":\"OK\",\"data\":{\"uid\":28147509676,\"countryCode\":\"+86\",\"phone\":\"18500000000\",\"createTime\":\"2016-03-29 02:44:56\"}}";
        I18nResponse<I18nUser> res2 = JSON.parseObject(msg2, new TypeReference<I18nResponse<I18nUser>>() {
        });
        System.out.println(res2.getData());
}
```
现象：
res解析成功，msg2中的data无法反序列化为I18nUser对象，而是转换为JSONObject对象
出现此问题的原因：
执行第一个parseObject时，ParserConfig类中的 derializers map对象缓存了I18nResponse，执行第二个parseObject时，I18nResponse<I18nUser>类的rawType为I18nResponse对象，所以缓存命中，导致泛型无法解析
![image](https://cloud.githubusercontent.com/assets/7007288/16331818/3b1d91e2-3a25-11e6-97b1-4632e972f6b9.png)
![image](https://cloud.githubusercontent.com/assets/7007288/16331831/565b988c-3a25-11e6-836d-bf22c5d0d223.png)

解决方案：
public ObjectDeserializer getDeserializer(Class<?> clazz, Type type) 方法中下面的代码注释即可，相当于缓存中即使type找不到，也不会使用rawType的缓存，防止反序列化时相互影响
![image](https://cloud.githubusercontent.com/assets/7007288/16331874/895a078c-3a25-11e6-88cc-6191e512d785.png)

## 不知道上面的解决方式是否合理，可能没搞明白上面截图中这段代码的真正意图，请作者帮忙解决这个问题，在网上也搜到一些相同的case，盼回复，谢谢

辅助类如下：
```java
public class I18nResponse<T> {

    private String code;
    private String message;
    private T data;
    
    //set get method...
}

public class I18nUser {
	private String uid;
	private String phone;
	private String createTime;
        // set get method...
}
```

**Comment by githublaohu** [comment]
可以不用 泛型吗？

**Comment by javaday2014** [comment]
可以，如下，但是两者混用以后就会有问题，这种场景应该是比较常见的
I18nResponse res = JSON.parseObject(msg, I18nResponse.class);

**Comment by a3349384** [comment]
@javaday2014 作者那样做应该是为了提升性能

**Comment by wenshao** [comment]
什么版本？

**Comment by javaday2014** [comment]
@wenshao 1.2.9

**Comment by wenshao** [comment]
升级到1.2.12试试看？

**Comment by javaday2014** [comment]
@wenshao 
1.2.12是OK的 ，请问12版本中是怎么修复的这个问题，我看getDeserializer(Class<?> clazz, Type type) 方法的代码也没变化，谢谢

**Comment by wenshao** [comment]
之前版本计算泛型的真实类型有问题
