### ISSUE TITLE
序列化指定类时，结果为空: { }

### ISSUE THREAD

**Issue by cnlinjie** [alibaba/fastjson#697]
序列化指定类时，结果为: { }
跟踪到 **com/alibaba/fastjson/JSON**的 **toJSONString** 时， 序列化对象： 
**springfox.documentation.spring.web.json.Json**  的对象有存在值（看图）。
然后继续到：
**com/alibaba/fastjson/serializer/JSONSerializer** 的 write(Object object) 方法时， write 的实际对象为：
nature = JavaBeanSerializer 
 
于是先到 JavaBeanSerializer  类中的write 方法断点，可是下一步时，居然没有进去，奇怪。。

最后出来的结果就是 ： { }。
 
![fastjson](http://7xk2gz.com1.z0.glb.clouddn.com/2016-06-25%2015-23-05%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

版本：fastjson-1.2.6

**Comment by cnlinjie** [comment]
看图，进来时**obj** 有值，序列化之后，**text **就为空了 !

![](http://7xk2gz.com1.z0.glb.clouddn.com/2016-06-25%2015-29-44%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by wenshao** [comment]
1.2.12版本呢？

**Comment by virtuecai** [comment]
各位大佬, 我也是查了一天了 ,终于发现了是fastjson 问题. 有什么解决办法? 还是移除FastJsonHttpMessageConverter ?

**Comment by virtuecai** [comment]
1.2.13 都试了

**Comment by wenshao** [comment]
是什么问题？

**Comment by virtuecai** [comment]
问题是解决了, springmvc 不能使用 FastJsonHttpMessageConverter, 具体原因没有跟进源代码代码,  是springfox 还是 fastjson 的问题, 还没深究. MessageConverter 只能继续使用 jackson.

**Comment by wenshao** [comment]
已修复，今天将会发布1.2.15解决此问题

**Comment by virtuecai** [comment]
力顶!!!
