### ISSUE TITLE
求原生支持jackson的jsonp功能和属性命名策略

### ISSUE THREAD

**Issue by weishuwei** [alibaba/fastjson#699]
属性命名策略：
`<bean class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
				<property name="objectMapper">
					<bean class="com.fasterxml.jackson.databind.ObjectMapper">
						<property name="propertyNamingStrategy">
							<bean class="com.fasterxml.jackson.databind.PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy" />
						</property>
					</bean>
				</property>
</bean>`

jsonp支持：
org.springframework.web.servlet.mvc.method.annotation.AbstractJsonpResponseBodyAdvice

**Comment by githublaohu** [comment]
你是想，实现jsonp对吧，
我觉得，作者会支持这个的。
这周，我尝试写下。

**Comment by wenshao** [comment]
很好的需求，将会尽快支持

**Comment by weishuwei** [comment]
1，propertyNamingStrategy：
这种场景是请求参数是user_name，可以直接映射到java bean的userName属性上；响应参数也可以把userName映射为user_name
2，AbstractJsonpResponseBodyAdvice
这种场景是当请求参数有?callback=test，那么就可以生成函数名为test的jsonp数据，而不用每个requestMapping对应的方法都写一遍

**Comment by wenshao** [comment]
已经支持，文档在这里
https://github.com/alibaba/fastjson/wiki/PropertyNamingStrategy_cn
