### ISSUE TITLE
新版本 1.2.13 无法兼容的问题

### ISSUE THREAD

**Issue by fengyapeng** [alibaba/fastjson#700]
对于 JavaBeanDeserializer 的无法兼容的问题：
我看到 commit  的history 
https://github.com/alibaba/fastjson/commit/0d8b086449e48a303bef16a203f696c16efe131a
修复JavaBeanDeserializer不能反序列化深层内部类的问题
但是，第113行。
`**  String typeName = type.getTypeName();**`
一段这样的代码：
而 这个方法的说明是：

```
public interface Type {
    /**
     * Returns a string describing this type, including information
     * about any type parameters.
     *
     * @implSpec The default implementation calls {@code toString}.
     *
     * @return a string describing this type
     * @since 1.8
     */
    default String getTypeName() {
        return toString();
    }
}

```
since 1.8。

而我们线上服务用的jdk 的环境是1.7 的环境。
不知道加入这段代码的时候有没有考虑jdk 的版本。或者1.2.13 只支持JDK1.8+  呢

**Comment by wenshao** [comment]
谢谢反馈，合并这个pull request的时候没有仔细检查。问题已经修正，将会尽快发布新版本1.2.14。
