### ISSUE TITLE
有关于SerializerFeature的失效

### ISSUE THREAD

**Issue by yangyile2011** [alibaba/fastjson#712]
请教一个问题：    
private static SerializerFeature[] features = {SerializerFeature.WriteNullNumberAsZero,SerializerFeature.WriteMapNullValue, SerializerFeature.WriteNullStringAsEmpty, SerializerFeature.DisableCircularReferenceDetect};
       
        User user = new User();  
        user.setId("");  
        user.setName(null);  
        user.setDescrition("大黄牛");  
  
        String text = JSON.toJSONString(user);  
        System.out.println(text);  
  
        User user1 = JSON.parseObject(text, User.class,features);  
然后发现添加的SerializerFeature.WriteNullStringAsEmpty没有发生作用，只有直接把参数text替换成user,如下：
 User user1 = JSON.parseObject(user, User.class,features); 然后SerializerFeature.WriteNullStringAsEmpty才会生效，请问是为什么呢？

**Comment by jason19659** [comment]
穿参数用这个 Feature.InitStringFieldAsEmpty

**Comment by wenshao** [comment]
@jason19659 的答案应该能解决你的问题，我先关闭issue啦
