### ISSUE TITLE
@JSONField配置getter/setter方法上有效，配置在Field上无效

### ISSUE THREAD

**Issue by yfn020** [alibaba/fastjson#717]
fastjson版本：1.2.13和1.1.52android版本

**Comment by wenshao** [comment]
能提供一下类结构代码

**Comment by yfn020** [comment]
public class Group {
    @JSONField(name = "ID")
    private Long id;
    private String NAME;
    @JSONField(serialize = false, deserialize = false)
    private String AUTHORITY;
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getNAME() {
        return NAME;
    }
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }
    public String getAUTHORITY() {
        return AUTHORITY;
    }
    public void setAUTHORITY(String AUTHORITY) {
        this.AUTHORITY = AUTHORITY;
    }
}


        Group group = new Group();
        group.setId(0L);
        group.setNAME("admin");
        group.setAUTHORITY("administrors");

        System.out.println(JSON.toJSONString(group));

还是会打印AUTHORITY字段：{"ID":0,"aUTHORITY":"administrors","nAME":"admin"}

**Comment by wenshao** [comment]
问题已经修正，预计在本周或者下周发布
