### ISSUE TITLE
JSONpath无法过滤数组中double以及boolean类型的数据。

### ISSUE THREAD

**Issue by ChenSen5** [alibaba/fastjson#722]
String json ="{\"user\":[{\"amount\":0.11,\"isadmin\":true,\"age\":18},{\"amount\":0.22,\"isadmin\":false,\"age\":28}]}";
		System.out.println(JSONPath.read(json, "$.user"));
		System.out.println(JSONPath.read(json, "$.user[age = 18]"));//可以取到
		System.out.println(JSONPath.read(json, "$.user[isadmin = true]"));//boolean类型的无法过滤，报错
		System.out.println(JSONPath.read(json, "$.user[amount = 0.11]"));//float类型无法过滤，报错

**Comment by wenshao** [comment]
已支持，请等待1.2.14版本

**Comment by ChenSen5** [comment]
预计什么时候会出1.2.14版本
