### ISSUE TITLE
Android gradle 版本配置与wiki不一样

### ISSUE THREAD

**Issue by zengcanxiang** [alibaba/fastjson#734]
我使用 gradle: compile 'com.alibaba:fastjson:1.1.52-android'是无法成功的
我看maven仓库，发现应该是 compile 'com.alibaba:fastjson:1.1.52.android'

**Comment by wenshao** [comment]
就应该是你说的这样啊，文档哪里写错了？

**Comment by zengcanxiang** [comment]
@wenshao 文档上是1.1.52-android,能够正确的导入的是1.1.52.android

**Comment by zengcanxiang** [comment]
可能是我看的地方有问题，在这个界面上
https://github.com/alibaba/fastjson/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by wenshao** [comment]
文档已修复，感谢反馈
