### ISSUE TITLE
writeInternal 能否支持jsonp

### ISSUE THREAD

**Issue by An0nymous0** [alibaba/fastjson#741]
spring原生是支持 直接配置的，换成FastJsonHttpMessageConverter4以后貌似不行了。

@ControllerAdvice
public class JsonpAdvice extends AbstractJsonpResponseBodyAdvice {
    public JsonpAdvice() {
        super("callback");
    }
}

**Comment by wenshao** [comment]
@VictorZeng 你帮忙看看

**Comment by VictorZeng** [comment]
@An0nymous0 
你所指的Spring原生的HttpMessageConverter, 应该是`MappingJackson2HttpMessageConverter`, 而你使用Jsonp的AOP抽象`AbstractJsonpResponseBodyAdvice` 继承自`AbstractMappingJacksonResponseBodyAdvice`类, 它仅仅支持Jackson的HttpMessageConverter, 所以对`FastJsonHttpMessageConverter`不生效.

`AbstractMappingJacksonResponseBodyAdvice` 的接口是 [`ResponseBodyAdvice<T>`] (http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice.html) 可以根据需要自己实现Jsonp AOP切面.

**Comment by myoss** [comment]
FastJSON能否用其它方式开启支持JSONP输出(spring mvc)

**Comment by VictorZeng** [comment]
@myoss 暂时无其他方式

**Comment by githublaohu** [comment]
@wenshao 这个需求我来做？
我在 FastJsonConfig 添加一个字段，用户识别 jsonp的执行方法。让后修改FastJsonHttpMessageConverter4的放回就行了。

**Comment by myoss** [comment]
@githublaohu @An0nymous0  https://github.com/alibaba/fastjson/wiki/FastJsonpHttpMessageConverter4_CN 已经实现了这个需求

**Comment by githublaohu** [comment]
@myoss 你写得好复杂啊。

**Comment by githublaohu** [comment]
建议。。可以说是要求。不要做得那么复杂。就在原有的基础上配置一个 callback 就行了。 @myoss

**Comment by myoss** [comment]
@githublaohu  不想去动`FastJsonHttpMessageConverter4`原来这一套逻辑代码，两套功能互相独立，这一套实现是参考`spring mvc`中`jackson`配置`callback`

**Comment by githublaohu** [comment]
@myoss 请求你这个设计，是不是所有的请求响应的数据都会经过那些代码？
