### ISSUE TITLE
Snake Case Serialization

### ISSUE THREAD

**Issue by elsennov** [alibaba/fastjson#746]
Hi,

Is it possible to serialize all the camel case fields to snake case automatically? Thanks

**Comment by wenshao** [comment]
Good idea, the next version will support

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/PropertyNamingStrategy_cn

**Comment by elsennov** [comment]
Wow so fast! Thanks!

**Comment by elsennov** [comment]
Is it has been released? If yes, i will close it @wenshao 
Thanks

**Comment by wenshao** [comment]
Today or tomorrow will release a new version 1.2.15.

**Comment by elsennov** [comment]
Ah ok!

**Comment by wenshao** [comment]
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.15/
