### ISSUE TITLE
fastjson 能否计划支持spring websocket？

### ISSUE THREAD

**Issue by 805728578** [alibaba/fastjson#750]
<websocket:sockjs message-codec="message-codec" />

**Comment by 805728578** [comment]
<websocket:sockjs message-codec="message-codec" />

**Comment by 805728578** [comment]
websocket:sockjs message-codec="message-codec"

**Comment by wenshao** [comment]
不了解，现在不能用么？

**Comment by wenshao** [comment]
已经支持了，是否能帮忙做测试一下

**Comment by 805728578** [comment]
maven 库中还没有1.2.16版本的jar包啊

**Comment by wenshao** [comment]
会在周末发布，如果可以，是否能帮忙自行编译打包然后做测试？

**Comment by 805728578** [comment]
@wenshao,好的，没问题

**Comment by wenshao** [comment]
@VictorZeng 你能帮看一下么？

**Comment by VictorZeng** [comment]
@wenshao 抱歉 Spring websocket 我也不太熟...
