### ISSUE TITLE
fastjson中如何实现jsonarray 数组排序？是否有更便捷的方式实现？

### ISSUE THREAD

**Issue by liuwenfeng554** [alibaba/fastjson#753]
如
[{"test":"2",.....},{"test":"1",.....},{"test":"4",.....},{"test":"3",.....}]

根据test value排序输出：
[{"test":"1",.....},{"test":"2",.....},{"test":"3",.....},{"test":“4",.....}]

**Comment by wenshao** [comment]
自己实现一个Comparator，然后调用Collections.sort方法
