### ISSUE TITLE
请求响应的JSON数组中使用引用，如何不使用引用？

### ISSUE THREAD

**Issue by 805728578** [alibaba/fastjson#755]
{
    "data": {
        "data": null,
        "list": [
            {
                "name": "WebEx XML会议",
                "rooms": [
                    {
                        "id": 8,
                        "name": "网络会议室[WebEx-8方]",
                    }
                ]
            },
            {
                "name": "WebEx XML",
                "rooms": [
                    {
                        "$ref": "$.data.list[0].rooms[0]"     //这里使用引用
                    }
                ]
            }
        ],
        "pageCount": 1,
        "pageNo": 1,
        "pageSize": 20,
        "total": 2
    },
    "msg": "",
    "status": 0
}

数组中第二个rooms使用引用，而不是具体的对象

如何不使用引用？

我系统使用SpringMVC

**Comment by wyamei** [comment]
entity.result = JSON.toJSONString(result, SerializerFeature.DisableCircularReferenceDetect);

**Comment by 805728578** [comment]
好的，谢谢
