### ISSUE TITLE
FastJsonHttpMessageConverter 默认contenttype与老版本不兼容

### ISSUE THREAD

**Issue by JeffLu** [alibaba/fastjson#757]
请保持兼容  super(new MediaType("application", "json", DEFAULT_CHARSET), new MediaType("application", "*+json", DEFAULT_CHARSET));
否则返回的content-type有可能在升级后变成非application/json导致前端识别有问题

**Comment by wenshao** [comment]
@VictorZeng 帮忙看看

**Comment by VictorZeng** [comment]
@wenshao 抱歉这几天outing 没网络...
@JeffLu 新版本的FastJsonHttpMessageConverter并没有指定特定的MediaType, 默认所有类型都支持. 如果需要对ContentType做限定可以设置`supportedMediaTypes`属性. 
e.g.
```
<bean class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">
	<property name="supportedMediaTypes">
		<list>
			<value>application/json</value>
			<value>application/*+json</value>
		</list>
	</property>
</bean>
```

**Comment by JeffLu** [comment]
多谢跟进，这样设置肯定是没问题的。我们之前1.2.6版本，没有设置supportedMediaTypes是没问题的，最近由于其他一些原因升级到了1.2.15，导致http response的content-type就变成application/octet-stream了。感觉还是默认制定json的MediaType合理一些

**Comment by VictorZeng** [comment]
@JeffLu 对于在升级过程中所造成的配置变更深感抱歉, 但保持开放性的原则更为理性.
