### ISSUE TITLE
转换entity后，多出new字段.

### ISSUE THREAD

**Issue by WellJay** [alibaba/fastjson#759]
```
{
    "data": {
        "birthday": "2014-04-04 00:00:00",
        "createTime": "2016-06-23 13:09:33",
        "id": "1",
        "new": false,
        "passWord": "you don't want to know",
        "phone": "1",
        "sex": "MAN",
        "userName": "123"
    },
    "message": "request success",
    "status": 200
}
```

如何取消显示这个对象的jpa新建状态？ 版本1.2.15

**Comment by wenshao** [comment]
所继承的类结构是怎样的？我可以在内置提供支持去掉的

**Comment by WellJay** [comment]
@wenshao 
`
@MappedSuperclass
public abstract class BaseUUIDEntity extends BaseEntity<String> {

    private static final long serialVersionUID = 1L;

    private String id;

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    @GeneratedValue(generator = "uuid")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}`
`
@Entity
@Table(name = "tb_user")
@DynamicUpdate
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Access(AccessType.FIELD) //强制hibernate全部访问字段注解
@Accessors(chain = true)
public class User extends BaseUUIDEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    public enum Sex {
        @MetaData("男")
        MAN, //男
        @MetaData("女")
        WOMAN //女
    }

    @Column(name = "user_name", length = 20, nullable = false)
    @MetaData("用户名")
    private String userName;

    @Column(name = "pass_word", length = 32)
    @MetaData("密码")
    private String passWord;

    @Column(length = 12)
    @MetaData("手机号")
    private String phone;

    @Column(name = "head_photo")
    @MetaData("头像")
    private String headPhoto;

    @Enumerated(EnumType.STRING)
    @Column(length = 5, columnDefinition = "varchar(5) default 'MAN'")
    @MetaData("性别")
    private Sex sex;

    @Temporal(TemporalType.DATE)
    @MetaData("生日")
    private Date birthday;

    @JSONField(serialize = false)
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "merchant_id")
    private Merchant merchant;
}`

**Comment by wenshao** [comment]
是hibernate的实现吗？

**Comment by wenshao** [comment]
能帮忙看isNew方法是在哪个class/interface中定义的

**Comment by WellJay** [comment]
麻烦了，找到了
```
public abstract class BaseServiceImpl<T extends PersistableEntity<? extends Serializable>, ID extends Serializable> implements BaseService<T, ID> {
```

```
public abstract class PersistableEntity<ID extends Serializable> implements Persistable<ID> {
```

```
/**
 * Simple interface for entities.
 * 
 * @param <ID> the type of the identifier
 * @author Oliver Gierke
 */
public interface Persistable<ID extends Serializable> extends Serializable {

	/**
	 * Returns the id of the entity.
	 * 
	 * @return the id
	 */
	ID getId();

	/**
	 * Returns if the {@code Persistable} is new or was persisted already.
	 * 
	 * @return if the object is new
	 */
	boolean isNew();
}

```
子类覆盖isNew加上@JSONField就搞定了，谢谢。粗心了
