### ISSUE TITLE
toJSONString时字符串中有单引号序列化出错

### ISSUE THREAD

**Issue by wangxin7** [alibaba/fastjson#761]
比如对象属性是这样的：
"x": 10000020,
"xx": "10000020",
"xxx": "roc'资金公司",
"xxxx": "c'资金公司",
"xxxxx": "C'ZJGS",

因为value的值里有单引号，序列化之后单引号变成了双引号，如下：
"x": 10000020,
"xx": "10000020",
"xxx": "roc”资金公司",
"xxxx": "c”资金公司",
"xxxxx": "C”ZJGS",

在浏览器中会报错，望知悉。版本：1.2.15
后改用GSON解决，序列化后是这样的：
"name": "roc\u0027资金公司"
GSON把单引号转义为了：\u0027 ，这点我觉得挺好

**Comment by wenshao** [comment]
不应该啊，fastjson不会把单引号变成双引号的，你是怎么使用的？能够提供重现问题的testcase么？

**Comment by wangxin7** [comment]
经过我仔细测试，fastjson确实不会把单引号变成双引号，我的问题出在SpringMVC身上，谢谢温少！ @wenshao
