### ISSUE TITLE
SerializeConfig 增加filter在map上失效

### ISSUE THREAD

**Issue by wyh6635** [alibaba/fastjson#763]
在配置SerializeConfig全局属性忽略时，如果是map对像时，无法传递filter，属性不生效

**Comment by wenshao** [comment]
可以提供重现问题的testcase么？我好确认到时候能够修复你的问题

**Comment by wyh6635** [comment]
@wenshao 
参考如下：有需要可加wyh6635微信，详细沟通，谢谢！


`import java.util.HashMap;
import java.util.Map;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializeConfig;
import com.alibaba.fastjson.serializer.SimplePropertyPreFilter;


public class MapSerializeTest {

    public static void main(String[] args) {
        Map<String, Object> reqDto = new HashMap<>();
        reqDto.put("name", "aaaa");
        reqDto.put("age", 50);
        reqDto.put("address", "深圳南山");
        
        
        SimplePropertyPreFilter filter = new SimplePropertyPreFilter();
        filter.getExcludes().add("name");

        SerializeConfig.getGlobalInstance().addFilter(Map.class, filter);
        System.out.println(JSON.toJSONString(reqDto));
    }
    
}
`
期望值：{"address":"深圳南山","age":50}
输出的结果：{"address":"深圳南山",**"name":"aaaa"**,"age":50}

**Comment by wyh6635** [comment]
环境：jdk1.8, fastjson 1.2.10, 1.2.11, 1.2.12

**Comment by wenshao** [comment]
问题重现，我尽量在周末发布的版本中修复，谢谢反馈

**Comment by wenshao** [comment]
问题已解决，将会在周末发布的版本1.2.16中修正此问题，谢谢反馈
