### ISSUE TITLE
原本运行正常的APP混淆后解析失败，提示ClassCastException

### ISSUE THREAD

**Issue by bing163** [alibaba/fastjson#765]
实体类如下
```java
public class ContentListResponse extends Response {
	private List<ContentList> data;
	public List<ContentList> getData() {
		return data;
	}
	public void setData(List<ContentList> data) {
		this.data = data;
	}
}`
解析如下：
`public abstract class BeanCallback<T> extends Callback<T> {
	private Class<T> clazz;
	public BeanCallback(Class<T> clazz) {
		this.clazz = clazz;
	}
	@Override
	public T parseNetworkResponse(Response response) throws Exception {
		String result = response.body().string();
		T t = JSON.parseObject(result, clazz);
		return t;
	}
}

new BeanCallback<ContentListResponse>(ContentListResponse.class) {......}
```

这样写在不混淆的时候是能正常解析成功的，但在加了混淆之后就一直报ClassCastException，已经把实体类和fastjson加到keep里了，混淆配置摘录如下：
`-keepattributes Singature      
-keepattributes *Annotation*
-keep class com.alibaba.fastjson.**{*;}
-keep class * implements java.io.Serializable { *; }
-dontwarn android.support.**
-dontwarn com.alibaba.fastjson.**`
把混淆关掉就又正常了
下午折腾一下午了，还没搞定

**Comment by wenshao** [comment]
fastjson什么版本，报错的详细信息能提供一下么？

**Comment by bing163** [comment]
fastjson-1.1.36           fastjson-1.1.52  都试了，报一样的错，java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.xining.app.firecontrol.model.ContentList

**Comment by wenshao** [comment]
应该是混淆之后把List<ContentList>这样的泛型信息抹掉了

**Comment by bing163** [comment]
终于发现问题了，我的错， -keepattributes Signature   中单词拼错了，拼成Singature  了； 现在可以了，这个关了吧，不好意思，添麻烦了

**Comment by wenshao** [comment]
哈哈，我关闭issue啦
