### ISSUE TITLE
能否添加注解指定序列化类的功能? 例如注解model某个long属性序列化除与100(金额"分"单位转成"元")

### ISSUE THREAD

**Issue by tianhao** [alibaba/fastjson#767]
场景用例:注解model某个long属性序列化时除与100(金额"分"单位转成"元")
使用方法: 只需添加一行注解指定序列化方法(将long除与100转成double)
优势: 直接指定某个属性转化而不是指定类型或所有相同的属性名称, 不需要修改原有接口,只需要在model中对指定属性添加注解
PS:  `FasterXML/jackson-databind `有类似的注解: `@JsonSerialize(using = ToStringSerializer.class)`

**Comment by wenshao** [comment]
好建议，将会尽快处理

**Comment by tianhao** [comment]
响应速度那么快!!!  期待新版本发布

**Comment by wenshao** [comment]
文档在这里
https://github.com/alibaba/fastjson/wiki/JSONField
第六点

**Comment by wenshao** [comment]
预计在这个周末发布新版本

**Comment by tianhao** [comment]
👍 , 反序列化可否也做上去, 我之前提出的是输出转化, 可否把输入转化也做进去?

**Comment by wenshao** [comment]
已经支持
