### ISSUE TITLE
FastJson很好用，但是做castToJavaBean 的时候不能按照类转List<String> 而要用数组？为什么呢

### ISSUE THREAD

**Issue by lujun0918** [alibaba/fastjson#769]
{"passType":"2_1,3_1","betArray":[
{"dan":false,"matchCode":"201608114301","betCodes:["01","02","03","04","05"]}]}

java 的代码就式betCodes是一个List<String> 调试了下，是因为fastjson认为这个式数组

**Comment by lujun0918** [comment]
知道BUG所在了，原来创建这个JSON的时候式用String[]创建的，后面直接拿这个String[]的JSON去序列化JavaBean,所以出现了上面的BUG。

**Comment by wenshao** [comment]
那我关闭issue啦
