### ISSUE TITLE
JSON本身并不支持注释，FastJSON可以扩展一下吗？

### ISSUE THREAD

**Issue by laiweiwei** [alibaba/fastjson#77]
JSON本身并没有注释相关的内容。但是我在项目里使用JSON格式内容作为配置，并添加注释来说明，因此很希望FastJSON在解析的时候可以实现忽略类似这样/**/的注释效果。下面啰嗦一下为什么要选择JSON作为配置：
    1）结构化+动态灵活性
    2）在1的基础上比XML轻量，没有XML那么啰嗦，XML相对来说太重了。
    3）Nutz也选择了JSON作为配置

**Comment by kfhanjie** [comment]
fastjson的1.2.7版本也没处理这个参数啊。 Feature.AllowComment 。希望支持啊 我们都是用json来配置一些信息，如果没注释 这些配置信息很难理解的！
