### ISSUE TITLE
JSONArray转string时小数点为0的浮点数会丢失精度问题

### ISSUE THREAD

**Issue by wanglei10500** [alibaba/fastjson#773]
一些价格类数据 如22.0 10.0 作为json的value 用fastjson转换时会省略后面的.0  在一些应用场景会出现问题。

**Comment by wenshao** [comment]
之前是故意去掉的，陆续有人反馈说有问题，你遇到的是具体什么问题？我好决定是否保留".0"

**Comment by wanglei10500** [comment]
例如[{"price":22.0},{“price”:10.0}] JSONArray.toString() 结果会变为"[{"price":22},{“price”:10}]" 类似这样 .0 会被去掉，在一些使用场景会出现问题,比如需要用这个串做签名和验签，串会不一致

**Comment by wufeigit** [comment]
使用FastJsonHttpMessageConverter4 结果仍然是"[{"price":22},{“price”:10}]"这种数据格式 ，没有保留小数位
