### ISSUE TITLE
$..name deepScan功能问题

### ISSUE THREAD

**Issue by github-nays** [alibaba/fastjson#774]
![image](https://cloud.githubusercontent.com/assets/11980080/17617941/6d7d1ba2-60af-11e6-8907-a2f0716888db.png)
@wenshao  
JSONPATH中 我看到已经支持deepScan，我觉得很好用，发现一些疑惑：就是如果JSON串中递归到深层，执行到下列代码
for (Object val : map.values()) {
                deepScan(val, propertyName, results);
}
此时map内容为{"subjectName":"总分","subjectId":"ALL"}，会尽继续进入deepScan进行递归，但是进入下一层递归中，没有任何逻辑可以执行，直到最后 throw new JSONPathException("jsonpath error, path " + path + ", segement " + propertyName);
就这样抛出了异常，这是正确的处理方式吗？没有匹配的方法执行应该可以return，回到上一级递归啊，怎么这个地方需要抛出一个异常？

**Comment by wenshao** [comment]
如你所说代码逻辑是不对的，谢谢帮忙做code review

**Comment by wenshao** [comment]
你按你所说的修复，问题先关闭啦
