### ISSUE TITLE
"{'token':'token':'sign':'bb'}"这种格式的字符串也能被解析

### ISSUE THREAD

**Issue by lzhcxk** [alibaba/fastjson#779]
String aaa = "{'token':'token':'sign':'bb'}";
BaseBusinessReq map = JSON.parseObject(aaa, BaseBusinessReq.class);
System.out.println(map.getToken());
System.out.println(map.getSign());
输出：
token
bb
在解析字符串成对象bean的时候能被解析成功，但解析成Map类型的时候会报错。
但这字符串并不是json字符串格式，这应该是个bug吧。
到fastjson 1.2.16版本都还是这样的

**Comment by githublaohu** [comment]
可以解析，fashjson支持多种风格的 json格式。
你可以去看下 fashjson的文档，上面说的很详细的。
不好意思，我基本没用过map作为数据格式。所以不知道map会不会报错。

**Comment by wenshao** [comment]
确实是bug，尽快修正，谢谢反馈

**Comment by wenshao** [comment]
问题已经修复，如无意外今天就会发布新版本
