### ISSUE TITLE
为什么字符串json在getJSONObject的时候不能转成JsonObject

### ISSUE THREAD

**Issue by strivezsh** [alibaba/fastjson#780]
JSONObject json = new JSONObject();
json.put("robj", "{abc: 123}");
System.out.println(json.getJSONObject("robj"));
处于什么考虑的
老版本的项目 一直木有问题
最近更新了 就抛出异常了

**Comment by githublaohu** [comment]
现在不会自动解析  robj的 key，
可以把代码修改下。
   JSONObject json = new JSONObject();
        json.put("robj", JSON.parseObject("{abc: 123}"));
        System.out.println(json.getJSONObject("robj"));

**Comment by wenshao** [comment]
下个版本会加上这个支持，预计会在周末8月28日发布
