### ISSUE TITLE
spring 前台post 的json数据，后台用fastjson 反序列化后，不能转换成相应 数组对象  而是数组的JSONOBJECT？

### ISSUE THREAD

**Issue by spiritelf** [alibaba/fastjson#781]
spring 前台post 的json数据，后台用fastjson 反序列化后，不能转换成相应 数组对象  而是数组的JSONOBJECT？ 这个是什么回事？

<mvc:annotation-driven>
	    <mvc:message-converters>
           <bean class="org.springframework.http.converter.StringHttpMessageConverter"/>
           <bean class="org.springframework.http.converter.ResourceHttpMessageConverter"/>
           <bean class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter"/>
        </mvc:message-converters>
   </mvc:annotation-driven>

public @ResponseBody String UpdatestStoPdStockForm(@RequestBody List<StPdStockDetail> stPdDetails,HttpServletRequest request, RedirectAttributesModelMap modelMap)

$.ajax({
	                type: "POST",
	                url: "/corp/stStoPdStockForm/UpdatestStoPdStockForm.jhtml?pdid=" + $("#pdid").val() +"&pdNo=" + $("#stock_span").text() + "&opt=" + Math.random()+"&strAction=editpdstock",
	                data: JSON.stringify(PostData),
	            	contentType : 'application/json',
	            	dataType:"json",
	                success: function (msg) {
	                    alert('保存成功');
	                    window.location.href = '/corp/stStoPdStockList.jhtml';
	                }
	            });

**Comment by wenshao** [comment]
@VictorZeng 帮忙看一下

**Comment by VictorZeng** [comment]
@spiritelf spring 和 fastjson都是什么版本

**Comment by spiritelf** [comment]
使用最新版本可以了
