### ISSUE TITLE
XMLGregorianCalendar 灵活度问题

### ISSUE THREAD

**Issue by sl-wxx** [alibaba/fastjson#782]
ObjectSerializer 都是按照类型自动匹配的，这样会在一定程度上不够灵活。比如要匹配javax.xml.datatype.XMLGregorianCalendar的所有实现类型，就有点困难。是否可以考虑增加一个 ObjectSerializer 的子接口，并定义一个返回boolean的方法，可以让用户自己去判断是否匹配。而不是只能根据类型判断。

**Comment by wenshao** [comment]
可以考虑更好的扩展支持，同时也可以做内置支持。如果是内置支持，你期望是怎样的结果？

**Comment by wenshao** [comment]
已经内置支持，和genson以及jackson一样

**Comment by Rocky-Hu** [comment]
序列化后的格式呢？ 怎么设置？比如说生成json的时候字符串展示 格式为“yyyy-MM-dd”这样
