### ISSUE TITLE
fastjson1.1.52 JSON.parse Exception

### ISSUE THREAD

**Issue by littleseven** [alibaba/fastjson#784]
JSON.parse("[{\"args\":[\"150\",\"change\",{\"timeStamp\":1471595047319,\"value\":\"\"},{\"attrs\":{\"value\":\"\"}}],\"method\":\"fireEvent\"}]");

上面这行代码在fastjson1.1.52 抛异常～在第73个字符

**Comment by githublaohu** [comment]
JSONArray object = JSON.parseArray("[{\"args\":[\"150\",\"change\",{\"timeStamp\":1471595047319,\"value\":\"\"},{\"attrs\":{\"value\":\"\"}}],\"method\":\"fireEvent\"}]");
        System.out.println( object.get(0).toString());

{"args":["150","change",{"timeStamp":1471595047319,"value":""},{"attrs":{"value":""}}],"method":"fireEvent"}

fashjson 版本 。1.2.7

**Comment by wenshao** [comment]
我测试了新版本是好的
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.16/

你试试看
