### ISSUE TITLE
如何对urlencode的字符串进行解析？

### ISSUE THREAD

**Issue by blackdog1987** [alibaba/fastjson#785]
例如：%7B%22companyId%22%3A1%2C%22subCompany%22%3A1%2C%22authorities%22%3A%222002003%22%7D

**Comment by githublaohu** [comment]
不好意思，
帮你找了一些地方，实在是没找到。fastjson的解决方案，
建议，自己转移下，其实也简单。这是 php传过来的数据吧。

**Comment by hinadong** [comment]
BASE64处理之后，再转换一道，难道不行？

**Comment by wenshao** [comment]
直接调用java.net.URLDecoder不行么？

**Comment by wenshao** [comment]
这个不是fastjson的问题，先关闭啦
