### ISSUE TITLE
为什么这里没有 fastjson 1.2.3 的源码呢

### ISSUE THREAD

**Issue by livem** [alibaba/fastjson#787]
想找一下 1.2.3 版的源码看看，看了一下没找着。。。。
在哪里可以下载呢？

**Comment by githublaohu** [comment]
用最新的不可以吗?

**Comment by livem** [comment]
老项目还在用的 fastjson 1.2.3 版本。。。

已经在这里 http://repo1.maven.org/maven2/com/alibaba/fastjson/  找到 fastjson 1.2.3 的源码了^_^
