### ISSUE TITLE
 Json 解析错误

### ISSUE THREAD

**Issue by xihacode** [alibaba/fastjson#793]
syntax error, expect {, actual [, pos 54, fieldName game_data
`{
   "code": 1000,
    "data": "success",
     "game_data": [],
     "member_list": [],
      "message": "\u6210\u529f"
     }`

解析这样的数据时会报错

**Comment by wenshao** [comment]
什么版本，我测试了问题没有重现

**Comment by xihacode** [comment]
不好意思，我的model有点问题
