### ISSUE TITLE
fastjson序列化是没处理特殊字符，转义后为\u007F

### ISSUE THREAD

**Issue by JerryLei** [alibaba/fastjson#798]
该非法字符反序列化后为\�，导致json结构错误：
范例：
String str = "<p>主要学校：密歇根大学 安娜堡分校、东密西根大学、 克莱利学院、康考迪亚学院 、瓦什特洛社区学院</p>";
        System.out.println(JSON.toJSONString(str));

**Comment by wenshao** [comment]
如沟通结果并经过测试问题不存在，先关闭啦
