### ISSUE TITLE
compile 'com.alibaba:fastjson:1.2.16'  和 compile 'com.alibaba:fastjson:1.1.54.android'有什么区别

### ISSUE THREAD

**Issue by maxinlei** [alibaba/fastjson#800]
支持android7.0吗？

**Comment by wenshao** [comment]
com.alibaba:fastjson:1.1.54.android是fastjson针对android特别优化的版本，jar更小，在android上运行比标准版更快。具体介绍看这里： https://github.com/alibaba/fastjson/wiki/Android%E7%89%88%E6%9C%AC

**Comment by maxinlei** [comment]
Thankyou
