### ISSUE TITLE
How to skip Exception when using JSONField(format="yyyy-MM-dd")

### ISSUE THREAD

**Issue by Andecy** [alibaba/fastjson#801]
code is :
@JSONField(format = "yyyy-MM-ddTHH:mm:ss.SSS")
but responese is :
0001-01-01T00:00:00
it will throw NumberFormatException AND stop parse remaining.

========= H O P E =========

throw and parse continuous?

thanks

**Comment by Andecy** [comment]
@wenshao I think it's helpful to add a boolean attr named "strict" to JSONFiled or whaterver like simpleXML

**Comment by Andecy** [comment]
it's well,thanks

**Comment by Coding-Qiang** [comment]
it helps a lot, thanks.
