### ISSUE TITLE
配合retrofit2使用，泛型解析失败

### ISSUE THREAD

**Issue by imliujun** [alibaba/fastjson#803]
{
    "code": "200",
    "msg": "操作成功",
    "token": "",
    "data": {
        "accept_push": 1,
        "items": [
            {
                "relation_id": 12462,
                "nickname": "29",
                "gender": 0,
                "grade": 7,
                "signature": "",
                "photo": "http://heixiucrm-test.oss-cn-beijing.aliyuncs.com/robot/1460705770811",
                "accept_push": 1
            },
            {
                "relation_id": 12463,
                "nickname": "哦1哦1哦1逆袭why",
                "gender": 0,
                "grade": 54,
                "signature": "",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/1226_head_20160831020021",
                "accept_push": 1
            },
            {
                "relation_id": 12367,
                "nickname": "去吧🤔",
                "gender": 0,
                "grade": 50,
                "signature": "",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/test_1269_head_20160824154244",
                "accept_push": 1
            },
            {
                "relation_id": 12488,
                "nickname": "急急如律令",
                "gender": 0,
                "grade": 52,
                "signature": "",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/heixiu1396_1471940861545",
                "accept_push": 1
            },
            {
                "relation_id": 12489,
                "nickname": "每天正能量～誉",
                "gender": 0,
                "grade": 37,
                "signature": "工具了家里",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/heixiu1628_1471601607282",
                "accept_push": 1
            },
            {
                "relation_id": 12368,
                "nickname": "拳怕少壮",
                "gender": 0,
                "grade": 56,
                "signature": "无限制",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/heixiu1914_1472523618816",
                "accept_push": 1
            },
            {
                "relation_id": 12365,
                "nickname": "666",
                "gender": 0,
                "grade": 58,
                "signature": "",
                "photo": "http://heixiu.oss-cn-beijing.aliyuncs.com/heixiu2440_1471941930217",
                "accept_push": 1
            }
        ]
    }
}

这个json格式是合法的。

```
public class HttpResult<T> {

    public String code;
    public String msg;
    public String token;

    public T data;
}

public class RecommendBean {
    public int accept_push;
    public List<ItemsBean> items;

    public static class ItemsBean {
        public int relation_id;
        public int gender;
        public int empiric;
        public String signature;
        public String photo;
        public int accept_push;
        public int user_id;
        public String nickname;//昵称
    }
}
```

上面那串JSON解析成 `HttpResult<RecommendBean>`，data属性变为了JsonObject，data没有解析成RecommendBean对象

---

{"code":"200","msg":"","token":"","data":{"liveList":[],"replayList":[]}}

```
public class LiveAttentionInfo {
    public List<LiveList> liveList;
    public List<ReplayList> replayList;
}
```

这一串JSON的data解析`HttpResult<LiveAttentionInfo>` 同样没有解析成泛型。

```
compile 'com.alibaba:fastjson:1.1.54.android'
```

解析方法

```
JSON.parseObject(jsonString, mType, config, featureValues, features != null ? features : EMPTY_SERIALIZER_FEATURES);
```

@wenshao

**Comment by imliujun** [comment]
本来用的是GSON，我给换成了fastJson,出现这个问题我找了一天的原因，刚才又换回GSON就没有问题了

**Comment by blackshadowwalker** [comment]
@imliujun 
应该是你的使用方式有问题，我测试没问题，经过查看源码是有做深层泛型解析的，看截图

![Version](https://img.shields.io/badge/fastjson-1.2.16-blue.svg)
![jdk       ](https://img.shields.io/badge/Jdk-1.8-blue.svg)
![OS       ](https://img.shields.io/badge/OS-Windows 10 x64-blue.svg)

![image](https://cloud.githubusercontent.com/assets/5380980/18190597/937a4314-70f6-11e6-84dc-bfd2a36c06d6.png)

**Comment by imliujun** [comment]
我单个测好像也没有问题，但是配合retrofit2进行解析就出问题了。我调试到
```
JSON.parseObject(jsonString, mType, config, featureValues, features != null ? features : EMPTY_SERIALIZER_FEATURES);
```
发现mType带了泛型，可是解析出来变成了JSONObject或者JSONArray.
更深的我就没有跟下去了，具体原因也不清楚

**Comment by blackshadowwalker** [comment]
我也使用retrofit2试了一下，泛型我这使用的还多，也没问题

```java
ResponseDto<Page<List<UserInfo>>> ret = JSON.parseObject(jsonData, new TypeReference<ResponseDto<Page<List<UserInfo>>>>(){});
```

ResponseDto
```java
class ResponseDto<T> {
     int     code;
    T       data;
    String  msg;
    long    timestamp;
}
```

Page
```java
class Page<T> {
    Integer pageNum;
    Integer pageSize;
    T result;
}
```

```java
@Bean
public Retrofit retrofit(OkHttpClient okHttpClient) {
        return new Retrofit.Builder()
                .baseUrl(ENDPOINT)
                .addConverterFactory(FastJsonConverterFactory.create())
                .client(okHttpClient)
                .build();
}
```

![Version](https://img.shields.io/badge/fastjson-1.2.16-blue.svg)
![jdk       ](https://img.shields.io/badge/Jdk-1.8-blue.svg)
![OS       ](https://img.shields.io/badge/OS-Windows 10 x64-blue.svg)



![qq 20160902102748](https://cloud.githubusercontent.com/assets/5380980/18190898/7f0bbad2-70f8-11e6-91af-b15b76e6b5ee.png)

**Comment by imliujun** [comment]
我使用的是
https://github.com/ligboy/retrofit-converter-fastjson
难道是因为这个原因吗？
我试过fastjson 1.2.16版本和1.1.54.android，都出现这个问题。

**Comment by blackshadowwalker** [comment]
我使用的
```xml
 <dependency>
                <groupId>org.ligboy.retrofit2</groupId>
                <artifactId>converter-fastjson</artifactId>
                <version>2.1.0</version>
</dependency>
```

如果单个测试没问题，那个使用retrofit2是完全一样的，毕竟retrofit2也是http协议，最后解析的还是json字符串，与单个测试一样

**Comment by imliujun** [comment]
那么我们的区别就在JDK上面了，我用的是jdk1.7 
我有时间再测一下，现在项目紧没时间去测了

**Comment by dongyeforever** [comment]
我用的 fastjson 1.2.16  jdk1.8.0_65  retrofit:2.1.0 偶尔也是返现解析类型转换异常

> java.lang.ClassCastException
com.alibaba.fastjson.JSONObject cannot be cast to com.aladdin.bang.profile.bean.UserBean

**Comment by Andecy** [comment]
我配合Retrofit2+okHttp3使用了大半年了

**Comment by blackshadowwalker** [comment]
这个就是使用 Retrofit2+okHttp3 + Spring 写的，看看单元测试部分，使用的泛型，完全无压力
https://github.com/blackshadowwalker/spring-retrofit2

**Comment by dongyeforever** [comment]
接口是类似这样的：
`@GET("group/getGroupUsers")
    Observable<HttpResult<List<UserBean>>> getGroupUsers(
            @Query("groupid") String groupId
    );`

偶尔出现类型转换异常

**Comment by parcool** [comment]
@blackshadowwalker  你这是直接在TypeRefrence里写好了全部类型。但是这种就没法写完全部了：
`FastJsonResponseBodyConverter.java`
`    @Override
    public T convert(ResponseBody value) throws IOException {
        try {
//            return JSON.parseObject(value.string(), mType, config, featureValues,
//                    features != null ? features : EMPTY_SERIALIZER_FEATURES);
//            return JSON.parseObject(value.string(),new TypeReference<T>(){}.getType(),config,featureValues,features != null ? features : EMPTY_SERIALIZER_FEATURES);
            return JSON.parseObject(value.string(),new TypeReference<T>(){});
        } finally {
            value.close();
        }
    }`
这个问题还是依旧存在。·com.alibaba:fastjson:1.1.54.android·

**Comment by yubaokang** [comment]
遇到同样的问题

**Comment by blackshadowwalker** [comment]
已修复，复现请看 https://github.com/alibaba/fastjson/issues/569

**Comment by wenshao** [comment]
请使用最新版本1.1.55.android

**Comment by lxfeng** [comment]
1.1.56.android 还是会偶现这个问题

**Comment by F1ReKing** [comment]
@wenshao    1.1.56.android 还是依然会偶现这个问题

**Comment by nxSin** [comment]
我是用的fastjson-1.2.31.jar，还是有这个问题。

```
public class BaseResp<T> {

    /**
     * 同传参
     */
    private String reqMethod;
    /**
     * 同传参
     */
    private String reqParam;

    /**
     * 0正常，非0异常
     */
    private String resStatus;

    /**
     * 接口返回值
     */
    private T resData;

    public String getReqMethod() {
        return reqMethod;
    }

    public void setReqMethod(String reqMethod) {
        this.reqMethod = reqMethod;
    }

    public String getReqParam() {
        return reqParam;
    }

    public void setReqParam(String reqParam) {
        this.reqParam = reqParam;
    }

    public String getResStatus() {
        return resStatus;
    }

    public void setResStatus(String resStatus) {
        this.resStatus = resStatus;
    }

    public T getResData() {
        return resData;
    }

    public void setResData(T resData) {
        this.resData = resData;
    }

    @Override
    public String toString() {
        return "BaseResp{" +
                "reqMethod='" + reqMethod + '\'' +
                ", reqParam='" + reqParam + '\'' +
                ", resStatus='" + resStatus + '\'' +
                ", resData=" + resData +
                '}';
    }
}
```

传入范型是List<LoginResp>，如使用的时候：BaseResp<List<LoginResp>>。但是获取出来的List<LoginResp>是JSONArray，其中含有的是JSONObject。使用时报强转错误
