### ISSUE TITLE
SpringMVC+fastjson 不配置application/json;charset=UTF-8 能改变返回参数null为""

### ISSUE THREAD

**Issue by woailol930910** [alibaba/fastjson#805]
关于fastjson的问题 我们项目在使用工作流前台画图的时候 如果在SpringMVC中加入配置application/json;charset=UTF-8，画图就出现了问题（具体问题 我没有负责流程图那部分不怎么清楚，大概是key相同的问题） 如果我注释掉该配置，我想把返回给界面对象的参数中的null转化为""，有办法吗？

**Comment by 805728578** [comment]
![default](https://cloud.githubusercontent.com/assets/9798724/18158484/398a29aa-7056-11e6-83aa-59964510781e.png)

请查看配置文件如图标记是否配置

**Comment by woailol930910** [comment]
如果不使用配置呢

**Comment by 805728578** [comment]
那就需要在后台返回时做处理

比如：
JSON.toJSONString(data, new SerializerFeature[] { SerializerFeature.WriteDateUseDateFormat, SerializerFeature.WriteNullStringAsEmpty, SerializerFeature.BrowserCompatible })

对返回data数据格式化

**Comment by woailol930910** [comment]
谢谢
