### ISSUE TITLE
为什么用getObject方法某些个字段解析结果为null

### ISSUE THREAD

**Issue by hynb** [alibaba/fastjson#807]
example：jsonobj.getObject("userInfo",WechatUserInfo.class); 中例如名字，头像地址，性别都能正常获取到，但是id类的字符串解析均为null，例如："unionid":"oq9QRtyW-kb6R_7289hIycrOfnyc" ，"openid":"oEH-vt-7mGHOQets-XbE1c3DKpVc"，
但是用parseObject（jsonStr，xx.class）；这种又能正常解析，不知道为啥，求大牛解答~
完整json：{"ckid":"81a5953835310708e414057adb45e826","rcToken":"E+jkQCWSwop+JICPBHc+fxMYeExTx2NTDGZCJ8gIPg7NbMLNvfmZBPU2dR5uxpRRe+zPnOIaCATpHcSa6q+k39HGjNFFDRt9PNlEJokpxhTw9gYJ/WKoSlVR/4ibjIgjvVHxS2lNLS4=","userInfo":{"openid":"oEH-vt-7mGHOQets-XbE1c3DKpVc","nickname":"Pietro","sex":1,"language":"zh_CN","city":"","province":"Beijing","country":"CN","headimgurl":"http://wx.qlogo.cn/mmopen/kox8ma2sryApONj7kInbic4iaCZD8tXL4sqe7k3wROLpb2uCZhOiceAbL69ANeXSMu9zf7hibmt3Y0Ed4A6zIt9ibnPaiciauLZn57c/0","privilege":[],"unionid":"oq9QRtyW-kb6R_7289hIycrOfnyc"},"isNewUser":false}

**Comment by githublaohu** [comment]
??????????

**Comment by wenshao** [comment]
WechatUserInfo类结构是怎样的？

**Comment by hynb** [comment]
public class WechatUserInfo implements Serializable {

    public String unionId;
    public String openId;
    public String nickname;
    public int sex;
    public String province;
    public String country;
    public String headimgurl;

} @wenshao  WechatUserInfo类结构

**Comment by wenshao** [comment]
因为unionid大小写不匹配，没有智能识别。。。

**Comment by wenshao** [comment]
已经支持，请等1.2.17版本发布吧

**Comment by hynb** [comment]
Thank you 😄😄😄
