### ISSUE TITLE
支持OSGi规范吗？

### ISSUE THREAD

**Issue by watonyweng** [alibaba/fastjson#811]
解压jar后查看MANIFEST.MF文件未发现Bundle相关的声明

**Comment by wenshao** [comment]
我不够了解相关技术，你能帮忙提交一下相关配置文件么？

**Comment by watonyweng** [comment]
@wenshao [OSGI](https://en.wikipedia.org/wiki/OSGi#Bundles)

**Comment by SpriMoon** [comment]
什么时候能支持bundle打包
