### ISSUE TITLE
纯文本字符串返回为{}问题？

### ISSUE THREAD

**Issue by 805728578** [alibaba/fastjson#815]
1.FastJsonControllerTest增加

@RequestMapping(value = "/test9", method = {RequestMethod.POST, RequestMethod.GET},produces = {"text/plain", "application/*"})
 public  Object test9(@RequestParam(defaultValue="0")long userId,String lang){
 log.info("--请求参数{userId:"+userId+",lang:"+lang+"}json:");
    return "ok";
 }

2.FastJsonHttpMessageConverterTest增加

@Test 
 public void test9() throws Exception {
 mvc.perform((post("/fastjson/test9").characterEncoding("UTF-8")
 .param("userId", "3")
 .param("lang", "zh")
 .contentType(MediaType.MULTIPART_FORM_DATA_VALUE))).andDo(print()); 
 }

期望返回结果: ok
实际返回结果: {}

**Comment by 805728578** [comment]
问题已解决，返回类型前加入@ResponseBody 解决

**Comment by wenshao** [comment]
那我关闭啦
