### ISSUE TITLE
fastjson对于String类型中值中使用了",如何默认不转义成\"

### ISSUE THREAD

**Issue by firekirin67** [alibaba/fastjson#822]
RT

**Comment by githublaohu** [comment]
能出一个列子吗？

**Comment by firekirin67** [comment]
@githublaohu [''aaaa","bbbbb"]"  这个字符串本身是不带转义的 用String引用该值
JSON.toJSONString(str)得到的结果就成[\"aaaa\",\"bbbbb\"]

**Comment by firekirin67** [comment]
@githublaohu 发现使用SerializerFeature.UseSingleQuotes能够解决这个问题但是field都是用了'单引号包裹

**Comment by githublaohu** [comment]
这是你自己的问题。
为什么还要 toJsonString 了？
已经是 是 json格式的字符串了。

**Comment by firekirin67** [comment]
@githublaohu 很是纠结啊  本身是个json格式的字符串了 但是用String保存  之后再对对象进行序列化就转义了  哎

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/JSONField_jsonDirect_cn
看这个是否能满足你的需求

**Comment by JeremyZheng** [comment]
> https://github.com/alibaba/fastjson/wiki/JSONField_jsonDirect_cn
> 看这个是否能满足你的需求

如果这个field不是json格式怎么设置不转义？

**Comment by huahuayu** [comment]
> https://github.com/alibaba/fastjson/wiki/JSONField_jsonDirect_cn
> 看这个是否能满足你的需求

试了没用

**Comment by huahuayu** [comment]
实测，外面套一个`StringEscapeUtils.unescapeJava`方法即可去掉转义。
``` java
StringEscapeUtils.unescapeJava(JSON.toJSONString(response))
```

**Comment by firekirin67** [comment]
忘记关闭了 多谢各位

**Comment by firekirin67** [comment]
忘记关闭了 多谢各位
