### ISSUE TITLE
ordinal扰乱反序列化中的二分查找导致JavaBean转换时属性值丢失

### ISSUE THREAD

**Issue by yinbin1yd** [alibaba/fastjson#827]
在实体类中的@JSONField(ordinal = 1)/@JSONField(ordinal = 999)会影响数据的反序列化，具体在JavaBeanDeserializer.getFieldDeserializer中的二分查找法，因为ordinal会扰乱sortedFieldDeserializers这个属性的排序；
因为sortedFieldDeserializers这个数组是按字母排序的，如果说我有一个属性叫createId(ordinal=999)，那么在sortedFieldDeserializers这个数组中必定会处于最后一个(属性不超过999个的情况下)，扰乱了sortedFieldDeserializers的原始顺序，导致二分查找法失效(二分查找要求数组必须是有序的)

com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer
OrderDetailField order = obj.getObject("order", OrderDetailField.class);

不知是否可以使用Map替换原二分查找？

private final FieldDeserializer[]   fieldDeserializers;
    protected final Map<String, FieldDeserializer> sortedFieldDeserializerMap;  //定义Map，key为fieldName
    protected final FieldDeserializer[] sortedFieldDeserializers;
    protected final Class<?>            clazz;
    public final JavaBeanInfo           beanInfo;
    
    public JavaBeanDeserializer(ParserConfig config, Class<?> clazz) {
        this(config, clazz, clazz);
    }

    public JavaBeanDeserializer(ParserConfig config, Class<?> clazz, Type type){
        this(config, JavaBeanInfo.build(clazz, type, config.propertyNamingStrategy));
    }
    
    public JavaBeanDeserializer(ParserConfig config, JavaBeanInfo beanInfo){
        this.clazz = beanInfo.clazz;
        this.beanInfo = beanInfo;
        
        sortedFieldDeserializerMap = new ConcurrentHashMap<String, FieldDeserializer>(beanInfo.sortedFields.length);
        sortedFieldDeserializers = new FieldDeserializer[beanInfo.sortedFields.length];
        for (int i = 0, size = beanInfo.sortedFields.length; i < size; ++i) {
            FieldInfo fieldInfo = beanInfo.sortedFields[i];
            FieldDeserializer fieldDeserializer = config.createFieldDeserializer(config, beanInfo, fieldInfo);

            sortedFieldDeserializers[i] = fieldDeserializer;
            
            sortedFieldDeserializerMap.put(fieldInfo.name, fieldDeserializer); //将属性放入Map中
        }

        fieldDeserializers = new FieldDeserializer[beanInfo.fields.length];
        for (int i = 0, size = beanInfo.fields.length; i < size; ++i) {
            FieldInfo fieldInfo = beanInfo.fields[i];
            FieldDeserializer fieldDeserializer = getFieldDeserializer(fieldInfo.name);
            fieldDeserializers[i] = fieldDeserializer;
        }
    }

    // 此处用Map替换原数组二分查找算法
    public FieldDeserializer getFieldDeserializer(String key) {
        if (key == null) {
            return null;
        }
        
        return sortedFieldDeserializerMap.get(key);
    }

    public FieldDeserializer getFieldDeserializer_(String key) {
        if (key == null) {
            return null;
        }
        
        int low = 0;
        int high = sortedFieldDeserializerMap.size() - 1;

        while (low <= high) {
            int mid = (low + high) >>> 1;
            
            String fieldName = sortedFieldDeserializers[mid].fieldInfo.name;
            
            int cmp = fieldName.compareTo(key);

            if (cmp < 0) {
                low = mid + 1;
            } else if (cmp > 0) {
                high = mid - 1;
            } else {
                return sortedFieldDeserializers[mid]; // key found
            }
        }
        
        return null;  // key not found.
    }

**Comment by yinbin1yd** [comment]
忽略吧，升到最新版又好了！

**Comment by yyf-it** [comment]
1.2.60版本依然存在这个问题
