### ISSUE TITLE
fastjson序列化异常java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by jarvan4dev** [alibaba/fastjson#830]
在JDK8中，接口MyInterface中有一个default方法，该接口的实现类在被fastjson序列化的时候抛出异常
java.lang.IncompatibleClassChangeError: Found interface com.ins.car.common.dto.ICarInfo, but class was expected

**Comment by jarvan4dev** [comment]
@wenshao

**Comment by wenshao** [comment]
能提供出错类的代码么，好让我重现问题

**Comment by wenshao** [comment]
我没有重现问题，能否提供出错类的代码和fastjson的版本号

**Comment by jarvan4dev** [comment]
不好意思，忘了，我明天看下怎么重现

**Comment by wenshao** [comment]
能重现么？

**Comment by jarvan4dev** [comment]
@wenshao 不好意思，一直忘记提；
`public interface ICarInfo {
    String getCarModelNo();
    default String getDescrip(){
        return "你好";
    }
}`

`public class VehicleModel implements ICarInfo  {
    private String carModelNo;
    private String descrip;
    private int seatCount;
    public void setCarModelNo(String carModelNo) {
        this.carModelNo = carModelNo;
    }
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
    public int getSeatCount() {
        return seatCount;
    }
    public void setSeatCount(int seatCount) {
        this.seatCount = seatCount;
    }
    public String getCarModelNo() {
        return carModelNo;
    }
}
`

`public static void main(String[] args) {
        VehicleModel vehicleModel = new VehicleModel();
        vehicleModel.setCarModelNo("aaaa");
        vehicleModel.setSeatCount(10);
        String str = JSON.toJSONString(vehicleModel);
        System.out.println(str);
    }`

结果：
`Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface com.zuihuibao.test.ICarInfo, but class was expected
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:374)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:394)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:382)
	at com.zuihuibao.test.Test.main(Test.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

**Comment by jarvan4dev** [comment]
@wenshao

**Comment by CharkeyQK** [comment]
我也遇到这个问题了，@wenshao，again

**Comment by wenshao** [comment]
重提已经重现，尽快修正，周末发布

**Comment by wenshao** [comment]
问题已经修复，请使用1.2.22版本

**Comment by CharkeyQK** [comment]
@wenshao 反序列化出现同样的错误是不是bug只修复了一半？

**Comment by zhenzhenailzlx** [comment]
> @wenshao 反序列化出现同样的错误是不是bug只修复了一半？

请问 这个反序列化问题在1.2.22版本还存在吗？或者在什么版本修复了？
