### ISSUE TITLE
应用FastJsonHttpMessageConverter产生的字符串多一对引号

### ISSUE THREAD

**Issue by sjywying** [alibaba/fastjson#84]
当Controller中返回的值为字符串时。对于writeInternal方法中直接调用String text = JSON.toJSONString(obj, features); 此时会在obj的字符串两边加上一对引号导致返回到前台的json并非严格的json结构

举例： 希望得到的值为{data:1} 实际得到的值为 “{data:1} ”

**Comment by shotdog** [comment]
1.1.37 不会出现  1.2.29 则会出现怎么解释？
