### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by w17731138318** [alibaba/fastjson#840]
{"groupNum":"绗竴缁?","userList":[{"age":28,"mame":"鐜嬩簲","sex":"鐢?"},{"age":24,"mame":"寮犱笁","sex":"鐢?"},{"age":26,"mame":"鏉庡洓","sex":"鐢?"}]}
最简单的测试都这么坑。。。

**Comment by w17731138318** [comment]
已解决~

**Comment by Angela-shi** [comment]
您好，请问您的这个问题解决了吗
