### ISSUE TITLE
椰果：提需求：jsonArray能否保证内部对象属性的顺序

### ISSUE THREAD

**Issue by flyingtower** [alibaba/fastjson#847]
现在在使用fastjson的时候出现了一个很麻烦的问题 将js对象数组转换为jsonArray的时候js数组中每个元素内部的属性顺序无法保障 能否为JSONArray的解析也提供一个类似JSONObject中OrderedField选项 就是类似这种 JSON.parseObject(str, Feature.OrderedField);
我需要 JSON.parseArray(str, Feature.OrderedField); 输入 "[{a:1,c:1,b:1}]" 得到对象 [{a:1,c:1,b:1}]
酱紫
多谢了！

**Comment by wenshao** [comment]
问题已解决，我关了哈
