### ISSUE TITLE
IdentityHashMap占用内存大

### ISSUE THREAD

**Issue by waterdream** [alibaba/fastjson#849]
线上代码运行2天后，com.alibaba.fastjson.util.IdentityHashMap内存占用特别大，如果持续运行十几天，会导致内存用完，频繁fullgc。

![image](https://cloud.githubusercontent.com/assets/15976489/19219942/08c04a04-8e54-11e6-8af0-2d51283da978.png)

看了一下identityhashmap的内容，相同的key值有很多份，正常情况应该只有一份吧。
![image](https://cloud.githubusercontent.com/assets/15976489/19220009/930a35c0-8e55-11e6-9404-218ade6dd7ba.png)

**Comment by wenshao** [comment]
fastjson什么版本？

**Comment by waterdream** [comment]
1.2.14

**Comment by wenshao** [comment]
TypeReference每次都new了？

**Comment by waterdream** [comment]
我们的代码是这么使用的。
`public static <T> OpenInResponse<T> parse(String text, Class<T> type) {
        OpenInResponse<T> response = JSON.parseObject(text, new TypeReference<OpenInResponse<T>>(type) {
        });
        if (response == null) {
            response = OpenInResponse.fail(-1, "unkown_error", text);
        }
        return response;
    }`

fastjson的代码里如截图，是每次都new一个出来
![image](https://cloud.githubusercontent.com/assets/15976489/19230614/131a38d4-8f08-11e6-993f-6d40839e29de.png)

**Comment by waterdream** [comment]
和https://github.com/alibaba/fastjson/wiki/TypeReference链接给的例子一样的用法
