### ISSUE TITLE
父类的字段在使用@JSONField指定名称的时候，不支持自定义吗

### ISSUE THREAD

**Issue by fightchwang** [alibaba/fastjson#861]
比如 存在 类 Parent{
@JSONField(name = "ID")
private String id;
....
}
子类 Child {
@JSONField(name = "Desc")
private String desc;
....
}
如：
Parent p = new Child();
...
JSON.toJSONString(p); 得到的Json字符串是{"id":"123","Desc":"234"} 而非{"ID":"123","Desc":"234"} 

使用的1.1.17

**Comment by yx91490** [comment]
1.1.42以后好像支持了

**Comment by yx91490** [comment]
1.1.42以后好像支持了
