### ISSUE TITLE
parseObject方法在Java7和Java8下的表现不一致

### ISSUE THREAD

**Issue by 18981119465** [alibaba/fastjson#863]
如下代码：
`System.out.println(JSONObject.parseObject("{\"ShopName\":\"xxxx\",\"PageSize\":\"2\"}").toJSONString());
System.out.println(JSONObject.parseObject("{\"ShopName\":\"xxxx\",\"PageSize\":\"2\"}", Feature.OrderedField).toJSONString());`
在Java8环境下，执行结果为（无法按key排序）：
{"ShopName":"xxxx","PageSize":"2"}
{"ShopName":"xxxx","PageSize":"2"}
在Java7环境下，执行结果为（可以按key排序）：
{"PageSize":"2","ShopName":"xxxx"}
{"ShopName":"xxxx","PageSize":"2"}

注：测试版本：1.2.18

**Comment by wenshao** [comment]
```java
JSON.parseObject("...", Feature.OrderedField);
```
