### ISSUE TITLE
关于提高序列化SerializerFeature.WriteNullXXXX的用户体验

### ISSUE THREAD

**Issue by yuankui** [alibaba/fastjson#867]
你好，今天我在序列化一个Bean的时候，使用了`SerializerFeature.WriteNullStringAsEmpty`这个feature，然后发现没有生效。
最终通过搜索issue，自己解决了，方法就是同时使用SerializerFeature.WriteNullStringAsEmpty, SerializerFeature.WriteMapNullValue两个feature。

```
public class DemoTest {
  @Test
  public void testIt() {
    Bean bean = new Bean();
    System.out.println("bean.getName() = " + bean.getName());
    System.out.println(JSON.toJSONString(bean, SerializerFeature.WriteNullStringAsEmpty));
  }

  private static class Bean {
    private String name;

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }
  }
}
```

所以现在的问题是，大家都潜意识都以为，只要指定了这个`SerializerFeature.WriteNullStringAsEmpty`这个feature，nullstring就会被序列化，结果却出乎意料。

因此我想说的是，这块的用户体验是不是可以提升一点。
给用户他们期望的结果，OK？

相关issue列表

- https://github.com/alibaba/fastjson/issues/712
- https://github.com/alibaba/fastjson/issues/474
- https://github.com/alibaba/fastjson/issues/398
- https://github.com/alibaba/fastjson/issues/398

还有很多。。。

**Comment by wenshao** [comment]
批评的对，很好的建议！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.20
问题已经修复，请使用新版本，你提的相关issue会晚些挨个跟进

**Comment by yuankui** [comment]
谢谢

**Comment by yqeric** [comment]
今天更新了 1.2.20 版本发现，发现空值的序列化与之前版本不一致，之前默认不序列化空值，新版本序列化了空值，不得以又退回了之前的版本，请问，新版本就这个问题怎么与以前保持一致。

**Comment by waitttttttttttttttttttttttting** [comment]
@yqeric 我懂你的苦衷，我们这边fastjson的依赖配置在一个commons包里，很多业务线都在依赖，因为之前的版本需要同时配置WriteMapNullValue，但我们这边发现好多业务线都只配置WriteNullStringAsEmpty，实际上最终序列化时还是会忽略掉值为null的字段，但前端团队比如iOS这边，就根据有没有返回这个字段来做逻辑处理，所以升级到新版本后，如果业务线不改之前的Spring MVC HttpMessageConverter配置，WriteNullStringAsEmpty就生效了，而且会返回null字段，这样到iOS这边就解析成了一个NSNull对象，但他们又没有对NSNull做处理。所以在升级fastjson版本时需要额外做下处理，重写FastJsonHttpMessageConverter#setFeatures：
`@Override
    public void setFeatures(SerializerFeature... serializerFeatures) {
        int currentVersion = Integer.valueOf(JSON.VERSION.replace(".",""));
        if (currentVersion < 1220) {
            super.setFeatures(serializerFeatures);
            return;
        }

        boolean hasWriteNullFeature = false;
        for (SerializerFeature feature : serializerFeatures) {
            if (WriteMapNullValue == feature) {
                hasWriteNullFeature = true;
                break;
            }
        }

        // getFastJsonConfig method（since 1.2.11）
        FastJsonConfig fastJsonConfig = getFastJsonConfig();

        if (hasWriteNullFeature) {
            fastJsonConfig.setSerializerFeatures(serializerFeatures);
            return;
        }

        List<SerializerFeature> serializerFeatureList = new LinkedList<SerializerFeature>(Arrays.asList(serializerFeatures));
        Iterator<SerializerFeature> featureIterator = serializerFeatureList.iterator();
        while (featureIterator.hasNext()) {
            SerializerFeature feature = featureIterator.next();
            if (WriteNullBooleanAsFalse == feature || WriteNullStringAsEmpty == feature) {
                featureIterator.remove();
            }
        }

        SerializerFeature[] newSerializerFeatures = {};
        newSerializerFeatures = serializerFeatureList.toArray(newSerializerFeatures);
        fastJsonConfig.setSerializerFeatures(newSerializerFeatures);
    }`

**Comment by waitttttttttttttttttttttttting** [comment]
升级前的配置：
<bean id="fastJsonHttpMessageConverter" class="com.xx.commons.converter.FastJsonHttpMessageConverter">
		<property name="supportedMediaTypes">
			<list>
				<value>application/json;charset=UTF-8</value>
				<value>text/html;charset=UTF-8</value>
			</list>
		</property>
		<property name="features">
			<list>
				<value>WriteNullBooleanAsFalse</value>
				<value>QuoteFieldNames</value>
				<value>WriteDateUseDateFormat</value>
				<value>WriteNullStringAsEmpty</value>
			</list>
		</property>
	</bean>

	<mvc:annotation-driven
			content-negotiation-manager="contentNegotiationManager">
		<mvc:message-converters register-defaults="true">
			<ref bean="fastJsonHttpMessageConverter" />
		</mvc:message-converters>
	</mvc:annotation-driven>

	<bean id="contentNegotiationManager"
		  class="org.springframework.web.accept.ContentNegotiationManagerFactoryBean">
		<property name="favorPathExtension" value="true" />
		<property name="favorParameter" value="false" />
		<property name="ignoreAcceptHeader" value="true" />
		<property name="mediaTypes">
			<props>
				<prop key="json">application/json</prop>
				<prop key="xml">application/xml</prop>
			</props>
		</property>
	</bean>

升级之后的配置：
<bean id="fastJsonConfig" class="com.alibaba.fastjson.support.config.FastJsonConfig">
		
		<property name="serializerFeatures">
			<list>
				<value>WriteDateUseDateFormat</value>
			</list>
		</property>
	</bean>

	<bean id="fastJsonHttpMessageConverter" class="com.tongbanjie.commons.converter.FastJsonHttpMessageConverter">
		
		<property name="supportedMediaTypes">
			<list>
				<value>application/json;charset=UTF-8</value>
				<value>text/html;charset=UTF-8</value>
			</list>
		</property>
		
		<property name="fastJsonConfig" ref="fastJsonConfig" />
	</bean>
