### ISSUE TITLE
It shall raise exception when value is out of scope

### ISSUE THREAD

**Issue by greenlaw110** [alibaba/fastjson#868]
Given the following program:

``` java
    public static void foo() throws Exception {
        String str = String.valueOf(Integer.MAX_VALUE);
        short sh = JSON.parseObject(str, short.class);
        System.out.println(sh);
    }
```

FastJson will return `-1` when the value is out of the scope of `short` type. Suppose it shall raise an exception in such case.

**Comment by greenlaw110** [comment]
The above code is for `short` type overflow, the behaviour is correct when it is for int type overflow:

![image](https://cloud.githubusercontent.com/assets/216930/19617985/c5b8619c-988a-11e6-9736-3a636c88d79c.png)

**Comment by greenlaw110** [comment]
for all primitive type overflow testing, the following types cannot pass:

* byte
* double
* float
* short

![image](https://cloud.githubusercontent.com/assets/216930/19618038/60cd0c82-988b-11e6-98ac-82257e94b576.png)

**Comment by wenshao** [comment]
byte/short type overflow already raised exception. Can you tell me how you test float / double overflow?

**Comment by greenlaw110** [comment]
They come up with special `Float` and `Double` value:

![image](https://cloud.githubusercontent.com/assets/216930/19629370/b3e0ef58-99bf-11e6-90c5-4a94f0716587.png)

**Comment by greenlaw110** [comment]
Just FYI, in my param value resolver (aimed to bind form/request param) I have the logic to check the Infinity:

![image](https://cloud.githubusercontent.com/assets/216930/19629410/8ad41832-99c0-11e6-94fa-889edc5fdca3.png)

**Comment by wenshao** [comment]
bug fixed. please use last version https://github.com/alibaba/fastjson/releases/tag/1.2.21

**Comment by greenlaw110** [comment]
@wenshao  The issue with Float has been fixed, but Double still have the same issue
