### ISSUE TITLE
被代理的ENTITY序列化时，WriteClassName 所序列化的classname不是真实classname

### ISSUE THREAD

**Issue by wander2016** [alibaba/fastjson#872]
被代理的ENTITY序列化时，WriteClassName 所序列化的classname不是真实classname；
当下次被反序列化时会报 type not match的错误！

建议在WriteClassName 添加Object的检查，确认是否为被代理的对象。

**Comment by wenshao** [comment]
被什么代理？是java.lang.reflect.Proxy 还是cglib或者其他？

**Comment by wander2016** [comment]
cglib或者javassist!
目前使用WriteClassName 特性时，序列化之后的classname："com.xxxx.bean.MyBean_&&_aa"，再反序列时会报错，目前使用@JSONType配置typeName 暂时解决了，但还是建议优化下！

PS:
SerializeConfig#getObjectWriter(**)对于代理class的判断方法可以直接复用JavaBeanSerializer#writeClassName(**)

**Comment by wendellxoo** [comment]
我试了一下，无论序列化还是反序列化，都不会报错，当然前提有个两个：一，使用了setSuperclass方法将生成的代理的父类设置为原始类。二，反序列化的时候使用原始类（生成的代理类也无法得到class）。所以，我有两个问题：一，什么情况下报type not match，二，你的诉求是是不是希望WriteClassName的时候写的是原始class name而不是代理的class name？

**Comment by wenshao** [comment]
问题修复，请等待1.2.21版本发布
