### ISSUE TITLE
变量命名导致不能解析成功

### ISSUE THREAD

**Issue by zishinan** [alibaba/fastjson#886]
一个对象Commodity对象中，有一个List<NSku>集合，当变量名为nSkus时不能解析，但是改为nskus时就可以解析了，估计是驼峰命名法规则，在生成get方法的时候，你判断略过了该属性。

**Comment by githublaohu** [comment]
这是  驼峰命名法规则 ，你没有遵循，请遵循 驼峰命名法规则。基本所有json库都是 这样的。

**Comment by zishinan** [comment]
好吧 已经自己改了命名
