### ISSUE TITLE
可以直接更新到java对象么

### ISSUE THREAD

**Issue by halfhq** [alibaba/fastjson#891]
现在使用A a= JSON.parseObject(json, A.class);来通过json创建A对象
当接收到一个json字符串时，有没办法直接更新到A a中？
例如 JSON.parseObject(json, a)。
需求是：不停获取到json，但是增量的。因此只需要将存在的（改动）更新到上次的。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/ParseToExistingObject
看这个是不是你要的

**Comment by halfhq** [comment]
就是这个，非常感谢。
