### ISSUE TITLE
反序列化建议

### ISSUE THREAD

**Issue by ifeikong** [alibaba/fastjson#892]
String jsonString = "{\"title\":null,\"name\":\"dfs\"}";
JSONObject json = JSONObject.parseObject(jsonString);

更多的时候是不希望title字段直接被忽略，序列化的时候可以配置，反序列化建议也可以让用户自己决定是否需要保留值为null的属性

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/ParseToExistingObject

**Comment by 1574359445** [comment]
> https://github.com/alibaba/fastjson/wiki/ParseToExistingObject

有用？不好使吧？
