### ISSUE TITLE
fastjson序列化顺序建议

### ISSUE THREAD

**Issue by qqcbqqkcel** [alibaba/fastjson#903]
我知道可以通过这个注解实现 @JSONField(ordinal = 2)
目前写restful 接口，类的属性很多主表字段20多个，行表10多个。
然后我写接口文档肯定是按属性从上到下的写，一个参数一个的写，说明其含义，字段类型等。
然后再输出一个JSON，和文档字段相对应。这样客户看起来比较方便。
日后调试时如果我输出的JSON也是按文档顺序的话客户调试起来也比较方便。

现在问题来了，加这个注解@JSONField(ordinal = 2)，一个一个的加太多了。而且有时候这些类是别人打包给我的，我不能修改源码。

我知道默认按字母排序速度快，但是如果能在序列化时，指定一个不排序的参数，损失一点效率是可以忍受的。
这个问题我在网上和fastjson issues里看到已经有不少人有这样的需求，网上更是有人直接修改源码来实现。

我现在就是序列化时用jackson，反序列化时用fastjson这样很不好。大神能不能考虑考虑这个问题。
谢谢。

**Comment by wenshao** [comment]
看这个是不是你想要的：
https://github.com/alibaba/fastjson/wiki/JSONType_alphabetic_cn

**Comment by wanwaner** [comment]
不好用

**Comment by DreamPWJ** [comment]
@JSONType(alphabetic = false)加上确实不生效
