### ISSUE TITLE
1.2.8以后的BrowserCompatible对丢失精度问题没有彻底解决

### ISSUE THREAD

**Issue by lvkangk** [alibaba/fastjson#904]
虽然1.2.8以后可以通过BrowserCompatible来吧长整型序列化成字符串,但是属性类型必须是Long(对象类型),然而我的model中很多都是long基本类型,这样就依然无法用BrowserCompatible转成字符串. 
      能否给加上基本类型long转为字符串的功能 ?

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by lvkangk** [comment]
今天想重新写个testcase 发现没有这个问题了...   请问是你们解决了?

**Comment by lvkangk** [comment]
我gitHub里新建了一个项目:lvkTest  在test路径下谢了一个testcase 您可以看一看

**Comment by cyberdak** [comment]
先关闭ASM吧，没有ASM的情况下是正常的。long也可以转成string

**Comment by lvkangk** [comment]
我没有用asm    我试的结果是: 当写test时 把实体类直接写到test类里,long是可以转换成String的,但是只要实体类和转换的test不写在同一个类里, long就转不成String , 要改成Long才可以
