### ISSUE TITLE
spring mvc 整合 fastjson 问题

### ISSUE THREAD

**Issue by DongYuanChun** [alibaba/fastjson#908]
spring 版本 是 4.0.9
fastjson版本是1.2.21

总报这个错
org.springframework.beans.factory.BeanCreationException: Could not autowire field
nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: 
Error loading class [com.alibaba.fastjson.support.spring.FastJsonpResponseBodyAdvice]
for bean with name 'fastJsonpResponseBodyAdvice' defined in URL 
[jar:file:XXX/WEB-INF/lib/fastjson-1.2.21.jar!/com/alibaba/fastjson/support/spring/FastJsonpResponseBodyAdvice.class]: 
problem with class file or dependent class; 
nested exception is java.lang.NoClassDefFoundError: org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice

**Comment by myoss** [comment]
方便给个项目代码看看吗？

**Comment by myoss** [comment]
[FastJsonpHttpMessageConverter4](https://github.com/alibaba/fastjson/wiki/FastJsonpHttpMessageConverter4_CN)  看起来你是用了这个，但这需要`spring 4.2+`支持

**Comment by DongYuanChun** [comment]
这么高大尚的东西我不会使~~！ 
呃~~  要不你加我下QQ？

**Comment by DongYuanChun** [comment]
呵呵，感觉到了。
不过谢谢你，选了一个低版本的就好了
谢谢

**Comment by zhaoxilingcheng** [comment]
@dongyuanchun  你好，选了一个什么低版本？

**Comment by dongyuanchun** [comment]
@zhaoxilingcheng JAR与JAR的发版日期相近  就可以了

**Comment by zhaoxilingcheng** [comment]
@dongyuanchun 没明白

**Comment by zhaoxilingcheng** [comment]
是要更换哪个项目的版本吗

**Comment by dongyuanchun** [comment]
@zhaoxilingcheng 就是 JAR 的发布是有时间的  
两个JAR 发版的时间相近 基本上就没啥问题

**Comment by zhaoxilingcheng** [comment]
找到原因了，是因为我扫描com的原因

**Comment by qcmoke** [comment]
> 找到原因了，是因为我扫描com的原因

感谢你，我也是扫描了com包后不能用了
