### ISSUE TITLE
Please support multi alias,Thanks!

### ISSUE THREAD

**Issue by Andecy** [alibaba/fastjson#913]
I have a class to accept JSON,but there is a attr have 2 different name

Thanks!

```json
{
"userID":"hd123"
}
```

```json
{
"uID":"hd124"
}
```

**Comment by githublaohu** [comment]
uId ，Do not conform to the hump nomenclature.So the parse error

不符合 驼峰命名法。所以解析错误

**Comment by Andecy** [comment]
@githublaohu hello,it's not the point about alias I think...
the point is my java code like this:
```java
@JSONFiled (name= "uId")
public String userId;
```
but the jsonStr has 2 or more different key:
```json
{
"userId":"hd123"
}
```
or
```json
{
"uId":"hd124"
}
```
or
```json
{
"accountId":"hd125"
}
```

so I hope like this:
```java
@JSONFiled(name = {"uId","userId","accountId"})
public String userId;
```

**Comment by githublaohu** [comment]
多key 情况下，只能通过反序列化处理器解决。比较麻烦。请看下面的连接
Many key cases, can only be solved through deserialization processor.More troublesome.Please see the links below
https://github.com/alibaba/fastjson/wiki/ParseProcess

**Comment by wenshao** [comment]
```java
JSONField(alternateNames={"n1", "n2"})
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/JSONField_alternateNames_cn

**Comment by Andecy** [comment]
@wenshao thank you very much!
