### ISSUE TITLE
Java中共享MAP序列化时，出现问题。

### ISSUE THREAD

**Issue by zq99299** [alibaba/fastjson#931]
> {"code":"200","data":{"total":1,"totalPage":1,"chartMaps":{"wigs":{"2015-11":246000,"2015-12":246000,"2016-1":301000,"2016-10":368000,"2016-2":301000,"2016-3":301000,"2016-4":301000,"2016-5":301000,"2016-6":301000,"2016-7":301000,"2016-8":301000,"2016-9":301000}},"btnNum":10,"list":[{"AdwordsCompetition":"high","avgCPC":1.099505,"avgMonthlySearchVolume":301000,"categoryIds":[10176,13842,10005,10021,10055,13575,10332,10924],"competition":0.9851638624159192,"keywordText":"wigs","monthlySearchVolume":{"$ref":"$.data.chartMaps.wigs"},"totalCount":1}],"currentPage":1},"msg":"业务处理成功"}

注意看上面的数据结构：
chartMaps ： 里面的数据 是获取chartMaps.put("xxx",list.get(n).getMonthlySearchVolume)
然后使用  JSON.toJSONString(); 序列化上面这样的数据结构的时候，就出现上面的问题了。,"monthlySearchVolume":{"$ref":"$.data.chartMaps.wigs"} 该字段序列化出错。

然而我尝试把 chartMaps  从上面的数据结构中去除，再序列化，list中的字段全部正常。搞不懂是为什么。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
第10点
