### ISSUE TITLE
Debug下JSON转Object正常，打包之后报ClassCastException,JSONObject cannot be cast to...

### ISSUE THREAD

**Issue by Guangsu** [alibaba/fastjson#936]
项目中也有其他JSON转Object的，都没有问题。

P.S.  看过反编译之后的源码，跟混淆没关系，不知道这是BUG还是我哪里用错了？

**Comment by cyberdak** [comment]
版本号？场景？

2016-12-06 12:05 GMT+08:00 冯景润 <notifications@github.com>:

**Comment by Guangsu** [comment]
版本：fastjson-1.2.3/fastjson-1.2.21
方法：JSON.parseObject(jsonStr,A.class);
具体：
```
class A{
    ...
    private List<B> b;
    private List<C> c;
}

class B {
    private String str;
    private List<C> c;
}

class C {
    private String str;
    ...
}
```

Exception:com.alibaba.fastjson.JSONObject cannot be cast to **B**

**Comment by Guangsu** [comment]
已确认是代码混淆导致的问题。

谢谢回复。
