### ISSUE TITLE
怎么使得fastjson仅将一个对象按照接口的get方法生成json字符串

### ISSUE THREAD

**Issue by nikorliu** [alibaba/fastjson#938]
public interface IPerson{
        public String getPersonId();
        public String getName();
}
public class Child{
       public String getPersonId(){
                return "010";
       }
       public String getName(){
                return "张三";
       }
       public String getAge(){
               return "5";
        }
}
下面是生成JSON文本
IPerson person = new Child();
String json = JSON.toJSONString(person);
这样生成的json文本会包含age:'张三',怎么使得fastjson仅按照IPerson接口定义的get方法生成文本呢？继承类也是一样的，有其它人遇到过吗？

**Comment by wuwen5** [comment]
用过滤器是可以完成你的需求的（也许不是最佳方案）.
```Java
JSON.toJSONString(person, (PropertyFilter) (o, s, o1) -> Stream.of(IPerson.class.getMethods()).anyMatch(m -> m.getName().equalsIgnoreCase("get"+s)))
```

**Comment by nikorliu** [comment]
嗯，基本上能解决问题。
实际的是我把这个应用在spring mvc里返回json对象，用过滤器的话这样就要手工显示在controller里面显式转换为json字符后再返回了

**Comment by duwei54** [comment]
@nikorliu 你好,我也有这个需求,springMVC 希望返回Interface的时候按照接口定义的getter返回字段,请问你解决了这个问题么
