### ISSUE TITLE
对象列表的反序列化时最后一个对象的json如果没有逗号就会缺少属性

### ISSUE THREAD

**Issue by woovan** [alibaba/fastjson#943]
用如下json反序列化这样一个属性private List<Symbol> symbols;，如果{"id":13,"type":"BONUS"}这行最后不带逗号，序列化后再输出，则type属性就丢失了(如果带逗号则好使)，type是个枚举类型。
   "symbols":[
	    {"id":1,"type":"NORMAL"},
	    {"id":2,"type":"NORMAL"},
	    {"id":3,"type":"NORMAL"},
	    {"id":4,"type":"NORMAL"},
	    {"id":5,"type":"NORMAL"},
	    {"id":6,"type":"NORMAL"},
	    {"id":7,"type":"NORMAL"},
	    {"id":8,"type":"NORMAL"},
	    {"id":9,"type":"NORMAL"},
	    {"id":10,"type":"NORMAL"},
	    {"id":11,"type":"WILD"},
	    {"id":12,"type":"SCATTER"},
		{"id":13,"type":"BONUS"}
	]

**Comment by wuwen5** [comment]
没有重现你说的问题，你可以贴下测试代码.

**Comment by woovan** [comment]
发现了，把json做换行缩进处理，就会出这个问题，把空格换行删除就好了，请问这是bug吗，因为要用json做配置，这样写更方便维护数据
{
	"symbols":[
	    {"id":1,"type":"NORMAL"},
	    {"id":2,"type":"NORMAL"},
	    {"id":3,"type":"NORMAL"},
	    {"id":4,"type":"NORMAL"},
	    {"id":5,"type":"NORMAL"},
	    {"id":6,"type":"NORMAL"},
	    {"id":7,"type":"NORMAL"},
	    {"id":8,"type":"NORMAL"},
	    {"id":9,"type":"NORMAL"},
	    {"id":10,"type":"NORMAL"},
	    {"id":11,"type":"WILD"},
	    {"id":12,"type":"SCATTER"},
	    {"id":13,"type":"BONUS"}
	]
}
类是这样就一个属性，不贴全了
public class SlotConfig {

	private List<Symbol> symbols;
序列化后再转成json输出就成了这样，最后一个type没了
{"symbols":[{"id":1,"type":"NORMAL"},{"id":2,"type":"NORMAL"},{"id":3,"type":"NORMAL"},{"id":4,"type":"NORMAL"},{"id":5,"type":"NORMAL"},{"id":6,"type":"NORMAL"},{"id":7,"type":"NORMAL"},{"id":8,"type":"NORMAL"},{"id":9,"type":"NORMAL"},{"id":10,"type":"NORMAL"},{"id":11,"type":"WILD"},{"id":12,"type":"SCATTER"},{"id":13}]}

**Comment by woovan** [comment]
补充一下，json是从文本文件读的，有缩进和换行

**Comment by wenshao** [comment]
我补充了testcase，重现不了问题

**Comment by woovan** [comment]
```
package com.java.test;

import java.util.List;

import com.alibaba.fastjson.JSON;

public class SlotConfig {

	private List<Symbol> symbols;
	
	
	public static void main(String[] args) {
		
		String text = "{\n" +
				                 "\t\"symbols\":[\n" +
				                 "\t    {\"id\":1,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":2,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":3,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":4,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":5,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":6,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":7,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":8,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":9,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":10,\"type\":\"NORMAL\"},\n" +
				                 "\t    {\"id\":11,\"type\":\"WILD\"},\n" +
				                 "\t    {\"id\":12,\"type\":\"SCATTER\"},\n" +
				                 "\t    {\"id\":13,\"type\":\"BONUS\"}\n" +
				                 "\t]\n" +
				                 "}";
		
		SlotConfig config = JSON.parseObject(text, SlotConfig.class);
		System.out.println(config);
	}
	
	@Override
	public String toString() {
		return JSON.toJSONString(this);
	}

	public List<Symbol> getSymbols() {
		return symbols;
	}

	public void setSymbols(List<Symbol> symbols) {
		this.symbols = symbols;
	}
	
	class Symbol {
		private int id;
		
		private SymbolType type;
		
		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}

		public SymbolType getType() {
			return type;
		}

		public void setType(SymbolType type) {
			this.type = type;
		}
	}
	
	enum SymbolType {
		NORMAL, WILD, SCATTER, BONUS
	}
	
}

```
重现问题的代码，帮忙看下

**Comment by wuwen5** [comment]
@wenshao 问题已重现，请review #949
