### ISSUE TITLE
使用1.2.21 的SkipTransientField不起作用

### ISSUE THREAD

**Issue by jackmiking** [alibaba/fastjson#944]
transient的属性依然被序列化，应该是要忽略掉transient的属性

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by jackmiking** [comment]
public class JsonObjectTest {
    private String name;
    private Integer age;
    private Date time;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @Transient
    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }


    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }


    public static void main(String[] args) {
        JsonObjectTest jsonObjectTest = new JsonObjectTest();
        jsonObjectTest.setTime(new Date());
        jsonObjectTest.setAge(3);
        jsonObjectTest.setName("abc");
        String s=JSONObject.toJSONString(jsonObjectTest, SerializerFeature.SkipTransientField);
        System.out.println(s);
    }
}
然后输出是：
{"age":3,"name":"abc","time":1481535111675}
age是transient属性来的，应该不能够被序列话出来。

**Comment by wenshao** [comment]
已经支持java.beans.Transient，请等待1.2.23版本
