### ISSUE TITLE
1.2.22版本，Jdk8DateCodec里面的格式化格式不生效

### ISSUE THREAD

**Issue by cnhans** [alibaba/fastjson#948]
fastjson 1.2.22版本
Jdk8DateCodec.java

LocalDateTime dateTime = (LocalDateTime) object;
                if (dateTime.getNano() == 0) {
                    String format = serializer.getDateFormatPattern();
                    if (format == null) {
                        format = JSON.DEFFAULT_DATE_FORMAT;
                    }
                    write(out, dateTime, format);
                } else {
                    out.writeString(object.toString());
                }

看 这里是 dateTime.getNano() == 0 才会进行format处理，LocalDateTime.now()产生的时间，都是不成立的，所以在toString时，即使是这样设置，都不会生效：
 @Override
    public String toString() {
        return JSON.toJSONStringWithDateFormat(this,"yyyy-MM-dd HH:mm:ss:SSS",
                SerializerFeature.DisableCircularReferenceDetect);
    }

按理纳秒都要能处理啊。
![image](https://cloud.githubusercontent.com/assets/563838/21089512/94fd7324-c073-11e6-88d0-e57b25ca1d9f.png)

**Comment by qiyuey** [comment]
急需啊

**Comment by wenshao** [comment]
1.2.23已经修复问题，将会尽快发布新版本
