### ISSUE TITLE
JDK8的LocalDateTime字段序列化不支持UseISO8601DateFormat

### ISSUE THREAD

**Issue by qiyuey** [alibaba/fastjson#952]
使用版本：1.2.22
序列化VO对象中包含LocalDateTime，设置参数UseISO8601DateFormat
输出结果为：yyyy-MM-dd HH:mm:ss
期望结果为：yyyy-MM-dd'T'HH:mm:ss

**Comment by wenshao** [comment]
问题已经修复，请等待1.2.23版本
