### ISSUE TITLE
1.1.55.android 如何定制某些字段的序列化和反序列化呢？

### ISSUE THREAD

**Issue by lixi0912** [alibaba/fastjson#953]
请问下，如何对某些字段定制序列化和反序列化？
例如:
> class 

```java
class Vo{
boolean isEnable;
String date; // format: yyyy-MM-dd
}
```
> json

```json
{"isEnable":1,"date":123456}
```
* date:   unix timestamp
* isEnable: 1-TRUE / 0-FALSE

**Comment by renzhipengmm** [comment]
简单的使用 ，可使用 添加注解使用
`@JSONField(format = "yyyy-MM-dd")`
全局可直接使用
  `writeJSONString(OutputStream os, 
                                             Charset charset, 
                                             Object object, 
                                             SerializeConfig config, 
                                             SerializeFilter[] filters, 
                                             String dateFormat, 
                                             int defaultFeatures, 
                                             SerializerFeature... features) throws IOException `
此时直接指定 dateFormat 格式即可
