### ISSUE TITLE
反序列化失败注解参数deserializeUsing无效

### ISSUE THREAD

**Issue by wensiqun** [alibaba/fastjson#963]
public class MainTest {

		@Test
		public void test() {
			Mock mock = JSON.parseObject("{\"type\":\"boolean\"}", Mock.class);
			Assert.assertEquals(EnumType.BOOLEAN, mock.getType());
		}

		public enum EnumType {
			BOOLEAN;
			@Override
			public String toString() {
				return name().toLowerCase();
			}
		}

		public static class Mock {

			@JSONField(serializeUsing = EnumTypeCodec.class, deserializeUsing = EnumTypeCodec.class)
			private EnumType type;

			public EnumType getType() {
				return type;
			}

			public void setType(EnumType type) {
				this.type = type;
			}
		}

		public static class EnumTypeCodec implements ObjectSerializer, ObjectDeserializer {

			@Override
			public <T> T deserialze(DefaultJSONParser parser, Type type, Object fieldName) {
				String uncasedSensitive = StringCodec.instance.deserialze(parser, type, fieldName);
				return (T) EnumType.valueOf(uncasedSensitive.toUpperCase());
			}

			@Override
			public int getFastMatchToken() {
				return JSONToken.LITERAL_STRING;
			}

			@Override
			public void write(JSONSerializer serializer, Object object, Object fieldName, Type fieldType, int features) throws IOException {
				SerializeWriter out = serializer.out;
				if (object == null) {
					out.writeNull();
					return;
				}
				StringCodec.instance.write(serializer, ((EnumType) object).name().toLowerCase(), fieldName, fieldType, features);
			}

		}
	}

**Comment by wensiqun** [comment]
另外issue 901 在1.2.22任然存在

**Comment by wenshao** [comment]
只是enum类型不可以

**Comment by CharkeyQK** [comment]
这个 bug fix 也修复了使用 ASM 序列化/反序列化的情况吗？

**Comment by wenshao** [comment]
是的，这几天就会发布新版本
