### ISSUE TITLE
fastjson 真的足够fast么？

### ISSUE THREAD

**Issue by anjia0532** [alibaba/fastjson#966]
fastjson的wiki上提到的测评，包括网上流传的测评，都是好几年前的了。是否有近期，新版本的测评？

最近看到一个产品，http://jsoniter.com/benchmark.html ，该测评结果是否真实有效？

**Comment by wenshao** [comment]
在https://github.com/eishay/jvm-serializers/wiki的测试结果中，在json/xxxx/databind/类型的测试中，fastjson还是最快的，最近更新的测试结果2016年7月9日。我做过简单测试，jsonitor功能单一，不支持enum，无法跑eishay的测试，我在简单测试了一下，其databind场景性能并不好，比fastjson慢多了。

**Comment by shibenli** [comment]
不知道什么产品对效率要求分的这么细，感觉现在都是各种黒别人的，找一个能满足需求的就是好的。

**Comment by anjia0532** [comment]
@wenshao 恩恩，谢谢温少的耐心讲解

**Comment by wbfabc** [comment]
> 不知道什么产品对效率要求分的这么细，感觉现在都是各种黒别人的，找一个能满足需求的就是好的。

如果你有一天几个T的json日志要处理，就不会这么认为了。
