### ISSUE TITLE
JSONObject.getObject(key,new TypeReference<VO>(){}.getClass())转换失败

### ISSUE THREAD

**Issue by anjia0532** [alibaba/fastjson#969]
假设我需要转换jsonobject对象中的某个子对象

```
JSONObject.getObject(key,new TypeReference<VO>(){}.getClass())
```
转换失败

只能通过JSON.parseObject(jsonobj.getString(key), new TypeReference<VO>(){})

**Comment by wenshao** [comment]
为什么要getClass？

**Comment by anjia0532** [comment]
因为我是想将jsonobject对象中的某个属性转换成bean，目前只有

```java
getObject(String key,Class<T> clazz)

parseObject

toJavaObject(JSON json,Class<T> clazz)

```
如果不加getClass,getObject(key,new TypeReference<VO>(){})，则会报以下错误，编译都不通过

The method getObject(String, Class<T>) in the type JSONObject is not applicable for the arguments (String, new TypeReference<T>(){})

**Comment by anjia0532** [comment]
@wenshao

**Comment by wenshao** [comment]
```
JSONObject.getObject(key,new TypeReference<VO>(){}.getType())
```

**Comment by anjia0532** [comment]
@wenshao 温少，新年快乐。

我说的 `JSONObject.getObject(key,type);`中的JSONObject是一个JSONObject对象，不是`com.alibaba.fastjson.JSONObject`类

然后，

```java
JSON.parseObject(String)    //(1)
.getObject("key", new TypeReference<VO>(){}.getType());//(2)
```

(1) 处是将字符串反序列化成jsonobject对象
(2) 处是使用JSONObject实例的getObject方法将某个属性反序列化VO类实例

但是此时编译会报错，假设是eclipse
```
The method getObject(String, Class<T>) in the type JSONObject is not applicable for the arguments (String, Type)
```

不支持 `new TypeReference<VO>(){}.getType()`

目前我是使用

```java
JSON.parseObject(JSON.parseObject(str).getString(key),  //(1)
new TypeReference<VO>(){}.getType()); //(2)
```
(1)  将str反序列化成jsonobject对象，然后通过key转换成string
(2) 通过JSON.parseObject(String,Type)反序列化成VO类

**Comment by anjia0532** [comment]
@wenshao 求大神指教

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
