### ISSUE TITLE
可以支持double类型数据format注解么？

### ISSUE THREAD

**Issue by heiliguai** [alibaba/fastjson#971]
在同一个对象中，double类型的数据可能需要输出不同的格式。比如，金额显示两位小数，价格显示三位小数。
JSONField注解的format只支持日期对象，不知道这样设计是基于什么样的考虑。

可以增加double类型格式注解支持么？
@JSONFiled(format="0.00")
private Double price;
类似这样的。

**Comment by heiliguai** [comment]
JSONSerializer    
public final void writeWithFormat(Object object, String format) { }

这个方法被标记为final了。

**Comment by wenshao** [comment]
已经支持，预计在春节前会发布新版本
