### ISSUE TITLE
toJSON和toJSONString的问题。

### ISSUE THREAD

**Issue by zern-king** [alibaba/fastjson#978]
三个属性
@JSONField(format="yyyy-MM-dd HH:mm:ss")
private Date createTime

@JSONField(serialize = false);
private String password;

private String email;

使用toJSON输出{"createTime":1483413683714,"email":"eee"}
使用toJSONString输出{"createTime":"2017-01-03 11:21:23","email":"eee"}

为什么format对toJSON不起作用呢

**Comment by wuwen5** [comment]
个人的理解:
toJSON 是转成K/V的```JSONObject```对象，使用的javaBean序列化的方式，value都是获取原对象的值，是不进行json转换的，注解是不生效的。 此后执行```toString()``` -->```toJsonString()``` 是对```JSONObject```转jsonString操作，这个过程是不会处理注解的。

toJSONString 是直接使用json序列化处理java bean对象的，注解是生效的。

**Comment by zern-king** [comment]
password这个字段被过滤掉了，说明注解还是有用的
