### ISSUE TITLE
能够针对Entry增加新特性

### ISSUE THREAD

**Issue by wensiqun** [alibaba/fastjson#983]
能否增加对Entry的默认序列化和反序列化，默认序列化为{key : value}, 反序列化默认用AbstractMap的SimpleEntry

**Comment by wenshao** [comment]
不明白你的意思，能够举例么？

**Comment by wensiqun** [comment]
Entry entry = new SimpleEntry("name", "foo");
    JSON.toJSONString(entry);

输出

    {"name" : "foo"}

**Comment by wenshao** [comment]
已经实现，请使用1.2.24版本
