### ISSUE TITLE
 com.alibaba.fastjson.JSONException: Invalid long: "2016-11-10T11:40:42.4Z"

### ISSUE THREAD

**Issue by yuhaocan** [alibaba/fastjson#987]
在retrofit使用.addConverterFactory(FastJsonConverterFactory.create())出现的问题
解析字段 "createdAt": "2016-11-09T09:57:20.445Z"，当Z前为三位时可以解析，如果为一位则解析失败报异常。
即使在字段上加上注解也没用@JSONField(format = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")

**Comment by wenshao** [comment]
android环境么？

**Comment by yuhaocan** [comment]
是的

**Comment by wenshao** [comment]
为什么会有这样的需求？

**Comment by yuhaocan** [comment]
我是在调用GankIo的公用接口时发现这个问题的，Api作者应该是用了ISO 8601扩展格式吧

**Comment by wenshao** [comment]
已经支持，在1.1.55.android和1.2.24版本中都会修复此问题，预计在春节前发布新版本
