### ISSUE TITLE
fastjson1.2.23与Spring 4.3.5不兼容,降回1.2.17问题解决,望早日修复

### ISSUE THREAD

**Issue by ShadowSaint** [alibaba/fastjson#996]
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fastJsonpResponseBodyAdvice' defined in URL [jar:file:/D:/work/MedicalRecruit/out/artifacts/MedicalRecruit_war_exploded/WEB-INF/lib/fastjson-1.2.23.jar!/com/alibaba/fastjson/support/spring/FastJsonpResponseBodyAdvice.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String[]' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1154)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1056)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)`
新版本增加的JSONArray.toList非常好用,
新版本的SerializerFeature.WRITE_MAP_NULL_FEATURES也有问题,
还望早日解决问题,谢谢大神

**Comment by wenshao** [comment]
@VictorZeng 帮忙看一下？

**Comment by VictorZeng** [comment]
@myoss support 一下 谢谢~

**Comment by myoss** [comment]
我测试看看呀

**Comment by wanghantong** [comment]
我也遇到了。。。

**Comment by myoss** [comment]
能否提供下错误的示例工程代码？我升级工程的spring到4.3.5，我没重现出来 @wanghantong @ShadowSaint

**Comment by javaXN** [comment]
今天也遇到了同样的问题（同样的错误）。除spring4.3.5+fastjson1.2.16 均出现相同问题。 fastjson1.2.17~1.2.24 均有同样问题。

**Comment by ShadowSaint** [comment]
请问错误的示例工程代码怎么发给你呢?提供一个邮箱吧.
另外我描述出错了,应该是SpringMVC 4.3.5用不了fastjson1.2.23
 @myoss

**Comment by myoss** [comment]
jerry.work@aliyun.com @ShadowSaint

**Comment by XiaoSK** [comment]
参照 [https://github.com/alibaba/fastjson/wiki/FastJsonpHttpMessageConverter4_CN](https://github.com/alibaba/fastjson/wiki/FastJsonpHttpMessageConverter4_CN) 添加相应 bean 定义，注意 autowired=byName 即可。

**Comment by ShadowSaint** [comment]
目前可以使用了,解决途径是在DispatcherServlet-context.xml里加入了
`<bean id="fastJsonpResponseBodyAdvice" class="com.alibaba.fastjson.support.spring.FastJsonpResponseBodyAdvice">
              <constructor-arg>
                     <list>
                            <value>callback</value>
                            <value>jsonp</value>
                     </list>
              </constructor-arg>
       </bean>`
可是我有个疑问,不是所有项目都需要灵活转Jsonp的,如果不配置这个就没法正常使用fastjson的话,会不会有点...呃...不太好...?应该谁需要谁配置开启的吧...(或者是我没有正确的掌握使用方法...?)
从前只需要导入maven包就行了,现在还要在xml里配置,会有会有点..不是那么..轻量级...?
@wenshao @myoss @VictorZeng 
最基本的SpringMVC项目配置已经打包发给 @myoss 了,intellij idea项目,导入,add framework support,加入web就可以了,望各位大牛看一下,谢谢

**Comment by myoss** [comment]
代码收到了，目前还是没有重现出来，还在和 @ShadowSaint 沟通中。

**Comment by ShadowSaint** [comment]
@wenshao @VictorZeng @myoss 
非常对不起,在myoss回复我使用我的代码并没有问题以后,
我在多个同事的电脑上导入了我的项目,运行,果然没有问题,断定是我电脑的问题.
于是我将jdk升级至1.8.0.121,tomcat升级至9.0.0.M17,idea升级至2016.3.4,重新配置以后,问题解决
我这台电脑已经用来开发了一年多了,一直没有问题,出了问题以后我没想过是由于电脑导致的,给你们带来了诸多困扰,我感到非常的抱歉.
对不起.
非常感谢你们给我们开发者带来这么好用的JSON工具,谢谢.
